### ISSUE TITLE
VICE test /testprogs/VICII/colorram

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkwhoffmann/virtualc64#152]
```
Middle are: VICE displays a lot of special characters
VirtualC64 mainly displays standard characters
Bitmaps seem to be fetched from wrong location


```

Original issue reported on code.google.com by `dirk.hof...@gmail.com` on 4 Jan 2015 at 6:25

**Comment by dirkwhoffmann** [comment]
Fixed (by initializing the RAM with the 00 .. 00 FF .. FF 00 .. 00 FF .. FF power up pattern)
