### ISSUE TITLE
Allow numerical keys as joystick directions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dirkwhoffmann/virtualc64#176]
```
Right now, Virtual C64 does not want to recognize them.

```

Original issue reported on code.google.com by `dirk.hof...@gmail.com` on 12 Apr 2015 at 10:32

**Comment by dirkwhoffmann** [comment]
Joystick emulation key mapping has been changed.
In the next release, keys on the numeric keypad will be treated as separate keys. 
Works well with my german keyboard. Other keyboards haven't been tested, though.

**Comment by dirkwhoffmann** [comment]
More work to do: 
Store NUMERIC_KEYPAD_ATTR in fingerprint, but only for number keys.

**Comment by dirkwhoffmann** [comment]
done
