### ISSUE TITLE
Latest few versions do not run in latest OS X Yosemite 10.10.5. 

### ISSUE THREAD

**Issue by byron426** [dirkwhoffmann/virtualc64#201]
When attempting to execute latest release candidates, they all fail to get beyond the first window as it begins to appear. It then crashes. I've uploaded an image of the crash.
Last working version (that I've still kept, because I really like this app) is version 0.9.9.8. Every update after that has been doing exactly the same as described above.

![screenshot_9_4_15__3_02_pm](https://cloud.githubusercontent.com/assets/4040865/9692279/fc369a10-5315-11e5-84ba-bab6009952a7.png)

**Comment by dirkwhoffmann** [comment]
It is not a Yosemite issue (the emulator runs fine on my own Yosemite macbook). 

Can you scroll down in the crash reporter window and paste everything related to thread 0? (The screenshot shows that thread 0 has crashed).

Do you see any output in the console window (console.app) prefixed with "VirtualC64:"?

As the emulator crashes on startup, it might have to do with the handling of user defaults. To test, please delete file de.dirkwhoffmann.VirtualC64.plist which should be located in ~/Library/Preferences

**Comment by byron426** [comment]
I removed the plist files. No difference. Attached are the text from the
crash reporter and a screen shot of the console. Let me know if I can
provide further info.
Thanks, Jorge

**Comment by dirkwhoffmann** [comment]
The attachments don't show up

**Comment by belucid** [comment]
Just another data point, I'm running Version 1.0rc3 just fine on 10.10.5 as well.

**Comment by byron426** [comment]
Let's try the attachments once again 1 of 2.

**Comment by byron426** [comment]
Attachments 2 of 2.

**Comment by dirkwhoffmann** [comment]
Problem is most likely fixed in 1.0rc4. Please reopen if not.

**Comment by byron426** [comment]
Worked very well, thank you. :-)
