### ISSUE TITLE
Insert new disk without reseting emulator

### ISSUE THREAD

**Issue by andrewmondt** [dirkwhoffmann/virtualc64#207]
is there a way top insert a new disk without reseting the emulator? I'm load the COMAl language and then wish to load and save my project without the reset.

**Comment by dirkwhoffmann** [comment]
Simply drag and drop a D64 file into the main window and hit "Insert" in the upcoming drop-down sheet. The old disk will be replaced by the new one with everything else staying in place. To avoid data loss (if you saved some files to disk), you might want to export it to a new D64 image first (menu File->Export->D64)

**Comment by andrewmondt** [comment]
Thank you so much! 

Andrew

**Comment by andrewmondt** [comment]
Thanks for the information. What is the best way to emulate the keyboard? In other emulators, which no longer work in osx, I plugged in an old pc keyboard which worked well. 

Thanks, 
Andrew
