### ISSUE TITLE
Metal not supported on all machines that can run 10.11

### ISSUE THREAD

**Issue by clobber** [dirkwhoffmann/virtualc64#208]
Dunno if you care or not, but wanted to point out that Metal cannot be used on all machines that can actually run 10.11. Only [2012 models and above](https://support.apple.com/en-us/HT205073), so machines that run your app without Metal support will simply not be able to run software:

```
VirtualC64[3055]: MyDocument::init
VirtualC64[3055]: MyDocument::makeWindowControllers
VirtualC64[3055]: C64Proxy::init
VirtualC64[3055]: MyMetalView::awakeFromNib
VirtualC64[3055]: MyMetalView::buildMetal
VirtualC64[3055]: *** Assertion failure in -[MyMetalView buildMetal], /Users/hoff/VirtualC64/virtualc64/OSX/MacGUI/MyMetalViewSetup.mm:41
VirtualC64[3055]: Metal device must not be nil
```

Maybe you want to keep OGL around as an alternative path for those machines, or just output the frame buffer directly to an IOSurface (which also means those machines wouldn't get access to the filters/shaders).

**Comment by dirkwhoffmann** [comment]
Thank you for pointing this out, I wasn't aware of the compatibility problem. I have updated the release notes with a link to the compatibility page and put a permanent link to V1.0rc4 on the download page. 
Unfortunately, as I am the only developer right now, I don't think I can maintain both Metal and OpenGL.
