### ISSUE TITLE
Latest update crashes on startup

### ISSUE THREAD

**Issue by byron426** [dirkwhoffmann/virtualc64#210]
Here are the problem details in the problem report:

Process:               VirtualC64 [10823]
Path:                  /Applications/VirtualC64.app/Contents/MacOS/VirtualC64
Identifier:            de.dirkwhoffmann.VirtualC64
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VirtualC64 [10823]
User ID:               501

Date/Time:             2015-10-24 21:47:15.275 -0400
OS Version:            Mac OS X 10.10.5 (14F1021)
Report Version:        11
Anonymous UUID:        DE34E6D8-D543-41ED-49EE-C342B6D20C34

Sleep/Wake UUID:       A67ABF47-9F35-43C5-94A7-183459800FC3

Time Awake Since Boot: 5400 seconds
Time Since Wake:       240 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/ModelIO.framework/Versions/A/ModelIO
  Referenced from: /Applications/VirtualC64.app/Contents/MacOS/VirtualC64
  Reason: image not found

Binary Images:
    0x7fff6f53e000 -     0x7fff6f574887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld

Model: MacBookAir6,1, BootROM MBA61.0099.B20, 2 processors, Intel Core i7, 1.7 GHz, 8 GB, SMC 2.12f143
Graphics: Intel HD Graphics 5000, Intel HD Graphics 5000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E384A544D4C41522D4E544D
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 23.6

**Comment by dirkwhoffmann** [comment]
V1.1 and above require a Metal capable Mac and OS  X 10.11. Your Macbook is running 10.10.5.

Of course, the app should not crash, but issue a warning message instead. I will investigate how the OS version can be checked on startup (up to now, I thought OS X would do the check on app launch, but it obviously does not)...
