### ISSUE TITLE
Version 1.1.3 crashing at launch on OSX 10.10

### ISSUE THREAD

**Issue by pedgarcia** [dirkwhoffmann/virtualc64#211]
This is the dump I get when I try to launch it. Not sure if it can help:

Process:               VirtualC64 [35912]
Path:                  /Applications/Emulators/VirtualC64.app/Contents/MacOS/VirtualC64
Identifier:            de.dirkwhoffmann.VirtualC64
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VirtualC64 [35912]
User ID:               1933813047

Date/Time:             2015-10-30 09:05:56.807 -0400
OS Version:            Mac OS X 10.10.5 (14F1021)
Report Version:        11
Anonymous UUID:        3622B1AB-9EC2-073D-A53E-542D30CE8D58

Sleep/Wake UUID:       C6F7B4FF-6B9F-481E-BBF7-4A56C87C345C

Time Awake Since Boot: 44000 seconds
Time Since Wake:       3100 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/Library/Frameworks/ModelIO.framework/Versions/A/ModelIO
  Referenced from: /Applications/Emulators/VirtualC64.app/Contents/MacOS/VirtualC64
  Reason: image not found

Binary Images:
    0x7fff6ee28000 -     0x7fff6ee5e887  dyld (353.2.3) <B1B370A5-479F-3533-8AD7-97B687D4F989> /usr/lib/dyld

Model: MacBookPro11,3, BootROM MBP112.0138.B16, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.19f3
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Graphics: NVIDIA GeForce GT 750M, NVIDIA GeForce GT 750M, PCIe, 2048 MB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, -
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x02FE, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.15.166.24.3)
Bluetooth: Version 4.3.6f3 16238, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB Ethernet, Ethernet, en5
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: Internal Memory Card Reader
USB Device: USB2.0 Hub
USB Device: USB2.0 Hub
USB Device: Keyboard Hub
USB Device: Apple Keyboard
USB Device: Hub
USB Device: Hub
USB Device: Ultra Fast Media Reader
USB Device: Hub
USB Device: AS2105
USB Device: AX88x72A
USB Device: Microsoft® 2.4GHz Transceiver v9.0
USB Device: Display iSight
USB Device: Apple LED Cinema Display
USB Device: Display Audio
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1

**Comment by dirkwhoffmann** [comment]
V1.1 and above need 10.11 (El Capitan) and a Metal enabled Mac (late 2012) to run.

**Comment by dirkwhoffmann** [comment]
Version 1.2 should issue a warning message on Yosemite. 
(Unfortunately, I cannot test this myself as I already upgrade all my machines to 10.11)
