### ISSUE TITLE
Support the C64 PP MNIB (.nib) image

### ISSUE THREAD

**Issue by clobber** [dirkwhoffmann/virtualc64#218]
http://c64preservation.com/nibtools
http://c64preservation.com/c64pp/bbs/dm.php?id=2068

I don't know much about the format, maybe it's just another container like d64, but I've come across these .nib dumps which VICE seems to load natively. Not clear if it has to do any conversion before loading though.

By the way we (OpenEmu) now have a working port of your emulator here https://github.com/OpenEmu/VirtualC64-Core

Thanks for all the great work on VirtualC64!

**Comment by dirkwhoffmann** [comment]
It's great to hear that VirtualC64 is now available as an OpenEmu plugin :). 

I have looked into the NIB format, but experienced serious issues. The NIB format is a dump of raw data that cannot be used without further post-processing (which VICE must do on the fly). The main problem is as follows: In a NIB file, all tracks are stored as a bit stream of length 0x2000 bytes. The post-processor has to determine the real track length by detecting a loop in the bit stream. Unfortunately, I was not able to come up with a loop detection method that worked for all NIB files I have. It seems that the repeated data is not always a one to one copy of the first loop (i.e., some bits seem to differ which makes loop detection very hard).

I need to check if n2g is GPL. In that case, I could perform an on-the-fly conversion with n2g internally and mount the nib file as a G64 image...

**Comment by dirkwhoffmann** [comment]
will be supported in the next release

**Comment by clobber** [comment]
Very much appreciated!

By the way, for weird files showing up in your unstaged commits that sneak their way in (81d3aad5065354e5403d159889594332c161a363), you can just set up and push a .gitignore file [like so](https://github.com/OpenEmu/OpenEmu/blob/master/.gitignore) and Git will ignore them so they don't get committed.
