### ISSUE TITLE
Can't press run/stop key ?

### ISSUE THREAD

**Issue by dragonfry** [dirkwhoffmann/virtualc64#223]
Hi,

this is a great project! I can't seem to press the run/stop key though (other than via the menu item). The esc is not having any effect.
Can i tweak some ini file or so to switch the keyboard setup?
I'm using Mac Book Air, OSx El Capitan.

Thanks in advance!

Tom

**Comment by dirkwhoffmann** [comment]
Right now, there is no way to switch the keyboard setup and using the menu option is the only way to press run/stop.
I didn't map ESC (yet), because it is the common way to leave fullscreen mode.

--
Dirk

**Comment by dirkwhoffmann** [comment]
In 1.4.2, the ESC key will be mapped to Runstop

**Comment by dirkwhoffmann** [comment]
1.4.2 is now available as download
