### ISSUE TITLE
Add option to keep CTRL key pressed

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#232]
User request: " I needed access to the CTRL key and I added this to the keyboard menu items, CTRL On, CTRL off so you can toggle it depressed and undepressed. This was useful for the game Might and Magic where many of the main editing features required a CTRL + KEY combo..

Please find attached the modified code, both interface and c++/ obj-c."

[V64 CNTR Mod.zip](https://github.com/dirkwhoffmann/virtualc64/files/471444/V64.CNTR.Mod.zip)

**Comment by jimrogerz** [comment]
The control key works normally now without the menu item
