### ISSUE TITLE
Hide mouse cursor in full screen mode + add keyboard shortcut to enter and leave full screen mode

### ISSUE THREAD

**Issue by neosquid** [dirkwhoffmann/virtualc64#233]
Would like Virtual 64 to hide the mouse cursor after a few seconds if the mouse is not active, only showing if the mouse is moved.

Also, pressing alt+enter, or alt+f to enter and leave full screen mode is always handy for using emulators.

Thanks for considering this.

**Comment by dirkwhoffmann** [comment]
Mouse cursor now hides after 1 sec

**Comment by dirkwhoffmann** [comment]
ESC now leaves fullscreen mode

TODO: 
- In most apps, fullscreen mode can be toogled by pressing CTR+ALT+F.
- To support this shortcut, menu item "Enter fullscreen mode" needs to be implemented manually. However, I just noticed that some apps show this item under "View" and others under "Window". Before implementing, we need to find out which one is standard.

**Comment by dirkwhoffmann** [comment]
I figured it out. The standard location for "Enter Fullscreen Mode" ist the "View" menu. I added such an item (it was not there before). As a side effect, Apples standard key combination (CTR+CMD+F) is now working properly.

New code is already checked in.
