### ISSUE TITLE
Make disk not write protected by default

### ISSUE THREAD

**Issue by jimrogerz** [dirkwhoffmann/virtualc64#234]
I almost gave up on VirtualC64 because a game wasn't working. The graphics and UI were so much better than VICE that I kept on troubleshooting. The problem was the disk was write protected.

**Comment by jimrogerz** [comment]
Looks like the intent of the code is only to write protect when bit accuracy is disabled. Current code is always write protecting. I have a fix if you can make me a contributer.

**Comment by dirkwhoffmann** [comment]
Hi Jim, thanks for pointing this out. I'll make you a contributor...

**Comment by jimrogerz** [comment]
Bit accuracy is enabled by default, which now disables write protect by default: https://github.com/dirkwhoffmann/virtualc64/pull/235
