### ISSUE TITLE
How to use converted .CRT files?

### ISSUE THREAD

**Issue by dafi** [dirkwhoffmann/virtualc64#253]
Hi,

I've the 64MON's `.crt` file and I've saved to `.prg` using Vice and then converted to `D64` using the c1541 tool, virtualc64 opens it without problems but when I try to run with `sys 32820` the program doesn't start.

Running it from Vice works fine, any idea?

The steps to create the d64
1. from Vice attach cartridge
2. from Vice monitor saved to `prg` with the command `S "/Users/dave/c64stuff/64mon.prg" 0 8000 9FFF`
3. from bash saved the `prg` inside a `d64` with the command `c1541 -format diskname,id d64 64mon.d64 -attach 64mon.d64 -write 64mon.prg 64mon`

I own an old rare original 64MON cartridge so my use is almost legal.

**Comment by dirkwhoffmann** [comment]
I think it was a problem with the emulator and not with the converted file. 
In version 1.6., the 64MON cartridge seems to work fine. 
Please reopen, if there are still issues.

**Comment by Zibri** [comment]
@dafi hi (ciao!) can you share the dump of your cartridge?
