### ISSUE TITLE
Adding in Network Capabilities

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#254]
Feature request:
Macvice networking doesn’t work well and is not supported very well. There is so many tutorials how to get onto BBS these days as well as Quantum Link via telnet. But everytime I try, I doesn’t work.

My solution, I found a app (discontinued) but works that creates virtual com port and i use it with macvice. Works, and I have attached pics of my settings as well as the app.

I would be nice to see virtual64 work with this as well have a network feature as more 64/bbs and services are coming back online. Please see what you can do. It would be appreciated! Virtual64 is my goto app over vice.

[MultiCom-1.2.zip](https://github.com/dirkwhoffmann/virtualc64/files/1161723/MultiCom-1.2.zip)
<img width="351" alt="screen shot 2017-07-20 at 1 37 05 am" src="https://user-images.githubusercontent.com/12561945/28409197-2502eda0-6d3a-11e7-8acb-0f77d12470b7.png">

**Comment by dirkwhoffmann** [comment]
What is exactly meant by adding networking support to VirtualC64? Does it mean to emulate an old acoustic coupler? What would be a specific use case? Which specific website or web service could serve as my counterpart (data provider) for testing? Sorry if this is a stupid question, but I never used my real C64 in any networking environment.

**Comment by bluecursor** [comment]
With acutual hardware : https://www.cbmstuff.com/proddetail.php?prod=WiModemOLED. 

Example:https://www.youtube.com/watch?v=TeuQVKRsObk
Example: https://www.youtube.com/watch?v=obiJMlkg-bs
Example: http://www.lemon64.com/forum/viewtopic.php?t=65312
Example: https://1200baud.wordpress.com/2017/04/24/wednesday-night-q-link-hangout/

Back in the80's: https://www.youtube.com/watch?v=S-ChICic2TA

https://www.eltima.com/products/virtual-modem-pro/

**Comment by dirkwhoffmann** [comment]
Thanks a lot for providing various links! I will look into it.

**Comment by dirkwhoffmann** [comment]
Sorry, no progress yet. I watched the videos and it doesn't seem to be an easy task. As I am not a networking expert, I don't think that I will be able to implement it myself.

**Comment by dirkwhoffmann** [comment]
I close this issue for now as I don't expect network support to come soon.  Anyway, thanks a lot for the links above! They will be very helpful for everyone who is eager to put their hands on this problem.
