### ISSUE TITLE
help not available

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#257]
VirtualC64  Version 1.5.1 (1.5.1)

*Steps*
Select Help/VirtualC64 Help 

*Observation*
Help fails to load, see screenshot.
![screen shot 2017-08-31 at 00 09 05](https://user-images.githubusercontent.com/3512672/29899006-c0b7d64a-8de0-11e7-9bdc-48fc4dfb9a93.png)

**Comment by dirkwhoffmann** [comment]
Unimplemented help menu item has been removed
Help menu is still there (serving the standard search field which all apps have)
