### ISSUE TITLE
Hangs when quiting from dock context menu

### ISSUE THREAD

**Issue by troydm** [dirkwhoffmann/virtualc64#266]
VirtualC64 1.5.2 hangs on latest OSX El Capitan 10.11.6 when I press quit by right clicking in Dock on the icon and then clicking on Quit, after the Save dialog. If I quit from Menu it exits without any issues

update: sometimes it hangs even when I quit from menu

**Comment by dirkwhoffmann** [comment]
Does it still hang? It seems to work well on High Sierra 10.13.2.

**Comment by troydm** [comment]
@dirkwhoffmann yes unfortunately on El Capitan 10.11.6 it's still hangs as described

**Comment by dirkwhoffmann** [comment]
The initialization and shut down procedures have been changed considerably in V1.8, so there is a big chance that the bug is eliminated. I'm closing this issue in the hope that it's really fixed. Unfortunately, I cannot reproduce the issue on my machines (all are running HighSierra).

**Comment by troydm** [comment]
Actually in newer version this bug is fixed however another problem with screen appears but it's a different bug I guess

**Comment by dirkwhoffmann** [comment]
What is the symptom of the new bug?

**Comment by troydm** [comment]
@dirkwhoffmann this is what I see when I start v1.8 on El Capitan: https://i.imgur.com/hmCMnqH.jpg

This doesn't happens on High Sierra with v1.8

**Comment by dirkwhoffmann** [comment]
OK, I see. It seems that the emulator uses wrong window parameters when it calculates its 3D projection matrices on start up. Does the problem go away if you resize the window manually?

**Comment by troydm** [comment]
@dirkwhoffmann nope, the size stays the same

**Comment by troydm** [comment]
@dirkwhoffmann latest 1.8.1 update fixed the window issue, now everything works correctly, thanks alot
