### ISSUE TITLE
Keyboard mapping problem: Up arrow is not present on my MacBook PRO ITA layout

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#271]
Good day,

on my macbook pro (italian keyboard) the up arrow symbol used in math for exponentiation is missing using the emulator.
Is there the way to remap VirtualC64 keyboard ?

![untitled](https://user-images.githubusercontent.com/34916641/34648918-53621a2c-f3a4-11e7-8463-949f0c0aabb8.png)

**Comment by dirkwhoffmann** [comment]
Thanks for reporting this. You can download an experimental fix here: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64experimantal.zip

If you hold down SHIFT and press the key in the upper left corner, an uparrow instead of a leftarrow should appear. It works on german keyboards, but I am not sure if it works on Italien keyboards as well. If not, I will try a different solution.

**Comment by Alessandro1970** [comment]
I thank you for the quick and kind reply.

However the problem remains. Can you map the "up arrow" on the accented "ì" found on Italian keyboards on the right-upper (Photo)? 
Could there be a way to map the keys in the emulator (as we do with the CBM joystick for games) ?

![keymapita](https://user-images.githubusercontent.com/34916641/34655263-9b7d50c4-f3fe-11e7-89db-179075a899ba.jpg)

Anyway, thanks.

**Comment by dirkwhoffmann** [comment]
OK, here is another try: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64experimantal.zip

In this version, I try to map  "î" as a character and not as a key. Unfortunately, I cannot test it on my german keyboard.

**Comment by Alessandro1970** [comment]
In this version using my "ì" key with shift key I obtain this: "<-" and not up arrow (probably "î" is not my "ì", different accent).
But using your joystick emulation pannel I notice that my "ì" key has this value: "24", if it could be of interest.

**Comment by Alessandro1970** [comment]
Solved. 
In your last revision I have seen that on my macbook pro the "|" key 'shifted' (not the letter "I") works perfectly.

Thank you

**Comment by dirkwhoffmann** [comment]
Great :-)
