### ISSUE TITLE
Customize the keyboard with a special menu

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#274]
Hi,

I've been using this fantastic emulator for a long time, even with Geos. It works really well and I am very satisfied with it.
I find it necessary to modify the position of the keys directly for the graphic characters and for the letters directly with the emulator.
I'm asking if a special menu could be created with an interactive graphic image (as in the photo) that allows to change the position of the keys during the emulation like the joystick options.
I think it would be very useful for all those who have different keyboards and can not use all the characters.
The image inserted is not an apple keyboard and is purely indicative to understand that it would be great to have an image of the keyboard to configure it entirely during the emulation.

![799px-italian_keyboard_layout](https://user-images.githubusercontent.com/34916641/34908941-c9c231e0-f898-11e7-8a21-2b98b13a54fd.png)

Thank you

Best wishes

**Comment by dirkwhoffmann** [comment]
Yes, I agree that something needs to be done in regard to keyboard customization. However, I need to think about a clean way to do it.

Currently, I am favoring of a two stage approach. 

1. First of all, the keyboard manager will be extended by a user-definable list of specially mapped keys. By default, this list is empty. When a keys is pressed, the keyboard manager first checks this list and if it finds something, it'll hit the mapped key on the virtual C64 keyboard (together with, e.g., SHIFT, if a key modifier is present). 

2. If no match is found, the keyboard manager tries to map the keys by character (same way as it works right now for most keys). E.g., a pound sign will be translated to the C64 pound key, regardless of the used mac keyboard. This approach works only for printable ASCII characters which is the reason that we also need phase 1. 

The mac version of VICE is much simpler. It only maps by keycode (and not by ASCII character) which has some ugly drawbacks. E.g., if you hit SHIFT-3, you'll get a "#", just as you would on a real C64 keyboard. However, I want to get POUND on the keyboard shown above. 

To make a long story short: The keyboard manager should map a key by its textual ASCII representation as long as this is possible. If it's a non textual key or a key that does not exist on the virtual keyboard (such as the german "ü"), it falls back to a (user-definable) keycode map.

**Comment by dirkwhoffmann** [comment]
Fixed in 1.8 which was just released.
