### ISSUE TITLE
Animation effects slow down when using Gaussian blur filter

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#276]
To reproduce: 

Select Gaussian Blur as post-processing filter
Perform a reset

None of the other filters causes the same effect
Did not occur in 1.5.2 (texture size was smaller in 1.5.2, though)

TODO: It seems like fps is not computed properly (VirtualC64 measure seems to measure how many VIC frames are drawn which is always proportional to the CPU frequency). The implementation should measure how many Metal screens are drawn. I guess the Gaussian blur implementation is slow in general and the effect can only be recognized during animation effects.

**Comment by dirkwhoffmann** [comment]
My expectation was right. Gaussian blur slows emulator down to 30 fps.

GPU code needs a design improvement. The current GPU code works as follows: 

1. Run upscaler: 2048 x 2048 texture -> 2048 x 2048 texture
2. Run filter: 2048 x 2048 texture -> 2048 x 2048 texture
3. Draw into framebuffer

Improvement idea: 
Apply the filter in stage 3 when drawing into the framebuffer

**Comment by Alessandro1970** [comment]
Thanks for the advice a few days ago, I had no discussion on the debate on "Gaussian Blur and FPS"!

My MBP without the filter 60fps:

<img width="779" alt="schermata 2018-08-05 alle 09 47 47" src="https://user-images.githubusercontent.com/34916641/43683877-680ce5c4-9895-11e8-96aa-56b9e2c2a602.png">


My MBP with the filter 28fps:

<img width="778" alt="schermata 2018-08-05 alle 09 46 29" src="https://user-images.githubusercontent.com/34916641/43683874-616eb5e4-9895-11e8-9f6f-374336d2458e.png">

**Comment by dirkwhoffmann** [comment]
Fixed by the two-pass Gaussian blur shader implemented by Jim.
