### ISSUE TITLE
feature request: Escape key to close dialog box

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#293]
Congratulations on the Version 1.7.2 release, very nice.

I'm used to pressing escape to exit a dialog box. I imagine many people are. In the screenshot of the Disk inspector dialog, I can exit by moving the mouse over the close button and clicking. It would be great if I could press the Escape key on the keyboard to achieve the same result.

![screen shot 2018-02-20 at 00 28 25](https://user-images.githubusercontent.com/3512672/36402275-3176b21c-15d5-11e8-9d10-8533549f31a5.png)

I propose that logic is added so that if in a dialog and the escape key is pressed then the dialog closes. This should apply to all dialog boxes:

Thanks.

**Comment by dirkwhoffmann** [comment]
Fixed in 1.8
