### ISSUE TITLE
build fails : diskette_light.png missing

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#294]
I forked the latest and attempted to build. I was presented with 1 error

```
Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng failed with exit code 1

CopyPNGFile /tmp/V64.dst/Users/d/Applications/VirtualC64.app/Contents/Resources/diskette_light.png images/diskette_light.png
    cd /Users/d/Sites/virtualc64/OSX
    export DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer
    export TOOLCHAINS=
    /Applications/Xcode.app/Contents/Developer/usr/bin/copypng /Users/d/Sites/virtualc64/OSX/images/diskette_light.png /tmp/V64.dst/Users/d/Applications/VirtualC64.app/Contents/Resources/diskette_light.png

ERROR: Can't find /Users/d/Sites/virtualc64/OSX/images/diskette_light.png
Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng failed with exit code 1
```

**/Users/d/Sites/virtualc64/OSX/images/diskette_light.png is  missing from the latest codebase.** :(

xCode: Version 9.2 (9C40b)

most recent commit:
commit 1ec270e400dd4e8b149fd0cf58edf5c7f787a4c6 (HEAD -> master, origin/master, origin/HEAD)
Author: Dirk Hoffmann <hoff@dark-vader.local>
Date:   Wed Feb 14 18:15:22 2018 +0100

    This is VirtualC64 1.7

---

**Comment by dirkwhoffmann** [comment]
Fixed. I forgot to put two files under version control.
