### ISSUE TITLE
Maniac Mansion hangs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#297]
After loading a while, Maniac Mansion hangs in an endless loop. 

Inside the loop, it accesses: 

1) Zero page registers $00, $01
2) Zero-page value related to RND()

Don't know what's going wrong, yet.

**Comment by Alessandro1970** [comment]
Hi,
I've tried different versions of Maniac Mansion downloaded from the Internet but none of them worked for me either.
All of them stop at the same point and the initial screen of the game with the choice of characters does not appear, the screen remains black.
Bye

**Comment by dirkwhoffmann** [comment]
What I found out so far:

1. Emulator hangs in the game loader code, not the game. (Same game loader is used by Zack, same bug)
2. The loader seems to execute code on the VC1541 (VC1541 hangs in an infinite loop waiting for the ACK signal to change)
3.  As the code running on the VC1514 is peeking register PRA of the VIA chip, the reason might be the same as the reason why test via10 fails (which is also peeking PRA). 

Next steps: Fix test case via10.

**Comment by dirkwhoffmann** [comment]
Good and bad news: All "viavarious" test cases work fine now, but it doesn't solve the Maniac Mansion loader bug.

**Comment by dirkwhoffmann** [comment]
Found it. The culprit was the IEC bus interface which worked well with the original C64 kernel routines, but failed to work with some custom loaders (such as the eagle soft loader).

![maniac](https://user-images.githubusercontent.com/12561945/39622863-00a45592-4f94-11e8-9d28-f768ad66998c.png)
