### ISSUE TITLE
Tiny C64 screen 

### ISSUE THREAD

**Issue by DkWeb** [dirkwhoffmann/virtualc64#299]
After upgrading to the new version 1.8 the C64-screen is not using the whole window. Instead, it just uses a small area in the upper left corner (see screenshot). "Enter Fullscreen" or "Window -> Zoom" doesn't affect this problem.

My environment:
- Mac Book Pro (Mid 2012)
- macOS Sierra, 10.12.6

![small-window](https://user-images.githubusercontent.com/10188455/37255444-cfde885e-254c-11e8-91a9-19cc0d11f854.png)

**Comment by dirkwhoffmann** [comment]
Seems to be a problem related to Sierra (which is bad, because all my machines are running HightSierra :-( ). Does it also occur in 1.7.2?

**Comment by DkWeb** [comment]
I've just re-checked with 1.7.2 and some previous versions, too. The latest 1.5 version (that is 1.5.2) is the last version which runs fine on my machine. I'm a bit surprised that I've missed out so many releases. 

At the moment I don't want to upgrade to HighSierra because of APFs and some potential compatibility issues with other software. Maybe I can enable some debug-mode to collect some more information about what is going wrong?

**Comment by dirkwhoffmann** [comment]
Thanks for testing with different versions. For some reason, the 3D projection matrices are not initialized properly on Sierra. There have been a lot of under-the-hood changes in 1.6 (large portions of the old ObjC code have been ported to Swift and cleaned up), so it's hard to tell why it's going wrong. More interestingly, it's hard to tell why it's working in HighSierra.

**Comment by DkWeb** [comment]
Thanks for the info (and for VirtualC64 in general). Just give me a message in case you need some log output from the console-app or something like this.

I will hopefully be able to switch to HighSierra in a few days (or at least weeks) and I will definitely give you an update if this fixes the problem with VirtualC64 on my machine, too.

**Comment by DkWeb** [comment]
I have spend some time to search for the cause of this problem in the source code. I think the problem occurrs because of upscaling the C64 texture to 2048x2048 pixels (this is done in MetalSetup.swift at line 89). 

When I avoid this upscaling by simply setting those width and height values back to 512x512 everything seems to work fine. Maybe this problem arises because of the quite old Intel HD Graphics 4000 chip inside my MacBook: not quite sure if this chip really supports textures being that huge. But at least I would expect MTLDevice::makeTexture throwing some error or returning a null-pointer in case the current device doesn't support a texture which those dimensions. But maybe there is some other trick to detect the maximum supported texture size of the current device?

**Comment by Alessandro1970** [comment]
Goodmorning everyone,
if it can be of interest on my MBP with Intel HD Graphics 5000 and Intel HD Graphics IRIS there are no such problems.
Greetings

**Comment by dirkwhoffmann** [comment]
According to the specs, all metal enabled Macs should be able to handle textures up to 16384 x 16384 pixels.

When you hit reset and watch the rotating cube, does the cube cover the whole window area or just the upper left corner? If the cube is small, there might be something wrong with the projection matrices. If this is the case, the following functions might be the culprits (they handle window resizing and matrix stuff): adjustWindowSize(), reshape()

**Comment by DkWeb** [comment]
@dirkwhoffmann Unfortunately the cube has the expected, normal size, only the C64-texture is that small (as you can see from the attached screenshot). I've also colorized the background red and asked Xcode to draw only the wireframe (see the other screenshot): the mesh itself looks fine, it is just the texture which isn't "spanned" correctly.
![screenshot_reset](https://user-images.githubusercontent.com/10188455/37623761-19c83418-2bc6-11e8-9897-4cc16462333e.png)
![wireframe](https://user-images.githubusercontent.com/10188455/37623776-25a03b8c-2bc6-11e8-9f2c-d1e79d832d9c.png)

Nevertheless I've taken a short look at adjustWindowSize and reshape: the dimensions of the window look okay for me and also the matrices seem to have some sound values (although it is hard to be sure about this, because it is a real pain to check matrices within the Xcode debugger).

Any further ideas?

@Alessandro1970 thanks for your Feedback. But you did not mention what kind of macOS you are using. Do you use Sierra or High Sierra on your MBP?

**Comment by Alessandro1970** [comment]
...sorry, High Sierra last revision

**Comment by dirkwhoffmann** [comment]
OK, the cube is all right. My second guess would be that the texture cutout is wrong for some reason. The texture coordinates are set in function updateScreenGeometry (file MetalView.swift): 

textureRect = CGRect.init(x: rect.minX / C64Texture.orig.width,
                                  y: rect.minY / C64Texture.orig.height,
                                  width: rect.width / C64Texture.orig.width,
                                  height: rect.height / C64Texture.orig.height)

Could you perhaps replace it by: 

textureRect = CGRect.init(x: 0, y: 0, width: 1.0, height: 1.0)

This should render the whole texture on the quad (so one can see how the computed texture really looks like).

**Comment by DkWeb** [comment]
I've replaced the line you've mentioned, but the output is not very promising: the texture is still not "stretched" to the whole rect (as you can see from the attached screenshot).
![texture_rect_full](https://user-images.githubusercontent.com/10188455/37680808-4a6c13ea-2c85-11e8-9edb-2fbbcb635fcf.png)
By the way: I've asked a colleague to install and start VirtualC64 on his newer MBP with a retina display and an Intel Iris graphics chip and he has absolutely no problem with the texture. It is spanned over the full rectangle as expected, even with Sierra.

**Comment by dirkwhoffmann** [comment]
OK, now we definitely see the whole texture. The problem seems to be that the texture is really not upscaled. The simples upscaler is the bypassUpscaler in file Shaders.metal which is invoked when setting Upscaling to "none" in the emulator preference window. Internally, it simply does the following (nearest neighbour upscaling, each pixel is translated into a 2x2 square in the new texture): 

float rx = outTexture.get_width() / inTexture.get_width();
float ry = outTexture.get_height() / inTexture.get_height();
half4 result = inTexture.read(uint2(gid.x / rx, gid.y / ry));
outTexture.write(result, gid);

I guess that either rx, ry have wrong values (which could be tested by setting rx = ry = 4.0) or the texture size of outTexture is not 2048x2048 as expected. It's a really strange bug.

**Comment by DkWeb** [comment]
You are absolutely right: when I set rx = ry = 4.0 everything works fine on my machine (see attached screenshot). 
![rx_ry_set_to_4](https://user-images.githubusercontent.com/10188455/37734668-2770e344-2d4c-11e8-9b0f-3e2beca71730.png)

So, there must be some wrong values for the size of the in and out textures.

**Comment by DkWeb** [comment]
Unfortunately I can not debug the shader itself. But I've played a little bit around with the code in there. One interesting detail is, that it makes no difference if I write 
<pre>
float rx = outTexture.get_width() / inTexture.get_width();
</pre>

or
<pre>
float rx = inTexture.get_width() / outTexture.get_width();
</pre>
The resulting texture seems to cover always the same 1/4th of the screen, i.e. both values should be equal (so that the ratio between them should be nearly 1).

**Comment by DkWeb** [comment]
The strange thing is, that when debugging the apply-function of Shaders.swift I can confirm that the source and target textures within
<pre>
 encoder.setTexture(source, index: 0)
encoder.setTexture(target, index: 1)
</pre>
have the correct width value.

**Comment by dirkwhoffmann** [comment]
Great, it seems like we nailed it down. It's either a bug in the Metal API on Sierra or a non-retina problem. As a workaround, I'll use a constant as scaling factor (4.0) instead of computing it dynamically. It's not the nicest solution, but I don't know how to fix it in another way.

**Comment by DkWeb** [comment]
I think it isn't that bad to use a constant here: of course, whenever you decide to change the size of the textures in the future you will have to adapt the constant as well, but this shouldn't happen so often.

A possible alternative to the constant would be, to extend the parameter-list for the bypassupscaler with a ratio-parameter, calculate the correct value from swift before calling upscaler.apply(...) within MetalView.swift and just pass this calculated value to the shader. But I'm note quite sure if this is worth the trouble.

Thanks for all your help with finding this problem :-)

**Comment by dirkwhoffmann** [comment]
I just uploaded version 1.8.1 which uses a hard-coded scaling factor for the bypass upscaler. The code change only affects the bypass upscaler, because the EPX and the xBR upscaler already used constant factors. This means that the tiny texture issue should go away in 1.8. if one of these upscalers are selected. Or the other way round: If the EPX and the xBR upscalers are broken in 1.8.,  they will be still broken in 1.8.1.

I'm closing this issue in the hope that 1.8.1 really fixes the problem. If not, please reopen.
