### ISSUE TITLE
audio mutes when focus is moved to another window

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#300]
When I run a Prg inside VirtualC64 and then switch the window focus to another window eg: Safari, the Prg continues to run but the audio mutes. When I switch the window focus back to VirtualC64 by clicking anywhere within the VirtualC64 app, the audio unmutes and is audible. 

Perhaps this is by design but it appears a bit strange to me.I would assume the audio would continue as the Prg continues to exeute.

I tried switching the Sid chip but this didn't make any difference. I couldn't find any preferences related to this.

If this is by design perhaps you could implement a preference which when ticked allows the audio to continue when the window focus changes from VirtualC64.

Mac OS X 10.13.3
VirtualC64 1.8 (I've noticed this in 1.7 also).

Thanks for the great app!
Danny.

**Comment by Alessandro1970** [comment]
Sorry, I think that the audio must only work while the window is active, otherwise with other open applications only a hubbub can occur.

**Comment by Ottavius** [comment]
I had not read this discussion in the past. 
No, if you do not play it is better that you do not hear sounds or noises at the same time as other applications. 
For me the VirtualC64 it's ok as it is

**Comment by DannyCork** [comment]
I'd like to revisit this. Let me give an example.

Imagine if iTunes muted when it was in the background. 

Now imagine I'm watching a demo on Virtual C64 but also reading a webpage. When V64 is in the background, the demo continues but the sound is muted. Or imagine I'm playing a game and need to write an email, all of a sudden there is silence from V64.

Or imagine I'm performing video capture of the V 64 window in one screen. I have to stay on the v64 window and can't do anything else at all while the video is being captured as otherwise the audio mutes:(

It's a bit strange that V64 continues but the volume doesn't.

Perhaps to satisfy all this could be an option like don't mute while in background.

**Comment by dirkwhoffmann** [comment]
OK, your examples sound convincing to me. 

Instead of adding another "Don't mute while in background" option, we should probably bound it directly to the "Don't pause while in background" option (This options wasn't there when you first opened this issue and I'd like to keep the number of options as low as possible. There are already so many...). 

So in future, "Don't pause in background" is supposed to do the following:

CHECKED: Emulator keeps on running, sound keeps on playing
UNCHECKED: Emulator stops, sound stops.

**Comment by dirkwhoffmann** [comment]
Here comes a prototype of my proposed solution: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha9.zip

Now, a running emulator window only stops audio, if another emulator window becomes active. This is important if multiple emulator windows are open to prevent them playing simultaneously.

**Comment by DannyCork** [comment]
I've tested it as follows:
- V64 window out of focus.
- V64  window hidden.
- switched to a different MacOs X space.
-dragged V64 to a different MacOsX space.
-V64 window maximised.

The audio continues in all instances. This is excellent, many thanks!

**Comment by dirkwhoffmann** [comment]
Good to hear that it's working 😀.
