### ISSUE TITLE
No mouse over help info for floppy disk icon

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#301]
![untitled 2018-03-12 00-22-03](https://user-images.githubusercontent.com/3512672/37260473-7a0385b2-258b-11e8-83e9-a7aee97234a8.png)

There is no mouse-over help info for floppy disk icon in the bottom left corner of VirtualC64. I've tried hovering over the floppy disk for 5 seconds but nothing appears.

The "Connect/Disconnect Drive" and "Drive led" icons display help text when the mouse hovers over them. I imagine the floppy disc icon should also.

**Comment by dirkwhoffmann** [comment]
The disk icons solely purpose is to indicate that there is a disk inside. In former releases, there was an eject button next to the disk icon. The eject button has been removed because of the new "Disk" menu in the menu bar which now contains this functionality.
