### ISSUE TITLE
VirtualC64 ends after closing the untitled window

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#304]
Hi,

very often VirtualC64 ends after I close the untitled window on the left. See the photos.
Generally I start the emulator, I opend a disk image so a new tab starts, then I close with the mouse the tab "untitled" on the left and the emulator ends. 

<img width="806" alt="schermata 2018-03-24 alle 09 30 50" src="https://user-images.githubusercontent.com/34916641/37862083-8f5b77e2-2f47-11e8-92b0-10d78dc95a97.png">
<img width="452" alt="schermata 2018-03-24 alle 09 35 57" src="https://user-images.githubusercontent.com/34916641/37862085-926774c2-2f47-11e8-88bd-b1a521fd6336.png">

<img width="805" alt="schermata 2018-03-24 alle 09 30 34" src="https://user-images.githubusercontent.com/34916641/37862070-6560451c-2f47-11e8-9c7f-3cf478e2e1c7.png">

[VirtualC64_error.txt.zip](https://github.com/dirkwhoffmann/virtualc64/files/1844187/VirtualC64_error.txt.zip)

**Comment by dirkwhoffmann** [comment]
According to the crash report, the emulator crashes in the touch bar code when updating NSScrubber. An NSScrubber ist used to display the small snapshot images on the touch bar. I guess the GUI is trying to update the touchbar, but does not check if the underlying emulator is still there.

**Comment by dirkwhoffmann** [comment]
Fixed in 1.9. Unfortunately, Maniac Mansion is still not working.
