### ISSUE TITLE
Tab key is not recognized as key press

### ISSUE THREAD

**Issue by troydm** [dirkwhoffmann/virtualc64#311]
When using [Map keys by Position] Tab key is completely ignored no matter what key it's bidden to in the key matrix

**Comment by dirkwhoffmann** [comment]
Thanks for reporting! The problem seems to be  that the event loop reacts on the tab key by shifting the focus to the next GUI element. As a result, no keyDown event is triggered in the KeyboardController. Unfortunately, I didn't find a way to get around this, yet, but I'll keep looking.

**Comment by dirkwhoffmann** [comment]
Will be fixed in the next release. 

The TAB key is recognized if the emulator windows is used as first responder for keyboard events. In the old implementation, events are handled by the keyboard controller which does not get informed about the TAB key.
