### ISSUE TITLE
Arkanoid game with mouse emulation

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#312]
Hi,
Thank you for this great c64 emulator for mac. 
Is there a way to play arkanoid with a magic mouse using the emulation for 1351 commodore mouse ?

---
 
[](https://www.c64-wiki.com/wiki/Mouse)

**Comment by dirkwhoffmann** [comment]
The magic mouse is not supported, yet. I'll try to support it in one of the next releases.

**Comment by puleyo** [comment]
Thank you

**Comment by dirkwhoffmann** [comment]
VirtualC64 1.11 will support three mice models (C1350, C1351, and Neos):

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_1_11_beta.zip

Any feedback on the beta version is highly appreciated.

**Comment by Ottavius** [comment]
It's ok for me with neos emulation

**Comment by Alessandro1970** [comment]
I tried different levels of Arkanoid 1 and Arkanoid 2 just this morning using the NEOS MOUSE. Everything works perfectly, OK for me!

**Comment by puleyo** [comment]
Many thanks ARKANOID also works to me with the neos.

But where did you find Arkanoid the Revenge of DOH? I would like to try it too !!!

**Comment by Alessandro1970** [comment]
You can look on this website:
http://www.planetemu.net/rom/commodore-c64-games-d64/arkanoid-2-revenge-of-doh-1988-imagine-software-cr-flt-t-2-flt

**Comment by dirkwhoffmann** [comment]
Fixed in V1.11
