### ISSUE TITLE
WeComeInPeace.d64 not working

### ISSUE THREAD

**Issue by AdamBazaroff** [dirkwhoffmann/virtualc64#320]
Great emulator! But it can’t run some new demos :(
For example WeComeInPeace.d64. After RUN it’s load and load and load... from floppy
VICE users says me it’s because no «true drive emulation». Howto do it?

**Comment by Ottavius** [comment]
Hi AdamBazaroff,

I just tried today all what you said !
Yes, using Vice if you load WeComeInPeace.d64 with "True Drive Emulation ON"- it works.
If one load and run WeComeInPeace.d64 without the "True Drive Emulation" [OFF] it does not load data from .d64 and it hangs like VirtualC64.

I do not know the meaning of this option but WeComeInPeace.d64 is the first disk that do not work with my VirtualC64...

**Comment by AdamBazaroff** [comment]
Many big demos for C64 won't run in VirtualC64 :( This is big problem, because VICE for Mac is very ugly.

**Comment by dirkwhoffmann** [comment]
Drive emulation is still somewhat limited in VirtualC64. In 1.10, emulation of both VIA chips has been improved considerably (nearly all VICE tests are passed), but the rest is still far less accurate than the emulation in VICE or Hoxs64.

**Comment by Alessandro1970** [comment]
Hello to all,
if you are interested in trying this demo, you can download it at this address:

[http://csdb.dk/release/download.php?id=201985](url)

**Comment by Alessandro1970** [comment]
Good morning,
I also tried the following demo but it does not work.
I noticed that on VICE 3.1 of a friend of mine with the "TRUE DRIVE EMULATION" option on it works correctly; but if we remove the "TRUE DRIVE EMULATION" option the VICE does not load the demo.

Is it possible for you to import the routines related to the "TRUE DRIVE EMULATION" from the VICE and insert them in the VIrtualC64 code ?

Demo [Incoherent Nightmare]: https://csdb.dk/release/?id=151257

**Comment by puleyo** [comment]
Hello,
I tried the Redefinition demo but it does not work; using VICE 3 on my Mac only works if True Drive Emulation is enabled.
Also I would be very happy if you can implement this option in the VirtualC64 that for mac is the maximum.
Thank you

https://csdb.dk/release/?id=130309

**Comment by Ottavius** [comment]
... could be the problem that in the emulator there is no option to read floppy disks images using 40 track.
I noticed, I believe, that VirtualC64 can not access the disk image when the demo starts. 
It seems that this demo accesses the disk to load data frequently.
Bye

**Comment by Alessandro1970** [comment]
It could be that the demo is structured on the floppy with files hidden in a "linear" way for the loading order. 
It could be a way to work that will be the same as the next file but maintaining an exact position from which to read the new file, and the emulator could not know where to read or where to start reading.

**Comment by Ottavius** [comment]
Is it possible that the problem to emulate this demo is only a multiload system error ?

**Comment by dirkwhoffmann** [comment]
In version 2.1, the following demos will load smoothly: 

We come in peace
Redefinition
Incoherent Nightmare

<img width="835" alt="nightmare" src="https://user-images.githubusercontent.com/12561945/41995816-456eee1e-7a53-11e8-99b4-60163fe4d839.png">

The new source code is already checked in. However, the drive emulation is still far from being perfect. E.g., all copy protection mechanisms that manipulate the density of the disk bit stream (physical length of a single bit on disk) won't work.

**Comment by Alessandro1970** [comment]
Great, I do not look forward to try this new version! 
Thank you.

**Comment by dirkwhoffmann** [comment]
V2.1 is online
