### ISSUE TITLE
Operation Wolf and VirtualC64

### ISSUE THREAD

**Issue by Alvarez81** [dirkwhoffmann/virtualc64#321]
Hello to all,

how can I configure the mouse to play Operation Wolf?

Greetings, superb emulator 

![99230](https://user-images.githubusercontent.com/39189763/39922317-d8af9c78-551e-11e8-9044-be551b3986e0.gif)

**Comment by Alessandro1970** [comment]
Hi,
... you have to wait until the support for 1351 is available, it seems to be in the next version. 
I had already reported it to be able to use the mouse with the GEOS under VirtualC64.

**Comment by dirkwhoffmann** [comment]
VirtualC64 1.11 will support three mice models (C1350, C1351, and Neos):

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_1_11_beta.zip

Any feedback on the beta version is highly appreciated.

**Comment by Alvarez81** [comment]
Oh yes, I succeed in doing it. All works fine, thank you

**Comment by dirkwhoffmann** [comment]
Fixed in V1.11
