### ISSUE TITLE
DEZ ?

### ISSUE THREAD

**Issue by Ottavius** [dirkwhoffmann/virtualc64#324]
What do we mean by the abbreviation DEZ?

![bildschirmfoto-2012-07-02-um-22 00 32_thumb](https://user-images.githubusercontent.com/38980466/40051432-ff171962-583a-11e8-8e87-187ed59f1c8b.jpg)

**Comment by Alessandro1970** [comment]
...ehm, in English "dec" (decimal).
Dez is an abbreviation derived from the dezimal in German.
