### ISSUE TITLE
Game "Destiny" (1985) hangs

### ISSUE THREAD

**Issue by ChuckCaplan** [dirkwhoffmann/virtualc64#328]
What are some things I can do to troubleshoot a game that freezes? There is a game called Destiny from 1985 that is 2 disks (the filenames I have seen are DESTINY0.D64 and DESTINY1.D64). About halfway through the game you need to switch to disk 2, so I drag the disk 2 file to the screen, it loads, and the game continues. Then on the first screen using disk 2, I click on something and the game freezes. In the monitor it keeps looping over and over on these addresses:
E5CD,A5,C6,,LDA C6
E5CF,85,CC,,STA CC
E5D1,8D,92,02,STA 0292
E5D4,F0,F7,,BEQ,E5CD

Is there anything I can do to debug further and see what is going on, and potentially get past the issue? Thanks for your help.

**Comment by dirkwhoffmann** [comment]
Unfortunately, there is not much you can do unless you want to debug the game deeply in XCode. When a game hangs in a loop such as the one you mentioned, it is most likely because of an error that occurred many CPU cycles earlier. If a game works in VICE (which is likely), I usually run the faulty game in VirtualC64 until the error occurs.Then, I hit "Rewind" to revert to the last auto-save snapshot and invoke CPU tracing. I then try to run the game in VICE, set a breakpoint in the debugger and try to compare the CPU traces line by line. This doesn't work in all cases, because it's often hard to break at the proper location. Remember that the CPU processes 1.000.000 micro instructions per second (which is about 250.000 assembler commands) and there are a lot of side effects going on (interrupts, VIC DMA accesses etc.).

**Comment by Alessandro1970** [comment]
Hi ChuckCaplan,
1) I could not try the game right now, but could you send me the game screen where it crashes ?
       (I normally make screenshots in OSX with command-shift-4, so I can select an area: the game area)
2) Could you meanwhile try if the game also crashes with this version?

**Disk A:** _http://www.planetemu.net/rom/commodore-c64-games-d64/destiny-1985-destiny-software-side-a-cr-starforce_
**Disco B:** _http://www.planetemu.net/rom/commodore-c64-games-d64/destiny-1985-destiny-software-side-b-cr-starforce_

**Comment by ChuckCaplan** [comment]
Hi,

Here is a screenshot.  If I choose LOOK and click on the large circle on the left side of the screen, it says:
THERE IS AN OLD BILL LAYING
THERE FROM THE PIRANHA
DISPOSAL COMPANY.

But if I click GET and try to get the bill, or if I try almost any of the other non-DIRECTION buttons, my mouse pointer goes away and the game freezes. The same thing happens if I use the DIRECTION buttons to move to other screens on disk 2, and then try commands on those screens. Disk 1 does not have an issue.

I tried the disks Alessandro referenced but they did the same thing. I didn't do a binary compare, but the files are the same size as mine so I assume they are the same. I also tried this in an online emulator, and the same thing happened, so it doesn't look specific to VirtualC64

Thanks for looking at this, everyone.

Chuck

![screen shot 2018-06-04 at 9 57 21 pm](https://user-images.githubusercontent.com/22998682/40950820-580ccc94-6842-11e8-83d3-580439697420.png)

**Comment by Alessandro1970** [comment]
Hi ChuckCaplan,

I have found that the problem does not concern any emulator. Destiny is protected with "Rapidlock" and does not work in PAL mode, you need the right crack, the Starforce version is corrupted.
At the moment I think the best thing you can do is to try this version which should have the protection removed:
ftp://arnold.c64.org/pub/games/d/Destiny%20[Software_Investments_Plus_1985](cracked).zip

Let me know, Destiny is a great game, I had never played it unfortunately, but now I'll try ...

**Comment by ChuckCaplan** [comment]
That version works! Thank you so much!  I appreciate you spending so much time to help me with this. I read up on Rapidlok and it is fascinating that a game like Destiny would use such complex copy protection.

**Comment by Alessandro1970** [comment]
Great! I'm very happy that you can play Destiny with the VirtualC64 !
... also many thanks to Dirk who is making a masterpiece with VirtualC64.
I'm really waiting for the new version with the DiskDrive management improvements !!!
Thanks Dirk!
... and a healthy beer for all CBM64 virtual friends!

**Comment by ChuckCaplan** [comment]
Thank you both!
