### ISSUE TITLE
"Blast from the past vol. 004": Disk loader hangs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#329]
LOAD "*",8,1 brings up a selection menu. When hitting, e.g., 1, the loader stops and the ready prompt appears. Loading the games directly seems to work, so it's most likely an issue with the fast loader code.

**Comment by Ottavius** [comment]
Hi,
I tried to load the disk with the vice without the True Drive Emulation option and the problem also occurs with this emulator.
But with VICE if I remove the TRUE DRIVE EMULATION I do not even load the directory with LOAD "$", 8 even if the disk is inserted and without resetting if the TRUE DRIVE EMULATION is active instead it loads the directory ...
I believe it is the same problem as in issue # 320 and # 319 (all duplicate)

**Comment by parecibo** [comment]
I would like to try, where did you find "Blast from the past"b?

**Comment by Ottavius** [comment]
http://www.theisozone.com/downloads/retro/commodore-64/blast-from-the-past-1-340/

**Comment by parecibo** [comment]
Thanks

**Comment by dirkwhoffmann** [comment]
BTW, the loader has a really cool intro sound.

**Comment by dirkwhoffmann** [comment]
When the disk is ejected after the the loader terminates unexpectedly, the emulator warns about an unsaved disk. Maybe the drive implementation changes into write mode for some reason and corrupts the disk. Needs more investigation ...

**Comment by Alessandro1970** [comment]
...corrupts the disk ?
Have you tried to load the corrupted disk, in the second time, on another emulator (VICE)?
Does it work or is it permanently damaged?
The disk n. 004 on the VICE works but I have not checked if after using it with the Virtualc64 it will be damaged.

**Comment by dirkwhoffmann** [comment]
Good point. I tried to load the re-saved disk in VICE and it works. It must be something else.

**Comment by Alessandro1970** [comment]
Hi Dirk,

I tried the following disks with the VirtualC64:
blast004
blast031
blast039
blast048
I noticed that the menu starts correctly and then the chosen game stops during loading.
But I have noticed that if you load any game directly es.
LOAD "3", 8
RUN
all games work perfectly, so I think the problem is only in an incompatibility of the loading menu.

<img width="749" alt="schermata 2018-06-30 alle 08 40 51" src="https://user-images.githubusercontent.com/34916641/42122450-51ec140a-7c42-11e8-8734-b5d7a1488163.png">

**Comment by dirkwhoffmann** [comment]
Findings: On the drive side, the CPU hangs in a loop:

    F55D: 2C 05 18   03 12 00 33 NV-BdIzC BIT 1805
    F560: 10 F1      03 12 00 33 NV-BdIzC BPL F553
    F562: 2C 00 1C   03 12 00 33 NV-BdIzC BIT 1C00
    F565: 30 F6      03 12 00 33 NV-BdIzC BMI F55D
    F55D: 2C 05 18   03 12 00 33 NV-BdIzC BIT 1805
    F560: 10 F1      03 12 00 33 NV-BdIzC BPL F553
    F562: 2C 00 1C   03 12 00 33 NV-BdIzC BIT 1C00
    F565: 30 F6      03 12 00 33 NV-BdIzC BMI F55D
    F55D: 2C 05 18   03 12 00 33 NV-BdIzC BIT 1805

Might be related to a faulty handling of the PB7 pin which can be configured to generate pulsed on timer underflows.

**Comment by dirkwhoffmann** [comment]
Decoupling the VC1541 clock from the C64 clock fixes the problem. However, test case rpm.prg is broken now.

**Comment by dirkwhoffmann** [comment]
Replaced by #350
