### ISSUE TITLE
Cartridges and buttons

### ISSUE THREAD

**Issue by Ottavius** [dirkwhoffmann/virtualc64#332]
Hi all,
I would like to know which keys I need to press to use the buttons on the cartridges.
Example: if I insert a .crt file related to a generic cartridge with a **reset button** [B] and a **freezer button** [A] (like in photo) how does it work in VirtualC64 ? 
Which keys correspond to the buttons of the emulated cartridge?
Would it be possible to have the **two buttons [A] and [B] in the toolbar** to be able to use them with the mouse of the mac?
Thank you

![300px-fc3_modul](https://user-images.githubusercontent.com/38980466/41642802-a633e2e4-7469-11e8-916e-e6ebf5f60c55.jpg)

**Comment by dirkwhoffmann** [comment]
The onliest supported cartridge with buttons is the Final Cartridge III. If you attach it to the emulator, you will be able to push the buttons via the "Cartridge" menu. There is a special menu item named "Final Cartridge III". To my shame, I didn't test the FCIII cartridge in V2.0, so I hope I did not break anything.
