### ISSUE TITLE
Final Cartridge III

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#336]
In version 2.0 the Final III cartridge does not work anymore.
Both in the 1987 version and in the 1988 version the reset button used one or more times stops.

[Cartridge] http://www.lemon64.com/?mainurl=http%3A//www.lemon64.com/apps/list.php%3FGenre%3Dcarts
<img width="760" alt="schermata 2018-06-23 alle 10 48 42" src="https://user-images.githubusercontent.com/34916641/41807751-e47443ac-76d3-11e8-87f1-a4dbc0d4d289.png">

<img width="1066" alt="schermata 2018-06-23 alle 10 50 38" src="https://user-images.githubusercontent.com/34916641/41807753-e77462e4-76d3-11e8-8962-b7f4057cb9e2.png">

**Comment by dirkwhoffmann** [comment]
Ups, OK, I'll look into it.

**Comment by Alessandro1970** [comment]
Thank you
However VirtualC64 works very well with the Simon's Basic cartridge, I have tried several programs with it.

<img width="762" alt="schermata 2018-06-23 alle 10 43 14" src="https://user-images.githubusercontent.com/34916641/41817493-42231d20-779c-11e8-8738-371bd0014193.png">


<img width="760" alt="schermata 2018-06-23 alle 10 44 29" src="https://user-images.githubusercontent.com/34916641/41817496-4912c540-779c-11e8-8f9f-2a6c0780f6b7.png">

**Comment by dirkwhoffmann** [comment]
Simple thing: The final cartridge III reset routine does this: 

    memcpy(ram, c64->mem.ram, 0xFFFF);
    c64->reset();
    memcpy(c64->mem.ram, ram, 0xFFFF);

As this code is executed outside the emulator thread, the emulator needs to be halted while doing these operations. So, the solution is pretty simple:

    c64->suspend();
    memcpy(ram, c64->mem.ram, 0xFFFF);
    c64->reset();
    memcpy(c64->mem.ram, ram, 0xFFFF);
    c64->resume();

**Comment by dirkwhoffmann** [comment]
Fixed in V2.1
