### ISSUE TITLE
The window title does not change by inserting a disk

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#340]
Hi,
When I insert a disk (eg demo.d64) the title of the window above the toolbar will always be "**untitled**" and not the name of the inserted disk (eg demo.d64).
If the window shows the name that of the newly inserted disk it would be easier to avoid confusion when using many disks.

<img width="757" alt="schermata 2018-06-30 alle 09 40 32" src="https://user-images.githubusercontent.com/34916641/42122997-b667a7fc-7c4a-11e8-9d80-e113510df601.png">

**Comment by Ottavius** [comment]
I also noticed, sometimes the name changes and sometimes remains the untitled written especially when you insert a single disk and it is not updated.

**Comment by Alessandro1970** [comment]
Hello
I tried with different disks but this problem only occurs with those that have the name written incorrectly, renaming the file the problem disappears.
It is not a defect of the VirtualC64
Greetings
