### ISSUE TITLE
Ram Expansion Unit (REU) and geoRAM

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#341]
Hi,
Is there a way to add the REU to the VirtualC64?

<img width="765" alt="schermata 2018-06-30 alle 09 57 30" src="https://user-images.githubusercontent.com/34916641/42123085-3825a360-7c4c-11e8-8854-cfc8bbce9527.png">

Demo:
[BluREU_Crest_demo.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2151531/BluREU_Crest_demo.prg.zip)

**Comment by Ottavius** [comment]
Great. Does this memory expansion also work with Geos?

**Comment by dirkwhoffmann** [comment]
REU is not supported yet, but it shouldn't be too difficult to emulate it.

**Comment by Alessandro1970** [comment]
**_1764_ RAM EXPANSION UTILITY DISK**
**Side A:** 
[1764-utility.d64.gz](https://github.com/dirkwhoffmann/virtualc64/files/2154823/1764-utility.d64.gz)
**Side B:**
[1764-utility-geos.d64.gz](https://github.com/dirkwhoffmann/virtualc64/files/2154826/1764-utility-geos.d64.gz)

**Comment by Ottavius** [comment]
Would not it be better to add the emulation of the GeoRAM instead of the REU?

**Comment by Alessandro1970** [comment]
Ottavius, ask to Dirk about it, open an issue if you need it.

**Comment by dirkwhoffmann** [comment]
I didn't look into the details yet, but it shouldn't be too difficult to implement both. I'll look into it when I'm done with the VC1541 improvements.

**Comment by Alessandro1970** [comment]
Thank you Dirk

**Comment by puleyo** [comment]
Georam would be an another great add-on for me too.

**Comment by dada08ms** [comment]
Hello,
I am very happy when I will can use the REU in this great emulator; so we will can use the software RAMDrives with the VirtualC64.
Do you think that it will be possible to choose the amount of memory to associate with the REU ?
[256kb, 512kb and at least 1mb]

**Comment by Alessandro1970** [comment]
Originally the REU for commodore 64, I think, it was only 256 kb, but I can be wrong.

**Comment by dirkwhoffmann** [comment]
I did some research and found out the following: The REU's internal architecture is much more complicated than I thought originally, so I'm not sure if it is worth implementing. In contrast, the geoRAM seems to be quite easy to implement, because it simply has to blend in a certain page of the external RAM (no complicated memory transfer is required).

**Comment by Alessandro1970** [comment]
GEORAM is a 512K memory expansion unit made by Berkeley Softworks for use with GEOS. It can also be used for other programs. There are several programs that support GEORAM though, for example Maniac Mansion GOLD.
Neoram drive also works with georam (to use georam instead neu as ramdrive).
A ramdrive for NEO-ram and compatibles (i.e. GEOram).
NEOram being a modern batterie buffered version of georam with up to 2mb. 
Fully compatible to GEOram so you can use this with georam just as well.
The BLOCKS FREE is hardcoded to 2mb though, but can be used with 512KB.
check label "ramsize" and change i.e. to #$07 for 512 KB
Device-No is set to 2.
Use POKE 2,X to set device to X (8 also works btw)
also nice: use 1 and you can press SHIFT+RUN/STOP in directory listing!

Commands:
LOAD"$",2 for directory
LOAD"file",2(,1)
SAVE"file",2(,1)
VERIFY"file",2(,1)

further commands:
to INIT the drive use "arrow-left" as first char of filename! I.e. 
LOAD"<=",2,1 or LOAD"<=FILE",2 
will format the ram expansion.
f that happens accidentally, repair with NEOram Monitor since
only 4 bytes were overwritten

to SCRATCH a file use POUND-sign (%) as first char in filename:
LOAD"%file",2,1 
will scratch the file named "file".

Code currently at $ca00 so the LOAD-limit is about 193 blocks.
for basic loaders: about 153 blocks.

This version initialises the kicker that remains in NEOram.
You can launch it with SYS57000 or SYS57E3 anytime!
Due to the batterie buffer it is resistant and 
can be launched even after several days/weeks/months.
Source: https://csdb.dk/release/?id=61122&show=summary

**Comment by Alessandro1970** [comment]
Maniac Mansion GOLD [neoram]
https://csdb.dk/release/?id=84165

**Comment by Alessandro1970** [comment]
...NEOram emulation could be a solution for geos, ramdrives and some software.

**Comment by dirkwhoffmann** [comment]
<img width="835" alt="georam" src="https://user-images.githubusercontent.com/12561945/42733593-d8bb61b4-8833-11e8-9743-a4e80573fa85.png">

GeoRAM will be available in V2.3 (code is already checked in, branch V2.3). The NeoRAM seems to use the exact same hardware, so I guess it will work, too (at least, the NeoRAM drive application is working fine).

**Comment by Alessandro1970** [comment]
Georam works fine: Thanks
Why cannot I select any disk drive 9 ?

<img width="773" alt="schermata 2018-07-19 alle 22 52 56" src="https://user-images.githubusercontent.com/34916641/42969931-18e5bf4c-8ba8-11e8-80a0-c51357420b3a.png">
