### ISSUE TITLE
Enable the CP / M cartridge

### ISSUE THREAD

**Issue by ZieglerLaura** [dirkwhoffmann/virtualc64#348]
Hello, I would like to be able to get the CP / M back, I have the images of the disks but I can not start them.
Is there a way to enable the CP / M cartridge ?
Thank you very much for your help.
Greetings, Laura

**Comment by dirkwhoffmann** [comment]
Unfortunately, there is no way to use the CP/M module. This module contains a lot of custom hardware (e.g., a Z80 processor), so it's like a second computer that is connected to the C64 via the expansion port. Supporting this module would mean to emulate a second, completely different computer which can't be done with respect to the available development resources.

**Comment by Ottavius** [comment]
Hello everyone, I have noticed this issue closed for a long time but I remembered to have something about the source files of the CPM cartridge for the Commodore64 and also some scheme, could be useful?

[Cartridge_CPM_SOURCECODE.zip](https://github.com/dirkwhoffmann/virtualc64/files/2253985/Cartridge_CPM_SOURCECODE.zip)
![cpmmodul-schema](https://user-images.githubusercontent.com/38980466/43592148-39e18866-9675-11e8-93ef-b92eeb32e5f9.gif)
![cpmz80](https://user-images.githubusercontent.com/38980466/43592153-3c047392-9675-11e8-8f3d-e744bc72c5b1.gif)
![img_8936](https://user-images.githubusercontent.com/38980466/43592165-3f0a992c-9675-11e8-9b5a-a51064885ac7.jpg)

Those vatic of the VICE have it and they say it works, could we have it on our VirtualC64?

**Comment by Alessandro1970** [comment]
An hardware zx spectrum core for c64! :laughing:

**Comment by dirkwhoffmann** [comment]
Yes, it's a nice module, but as said in my post above, it would require to emulate a second computer. We would need to hire some developers first. 

If you don't mind, I close this issue again.
