### ISSUE TITLE
Fast loader incompatibility (BuggyBox, watchdog)

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#350]
Test cases watchdog.prg, rpm.prg, and BuggyBoy are closely related. 

Current situation (code on TrueDrive branch): 
Clocking drive with 1 MHz:         BuggyBoy succeeds, watchdog and rpm fail.
Clocking drive with C64 speed: BuggyBoy fails, watchdog and rpm succeed.

When running with 1 MHz, the following sequence is possible: 
executeC64()
executeDrive()
executeDrive()
executeC64()

This seems to break the fast loader used by watchdog.prg and rpm.prg.

Next steps: Unsure

**Comment by dirkwhoffmann** [comment]
Update: Even a small derivation between both frequencies break watchdog.prg. It seems like two consecutive calls to VC1541::executeOneCycle() break the test.

**Comment by dirkwhoffmann** [comment]
Culprit: Class CPU uses write delayed variables for implementing IRQ handling. These variables always read the C64 clock which is wrong when both CPUs are decoupled. 

TODO: Add a separate clock counter to class CPU. For the C64 CPU, this counter will always match the C64 clock. For the VC1541 CPU, both counter values will diverge.

**Comment by puleyo** [comment]
Hi,
I think all of you are right.
In my opinion the best solution to appreciate the characteristics of the legendary Commodore64 is to get as close as possible to reality.
Certainly the Commodore64 behaved differently than the television or monitor to which it was connected.
Personally, I preferred my SonyTriniton TV to the Commodore monitor, so _it could be a good thing that CRT + blur system_ (a kind of very soft blur) for the emulator.
The same thing for color management, fortunately there are different Palettes to use with the emulator, although I'm trying for more than a month to vary the combinations individually to get a result (in my eyes) appreciable, empirically I approached the mac monitor with the emulator (full screen) to my Commodore64 attached to the TV / Monitor, displaying both all the colored stripes ... it's not easy anyway.

**Comment by dirkwhoffmann** [comment]
Fixed. #351 is a follow up.
