### ISSUE TITLE
Diag C64 (586220) Cartridge fails interrups test

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#355]
Hi,
I realized that VirtualC64 does not pass the interrupts test foreseen in the diagnostic chart diag-c64_586220.
Is it normal for the emulator ?

<img width="778" alt="schermata 2018-07-08 alle 10 30 26" src="https://user-images.githubusercontent.com/34916641/42418196-7539222c-829b-11e8-905a-86479989ee96.png">

[C64 Diag 586220.zip](https://github.com/dirkwhoffmann/virtualc64/files/2173508/C64.Diag.586220.zip)

**Comment by dirkwhoffmann** [comment]
I tried the cartridge in VICE and it shows the same result. 

The cartridge is meant to be used via a user port hardware adapter which makes some external signals visible. I guess this is the reason for the failing test. 

I didn't try the cartridge in Hoxs64. If it shows the same result there, we should close the issue.

**Comment by Alessandro1970** [comment]
Hi,
I tried to use the cartridge on the HOSX64 on a PC of a friend of mine and as you have already said the situation does not change, here is the screen.
I close the issue.
Greetings

![untitled 2](https://user-images.githubusercontent.com/34916641/42431843-1009264c-8348-11e8-9849-08d44a04477a.jpg)

**Comment by dirkwhoffmann** [comment]
Alessandro, thank you very much for trying the cartridge in Hoxs64. In principle, those test cases are great, because they give us the chance to track down bugs in a limited program scope.
