### ISSUE TITLE
Action Replay VI and VirtualC64

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#357]
Hello to all.
I also owned the **Action Replay 6** cartridge and I was very happy with this.
Is there a way to get it started in VirtualC64?
How do the cartridge buttons work with the emulator?
Please, help me.

[action_replay_6.zip](https://github.com/dirkwhoffmann/virtualc64/files/2174987/action_replay_6.zip)

**Comment by Alessandro1970** [comment]
Oh yes, I had almost forgotten, now I'm too old, big days in those days!
The legendary Action Replay, beautiful.
Excellent mon editor and a lot of tools like the poke enterer, screen saver/editor, the disk fastloader...
Magnificent cartridge !!!

![action_replay_vi_6](https://user-images.githubusercontent.com/34916641/42436888-b2c328ac-835b-11e8-952e-bc3273fcaa31.jpg)

**Comment by Ottavius** [comment]
This cartridge is very much appreciated for me, let me know how I can use this with VirtualC64.
Do you have a quick guide?

**Comment by Alessandro1970** [comment]
You have to download the Puleyo's file, look inside, you will find the manual in English.

**Comment by Ottavius** [comment]
Ok done, Thank you. 
But VirtualC64 does't work with the Action Replay !
What am I doing wrong?

**Comment by Alessandro1970** [comment]
I don’t know. 
Probably It should still be implemented, I will try tonight at home. Now I cannot.

**Comment by Alessandro1970** [comment]
It is not supported yet.

**Comment by dirkwhoffmann** [comment]
The Action Replay cartridge needs a custom implementation similar to the Final Cartridge III. I'll put it on top on the list of the cartridges to be supported.

**Comment by Alessandro1970** [comment]
hi,
can someone tell me where I can find (download) the ActionReplay 3 .CRT file?
Thanks

**Comment by dirkwhoffmann** [comment]
http://ar.c64.org/wiki/Action_Replay

Scroll down and download 

Action_Replay_all_rr.c64.org_2013-01.rar

I'm trying to make the cartridge work, but I didn't succeed so far.

**Comment by dirkwhoffmann** [comment]
If you stumble across a schematics of the V3 version, please let me know.

**Comment by Ottavius** [comment]
Why AR MK3 ? ...it is buggy!
Version 4 or version 6 instead work well.

**Comment by Alessandro1970** [comment]
I  have found something here:

http://przychodnia-jawor.pl/temp/Commodore%2064/C64%20Cartridges/Action_Replay/AR_Sources/
http://przychodnia-jawor.pl/temp/Commodore%2064/C64%20Cartridges/Action_Replay/

**Comment by dirkwhoffmann** [comment]
I started with version 7.5., but I didn't get it to work. When selecting the fast loader, it resets to the main screen (current code in V2.3 branch, if you want to compile it with XCode). Therefore, I decided to go for AR3 first, because it has simpler hardware (no onboard RAM).

**Comment by Alessandro1970** [comment]
http://rr.c64.org/wiki/Inside_Replay_Essentials.txt

**Comment by dirkwhoffmann** [comment]
I made some progress on AR3. When the cartridge is attached and the freeze button is pressed, the AR3 menu comes up as expected. I didn't test all features extensively, but I was able to use to freezer to backup a running game to an empty disk and reload it from there. However, as I never had an AR cartridge, I don't know exactly how the correct behavior should be (especially for the other features). 

I have set up a beta version which can be downloaded here:

http://www.dirkwhoffmann.de/VirtualC64_2.3_beta1.zip

This version also supports the GeoRAM (use the cartridge menu to attach it). I didn't test it with Geos yet, but it seems to work well with the drive tool app that was mentioned in the GeoRAM thread.

**Comment by dirkwhoffmann** [comment]
AR7.5 also looks much better now: 

http://www.dirkwhoffmann.de/VirtualC64_2.3_beta2.zip

However, I think there is some incompatibility between the AR7 fast loader and the current drive implementation. While testing, I experienced some read failures from time to time. Please let me know if you experience similar issues.

**Comment by dirkwhoffmann** [comment]
There is definitely a problem with the AR7 fast loader. Hard to say, if it is related to the drive implementation or the AR cartridge implementation.

**Comment by dirkwhoffmann** [comment]
The cartridge itself seems to work, but the current drive emulation does not seem to be accurate enough. Issue #363 is a follow up.

**Comment by Alessandro1970** [comment]
The best-selling cartridges were Action Replay MK IV (1988) and Action Replay MK V (1989) in my opinion would be to enable only these. 
Few will have bought the VI ...
If you can add MK III, IV and V it would be the best...

**Comment by dirkwhoffmann** [comment]
IV, V and VI seem to use the exact same hardware. The issue with the AR7 fast loader is interesting by itself, because it points to a more general bug in the drive emulation code.

**Comment by Alessandro1970** [comment]
I haven't tried the fastoload but the cartridge MKIV works fine.
