### ISSUE TITLE
Add ISEPIC Cartridge support

### ISSUE THREAD

**Issue by dada08ms** [dirkwhoffmann/virtualc64#367]
Hi Dirk,
Please, could you add the support for the ISEPIC cartridge with its 2kb RAM and with the possibility of using its swicht in two ways ?
Thank you very much.
Bye

_The isepic cart has a switch which controls if the registers and ram is mapped in.
 When the switch is switched away from the computer the cart is put in 'hidden' mode,
 where the registers, window and ram is not accessable.
 When the switch is switched towards the computer the cart is put in ultimax mode,
 with the registers mapped, and the current page being mapped into any unmapped ultimax
 memory space, it will also generate an NMI. Which activates the freezer._

[ISEPIC.zip](https://github.com/dirkwhoffmann/virtualc64/files/2212694/ISEPIC.zip)

**Comment by Alessandro1970** [comment]
I also had the Freeze Frame cartridge and it's definitely the one I used the most for ease of use.
It was enough to load the program or game, then press the "free" key and then the "T" key to save to tape or "D" to save to disk.
Nice product, cheap and versatile.
If it will be implemented I will gladly try, more than the ISEPIC that I never had and that they told me, my classmates, that it was really complicated to use it with multiload games like Dragon's Lair ... and instead the Freeze Frame did not have problems.

![675px-freeze_frame_2_closed](https://user-images.githubusercontent.com/34916641/43130667-732341fe-8f37-11e8-999e-bf56acc37dbc.jpg)

**Comment by dada08ms** [comment]
Excuse me, too many years have passed and I got confused while surfing the web.
I saw the image posted by Alessandro70 and I unfortunately confused the FREEZE FRAME cartridge with the ISEPIC.
My request is wrong and I close this issue, supporting the one on FREEZE FRAME.

Sorry again
Bye
