### ISSUE TITLE
Commodore64 and FREEZE FRAME

### ISSUE THREAD

**Issue by Harlock70** [dirkwhoffmann/virtualc64#369]
Goodmorning everyone,

I downloaded this wonderful emulator and I can reproduce all the software I used when I was a student with success and above all with satisfaction.
I would like to say to you if you could be kind enough to support the cartridge I had years ago and that does not appear in the VirtualC64 menu, nor does its corresponding reset button appear anywhere..
Always if I do not ask for a brig or if I do not overturn with my present your work progress program.
I enclose the data in my possession related to the FREEZE FRAME I had found on the web some time ago.

Unpretentious, I greet you and guide you for any understanding of my request.

You are strong.
A greeting.

[Freeze_Frame.zip](https://github.com/dirkwhoffmann/virtualc64/files/2222899/Freeze_Frame.zip)

**Comment by Alessandro1970** [comment]
I also had the Freeze Frame cartridge and it's definitely the one I used the most for ease of use.
It was enough to load the program or game, then press the "free" key and then the "T" key to save to tape or "D" to save to disk.
Nice product, cheap and versatile.
If it will be implemented I will gladly try, more than the ISEPIC that I never had and that they told me, my classmates, that it was really complicated to use it with multiload games like Dragon's Lair ... and instead the Freeze Frame did not have problems.

![675px-freeze_frame_2_closed](https://user-images.githubusercontent.com/34916641/43130698-853234b8-8f37-11e8-98ab-bad0735a0290.jpg)

**Comment by Ottavius** [comment]
Is it freeware ?

https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/freezeframe.c

**Comment by Alessandro1970** [comment]
,,,vetusware, abandonware :laughing:

**Comment by Ottavius** [comment]
laughing laughing laughing

**Comment by shauladeneb** [comment]
Thanks for this emulator that reminds me of the first steps in computer science and also for the emulation of this "Freeze Frame" cartridge that my husband used always for his experiments with the Commodore 64 many years ago ...

**Comment by DaitarnIII** [comment]
Hello
just this was my legendary cartridge !!!

**Comment by Alvarez81** [comment]
I have also had this cartridge and I have also used some time, I'm really happy to be able to try again it

**Comment by Alessandro1970** [comment]
DaitarnIII, welcome my old friend !

**Comment by dirkwhoffmann** [comment]
Because of it's simple hardware design, this cartridge was easy going.

Code has been check into branch V2.4

<img width="835" alt="freezeframe" src="https://user-images.githubusercontent.com/12561945/43249764-e2c386ec-90bb-11e8-8ea3-10e9f477b073.png">
