### ISSUE TITLE
Snapshot bug in V2.2 and V2.3

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#370]
To reproduce (in V2.2):

1. Run demo "WeComeInPeace"
2. When the characters start falling down, save a snapshot to disk via "Save As..."
3. Reset
4. Load snapshot via drag and drop

The demo seems to run just fine, but it will not continue to load. Interestingly, the music keeps playing. Hence, some part of the internal state doesn't get saved to disk.

Todo: 
Check that all class members of all VirtualComponents are registered as state variables.

**Comment by dirkwhoffmann** [comment]
Bug also appears in V2.1

**Comment by Ottavius** [comment]
Does the original disk of the demo remain inserted once the snapshot is loaded?

It would almost seem like the Uploaded Snapshot Demo ["WeComeInPeace"] only started working with those data left in memory (like music) but could not find the disk inserted in the drive to load the data sequentially.
Now I do not have the mac with me, but if you remove the disk while the demo starts (when the letters fall and not with the snapshot)) the music continues and the graphics freezes? (For lack of inserted disk)

**Comment by dirkwhoffmann** [comment]
Found it. I reviewed all classes and found out that variables PA and PB of the CIA chips were not saved in snapshot files. These variables represent the port pin values of the peripheral ports A and B.
