### ISSUE TITLE
Goonies doesn't run when loaded with the AR 7.5 fast loader.

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#372]
To reproduce:

1. Install the Action Replay cartridge 7.5.
2. Insert Goonies.D64 into the drive
3. Load "*",8,1  (Goonies is loaded at $0801 to $ACCB)
4. Run

It starts as usual, but it doesn't continue to load the other files. 

I checked parts of memory (30 bytes at $1000 + x * $400 for increasing x) after loading the game with and without AR. The memory dumps are equal, so I think it's not related to the fast loader.

Until there is any clue about the cause of this bug, it doesn't make sense to track it down. If somebody has an idea, please post.

**Comment by Alessandro1970** [comment]
Hi,
there is a strange problem with fastloading.
But If you use the Action replay 4.1 REV 1 with the active fastload (fastload 4.0 - see virtualc64 ver 2.3 beta2), the Goonies game works.
With the other versions of fastloader it does not work, why ?

<img width="776" alt="schermata 2018-07-28 alle 09 33 13" src="https://user-images.githubusercontent.com/34916641/43354283-87f2f04c-9249-11e8-88d7-c788d46bc87e.png">

<img width="769" alt="schermata 2018-07-28 alle 09 32 29" src="https://user-images.githubusercontent.com/34916641/43354284-8c6baba0-9249-11e8-8dcf-0cb5e26bc298.png">

**Comment by Alessandro1970** [comment]
This is the cartridge with works with fastloader:
[Action_Replay_V4.2_4.0_1988_PAL_v1.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2237762/Action_Replay_V4.2_4.0_1988_PAL_v1.crt.zip)

This is my copy of the game used:
[Goonies, The (1985)(Datasoft).zip](https://github.com/dirkwhoffmann/virtualc64/files/2237763/Goonies.The.1985.Datasoft.zip)

**Comment by Alessandro1970** [comment]
Also this works fine with the fastloader in VirtualC64:

[Action_Replay_V4.2_4.0_1988_PAL_v2.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2237769/Action_Replay_V4.2_4.0_1988_PAL_v2.crt.zip)

**Comment by Ottavius** [comment]
Hallo, it works for me too the 4.2 rev 1 and 2!!!

**Comment by Alessandro1970** [comment]
...only fastloader 4.0 !
Fastloader 5.0 or greater hangs...

**Comment by dirkwhoffmann** [comment]
Not solved. However, it's good to know that the 4.0 fastloader works, because all AR cartridges >= 4.0 use the same hardware.

**Comment by puleyo** [comment]
Excellent thing would be to support only version 4 and if someone tried to insert the later versions the emulator should warn with the phrase: "Not yet supported try version 4".
I do not know if there is really the need to have superior vesions, already revision 4 has what is necessary.

**Comment by Alessandro1970** [comment]
Hei, what happened?
In the new version 2.4 beta 2 the AR 7.5 works, the goonies work!

<img width="766" alt="schermata 2018-08-01 alle 00 57 53" src="https://user-images.githubusercontent.com/34916641/43491762-25f70da8-9526-11e8-8ca6-fe94c1edf6bf.png">

<img width="776" alt="schermata 2018-08-01 alle 01 00 27" src="https://user-images.githubusercontent.com/34916641/43491799-525a7ae2-9526-11e8-9718-d70ab7134b65.png">

Great !

**Comment by dirkwhoffmann** [comment]
There is still an issue. I think we're using different versions of Goonies. This one works with AR 4.0, but hangs with AR 7.5:

[GOONIES.D64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2248961/GOONIES.D64.zip)

**Comment by dirkwhoffmann** [comment]
"In the new version 2.4 beta 2 the AR 7.5 works, the goonies game works!"

The screenshot shows "Loading $0801 $A133"

When I load the game "Goonies, The (1985)(Datasoft).zip", it shows "Loading $0801 - $BAEB" (like in the second post) and it doesn't run. Strange things are going on.

**Comment by Alessandro1970** [comment]
> The screenshot shows "Loading $0801 $A133"
> **That is another version of Goonies (maybe a different compressor/cruncher)**

The only version that works is another one (I have missed to explain it before, sorry).
I think that this version is crunched in another way and probably is a "mono"-file version.
Try this:
[The Goonies.zip](https://github.com/dirkwhoffmann/virtualc64/files/2252239/The.Goonies.zip)

**Comment by dirkwhoffmann** [comment]
OK, I see, thanks! It seems like loading a file via "LOAD ... ,8,1" works fine with all AR versions. Issues come up when a programs starts to reload other files.

**Comment by dirkwhoffmann** [comment]
Same with BruceLee. Hangs when trying to load other files from disk.

**Comment by Alessandro1970** [comment]
Now I do not have mac to try but a multiload game like Defender of the Crown could be interestg to try:
[Defender_of_The_Crown.Cinemaware 9.NOSTALGIA.zip](https://github.com/dirkwhoffmann/virtualc64/files/2252361/Defender_of_The_Crown.Cinemaware.9.NOSTALGIA.zip)

**Comment by dirkwhoffmann** [comment]
Works like a charm. 

<img width="835" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/43566665-80764a78-962f-11e8-9a97-32f0110ebee1.png">

When that game came out for the amiga, I knew: I desperately need such a machine!!! A couple months later (it took quite some time to convince my parents to buy me one), when my Amiga 500 arrived, my C64 was thrown into a box and taken to the attic. It was never seen since then 🤧.

**Comment by Ottavius** [comment]
Yep :sob:

**Comment by dirkwhoffmann** [comment]
Solve #376 before getting back to this issue!

**Comment by dirkwhoffmann** [comment]
Does somebody have a tool at hand that is able to convert the Goonies D64 file into a G64 file? I would like to try the AR cart on a G64 disk. Background: G64 files contain the real GCR bit stream whereas D64 files only contain a byte stream. Thus, the disk encoder is not applied when reading in G64 images.

**Comment by Alessandro1970** [comment]
http://markus.brenner.de/mnib/

**Comment by dirkwhoffmann** [comment]
n2g seems to convert nib to g64 only.

**Comment by Alessandro1970** [comment]
Sorry I spent some hours last night searching...but none

Have tiu tried this?
https://ist.uwaterloo.ca/~schepers/personal.html

**Comment by dirkwhoffmann** [comment]
Thanks for the link, 64copy works (besides the fact that running an ancient DOS app in 64 bit Windows is 😤)!

Findings: The G64 file doesn't work in VirtualC64 with AR 7.5 either (same behavior as loading from the D64 file).

I also tried the other way round. I exported VirtualC64's disk to a file in G64 format and loaded that one in VICE. VICE can load the game without any problem even if AR 7.5 is installed.

Conclusion: The "Goonies bug" is not related to VirtualC64's disk encoder as I hoped yesterday.

**Comment by dirkwhoffmann** [comment]
Fixed in V2.5 which is online now.

The problem was caused by the nasty ATN interrupt bug that I discovered yesterday. Sorry to have blamed the innocent Goonies for that. Now, I have to see how to get in level 2, I'm still stuck in level 1.
