### ISSUE TITLE
Agony Pain demo hangs shortly after the first images and return to the basic

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#373]
Agony Pain demo hangs shortly after the first images and return to the basic.
[agony_pain.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2237781/agony_pain.d64.zip)

...hangs after this image:
<img width="772" alt="schermata 2018-07-28 alle 10 14 43" src="https://user-images.githubusercontent.com/34916641/43354578-1c7b5e5c-924f-11e8-95d8-f8f2875fb5f2.png">

**Comment by puleyo** [comment]
It's strange but this demo:
works with VICE (**not sc**)
it does **not work** with the VICE SC.
Should not the VICE SC emulation be better?

**Comment by dirkwhoffmann** [comment]
I remember that some of the latest demos have been developed with VICE and not on a real C64. In some cases, they accidentally rely on VICE bugs and do not run on a real C64 or later VICE versions where these bugs have been fixed. I'm not sure if this applies to this demo though.

**Comment by Alessandro1970** [comment]
I found this demo randomly, now I tried it on the VICE to the basic configuration for both the **normal** and the **SC version**. **It does not work for me in both cases** with both TRUE and no! 
_How did you make it work in VICE?_
![vice](https://user-images.githubusercontent.com/34916641/43392114-f0d8e54e-93f2-11e8-8a06-9eca4ca9655e.jpg)

I also tried on the last version of **HOS64** and **it DOES NOT WORK**!

![h](https://user-images.githubusercontent.com/34916641/43392147-0b2c6358-93f3-11e8-8218-a369631fc553.jpg)

_Probably I found a faulty or non-working demo version_ ... **I would close the issue, if you agree with me** ...

**Comment by dirkwhoffmann** [comment]
Yes, should be closed.
