### ISSUE TITLE
Alert user when ActionReplay Cartridge V5 or higher is attached

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#374]
Warn user about the fast loader incompatibility.

**Comment by puleyo** [comment]
In **http://www.dirkwhoffmann.de/VirtualC64_2.4_beta1.zip** version doesn't works the alert

**Comment by dirkwhoffmann** [comment]
I've come across the problem that there are no means of detecting which software version the cartridge is running (all cartridges >= 4.0 use the same cartridge header). I could display a general warning if an AR cartridge >= 4.0 is attached, but I was not able to find a suitable text. Any ideas what we should display?

**Comment by Alessandro1970** [comment]
Only Action Replay version 4 is supported at the moment

**Comment by puleyo** [comment]
The fastload now works, I think you can close the issue.
