### ISSUE TITLE
Diagnostics cartridge: Alignment check fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#376]
Source: Diagnostics cartridge from http://blog.worldofjani.com/?p=2180

VirtualC64: 

<img width="835" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/43651519-f31c0d06-9742-11e8-9acc-3ddbacaa7083.png">

Vice 3.2: 

<img width="744" alt="ohne titel 2" src="https://user-images.githubusercontent.com/12561945/43651550-fdb856c0-9742-11e8-9170-cf4dfa7a53b1.png">

Some background info about this test: http://retro64.altervista.org/blog/commodore-1541-disk-drive-maintenance-part-2-head-alignment/

**Comment by dirkwhoffmann** [comment]
Problem seems to be caused by the disk encoder. When formatting the disk (pressing F in the cartridge menu) prior to running the alignment test, I get 100% for all tracks.

**Comment by Alessandro1970** [comment]
For me it is that if I format an empty disk with VirtualC64 and run the test I get this:
<img width="780" alt="schermata 2018-08-05 alle 11 06 04" src="https://user-images.githubusercontent.com/34916641/43684433-2e06c876-98a0-11e8-9d6c-6f1cc93c46e7.png">


but if I export the disk that tested 100% positively and then re-run the test I always get errors, then exporting the disk even if the test was successful does not work. I do not understand ? Exporting the working disk how is it possible that it will not work then?
<img width="783" alt="schermata 2018-08-05 alle 11 03 43" src="https://user-images.githubusercontent.com/34916641/43684436-3744adea-98a0-11e8-9cdd-01f0f0342e7f.png">

**Comment by dirkwhoffmann** [comment]
Loading has become slightly faster, because the sectors are ordered correctly now.

When loading with native speed (warp load off), Giana Sisters now loads in 1:49 compared to 2:14 with the wrong sector ordering.

Unfortunately, this bug has nothing to do with the ActionReplay incompatibility bug.
