### ISSUE TITLE
Keyboard doesnt stay open???

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#377]
Please add the ability to close the keyboard manually...

**Comment by Alessandro1970** [comment]
Good idea, maybe a little button top left...

**Comment by dirkwhoffmann** [comment]
I'll check if a sheet can be reopened as a stand-alone window. This would be necessary, if a "sticky" keyboard is offered in addition to the currently implemented version (auto-closing sheet).

**Comment by Alessandro1970** [comment]
For quick actions the “auto-close” keyboard i great, but a second keyboard, “windowed keyboard”, could be a lot useful to type while seeing and could help some people that has problem and can use only mouse. I’d like to keep these two keyboards: the quick one like is now: from the toolbar, else the windowed one running from the menù.

**Comment by dirkwhoffmann** [comment]
Please have a look at 2.5 beta 1: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_2.5_beta1.zip

If the virtual keyboard is opened via the toolbar, everything is as before. If you open it via the keyboard menu (select  "Open ..."), it opens as a separate window and does not close when hitting a key.

This beta also contains the recent VICII changes (Vandalism demo fix) as well as some minor changes to the IEC bus handler. Please let me know if I broke some stuff that was working before.

**Comment by dirkwhoffmann** [comment]
"Try using the the c= key or the shift key and then type a any character numerous times."

Will be fixed in 2.5
