### ISSUE TITLE
More VC 1541 test cases needed

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#378]
To debug the VC 1541 implementation, it would be helpful to have small test programs that do not work with the current version of VirtualC64.

Good candidates are programs that utilize a fast loader or rely intensively on IEC bus timing.

**Comment by Alessandro1970** [comment]
Here there are a lot of download tests:
http://wiki.icomp.de/wiki/Chameleon_Core_Bugs

https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/drive/iecdelay/iec-bus-delay-auto.prg?format=raw

**Comment by dirkwhoffmann** [comment]
Chameleon tests agains the VICE tests (the sourceforge repro). I always refer to this repro when I talk about "the VICE tests". More tests similar to those in testprogs/drive would be helpful. Most test in testprogs/drive are related to the VIA chip and most of them already pass.

**Comment by puleyo** [comment]
Can you tell me how to interpret the result of this test?


[1541disktest.zip](https://github.com/dirkwhoffmann/virtualc64/files/2269855/1541disktest.zip)

**Comment by dirkwhoffmann** [comment]
1541disktest needs to be started from the D64 image. It first scans for available tests (there are two disks in total with different tests) and then runs them. If you run your .prg version alone, it'll find no tests and therefore produces a null result (0 passed, 0 failed).
