### ISSUE TITLE
Vandalism demo not working 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#379]
VirtualC64: 

<img width="835" alt="irq-ack-vicii-fault" src="https://user-images.githubusercontent.com/12561945/43685294-9b746250-98b0-11e8-890f-4848cb3f900d.png">

Vice 3.1: 

<img width="744" alt="irq-ack-vicii" src="https://user-images.githubusercontent.com/12561945/43685297-a1751f64-98b0-11e8-9f04-b07e3ff3d552.png">

**Comment by dirkwhoffmann** [comment]
Adding one additional delay cycle when raising and clearing the IRQ line in VIC::poke seems to fix the issue: 

<img width="856" alt="rasterirq" src="https://user-images.githubusercontent.com/12561945/43710262-70d574b6-996f-11e8-8677-2485829b6243.png">

Todo items: 
1. Check what VICE is doing in their VIC implementation (delay cycles on the IRQ line) 
2. In Hoxs64's VIC implementation, I found the following comments: 

          // vandalismnews64 wants a 1 clock deplay.
          // passes the rastercompareirq beta test."

Find out what demo could be meant and which test is "rastercompareirq beta"? We should test VirtualC64 with those programs.

**Comment by Ottavius** [comment]
https://csdb.dk/release/?id=138976

**Comment by Alessandro1970** [comment]
in HOSX ...Fix VIC where a write to the raster compare register was causing a raster IRQ to occur one clock too soon. This fixes "Vandalism News #64" http://csdb.dk/release/?id=138976 reported by iAN CooG/HVSC.

**Comment by dirkwhoffmann** [comment]
Thanks for the link, that was quick. The demo does not work, even after applying the irq-ack fix. 

<img width="856" alt="vandalism" src="https://user-images.githubusercontent.com/12561945/43712189-acc2e610-9975-11e8-9919-4917513279d4.png">

**Comment by dirkwhoffmann** [comment]
Vandalism demo is working now. I should have read the Hoxs64 description more thoroughly which was posted above by Alessandro (" raster compare register"). Delaying the IRQ event by one cycle when poking into this register makes the demo fly. 

<img width="861" alt="vandalism" src="https://user-images.githubusercontent.com/12561945/43784265-fd0b48f8-9a63-11e8-9ea2-f716a712a4f3.png">
