### ISSUE TITLE
"Dual Drive Utility" doesn't show the directory of the FloppyDisk in Drive#2

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#382]
Using the "Dual Drive Utility" with the "1" option and selecting the unit "1" I would have to display the drive directory in the DRIVE2, but instead getting an error message.
Selecting unit "0" instead correctly obtains the directory of the disk inserted in DRIVE1.
Is it possible that there is a bug or am I wrong about using this utility?

[Dual Drive Utility Program (1984)(J.Rhodes).d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/2272145/Dual.Drive.Utility.Program.1984.J.Rhodes.d64.zip)

<img width="779" alt="schermata 2018-08-08 alle 23 52 41" src="https://user-images.githubusercontent.com/34916641/43866612-a958289e-9b66-11e8-98d0-63f4b465d860.png">

**Comment by dirkwhoffmann** [comment]
To me, it looks like a bug in the dual drive utility. I do get the same result in VICE (don't forget to activate the second drive in VICE, it's not connected automatically when a disk is inserted in device with device number 9). Using LOAD "$",9 works well in VICE (dito in VirtualC64), but the dual drive util reports a "DRIVE NOT READY" error (dito in VirtualC64).

**Comment by Alessandro1970** [comment]
Ok, it is a problem in the dual drive utility
