### ISSUE TITLE
"Diskid1.prg" failed

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#383]
In trying to verify the new version 2.5 I stumbled on this test that seems not to give a positive result.

[diskid1.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2272205/diskid1.prg.zip)

<img width="782" alt="schermata 2018-08-09 alle 00 17 47" src="https://user-images.githubusercontent.com/34916641/43867710-a6fbe780-9b6a-11e8-9de7-0b98dbc0c482.png">

**Comment by dirkwhoffmann** [comment]
Actually, it's not a bug, but a not so good designed test case. The test case compares the sector disk IDs against a hard coded value and not against the value found in the directory track. If the test is started from the D64 image, it passes: 

<img width="861" alt="diskid" src="https://user-images.githubusercontent.com/12561945/43879875-478442c0-9ba6-11e8-9dc1-d75659570de8.png">

If you load from a PRG, there are no disk IDs, so the disk encoder uses default values. These values do not match the hard-coded value in the test case.
