### ISSUE TITLE
PRG File and dialog window

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#389]
Why when I insert a PRG file the VirtualC64 dialog always shows the name "Hello VirtualC64" as the file name and not the real name of the file?

<img width="769" alt="schermata 2018-08-11 alle 11 16 20" src="https://user-images.githubusercontent.com/34916641/43990182-5d376e86-9d58-11e8-9dc9-97ff982e4125.png">

**Comment by dirkwhoffmann** [comment]
The current implementation simply assigns a default name, because a PRG has no name stored inside it. It would be possible, of course, to use the Mac file name instead. However, it's not a one liner, because the Mac file name needs to be truncated and not all characters are representable in PETSCII.

**Comment by Alessandro1970** [comment]
Ok,
between the file name, the file name under mac os and the possible non-detectable name of the prg file, it creates confusion. I think, in my opinion, it would be to change the string "Hello VirtualC64" with "File PRG" so a person knows what it loads.

**Comment by dirkwhoffmann** [comment]
Version 2.6. will show the following disk and file name when dragging in file "Pac_Mania.PRG":

<img width="861" alt="prgfile" src="https://user-images.githubusercontent.com/12561945/44001194-935e7092-9e2d-11e8-8996-f10778437a43.png">

ASCII characters that have no PETSCII representation will be substituted by " " and all alphanumerical characters will be converted to uppercase characters.
