### ISSUE TITLE
Virtual keyobard bug

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#390]
There is still a bug in the window and in the virtual keyboard:
if you press the commodore key several times and then the shift happens frequently as in the image that pressing the letter "A" does not get the symbol but just the letter "A".
<img width="769" alt="schermata 2018-08-11 alle 11 41 40" src="https://user-images.githubusercontent.com/34916641/43990497-9fa8d3d2-9d5c-11e8-9346-331a2c6a584d.png">

**Comment by dirkwhoffmann** [comment]
The problem here is that the virtual keyboard does not know if the C64 is in uppercase mode or lower case mode. When you press Commodore + Shift, the C64 switches modes. In the current implementation, the virtual keyboard always shows the symbols as they appear in uppercase mode. To get around this, one had to find out the correct display mode which could perhaps be done by reading some special zero page register.

**Comment by Alessandro1970** [comment]
Not a bug
This only occurs if you press Commodore + shift and everything remains tiny ...
... I did not realize I had entered such a keyboard mode, the keyboard was over the screen and I didn't see the letters.

**Comment by dirkwhoffmann** [comment]
For reference: 
Possible way to find out if C64 is in upper case or lower case mode: Peek VIC register 0xD018:

    0xD018 & 0x02 == 0 : Upper case
    0xD018 & 0x02 != 0 : Lower case

**Comment by dirkwhoffmann** [comment]
When I hit Commodore + "1" in the virtual keyboard, the cursor color changes to brown, but the original C64 key is labeled "BLK". How do I change to black on a real C64? Do I have to press a key other than Commodore? Does anybody remember how that worked?

**Comment by dirkwhoffmann** [comment]
Figured it out. It was CTRL + NUMBER. This means that the CTRL key in the virtual keyboard needs to be made a "sticky key" like Shift and Commodore.

**Comment by Alessandro1970** [comment]
Black=control+1
Brown=commodore+2

**Comment by rossimariolee** [comment]
This is the map of the c64 **directly colour keycombination**:
https://www.c64-wiki.com/wiki/Color

**Comment by dirkwhoffmann** [comment]
This is how it looks in V2.6 when the emulator is in lower case mode and the CTRL key is hold down:

<img width="679" alt="newvkeyboard" src="https://user-images.githubusercontent.com/12561945/44073825-274ad2b4-9f96-11e8-9d20-fda37574f4ba.png">

Still missing: A custom image for REVERSE ON, REVERSE OFF

**Comment by Alessandro1970** [comment]
Hello, in the keyboard menu could you change the word "Open ..." with the words "Show keyboard" ?
_...someone told me that he thought it was a command to load the key settings and not a window with a virtual keyboard, written in that way._

<img width="181" alt="schermata 2018-08-18 alle 09 34 59" src="https://user-images.githubusercontent.com/34916641/44297035-826bda80-a2ca-11e8-9aa9-6a6320f0fd33.png">

**Comment by dirkwhoffmann** [comment]
Will be named "Show ..." in 2.6

![keyboardmenu](https://user-images.githubusercontent.com/12561945/44297181-8ea56700-a2cd-11e8-9d3d-b3b968567df1.png)

**Comment by mortinus** [comment]
This is the combination of colours shown when **CTRL key is hold down**,
![untitled 1](https://user-images.githubusercontent.com/41686391/44396952-cf57e700-a53e-11e8-966e-f8f505db954c.jpg)

But does the virtual keyboard shows also the others colours when only the **C= key (sticky) is hold** down with the same numbers key ?
