### ISSUE TITLE
VICE test VICII/split-tests/modesplit fails

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#392]
VICE 3.1 (model "C64 PAL")

![modesplit_vice](https://user-images.githubusercontent.com/12561945/44041189-782a04bc-9f1d-11e8-9244-f656b095d333.png)

VirtualC64 2.5 

![modesplit_vc64](https://user-images.githubusercontent.com/12561945/44041201-7e72ad56-9f1d-11e8-810e-e01ae0323d8d.png)

Most notably differences are in the upper right white section.

**Comment by dirkwhoffmann** [comment]
Seems to be similar now 🤔...

<img width="853" alt="splittest" src="https://user-images.githubusercontent.com/12561945/45925045-ca34f000-bf61-11e8-9baf-aa358c6a91c7.png">

To make this test pass, I had to adapt the following from VICE: 

    if ((vicii.regs[0x11] ^ vicii.reg11_delay) & 0x20) {
            /* 6569 fetch magic! (FIXME: proper explanation)
               When changing from RAM to (char)ROM fetches, the LSB of the
               fetch address is (apparently) latched using the mode from
               the previous cycle, and the upper bits come from the current
               mode, due to ...

               TODO: test with $d018 splits and fix above test if needed.
            */
            uint16_t addr_from, addr_to;

            addr_from = g_fetch_addr(vicii.reg11_delay);
            addr_to = g_fetch_addr(vicii.regs[0x11]);

            if (!is_char_rom(addr_from) && is_char_rom(addr_to)) {
                addr = (addr_from & 0xff) | (addr_to & 0x3f00);
            }
        }

**Comment by Alessandro1970** [comment]
To be closed ...for my eyes is ok

**Comment by mortinus** [comment]
Yes, to be closed, I do not see sensible differences.

**Comment by dirkwhoffmann** [comment]
Broken in V3.0 🙁.  (New mismatch in line 6).

<img width="952" alt="bildschirmfoto 2018-10-13 um 10 34 21" src="https://user-images.githubusercontent.com/12561945/46903341-bd0d8000-ced3-11e8-94d1-e1dc2ab99893.png">

Does anybody has the 3.0 beta executables at hand? Unfortunately, I deleted them on my machine and would need to recreate them from the git repro. We need to find out which checkin has broken the test.

**Comment by Alessandro1970** [comment]
[VirtualC64_3.0_beta1.zip](https://github.com/dirkwhoffmann/virtualc64/files/2475313/VirtualC64_3.0_beta1.zip)
[VirtualC64_3.0_beta2.zip](https://github.com/dirkwhoffmann/virtualc64/files/2475314/VirtualC64_3.0_beta2.zip)
[VirtualC64_3.0_beta4.zip](https://github.com/dirkwhoffmann/virtualc64/files/2475316/VirtualC64_3.0_beta4.zip)
I have found these 3 beta

**Comment by dirkwhoffmann** [comment]
"Bug" is caused by clearing the processor stack: 

    // Make the screen look nice on startup
    memset(&ram[0x400], 32, 40*25); // Screen 
    memset(&ram[0x100], 0, 256);    // Processor stack

#445 is a follow up.
