### ISSUE TITLE
VICII model selection

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#393]
Eventually, I plan to support the same VICII models as VICE does when selecting "C64 PAL", "C64C PAL", "C64 old PAL", "C64 NTSC", "C64C NTSC", "C64C old NTSC" in the "Options -> Model" menu. Those chip models seem to be: 

MOS 6569 R1 (VICE C64 old PAL)
MOS 6569 R3  (VICE C64)
MOS 8565  (VICE C64C PAL) <- will be made the default option in VirtualC64

MOS 6567 (VICE C64 old NTSC)
MOS 6567 R56A (VICE C64 NTSC)
MOS 8562 (VICE C64C NTSC)

One difference between the PAL and the NTSC chips are the color values. VICE is already doing a great job about this, and if I remember correctly they do not even use hard coded RGB values, but compute them on the basis on some VICII hardware parameters. I plan to adapt (🤥 steal) their approach which means that in future, the color values will be determined by the selected VICII chip. Right now, the color values are determined by the (user selectable) color scheme that does not take care about PAL or NTSC. I therefore plan to get rid of the color scheme stuff completely. Doing so will make emulation a little more realistic, but on the downside, the user has less influence on the colors. In my opinion, this should be OK, because I guess that most users did not care about the selectable color  scheme and just sticked to the default value anyway.

**Comment by Alessandro1970** [comment]
Ok, good choice

**Comment by rossimariolee** [comment]
Great!!!

**Comment by DaitarnIII** [comment]
Good idea, but this means that many existing bugs and connected to the VICII would be deleted as the code is the same as that of the VICE that works well for PC?

**Comment by mortinus** [comment]
VIC and SID can very well be copied by VICE, indeed this would be great.

**Comment by Alessandro1970** [comment]
> MOS 8565 (VICE C64C PAL) <- will be made the default option in VirtualC64

Good, but does this mean that the "Emulamer's Errata" would work as soon as you entered the Vice VICII code?

**Comment by UgoCaneFifone** [comment]
it is good and right to import the VICII code of VICE, it works well and should solve many problems. I am very favorable.

**Comment by dirkwhoffmann** [comment]
Copying the VICII code directly from VICE is not possible, because the internal software architecture of VirtualC64 and VICE are very different. The existing bugs in VirtualC64 need to be ruled out one by one. 

Regarding the color scheme, I think it's best to keep the option. I'll replace the color scheme "VICE" by
"Default", "VICE (PAL)", and "VICE (NTSC)". "Default" will be the default color scheme (factory settings). When this color scheme is selected, the emulator will use "VICE (PAL)" in PAL mode "VICE (NTSC)" in NTSC mode. 

@mortinus: VirtualC64 and VICE use the same SID library (reSID), so they should already sound the same. If not, it's a bug.

**Comment by dirkwhoffmann** [comment]
I found this great article by Pepto about the computation of VICII color values:

http://www.pepto.de/projects/colorvic/

I implemented it that way and added three new sliders to the emulator preferences:

<img width="522" alt="emulatorsetup" src="https://user-images.githubusercontent.com/12561945/44149486-95c3da4a-a09c-11e8-8307-f92200299021.png">

Having these sliders, color schemes really seem obsolete and will be deleted.
