### ISSUE TITLE
Add support for VICII gray dot bug

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#395]
On machines with a 856x plugged in (C64 II, the white ones), the first pixel of a cycle is displayed in gray when a write access occurs to the currently used color register (0xD020 ... 0xD02E).

Effect shows up in test case lp-trigger/test1.prg

<img width="831" alt="graydotvice" src="https://user-images.githubusercontent.com/12561945/44267985-7af7f300-a230-11e8-8efc-7c29f73d7362.png">

TODO: 
1. Emulate gray dots
2. Add "[Check] Emulate gray dot bug" to the hardware preferences. Gray option out if a 656x VICII is selected.

**Comment by dirkwhoffmann** [comment]
<img width="791" alt="graydotbug" src="https://user-images.githubusercontent.com/12561945/44297051-cbbc2a00-a2ca-11e8-9816-b0531cd9c415.png">

Gray dots are emulated correctly now, but there is a performance hit which is due to the current structure of the VICII code. 

TODO: 
Modify readColorRegister() to return a uint64_t which stores the color values for all 8 pixels that are drawn in a single cycle. I.e., if a color register stores value 05, the function will no longer return 05, but 0505...0505. If the gray dot bug hits in, the function will return 0505...050F. 
This approach could also speed up function drawBorder() which needs to take care of a color register change after drawing the first pixel.

**Comment by Alessandro1970** [comment]
VICE 3.1 behaves like the VirtualC64 only if the **VICII 6569R1 (Old PAL)** is selected.
Also missing is the small gray square at the top left, in addition to the vertical gray line. They seem to behave in the same way in this situation.
![untitled 2](https://user-images.githubusercontent.com/34916641/44505986-a487a300-a6a4-11e8-94f0-e27107b2f8de.jpg)

**Comment by Alessandro1970** [comment]
The model VICII 6569 R1 could be put as default VIC in VirtualC64 instead of 8565?

**Comment by dirkwhoffmann** [comment]
VICII 6569 R1 wouldn't be a good choice for the default option, because it uses odd luminance values. VICII 6569 R3 would be better (I thinks this chip has been used in most of the brown "breadbox" C64s). VICE is using the newer 8565 as the default chip which has been used in the newer white C64s (called C64 II or C64C). In real situations, the gray dot bug is not that much of a problem, because it only arises when a color register is written at the same time it is used. A lot of test cases do this by purpose (as seen in the timing.prg test case), but in real programs, it barely happens.

**Comment by mortinus** [comment]
Good morning, but will VirtualC64 support **VICII 6569 R3** from version 2.6?

**Comment by dirkwhoffmann** [comment]
In 2.6, the supported models will be: 

PAL_6569_R1
PAL_6569_R3
PAL_8565
NTSC_6567
NTSC_6567_R56A
NTSC_8562

However, I'm still struggling with some performance drawbacks and some subtle compatibility issues (e.g., the gray line for 6569 R3 and the gray dot Alessandro noticed in the upper left corner).

**Comment by dirkwhoffmann** [comment]
Result of performance profiling with 'Instruments':

<img width="1282" alt="instruments" src="https://user-images.githubusercontent.com/12561945/44539886-9453e000-a705-11e8-9370-7080133dcf19.png">

So, it's clear who to blame (except me):

Chief suspect: 

    void
    PixelEngine::setSingleColorPixel(unsigned pixelNr, uint8_t bit /* valid: 0, 1 */)
    {
        if (bit) {
            drawForegroundPixel(pixelNr, col[bit]);
        } else {
            drawBackgroundPixel(pixelNr, col[bit]);
        }
    }

Interestingly, drawForegroundPixel and drawBackgroundPixel do not show up in the Instruments report. I guess, they have been optimized away by the compiler.

Todo item 1: Integrate the code directly into drawCanvasPixel to avoid the function call.

Todo item 2: Check if it's faster to write the colors into a local array int[8] and to copy the data into the screen buffer later. The current implementation directly writes into the screen buffer. But since the screen buffer stores a whole texture line, caching issues might slow us down here.

Second suspect: 

loadColors():
Todo item 1 (low hanging fruits first): Use one TimeDelayed<uint32_t> for all background colors instead of four TimeDelayed<uint8_t>. 

Todo item 2: Try to turn the table. In the current implementation, the colors are computed first. After that, pixels are drawn based on the bit patterns found. Now, try to grab the bit pattern first and then compute the color. It's hard to tell if this is really faster, because the number of colors that need to be computed depends on various parameters (xoffset, display mode changes etc.). We'll see...

**Comment by dirkwhoffmann** [comment]
Findings: 
Holding the screen buffer on the stack doesn't impress the CPU very much. Moving it to the heap had no effect and copying chunks of pixels instead of single pixels doesn't affect performance either. 

Anyway, I managed to come close to the old speed with multiple other minor modifications:

Comparison (VirtualC64 in warp mode on MacBook Pro 13,3)
 
   V2.5 (after reset): 7.8 MHz, current V2.6 beta: 7.3 MHz
   V2.5 (running Octopus in redwine): 3 MHz, current V2.6 beta: 2.7 MHz

The Octopus in redwine demo is pretty interesting. If sprite drawing is disabled, you see: nothing. This means that the whole scene is drawn with sprites which is also the reason why it slows down performance so much. 

Optimizations in loadColors() in drawCanvas() are yet to come. 

Despite the somewhat lower performance, the VICII implementation is much cleaner now from a software architectural point of view. One general problem with emulating hardware in software is that timing delays are tedious to simulate. E.g., some VICII register values need to be delayed by two cycles and nearly all emulators simulate this by implementing pipelines, i.e., they have code like this:

    pipe1 = valueToDelay
    pipe2 = pipe1

This intensive value copying must be done after every cycle to simulate the desired delay. VirtualC64's new VICII implementation has no pipelines any more (Woohoo!). To emulate a 8-bit register that is delayed by let's say 2 cycles, it is now simply declared as

    TimeDelayed<uint8_t>(2) someRegister; 

and 

    someRegister.delayed(); 
    someRegister.current();

returns either the value that was stored in there two cycles earlier or the current one.

This approach is pretty flexible. E.g., if it turns out that a value needs to be delayed by another cycle, the only thing to do is to replace the declaration by 

    TimeDelayed<uint8_t>(3) register; 

With the old pipeline approach, a new pipeline variable pipe3 had to be introduced and the code be modified at various places. Of course, wrapping timing delay stuff into a class is not for free performance wise, but the new approach seems to compete OK with manually managed pipelines that are faster.

**Comment by Alessandro1970** [comment]
Perfect, this night I will try to use the two versions with some .d64 that I usually prefer.
Thank you

**Comment by Alessandro1970** [comment]
The first problem I found with the WT version, with the following demo is very jerky (lag)
Instead the VirtualC64 2.6 (no WT) is much more fluid ... indeed very good.

[lft-safe-vsp.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2325523/lft-safe-vsp.prg.zip)

**Comment by Alessandro1970** [comment]
I noticed, however, that if you upload several demos, one behind the other. alternating them only with the reset button there is a decrease in performance; instead closing and restarting the VirtualC64 it disappears .... probably the POWER button does not re-initialize everything, something that slows down remains and only the exit from the app removes this problem.

**Comment by dirkwhoffmann** [comment]
The "Reset button" problem could simply be due to high processor utilization. If run your machine with a 100% processor load for a longer time, the CPU constantly heats up. To prevent damage, modern CPUs employ thermal throttling (they slow down automatically when a certain temperature is reached). If you quit the emulator in between, the CPU has time to cool down. Hence, the best benchmark results should show up when you run your computer inside the fridge 😉.

**Comment by Alessandro1970** [comment]
The "WT" version appears to be faster as read in the status bar for any application that is run.
I tried the software that I run more on the C64 and it seems to me that this "WT" version" has no problem.

Unfortunately, the Emulamer "Errata" and "Ruinded Art" demos remain unworkable.
<img width="1073" alt="schermata 2018-08-27 alle 23 36 42" src="https://user-images.githubusercontent.com/34916641/44687693-23d4f800-aa52-11e8-8f50-1287492daf70.png">

**Comment by mortinus** [comment]
The "WT" version works well for me too

**Comment by puleyo** [comment]
The "WT" version is OK.

<img width="776" alt="schermata 2018-08-27 alle 23 46 53" src="https://user-images.githubusercontent.com/38581054/44688123-87abf080-aa53-11e8-8482-025402096cec.png">

**Comment by dirkwhoffmann** [comment]
Thank you all for testing! Result was as expected (writing the screen buffer directly (the old approach) is slightly faster than writing a whole chunk at the end of a cycle (the VICE approach)). So, I'll keep the old (write through) method. 

"Unfortunately, the Emulamer 'Errata' and 'Ruinded Art' demos remain unworkable." 
Yes, but I didn't expect them to work, yet. Distinguishing between the different VICII models internally was just the necessary groundwork for tackling these issues. The old VICII was a hybrid (it behaved like the 85xx with respect to lightpen interrupts and like the 65xx with respect to register timing). 

Next step: We need to find out what VICE's "emulate glue logic" configuration option means.
