### ISSUE TITLE
Pause the emulation when VirtualC64 is not the frontmost application.

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#399]
Requested by Gjermund.

Should be made user configurable.

**Comment by Alessandro1970** [comment]
"Pause" user configurable, excellent idea, as command from the menu.

**Comment by mortinus** [comment]
The selectable pause when the window goes in the background can be very useful, I'm happy for this news.

**Comment by rossimariolee** [comment]
For the PAUSE, I would prefer an icon to the **left** of the POWER button, it can be much more useful managed like that.

**Comment by Alessandro1970** [comment]
...better an option, user configurable, in the emulator menù.

**Comment by dirkwhoffmann** [comment]
I think it's best to add it to the emulator preferences, in the "Misc" section.

[Checkmark] Pause emulation when application is in background.

Maybe with a better textual description. Any ideas? 

@rossimariolee: You can customize the toolbar and add the debugger pause icon to it. It does exactly what you are looking for (the pause icon is not very pretty though and should be replaced by a nicer looking one).

**Comment by Alessandro1970** [comment]
I'll prefear this desciption:
![q-emulator-003 jpg xxs](https://user-images.githubusercontent.com/34916641/44325091-03a4a800-a458-11e8-91bf-7f29b99b7f8a.jpg)

**Comment by Alessandro1970** [comment]
I would not want to create problems, but to hear about icons ...
Would it be better to adapt them all with a retro style closer to the commodore 64 or even get them from commodore designs or materials?
If you were to define a standard [PNG 400x300 numb. colors ...] we could find different, maybe even pleasant ...

**Comment by dirkwhoffmann** [comment]
Regarding icons, there are two important things to keep in mind: 

1) The icon set must look consistent (more difficult to achieve that is seems to be)
2) Copyright restrictions (this rules out mostly everything that is original Commodore). 
Even CreativeCommons stuff is sometimes problematic, because some licenses require an explicit author attribution or forbid to apply modification. Public domain stuff is best, GPL is fine, too, of course (the emulator itself is GPL).

Icon size should be 256 x 256 or 512 x 512 (for toolbar icons).

**Comment by dirkwhoffmann** [comment]
<img width="522" alt="autopause" src="https://user-images.githubusercontent.com/12561945/44705707-b18b0480-aa9f-11e8-8166-f8e90820cac7.png">
