### ISSUE TITLE
Rename "Drive 1" to "Drive 8" and "Drive 2" to "Drive 9"

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#400]
Another possibility would be to let the user configure the drive number (is made with dip switches on a  real drive).

However, I guess nobody needs drive numbers 10 and 11 instead of 8 and 9, respectively.

**Comment by Alessandro1970** [comment]
For me is ok "Drive 8" and "Drive 9". 
In those days the drives were known and named like that. In fact for those who used the C64 "Drive1" sounds a little bad.

**Comment by dirkwhoffmann** [comment]
Fixed in 2.6
