### ISSUE TITLE
Title windows

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#401]
Is it really necessary to keep the name at the top of the window?
Is it possible to **remove it**, or is it possible to put an option to permanently obscure it?

... sometimes even useless or annoying names appear, based on what one has on his HD.

<img width="783" alt="43989642-84853946-9d4e-11e8-9d32-e601fbd8d43e" src="https://user-images.githubusercontent.com/41686391/44332956-b3d0db80-a46d-11e8-923c-c7dfe3f3c71e.png">

**Comment by Alessandro1970** [comment]
In fact ...
Maybe an option box to be added to the emulator configuration screen, to remove this indication.
