### ISSUE TITLE
Changes in hardware / emulator preferences 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#405]
Options "Play drive sounds" and "Load with full" speed are not related to the C64's hardware. They are emulator features and should be moved to the emulator preferences. 

Since the emulator preferences are growing bigger and bigger, some options should be moved. A good candidate are the joystick emulation keys. I'll add a "Configure keys ..." item to the Port A and Port B toolbar selector. When choosing it, the joystick emulation key stuff will open up in a separate sheet.

**Comment by dirkwhoffmann** [comment]
In 2.6., a third toolbar icon will be added to open the joystick prefs window. 

<img width="190" alt="ohne titel 3" src="https://user-images.githubusercontent.com/12561945/44858223-cfa85e80-ac71-11e8-9da9-1b7b0295c915.png">
The other preferences windows currently look as follows: 

Emulator preferences: 

<img width="535" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/44857982-3ed18300-ac71-11e8-87a0-35a283ba8d5a.png">

Hardware preferences: 

<img width="520" alt="ohne titel 2" src="https://user-images.githubusercontent.com/12561945/44857980-3c6f2900-ac71-11e8-94d3-a54a08c42aeb.png">

An alternative would be to move the Mouse model settings from the hardware prefs to the joysticks prefs and rename the Joystick prefs to "Devices" or something. Still unsure about this.

**Comment by Alessandro1970** [comment]
...too many items, move Mouse model setting to the  Joysticks prefs and rename "Input Device Configuration"
![untitled 1](https://user-images.githubusercontent.com/34916641/44860789-6297c780-ac77-11e8-8564-53a5174e8295.jpg)

**Comment by Alessandro1970** [comment]
...also a lightpen settings, in the same place if it is implemented

**Comment by dirkwhoffmann** [comment]
After moving the mouse settings, it look pretty clear to me. 

Devices preferences: 

<img width="542" alt="ohne titel 4" src="https://user-images.githubusercontent.com/12561945/44862905-fbc8dd00-ac7b-11e8-8eda-0695f808d93e.png">

Emulator preferences: 

<img width="534" alt="ohne titel 5" src="https://user-images.githubusercontent.com/12561945/44862918-084d3580-ac7c-11e8-8380-fc67efc73e50.png">

Hardware preferences: 

<img width="521" alt="ohne titel 6" src="https://user-images.githubusercontent.com/12561945/44862922-0be0bc80-ac7c-11e8-9f88-f1f039f12a83.png">
