### ISSUE TITLE
GEORAM menù

### ISSUE THREAD

**Issue by UgoCaneFifone** [dirkwhoffmann/virtualc64#406]
Hello,
Many people have had the Neoram but they do not know that in fact it is the same as the Georam.
Why do not you change the name in the various menus from **GeoRAM** to **GEO/NEO Ram**?
At least it would be clearer for some users, in my opinion.

**Comment by dirkwhoffmann** [comment]
<img width="230" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/44856980-0cbf2180-ac6f-11e8-9aa7-8d22079551f6.png">

Fixed on branch "VICExperiments". Will be merged into main soon.
