### ISSUE TITLE
Autofire in the toolbar

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#407]
Hi, the C64 is above all a video game machine, is there a way to put in the toolbar a button for autofire and also the ability to enter the fire rate ?

**Comment by Alessandro1970** [comment]
The icon for autofire [ON-OFF] can be useful (for both joysticks), but the fire rate would leave it in the joystick settings window.

**Comment by dirkwhoffmann** [comment]
I think it's better to add a sixth key to the joystick emulation keymap (Left, Right, Up, Down, Fire, Autofire).

**Comment by dirkwhoffmann** [comment]
This is how I plan to design the joystick preferences window.

<img width="543" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/44837482-0b273680-ac3a-11e8-8230-d470bccc9185.png">

**Comment by dirkwhoffmann** [comment]
Feature will be available in 2.6. Code is already checked in.
