### ISSUE TITLE
Customizable ICONS themes for toolbar

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#408]
Is it possible to create a window, made like a library, that allows users to change the icons used by VirtualC64 with icons chosen by users and maybe we can save the configuration and layout on a file so as to have the new permanent combinations ? (Default theme overwritten)
It would also be a way for users to be able to (privately) use original icons :smiling_imp: .

**Comment by dirkwhoffmann** [comment]
Difficult to implement. All images are organized in a .xcassets archive which is processed by XCode in one of it's compile stages. To make a long story short: The standard cocoa approach (which VirtualC64 complies to) does not allow to exchange icons easily.

If you want to experiment with privately designed icons, it is easies if you download the source code and compile it with XCode. On High Sierra, VirtualC64 should compile out of the box (at least it is supposed to and if not, please report a bug). Then you can simply replace icons by dragging PNGs into the Media.xcassets archive.
