### ISSUE TITLE
Cartrigde EasyFlash Support

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#409]
Hi,

when I try to run [this easyflash-cartrigde file](https://csdb.dk/release/?id=166110) . The emulator says that it does not support it yet. Although when I look into the sources I find the type definition of "easyflash"-crt files.  Is this really not yet supported or did the computer made an mistake :-) 

BTW: thank you for this great piece of software !!

**Comment by dirkwhoffmann** [comment]
EasyFlash cartridges are not supported, yet. The emulator knows "Easy flash" only as far as to translate the CRT file signature to the string "Easy flash". This is needed to produce the error message you've seen.

The support cartridges are checked in the following function: 

    bool
    Cartridge::isSupportedType(CartridgeType type)
    {    
        switch (type) {
        
            case CRT_NORMAL:
            case CRT_ACTION_REPLAY:
            case CRT_ACTION_REPLAY3:
            
            case CRT_FINAL_III:
            case CRT_SIMONS_BASIC:
            case CRT_OCEAN:
            
            case CRT_FUNPLAY:
            case CRT_SUPER_GAMES:
            
            case CRT_EPYX_FASTLOAD:
            case CRT_WESTERMANN:
            case CRT_REX:
        
            case CRT_ZAXXON:
            case CRT_MAGIC_DESK:

            case CRT_COMAL80:
            case CRT_FREEZE_FRAME:
            
            case CRT_GEO_RAM:
                return true;
            
            default:
                return false;
        }
    }
