### ISSUE TITLE
Warp mode does not stop in Starion Demo

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#410]
Normally the Warp mode does not stop in Starion Demo, even manually.
I tried several times but the only way to see the Starion Demo with the VirtualC64 is to remove the "load with full speed" option **before** load it; otherwise there is no way to block the Warp Speed.
I'm using VirtualC64 WT.

[Starion.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2342164/Starion.prg.zip)

**Comment by rossimariolee** [comment]
I tried this demo.
After loading it starts and the warp mode does not stop automatically and the graphics run too fast.

**Comment by dirkwhoffmann** [comment]
Will be fixed in 2.6
