### ISSUE TITLE
ISEPIC Cartridge

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#413]
Hello, is it possible to add the ISEPIC cartridge to those already supported by VirtualC64?
Thank you

http://www.ar.c64.org/wiki/ISEPIC

**Comment by mortinus** [comment]
ISEPIC ... great cartridge.
I hope Dirk can make both ISEPIC and STARDOS work on VIRTUALC64.
This cartridge in those years possessed it in many people, but because I do not see a FREEZE button but I see a lever? ...what purpose does it serve ?
![img_0876_oc-500x500](https://user-images.githubusercontent.com/41686391/45077104-8e3e0600-b0ec-11e8-9073-6fe3e009cfb7.jpg)

**Comment by Alessandro1970** [comment]
> Marco van den Heuvel wrote:
> The isepic cart has a switch which controls if the registers and ram is mapped in.
>  When the switch is switched away from the computer the cart is put in 'hidden' mode,
>  where the registers, window and ram is not accessable.
>  When the switch is switched towards the computer the cart is put in ultimax mode,
>  with the registers mapped, and the current page being mapped into any unmapped ultimax
>  memory space, it will also generate an NMI. Which activates the freezer.

I saw this cartridge but I never liked it: **it does not work without the utility disk**.
In fact, after inserting the cartridge you have to load the software [LOAD "*", 8,1] then select the option and **move the switch** if necessary.
There was no reset button that I remember.
![untitled 52](https://user-images.githubusercontent.com/34916641/45077850-9f881200-b0ee-11e8-8fd2-7e054c8748a5.jpg)
![isepic_top](https://user-images.githubusercontent.com/34916641/45077859-a4e55c80-b0ee-11e8-908e-8793faf278fe.jpg)

**Comment by puleyo** [comment]
... it did not even work well ...

**Comment by rossimariolee** [comment]
Ok, you convinced me, I let it go. Then I saw that in the "closed" there was already a precedent...

**Comment by rossimariolee** [comment]
Greetings,
At this point is it possible to implement ISEPIC?
_The cartridge vanished at the end of 1985 but still sold 20,000 units around the world, mostly by word of mouth at local computer clubs and niche magazines_

**Comment by mortinus** [comment]
...remember those 2 kB RAM, on the cartridge, that could be reprogrammed...

**Comment by Alessandro1970** [comment]
Hi, dear C64 friends. You may need these:
1) Isepic Tool disk: https://csdb.dk/release/?id=63335
2) Isepic Cruncher: https://csdb.dk/release/?id=115512
3) Isepic Defroster: https://csdb.dk/release/?id=28949
4) Isepic File Copier: https://csdb.dk/release/?id=166336
5) Isepic Fixer: https://csdb.dk/release/?id=83189
6) Isepic Textboot Maker: https://csdb.dk/release/?id=86456
7) Isepic-Files-Changer: https://csdb.dk/release/?id=136476

**Comment by UgoCaneFifone** [comment]
Great! All downloaded !

**Comment by UgoCaneFifone** [comment]
ISEPIC Manual: https://ia800804.us.archive.org/25/items/Isepic_V1.0_Manual/Isepic_V1.0_Manual.pdf

**Comment by DaitarnIII** [comment]
I liked this cartridge

**Comment by UgoCaneFifone** [comment]
Help me, please !
I downloaded all the files you put on, but I can not find the .CRT file!
Where is the ISEPIC cartridge file?

**Comment by Alessandro1970** [comment]
#UgoCaneFifone
I believe that it must be implemented, as for the time of EasyFlash; there is no CRT file.

**Comment by dirkwhoffmann** [comment]
Hmm, yes, interesting. It seems like there is no Rom on board. The software has to be loaded from the Isepic tools disk. But there are only 2KB Ram on board, so the Isepic "operation system" has to be very small. I hope that we're not completely on the wrong track here.

If there is really no Rom (hence no .crt file), we could add an option to the Cartridge menu: 

Expansion -> Attach ISEPIC (just below Attach GEO/NEO Ram)

There must also be an option for the switch (which needs to be toggled manually a couple of times in the freezing procedure). Maybe, it would be nice to have an icon in the bottom bar which displays the current position of the switch and toggles it when pressed.

**Comment by Alessandro1970** [comment]
Icon in the bottom bar, great

**Comment by mortinus** [comment]
These isepic drivers (language c) could help ?

[isepic_source.zip](https://github.com/dirkwhoffmann/virtualc64/files/2685755/isepic_source.zip)

**Comment by dirkwhoffmann** [comment]
Does anybody know how to attach an ISEPIC cartridge in VICE (x64sc). I need to run the VICE debugger to compare the behaviour with my own solution (which is broken yet). 

The ISEPIC cartridge is somewhat complicated to emulate, because it uses a very special "custom" memory mapping. Since there are no schematics of the cartridge, it's hard to tell which memory chuncks need to be blended in under certain circumstances. Reading the VICE source code does not really help here (too obfuscated) ...

**Comment by Alessandro1970** [comment]
Hi, you have to download VICESDL version than use F12 to access the menu:
1)
![1](https://user-images.githubusercontent.com/34916641/50327320-d6900100-04ee-11e9-9f02-d9b0849cce80.png)
2)
![2](https://user-images.githubusercontent.com/34916641/50327324-db54b500-04ee-11e9-90ac-5c986066cdc3.png)
3)
![3](https://user-images.githubusercontent.com/34916641/50327326-de4fa580-04ee-11e9-928b-711d708ae9ba.png)

**Comment by dirkwhoffmann** [comment]
I also came across the picture you posted, and it seems to be the only "schematic" available. I found out that the big chip is the 2KB Ram storage. The uppermost chip contains NOR gates and the chip left to the switch contains D flip-flops. The chips at the bottom are NAND gates with 8 inputs each. 

One of the open questions I'm facing is how the NMI line is connected to the switch (pulling the switch towards the computer triggers an NMI). The NMI line is the left most pin at the other side of the board: 

![isepic](https://user-images.githubusercontent.com/12561945/50330396-50c68280-04fb-11e9-969b-ff277a66e221.png)

There are two possibilities which I cannot decide by looking at the available pictures:

1) The NMI line is hold down until the switch is pushed back.
2) The NMI line raises a short period time after pulling down (there are some capacitors and resistances which may do the job).

**Comment by dirkwhoffmann** [comment]
OK, I managed to mount an ISEPIC crt in VICE SDL.

Unfortunately, the SDL version does not support drag and drop, so I have to type LOAD "*",8 myself to load the ISEPIC software. I managed to type LOAD, but I'm stuck with '"'. Seems to be impossible on a German keyboard 🤔. The virtual keyboard in VICE doesn't show '"' either.

Do we really need this cartridge?

**Comment by Alessandro1970** [comment]
I have read this:
**Expert Cartridge** by the english company Trilogic came in the middle of 1986 relatively late to the european market but got into quite a success story due to its excellent software. Expert Cartridge is a RAM only cartridge carrying 8 kbyte of RAM which can be pre-programmed **just like an ISEPIC**.

http://rr.c64.org/wiki/Expert_Cartridge

**Comment by dirkwhoffmann** [comment]
"just like an ISEPIC". Cool, this might help a lot!!!

**Comment by rossimariolee** [comment]
...has the cartridge arrived from Canada ?

Bye

**Comment by dirkwhoffmann** [comment]
No ISEPIC from Canada yet. Still waiting.

**Comment by dirkwhoffmann** [comment]
Got it, but implementation will take some time. Busy with Amiga stuff ...

<img width="529" alt="screenshot 2019-01-20 at 16 03 47" src="https://user-images.githubusercontent.com/12561945/51440978-06d4e600-1ccd-11e9-8390-fcae9889bfed.png">

**Comment by rossimariolee** [comment]
Hi everyone,
Is there any chance of having revision 3.4 with isepic and mach5 support ?

**Comment by dirkwhoffmann** [comment]
Not likely to come soon. Busy with Amiga stuff...

**Comment by UgoCaneFifone** [comment]
Hi everyone, but there would be some chance to use this ISEPIC, it's been a while ?
...please

bye

**Comment by dirkwhoffmann** [comment]
Ugo, why not switch to the Amiga? It comes with stunning 4096 colours, multiple independent DMA channels, two build-in co-processors  and an incredibly fast, cutting-edge 68000 CPU running at unbelievable 7.2 MHz.

![comm_006-m](https://user-images.githubusercontent.com/12561945/57965568-35469300-7946-11e9-90a1-fab71d083704.jpg)

😅

**Comment by Alessandro1970** [comment]
🤣🤣🤣 🤪🤪🤪🤪 👏🏻👏🏻👏🏻

**Comment by Alessandro1970** [comment]
Otherwise VirtualC64 when will reach version 3.4 will be the top!!!

**Comment by shauladeneb** [comment]
Wonderful, we are all waiting for this revision 3.4 to be able to try the Isepic and the Mach.
We all hope that it is not too long to wait.
Thank you.
Bye

**Comment by PakkunKinoppi** [comment]
Hi, this is a great emulator for Mac! When will be completed the support for ISEPIC cart ?

**Comment by dirkwhoffmann** [comment]
Still busy working on vAmiga. The new emulator is so much fun at the moment I just can't stop working on it 🥳.

**Comment by dirkwhoffmann** [comment]
For fun, I started to reengineer the Isepic board. Although there are just a few simple ICs on the board, it turned out to be much more complicated than I thought. This is what I have so far: 

<img width="1315" alt="isepic_schematics" src="https://user-images.githubusercontent.com/12561945/62007827-7df2a780-b152-11e9-907f-471b4d1bb8b7.png">

It' incomplete and might be wrong in some details, too. 

At least I am able to formulate a hypothesis about the NMI line. Which is: 

- If the switch is up, NMI is always 1 (no interrupt)
- If the switch is down, an NMI is triggered when IO1 is accessed.

Not sure if this is correct, but at least it is consistent with the documentation: 
 
    "...  to flip the ISEPIC switch away from the computer. This causes the ISEPIC 
    cartridge to 'hide'."

**Comment by dirkwhoffmann** [comment]
Mapping of the on-board RAM (address bus A0 - A7): 

![schematics](https://user-images.githubusercontent.com/12561945/62009729-c9ad4d00-b162-11e9-9f64-d41b0929f834.jpg)

Interestingly, A0 and A1 are swapped, but that's not important for emulation.

**Comment by dirkwhoffmann** [comment]
I think I got it right now. 

With the latest code fixes, you can freeze a game as explained in the ISEPIC manual:

1. Attach the ISEPIC cartridge
2. Load the Isepic Starpoint Software Tooldisk: 

<img width="916" alt="Bildschirmfoto 2019-07-29 um 14 22 41" src="https://user-images.githubusercontent.com/12561945/62048133-5fe97d80-b20c-11e9-9f13-eb6739652d7e.png">

3. Hit "P" to prepare a storage disk
4. Export the disk to a D64 file

5. Hit "C"
6. Pull the switch to the left

Now, the C64 resets and you can do whatever you like, e.g., play BoulderDash.

7. Pull the switch to the right to start the freezer

<img width="916" alt="Bildschirmfoto 2019-07-29 um 14 15 36" src="https://user-images.githubusercontent.com/12561945/62048227-a3dc8280-b20c-11e9-9561-1a6c66fa4d4f.png">

8. After freezing, export the disk to another D64 file.

9. Quit the emulator and relaunch
10. Insert the exported disk from the previous session. In my case, the disk looks like this: 

<img width="916" alt="Bildschirmfoto 2019-07-29 um 14 18 18" src="https://user-images.githubusercontent.com/12561945/62048338-eaca7800-b20c-11e9-9d7b-a3a09b33a6f5.png">

11. LOAD "*",8,1

12. When the ISEPIC menu comes up, hit "R" for Run
13. Wait until loading is completed. It then shows:

<img width="916" alt="Bildschirmfoto 2019-07-29 um 14 19 17" src="https://user-images.githubusercontent.com/12561945/62048400-18afbc80-b20d-11e9-860e-a54d988dee2e.png">

14. Flip the switch and continue... 😎

<img width="916" alt="Bildschirmfoto 2019-07-29 um 14 19 25" src="https://user-images.githubusercontent.com/12561945/62048443-2f561380-b20d-11e9-9ab7-061984a17b53.png">

**Comment by Alessandro1970** [comment]
Great! ...so the 3.4 release is near ?!

**Comment by dirkwhoffmann** [comment]
> so the 3.4 release is near ?!

I'll integrate it in 3.3.3.

**Comment by dirkwhoffmann** [comment]
An ISEPIC capable VirtualC64 is here 😎: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b2.zip

Please reopen if you encounter any issues.

**Comment by Haroldo64** [comment]
Thank You

**Comment by rossimariolee** [comment]
Thank you

**Comment by PakkunKinoppi** [comment]
Thank you
...but are there some problems with Mach 5 cartridge ?
I have read the issue that it seemed to me that Mach 5 was a simpler cartridge than ISEPIC, it was common in Poland and it worked well with 1571 too.

**Comment by dirkwhoffmann** [comment]
> ...but are there some problems with Mach 5 cartridge ?

Mach 5 is yet to come. Since it requires a modification of the snapshot format (new cartridge), it has to be delayed to 3.4.

Depending on my time schedule, I can try to integrate it, skip 3.3.3, and go directly to 3.4.

**Comment by Alessandro1970** [comment]
Hi

almost certainly revision **3.4** will be **the best** (for now)!
This is very strange that everyone loves cartridges of all kinds but **nobody has asked for the RetroReplay cartridge** , in fact there are no interventions in that issue ???!!! Was this cartridge a clone of the Action Replay?

**Comment by Alessandro1970** [comment]
Ah ok I have read that Retroreplay was the same of the Action Replay but these two differences:

- RR has flashrom, so you can put any rom on it 
- RR has the infamous de00 read bug fixed (AR crashes when you read from dexx)

**"AR crashes when you read from dexx"** What would it mean?
