### ISSUE TITLE
StarDOS Cartridge

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#414]
Is it possible to fully support the StarDOS cartridge in VirtualC64?
(Including the button and the "_" command to start the commands)
Thank you

[StarDOS.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351435/StarDOS.zip)
[Stardos_Reverse_preliminary.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351437/Stardos_Reverse_preliminary.zip)
[StarDOS_Manual.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351439/StarDOS_Manual.zip)

**Comment by mortinus** [comment]
StarDOS cartridge, unfortunately, it does not work on HOXS and from what we read on LEMON64 gave a hard time to VICE for copying files and other...
From the photo the button is noticed, but I do not know if it is a RESET ...
![stardos_pcb2](https://user-images.githubusercontent.com/41686391/45075289-f0940800-b0e6-11e8-9e9b-171459f8eb00.jpg)

A classmate of mine had it but I do not remember any particular button, maybe it was just a reset. He copied files like a rocket ...

**Comment by puleyo** [comment]
Also interested in this cartridge, we hope it will be fully supported on VirtualC64
The manual is interesting

**Comment by dada08ms** [comment]
very interesting
bye

**Comment by DaitarnIII** [comment]
Interesting for me too, I will follow the topic update messages via email!

**Comment by UgoCaneFifone** [comment]
All crazy about this STARDOS! hehehe
Okay I'll follow you! This cartridge also interests me!

**Comment by Alessandro1970** [comment]
> On the original StarDOS cartridge, two databits are switched so if you read the EPROM it will look like garbage. This program switches those two bits so the code is readable again. After you have changed the code to your liking, run it through this program again to switch the bits and then you can burn the code to an EPROM and use it in the original StarDOS cartridge.

StarDOSfix.exe (C) Magnus Starseth 2017

Usage: StarDOSfix <input filename> <output filename>

This program fixes the switched D1-D2 bits in the ROM.
Run it again on the "decoded" file to make a file that
can be programmed into a PROM and used in the StarDOS
cartridge.

They switched places on the D1 and D2 data pins,
probably as some form of obfuscation of the code.
[StarDOSfix.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351826/StarDOSfix.zip)

**Comment by Alessandro1970** [comment]
> the stardos hardware is kindof perverted. it has two "registers", which
>     are nothing more than the IO1 and/or IO2 line connected to a capacitor.
>     the caps are then connected to a flipflop. now multiple reads of one of
>     the "registers" charges a capacitor, which then when its charged enough
>     causes the flipflop to switch. the output of the flipflop then controls
>     the GAME line, ie it switches a rom bank at $8000 on or off.
> 
>     the original stardos code reads either $de61 or $dfa1 256 times in a loop
>     to succesfully switch.
> 
>     the second rom bank contains a kernal replacement. the necessary select
>     signal comes from a clip that has to be installed inside of the c64.

Source: https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/stardos.c

**Comment by Alessandro1970** [comment]
[stardos-v1-4-decoded.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351867/stardos-v1-4-decoded.zip)

[stardosprg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2351869/stardosprg.zip)

This is what I found on the web

**Comment by Alessandro1970** [comment]
Here is the wiring diagram, the button is a reset button.
Reading the manual the commands are clear and practical, excellent cartridge.
![stardos_dwg](https://user-images.githubusercontent.com/34916641/45202178-667ba900-b278-11e8-9daf-73f1a479daf7.jpg)

**Comment by DaitarnIII** [comment]
There are the cartridge handling for StarDOS cart:

1) https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/stardos.c

2) https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/stardos.h

**Comment by Harlock70** [comment]
I will be very happy for this enhancement, thanks.

**Comment by dirkwhoffmann** [comment]
Unfortunately, I have to set the priority to low. The cartridges's hardware is so unusual that it's not compatible with the current software architecture.

**Comment by UgoCaneFifone** [comment]
... is there any hope of being able to use this cartridge?

**Comment by Alessandro1970** [comment]
I tried this cartridge on VICE out of curiosity and in my opinion (personal opinion and non-binding) would be to close the issue ...
As cartridge is not great, there are others already supported better, and the StarDOS has some compatibility problem as well on the VICE, several games, I tried, lock if they are multi-load / multi-file; by lifting the cartridge the games do not block (Maniac Mansion, Defend of the Crown, The pawn ...)
In my opinion it would be to leave both the STARDOS and the ISEPIC ...
:beer:

**Comment by mortinus** [comment]
Good morning,
Excuse me, maybe I missed some passages, but **why was this issue closed?**
All in all, the StarDOS is an excellent cartridge and would be positive if the VirtualC64 could support it.
_Is there a chance to reopen this ISSUE?_

**Comment by Alessandro1970** [comment]
![kwak-pauwel-8-34l](https://user-images.githubusercontent.com/34916641/47412087-f57e4b00-d76a-11e8-860b-0d03adb50971.jpg)

**Comment by mortinus** [comment]
Thanks, I like this cartridge.

**... what beer is that? Wonderfully bestial the mug!**

**Comment by Alessandro1970** [comment]
...great beer from Belgium

In the 18th century there was a very well-known brewer in the Dendermonde area; his name was Pauwel Kwak. He brewed his own beer, which was dark and heavy. He also has had a coaching inn on the road between Mechelen and Gent, where the mail coaches used to stop for a break.

In those days, the **Napoleonic Code ruled** that coach drivers were forbidden to drink beer with their passengers and so they were not allowed to leave the coach to quench their thirst. Pauwel Kwak invented an efficient solution to this problem by offering the famous Kwak beer in a special glass that could be fixed to the carriage, so the drivers could also enjoy one.

This story inspired a brewer from nearby Buggenhout and since the 1980s the Pauwel Kwak is brewed by Brouwerij Bosteels, which also produces the popular Tripel Karmeliet and the DeuS Brut des Flandres.

**Comment by mortinus** [comment]
...Napoleonic code... :rofl:  :rofl:  :rofl: 

I will try to drink it!

**Comment by mortinus** [comment]
found it !!!

It is easy to buy in Auchan, a very good beer with a wonderful color.
Thank you
I find it much nicer and more pleasant than my favorite St Denise

Thanks again for the suggestion, excellent with **French fries**... :grin:

**Comment by mortinus** [comment]
There are also the **StarDOS** handling file of the VICE version to peek into too...

**stardos.c**
https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/stardos.c

**stardos.h**
https://sourceforge.net/p/vice-emu/code/HEAD/tree/trunk/vice/src/c64/cart/stardos.h

**Comment by dirkwhoffmann** [comment]
I looked at the details again. This cartridge is so weird internally that it's really not worth the effort. E.g., according to the schematics, address line A13 is fed into a multiplexer and is then mapped to the Exrom line. To emulate this properly, the expansion port would have to emulated for alle memory accesses and not only for those in the cartridge address range (if I understand the schematics correctly). This would slow down the emulator even if no StarDos cartridge is attached. Therefore, I think it's better to live without it. As Alessandro already pointed out, ActionReplay 7.5 is a brilliant alternative.

**Comment by dirkwhoffmann** [comment]
<img width="791" alt="bildschirmfoto 2018-11-11 um 11 10 34" src="https://user-images.githubusercontent.com/12561945/48311605-7a0dfd80-e5a2-11e8-978b-296e5bbf4f52.png">

There is no real underscore on a C64 keyboard (just a graphics symbol that looks like an underscore). Which key do they mean???
Does anybody know how to type a pound sign in VICE? (I don't find a suitable key, at least not on a German keyboard).

**Comment by Alessandro1970** [comment]
...the underscore was a print error, already found it.

**Comment by Alessandro1970** [comment]
The only way to use VICESC on mac is to use the VICESC SDL it has a virtual keyboard (F12 and find it in the menu):
![schermata 2018-11-11 alle 14 13 56](https://user-images.githubusercontent.com/34916641/48313425-91f27b00-e5bc-11e8-83c9-b48cdc0a5795.png)

![schermata 2018-11-11 alle 14 13 23](https://user-images.githubusercontent.com/34916641/48313426-974fc580-e5bc-11e8-95b8-d6f0a3142817.png)

**Comment by dirkwhoffmann** [comment]
The current build (3.2 alpha 2) at

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_ActionPower.zip

contains experimental support for StarDos:

<img width="969" alt="bildschirmfoto 2018-11-11 um 16 49 37" src="https://user-images.githubusercontent.com/12561945/48315156-046e5580-e5d3-11e8-9395-aaba29f7d0ba.png">

However, there seem to be some remaining bugs. I.e., FileCopy and DiskCopy don't seem to work. I tried to run cartridge in VICE, but I don't get the SDL version running on my machine. 

When I start x64sc (SDL version), the app closes immediately after launching. Do I need to install some additional SDL stuff? 🤔 All I need is a pound key 😫.

**Comment by Alessandro1970** [comment]
Have you get the sdl library for osx ?
https://www.libsdl.org/

**Comment by dirkwhoffmann** [comment]
"Have you get the sdl library for osx ?" 

No 🙄. OK, I should have read the manual ...

I got the SDL framework now and copied it in /Library/Frameworks. Now, VICE is running (without any menus though 😳). Anyway, I managed to load StarDos with the F12 menu and it's up and running. "File copy" looks as follows in VICE: 

<img width="831" alt="bildschirmfoto 2018-11-11 um 18 06 25" src="https://user-images.githubusercontent.com/12561945/48315918-b65e4f80-e5dc-11e8-84d5-8754012d39fa.png">

The bad thing: I have no idea what to do next, i.e., copying a file (I know the manual could help ...).
The good thing: It looks the same in VirtualC64, so there is a real chance that StarDos is working (😎) ...

**Comment by dirkwhoffmann** [comment]
OK, here is the manual: 

<img width="844" alt="bildschirmfoto 2018-11-11 um 18 41 46" src="https://user-images.githubusercontent.com/12561945/48316363-ead50a00-e5e2-11e8-810e-16f93ecb646f.png">

Hitting 'R' results in: 

<img width="969" alt="bildschirmfoto 2018-11-11 um 18 36 03" src="https://user-images.githubusercontent.com/12561945/48316370-07714200-e5e3-11e8-9927-73109212dcd0.png">

Using 'C', one can indeed copy single files to another disk: 

<img width="969" alt="bildschirmfoto 2018-11-11 um 18 53 47" src="https://user-images.githubusercontent.com/12561945/48316372-2b348800-e5e3-11e8-8167-0adb34d33f0c.png">

😀

**Comment by Alessandro1970** [comment]
It works fine, great job.

The freeze button should be disabled, the Stardos cartridge has only the reset button.

**Comment by dada08ms** [comment]
StarDOS works fine !
Thank you
