### ISSUE TITLE
Sepia - greyscale

### ISSUE THREAD

**Issue by vodkaflip** [dirkwhoffmann/virtualc64#415]
Hi,

In the Emulator - Display - Filter dropdown menu, the options for greyscale and sepia seem to have been swapped.

Thanks for a great piece of software!

fliP

**Comment by Alessandro1970** [comment]
Also in version VirtualC64_2.6WT are inverted:
<img width="772" alt="schermata 2018-09-07 alle 23 31 42" src="https://user-images.githubusercontent.com/34916641/45244007-3bd03580-b2f6-11e8-98f2-dcab5b116313.png">
