### ISSUE TITLE
Commodore dm602 - 1901 "Green" monitor monochrome

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#416]
Hi,
is it possible to add a _green filter_ to simulate the green monitor monochrome Commodore ?

![commodore_dm602_green_small](https://user-images.githubusercontent.com/34916641/45244617-e5b0c180-b2f8-11e8-80b0-bebb6bc2adba.jpeg)

**Comment by dirkwhoffmann** [comment]
I plan to add a selection box "Monitor" to the Emulator settings with the following options: 

Color 
Black and white 
Monochrome (Green)
Monochrome (Amber)
Monochrome (Sepia)

I'm still unsure how to correctly convert an RGB color to a greenish color value. In the case of a black and white monitor, it's easy. One could simply convert the color to the YUV model and display the luminance. For a green display, one needs to "multiply" the luminance by a green base color and I guess the multiplication is different to a simple linear interpolation. Has anybody already found some document or example code that explains the conversion?

**Comment by Alessandro1970** [comment]
Green.vpl: 
#
# VICE Palette file
#
# Syntax:
# Red Green Blue Dither
#

# Black
0c 14 00 F

# White
95 FF 00 F

# Red
36 5C 00 F

# Cyan
6E BD 00 F

# Purple
44 75 00 F

# Green
65 AD 00 F

# Blue
18 29 00 F

# Yellow
83 E0 00 F

# Orange
49 7D 00 F

# Brown
20 36 00 F

# Light Red
61 A6 00 F

# Dark Gray
2B 4A 00 F

# Medium Gray
5B 9C 00 F

# Light Green
8A ED 00 F

# Light Blue
53 8F 00 F

# Light Gray
79 CF 00 F

**Comment by Alessandro1970** [comment]
Amber.vpl:
#
# VICE Palette file
#
# Syntax:
# Red Green Blue Dither
#

# Black
45 34 36 0

# White
E4 66 17 0

# Red
65 2D 2A 0

# Cyan
AA 4C 2A 0

# Purple
70 32 2B 0

# Green
9D 46 2A 0

# Blue
42 26 28 0

# Yellow
D8 61 21 0

# Orange
79 35 2B 0

# Brown
4E 29 29 0

# Light Red
92 41 2A 0

# Dark Gray
5A 2C 2A 0

# Medium Gray
89 3D 2A 0

# Light Green
E2 65 23 0

# Light Blue
81 3A 2A 0

# Light Gray
C6 59 24 0

**Comment by Alessandro1970** [comment]
I remember three types of monochromatic monitors on sale for the Commodore64 besides the TV B/W and the color one.
Here, they were known as the green phosphor monitor, the amber phosphor monitor and the white/paper phosphor monitor.  I do not know if at the time it was correct to say "phosphorus" but they were called that.
![untitled 1](https://user-images.githubusercontent.com/34916641/45806317-07c71e00-bcc1-11e8-9984-46d5a14a3788.jpg)

**Comment by rossimariolee** [comment]
Great.
I had a PC20 Commodore with a white/paper phosphor monitor: it was great for programming in turbo pascal, it did not strain your eyes.
It would be great to be able to choose these monitors in VirtualC64 and bring them in real time to see what effect it does!
Great option.
Thank you

**Comment by Alessandro1970** [comment]
For VICE have made 2 VPL files that should simulate the amber and green monitors, I tried them on the VICE but it does not seem a good result ...
[amber.zip](https://github.com/dirkwhoffmann/virtualc64/files/2400582/amber.zip)
[green.zip](https://github.com/dirkwhoffmann/virtualc64/files/2400584/green.zip)

**Comment by Alessandro1970** [comment]
Great, I appreciate it a lot.

**Comment by mortinus** [comment]
Beautiful add-on! Many thanks.

**Comment by mortinus** [comment]
Will there be a white/paper monitor filter?

**Comment by Alessandro1970** [comment]
White paper or BW have the same yield, the difference was in the monitor that was high persistence. With the emulator we have the same result as BW more or less.

**Comment by mortinus** [comment]
In Italy you had more monitors green phosphors because with your military system dated you had acquired more orders on the products here and remained in capital gains ...
In France we had more BLU monitors and I assure you that they were more relaxing ...

**Comment by Alessandro1970** [comment]
Eh.. yes you're right, Italy has had and has this kind of problems. 
I hope in a united Europe as the only hope not to sink into a deeper crisis because of the continued loss of possessions due to non-EU buyers (the evil from outside comes from the presence of groups with capital and no capital, understand me despite the language different: our capital should be preserved with commitment and sense of duty and not sold off...). 
And perhaps in the minds of some Europeans the common concept of the Holy Roman Empire has not completely vanished, I hope that too much weakness based on past taboos does not make us helpless and unable to react, unfortunately the story is always made by those who win and it is too easy bestowing sentences, after ...
However, this is not the place for 2 speeches and 4 beers, _not bad your idea of blue phosphors_, maybe Dirk implements it together with Amber and Green ... If yes, I'll try it willingly!

**Comment by puleyo** [comment]
Never heard of a commodore blue monitor for commodore 64/128

**Comment by Alessandro1970** [comment]
I never even heard of blue monitors for C64 too, but @mortinus in France **yes** !

**Comment by dirkwhoffmann** [comment]
When I add Duron paperwhite 

<img width="284" alt="duron" src="https://user-images.githubusercontent.com/12561945/45903603-6665d680-be3e-11e8-9e08-2e0185456448.png">

as base color, it looks like this:

<img width="791" alt="paperwhite" src="https://user-images.githubusercontent.com/12561945/45903586-5b12ab00-be3e-11e8-81e0-b8ee92b129d7.png">

It's very close to black and white though.

**Comment by dirkwhoffmann** [comment]
Does anybody have a reference picture of a blue monochrome monitor?

**Comment by Alessandro1970** [comment]
Commodore PET 2001 series had monochrome monitor (blue phosphor)
Monochrome monitors are commonly available in three colors: if the P1 phosphor is used, the screen is green monochrome. If the P3 phosphor is used, the screen is amber monochrome. If the P4 phosphor is used, the screen is white monochrome (known as "paper white"); this is the same phosphor as used in early television sets. An amber screen was claimed to give improved ergonomics, specifically by reducing eye strain; this claim appears to have little scientific basis. 
I do not find any blue monitor for C64 neither for the Amiga.

**Comment by dirkwhoffmann** [comment]
"If the P4 phosphor is used, the screen is white monochrome (known as "paper white")"

OK, cool, so the paperwhite option is meant to be similar to black and white.

**Comment by Alessandro1970** [comment]
PET 2001 series / 2001-N & -B series, CBM 3000 series
Video: discrete TTL video circuit, 9" monochrome monitor (**blue phosphor on the original 2001**, green on 2001-N PETs)

![commodore_pet_2001_display](https://user-images.githubusercontent.com/34916641/45918771-2dece980-be8c-11e8-995a-a2d11e032117.jpeg)

#
# VICE Palette file
#
# Syntax:
# Red Green Blue Dither
#

# white screens use P4 phosphor

# Background
00 00 00 0

# Foreground
FF FF FF F

**Comment by mortinus** [comment]
I'm sorry I was joking, I was not referring to the commodore 64, but to the monitors used in the offices of IBM that in those years were in blue phosphors.
Forget about that!
😆

**Comment by dirkwhoffmann** [comment]
Can I close?

**Comment by Alessandro1970** [comment]
Ok
