### ISSUE TITLE
Test_box_check_sprite_a.prg Failed

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#418]
Hello everyone, I found this c64 sprites test on the internet, it always fails on my VirtualC64.
[Test_box_check_sprite_a.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2364043/Test_box_check_sprite_a.prg.zip)

<img width="774" alt="schermata 2018-09-09 alle 09 28 38" src="https://user-images.githubusercontent.com/41686391/45262223-2c92da00-b413-11e8-8932-e1741150726d.png">

**Comment by dirkwhoffmann** [comment]
Thanks for finding this! Does the page where you've found it also provide the source code of this test or only the .prg?

**Comment by Alessandro1970** [comment]
...only this: https://csdb.dk/release/?id=88933
and something here: https://csdb.dk/forums/?roomid=7&topicid=73859&showallposts=1

**Comment by dirkwhoffmann** [comment]
Please post more of such test cases if you find any.

<img width="791" alt="spritechecka" src="https://user-images.githubusercontent.com/12561945/45581747-ff4c9d00-b8e6-11e8-9129-b21090a8c7ef.png">
