### ISSUE TITLE
CIA interface chip

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#422]
Hi,
what kind of CIA interface chip is used in VirtualC64 ?

**VirtualC64: Passed
ViceSC: Failed**

[vecefailedvia13.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2372812/vecefailedvia13.prg.zip)

ViceSC:
<img width="717" alt="schermata 2018-09-11 alle 23 36 50" src="https://user-images.githubusercontent.com/34916641/45389307-dfce1f80-b61b-11e8-9f49-75c8539758df.png">

VirtualC64:
<img width="778" alt="schermata 2018-09-11 alle 23 37 52" src="https://user-images.githubusercontent.com/34916641/45389317-e9578780-b61b-11e8-9ca0-50be63687112.png">

**Comment by Alessandro1970** [comment]
[vice failed_cia-sp-test-oneshot-new.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2372837/vice.failed_cia-sp-test-oneshot-new.prg.zip)

VirtualC64:
<img width="775" alt="schermata 2018-09-11 alle 23 42 41" src="https://user-images.githubusercontent.com/34916641/45389710-05a7f400-b61d-11e8-9a9d-97139a527029.png">

ViceSC:
<img width="712" alt="schermata 2018-09-11 alle 23 42 50" src="https://user-images.githubusercontent.com/34916641/45389713-0a6ca800-b61d-11e8-8ced-e1c379e32742.png">

**Comment by dirkwhoffmann** [comment]
Currently, VirtualC64 emulates the old CIAs. Hence, all VICE tests labeled "new" will fail.

I'll add support for the new CIAs in on of the next releases (most likely 2.7).
