### ISSUE TITLE
Bitfade.prg test fails

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#426]
Bitfade test fails (it could be involved in some Emulamer code).
[bitfade.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2386430/bitfade.prg.zip)
Source: https://sourceforge.net/p/vice-emu/code/HEAD/tree/testprogs/CPU/cpuport/

VirtualC64:
<img width="773" alt="schermata 2018-09-16 alle 10 59 40" src="https://user-images.githubusercontent.com/34916641/45594769-75610a80-b9a0-11e8-967a-9896c86effc9.png">

ViceSC:
<img width="715" alt="schermata 2018-09-16 alle 11 05 59" src="https://user-images.githubusercontent.com/34916641/45594776-8ad63480-b9a0-11e8-8620-ff9cdca23513.png">

**Comment by Alessandro1970** [comment]
+;----------------------------------------------------------------------------
+; SHA "stable" behaviour check
+; i**nspired by emulamers "bad copy"**
+;----------------------------------------------------------------------------
+
+basicstart = $0801
+
+                * = basicstart
+                !word basicstart + $0c
+                !byte $0a, $00
+                !byte $9e
+
+                !byte $32, $30, $36, $32
+
+                !byte 0,0,0
+
+                * = basicstart + $0d
+
+;---------------------------------------------------------


++++++++++++++++++

+;----------------------------------------------------------------------------
+; SHA "unstable" behaviour check
+; **inspired by emulamers "bad copy"**
+;----------------------------------------------------------------------------
+
+basicstart = $0801
+
+testpatternlen = 21 + 2
+
+                * = basicstart
+                !word basicstart + $0c
+                !byte $0a, $00
+                !byte $9e
+
+                !byte $32, $30, $36, $32
+
+                !byte 0,0,0
+
+                * = basicstart + $0d
+
+;----------------------------------------------------


https://mail.prefuse.org/p/vice-emu/mailman/vice-emu-commit/thread/From_gpz%40users.sourceforge.net_Thu_Apr_24_00%3A56%3A34_2014/

**Comment by dirkwhoffmann** [comment]
<img width="853" alt="badcopy" src="https://user-images.githubusercontent.com/12561945/45923913-aadc9980-bf46-11e8-90b9-93c9388de17d.png">

**Comment by dirkwhoffmann** [comment]
Do you remember which demo is using the processor port bitfading stuff? Although I have managed to get bitfade.prg to mimic VICE's output, I'm pretty sure that the implementation is not 100% accurate.

**Comment by Alessandro1970** [comment]
...not sure, maybe this:

[comaland100percent.zip](https://github.com/dirkwhoffmann/virtualc64/files/2409732/comaland100percent.zip)

**Comment by Alessandro1970** [comment]
...or this:
[Noice_PseudoCode.zip](https://github.com/dirkwhoffmann/virtualc64/files/2410014/Noice_PseudoCode.zip)

**Comment by dirkwhoffmann** [comment]
Both demos and the test case seems to work: 

<img width="978" alt="bildschirmfoto 2018-09-28 um 16 38 33" src="https://user-images.githubusercontent.com/12561945/46188412-09d25200-c33d-11e8-9f9f-fa16722fcbeb.png">

<img width="978" alt="bildschirmfoto 2018-09-28 um 16 36 15" src="https://user-images.githubusercontent.com/12561945/46188415-0dfe6f80-c33d-11e8-908b-67c4d2f1e040.png">

<img width="978" alt="bildschirmfoto 2018-09-28 um 16 33 32" src="https://user-images.githubusercontent.com/12561945/46188419-0fc83300-c33d-11e8-9799-5fa6793c0808.png">
