### ISSUE TITLE
WarpSpeed v2 1987 - Cartridge

### ISSUE THREAD

**Issue by shauladeneb** [dirkwhoffmann/virtualc64#428]
Good morning,
Could you add full Warpspeed cartridge support ?
It was very thin even for the disk editor.

Thank you
We attach everything we have about it.

regards

[WarpSpeed.zip](https://github.com/dirkwhoffmann/virtualc64/files/2419468/WarpSpeed.zip)

[WarpSpeed_Manual_with_Schematics.zip](https://github.com/dirkwhoffmann/virtualc64/files/2419472/WarpSpeed_Manual_with_Schematics.zip)

**Comment by mortinus** [comment]
Cool, what kind of cartridge is it? I never heard of it

**Comment by Alessandro1970** [comment]
Read shauladeneb's attached documents, Napoleon ! :laughing:  :rofl:  ...

![71oe61go8jl _ac_sl1500_](https://user-images.githubusercontent.com/34916641/46086925-7e748780-c1a9-11e8-8d75-9d345032135c.jpg)

**Comment by dirkwhoffmann** [comment]
😎

<img width="978" alt="bildschirmfoto 2018-09-28 um 18 27 57" src="https://user-images.githubusercontent.com/12561945/46191657-6ab55680-c34c-11e8-97a1-247f93fa48cf.png">

**Comment by mortinus** [comment]
Into internet about Warpspeed I have found:

_If you do a "/" load on a V2.0 cart, you get:
"WARP LOADING $0800 $0801 $0B40"_

What is this mean ?

**Comment by dirkwhoffmann** [comment]
"/" seems to be a shortcut for 

LOAD "*",8,1

<img width="978" alt="bildschirmfoto 2018-09-28 um 19 14 01" src="https://user-images.githubusercontent.com/12561945/46193572-c1be2a00-c352-11e8-96a1-571f2a1a4328.png">


This cartridge is really cutting edge, if we trust the manual:

"You now own the most useful and complete cartridge utility ever produced ... It contains the fastest Commodore-compatible DOS ever produced, allowing you to format disks, load, save, verify, and copy files up to ten times faster than before! "  😂

**Comment by mithrendal** [comment]
The new black darkmode theme with its icons is just stunning beautiful...

**Comment by rossimariolee** [comment]
The cartridge seems to work fine, but the dedicated cartridge menù with its reset button is missing. 
Has it to be added or not ?

**Comment by dirkwhoffmann** [comment]
I didn't add a dedicated menu, yet. Before doing so, I want to ask if somebody knows any cartridge that has buttons other than "Reset" or "Freeze". If not, it might be better to add two menu items "Reset" and "Freeze" to the cartridge menu and to enable or disable these items according to the plugged in cartridge. Otherwise, we end up with more and more submenus (for each cartridge with buttons) with the exact same menu items and the same functionality.

**Comment by Alessandro1970** [comment]
Warpspeed has only a reset button and a switch for compatibily mode (C64/C128), it has not a freezer option.
It would more easy for me to have only a **standard button menù** for cartridge, if a cartridge has not a button it will be grayed (like the smooth option that non worked yesterday)

**Comment by UgoCaneFifone** [comment]
@dirkwhoffmann this issue is closed, why is off the reset button in the menu ?
This cartridge ha a reset button

<img width="689" alt="schermata 2018-10-13 alle 09 41 25" src="https://user-images.githubusercontent.com/41686871/46902826-5fc20080-cecc-11e8-87ce-36b8106c5965.png">

**Comment by dirkwhoffmann** [comment]
Reset button will be enabled for this cart in V3.1
