### ISSUE TITLE
The Tool 64 from "Micro Application" doesn't work

### ISSUE THREAD

**Issue by puleyo** [dirkwhoffmann/virtualc64#430]
Hi, when I run VirtualC64 with THETOOLS64 cartridge it starts but it doesn't show me the freeze and the reset button in the menù.
Bye
<img width="775" alt="schermata 2018-09-29 alle 08 25 55" src="https://user-images.githubusercontent.com/38581054/46242019-3af56580-c3c3-11e8-95a9-1daf72ea49bf.png">
![tool-c64-cart](https://user-images.githubusercontent.com/38581054/46242021-40eb4680-c3c3-11e8-92c0-0d7938e061b3.jpeg)

**Comment by Alessandro1970** [comment]
I think that The Tool-64 from "Micro-Application" is not the same cartridge of The Tool from "Handic" but I suppose you have got this:

[tool64.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2430353/tool64.crt.zip)
[Manuale_the_tools_cartridge.PDF](https://github.com/dirkwhoffmann/virtualc64/files/2430354/Manuale_the_tools_cartridge.PDF)

...it is not supported yet also it run, buttons are missing but you can use the commands.

**Comment by dirkwhoffmann** [comment]
Due to the fact that the cartridge is accepted by the emulator, the .crt header must declare it as a "standard cartridge". Hence, there is no easy way to find out that buttons should be emulated.

**Comment by Alessandro1970** [comment]
I suggest, but it is only my thought, to learn well how to use this "Action Replay" with VirtualC64, because it is an excellent cartridge and works well.

[action replay mk v7.5 (1989)(datel).crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2430360/action.replay.mk.v7.5.1989.datel.crt.zip)

**Comment by dirkwhoffmann** [comment]
BTW, what is the button on this cartridge doing?

**Comment by Alessandro1970** [comment]
Freezer button, after pressed it launchs a menù (f1, f2,...)

**Comment by Alessandro1970** [comment]
The Tool [AKA THE TOOLS, AKA TOOL-64] Micro Application (Handic) was an interesting cartridge with only a HORRIBLE FREEZER BUTTON (because it was on the back) ...

![s-l16004](https://user-images.githubusercontent.com/34916641/46662924-fb95f880-cbbc-11e8-8cce-d5508136edc4.jpg)

**Comment by Alessandro1970** [comment]
This is the complete manual in English.
[The_Tool_for_the_Commodore_64_Manual_(Cartridge).zip](https://github.com/dirkwhoffmann/virtualc64/files/2459985/The_Tool_for_the_Commodore_64_Manual_.Cartridge.zip)

[](http://www.bombjack.org/commodore/applicationsThe_Tool_for_the_Commodore_64_Manual_%28Cartridge%29.pdf)

**Comment by UgoCaneFifone** [comment]
In the picture the button is a bit broken, generally it was leaking a bit more,
However, this was an excellent cartridge.

**Comment by dada08ms** [comment]
Hello to all,
I had this cartridge, I bought it by mail because I had seen the advertisement in a magazine, it did not have the reset button but only the freezer button.
All in all it was a good cartridge with various useful options.

**Comment by dirkwhoffmann** [comment]
There is only a freezer button, but no reset button, right?

**Comment by Alessandro1970** [comment]
This is a very rare cartridge, I do not think that someone has got the schematics.
The freezer button was the only button and it Launchs a menu...noyhing else I suppose.

**Comment by Alessandro1970** [comment]
Using the VICESC the cartridge **freezer button does not work**.
The Tool-64 is not supported on VICE version 3.2 GTK.

![untitled 2](https://user-images.githubusercontent.com/34916641/46931843-2fee3680-d04d-11e8-9a56-a5bd833c0817.jpg)
![untitled 3](https://user-images.githubusercontent.com/34916641/46931847-34b2ea80-d04d-11e8-8f70-b126cb92887c.jpg)

**Comment by dirkwhoffmann** [comment]
I guess VICE has the same "problem" as VirtualC64. The cartridge identifies itself as a cartridge of type "NORMAL", so it is treated like one without buttons.

**Comment by dirkwhoffmann** [comment]
I close this issue for now. Please reopen, if more information about the cartridge's internals are available.

**Comment by Alessandro1970** [comment]
I think this issue must be opened and closed.
I think the The-Tools cartridge produced by MICROApplication/Handic works very well on the VirtualC64.
I maybe this cartridge has been exchanged for another one with a similar name, but **if we talk about The-Tool 64 by Handic Software we can close** ...
I'll explain:
The cartridge: 
[TOOL-64_Handic.zip](https://github.com/dirkwhoffmann/virtualc64/files/2571098/TOOL-64_Handic.zip)
The complete and original manual:
[The_Tool_for_the_Commodore_64_Manual_(Cartridge).zip](https://github.com/dirkwhoffmann/virtualc64/files/2571100/The_Tool_for_the_Commodore_64_Manual_.Cartridge.zip)
Overview:
![untitled 3](https://user-images.githubusercontent.com/34916641/48335240-71c6c880-e65d-11e8-9d33-cd9a122ba619.jpg)

There is **no freeze button** , **neither a reset button** !!! This is only a Basic and Drive Cartridge enhancer !!!

:hugs:  :rofl:

**Comment by mortinus** [comment]
![03288203](https://user-images.githubusercontent.com/41686391/48338374-c4a47e00-e665-11e8-8725-7fc672f7ec2a.jpg)

Noooo, I did the freeze 1000 times for nothing .....
