### ISSUE TITLE
Rom dialog does reappears after adding all Roms

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#433]
When adding all four Rom files, the Rom dialog vanishes and appears again. 

Seen on Mojave, not tested on High Sierra.

**Comment by Alessandro1970** [comment]
Yes, it also happened to me on Mojave.
Would it be possible to insert the rom directly into the emulator file and not into an external preference file?

**Comment by dirkwhoffmann** [comment]
What do you mean by putting the rom directly into the emulator file?

**Comment by Alessandro1970** [comment]
Permanently insert the Roms in a folder right inside the VirtualC64 APP, the main file.
I had the impression that the roms were saved in a file inside the "preferences" folder because the VirtualC64 requested them again after deleting this file.

**Comment by dirkwhoffmann** [comment]
The Roms are not copied anywhere. VirtualC64 simply remembers their filename and path in the User Default Storage as a string.

**Comment by Alessandro1970** [comment]
ah, here it was I was wrong!
I did not know, I had removed the roms folder, so that the VirtualC64 had made a copy of its own ...
Sorry, my fault.
