### ISSUE TITLE
VC64 3.0 Beta 1 Screen

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#435]
Only shows half the screen/monitor?
<img width="1680" alt="screen shot 2018-10-03 at 8 12 31 pm" src="https://user-images.githubusercontent.com/31462938/46446176-d29edf00-c748-11e8-8d1f-7a1db1b51c2b.png">

**Comment by dirkwhoffmann** [comment]
I think this only happens, because your window is too big (the window keeps its aspect ratio and stretches into the non-existent monitor area). Try to enter and exit full screen mode.

**Comment by bluecursor** [comment]
Did. Fine in Full screen, but going back to windowed its the same, 1/2 screen

Frank Michielli

_o/ Sent with iOS Spark!
On Oct 4, 2018, 12:40 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

I think this only happens, because your window is too big (the window keeps its aspect ratio and stretches into the non-existent monitor area). Try to enter and exit full screen mode.

**Comment by dirkwhoffmann** [comment]
What happens if you downsize the window manually?

**Comment by bluecursor** [comment]
Yup that worked

Frank Michielli

_o/ Sent with iOS Spark!
On Oct 4, 2018, 12:47 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

What happens if you downsize the window manually?

**Comment by bluecursor** [comment]
Drag and Drop the Kernel File into vc64
