### ISSUE TITLE
CIA/cia-timer.prg fails for new CIAs

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#436]
<img width="1053" alt="bildschirmfoto 2018-10-04 um 07 49 07" src="https://user-images.githubusercontent.com/12561945/46455467-7620db80-c7ab-11e8-91c6-7b5aaaf2d104.png">

**Comment by dirkwhoffmann** [comment]
<img width="1029" alt="bildschirmfoto 2018-10-05 um 17 37 37" src="https://user-images.githubusercontent.com/12561945/46546675-0d7c5080-c8ca-11e8-831b-d2daad0fa18c.png">

That was an easy one. The old CIAs (NMOS technology) are affected by a race condition which is known as "Timer B bug". It prevents the IRQ bit in the ICR register being set for timer B, if the ICR register is read at the same time. The new CIA chips (HMOS II technology) don't seem to be affected by this "bug", because disabling the bug emulation code is enough to make the VICE test pass.

**Comment by Alessandro1970** [comment]
What am I wrong?
It does not work for me
<img width="793" alt="schermata 2018-10-07 alle 10 52 18" src="https://user-images.githubusercontent.com/34916641/46580116-17639800-ca1f-11e8-9c5b-050362b5122a.png">

**Comment by dirkwhoffmann** [comment]
3.0 beta 3 should fix it: 

http://www.dirkwhoffmann.de/virtualC64/VirtualC64_3.0_beta3.zip

BTW, thanks again to David Horrocks (Hoxs64). I shamelessly adapted his solution for this problem.
