### ISSUE TITLE
Adding in a BASIC editor, debugger and profile

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#438]
Title explains it, and Simular to:  http://sleepingelephant.com/ipw-web/bulletin/bb/viewtopic.php?f=14&t=8363

**Comment by dirkwhoffmann** [comment]
What exactly should be added?

**Comment by bluecursor** [comment]
Editor: editing, cut and paste, undo/redo, copy to emulator, save to prg, load from prg.

I find if you try to paste in a prg into vc64 it comes up with errors and it can't paste it completely.

The label feature is pretty nice too.

Frank Michielli
\0 Sent with Spark iOS
On Oct 7, 2018, 3:41 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

What exactly should be added?

**Comment by dirkwhoffmann** [comment]
If I unterstand you correctly, you are requesting a programming environment. For me, this seems to be a little off-topic for an emulator. However, I agree that at the moment it's not that easy to get large chunks of text from the Mac into the emulator. Networking could help, but adding this feature is too difficult for me at the moment. Does anybody know if VICE provides some means to get text files into the emulator quickly?

**Comment by dirkwhoffmann** [comment]
Unfortunately, there doesn't seem to be an easy way to get a BASIC program that is written on a Mac into the emulator. Basic programs are not stored in plain text in a C64. They are compressed (tokenized) and pointers are used to link to the next line.
