### ISSUE TITLE
"smooth" filter does not work in 3.0 beta 1

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#439]
Why does the "smooth" filter I used up to the previous version no longer works on 3.0 beta 1?
This is a real shame, as a result it was a good compromise.

<img width="659" alt="schermata 2018-10-06 alle 10 10 49" src="https://user-images.githubusercontent.com/34916641/46569091-760e1080-c950-11e8-87a8-0cd468187316.png">

**Comment by dirkwhoffmann** [comment]
The smooth filter is back. Code is checked in.

**Comment by rossimariolee** [comment]
I have had the same problem, is there a new VirtualC64 version downlodable?

**Comment by dirkwhoffmann** [comment]
V3.0 beta 2 is online.

**Comment by Alessandro1970** [comment]
Thanks, it works perfectly
