### ISSUE TITLE
 KCS POWER CARTRIDGE SUPPORT

### ISSUE THREAD

**Issue by UgoCaneFifone** [dirkwhoffmann/virtualc64#441]
Hello everyone !

Would it be possible to implement full support for the KCS POWER CARTRIDGE ?
It has only one button: the freezer (Menù)

[KCS_Power_Cartridge_1989.zip](https://github.com/dirkwhoffmann/virtualc64/files/2464298/KCS_Power_Cartridge_1989.zip)

KCS Power Cartridge is a multi-function cartridge with the following features:
1. a powerful BASIC TOOLKIT (aid) that considerably simplifies  programming and the detection of errors in programs. You can  use the TOOLKIT commands in your own programs.
2. a quick-loader for DISK as well as TAPE which can also load the more ambitious programs and games.
3. a monitor that is always at your disposal and which gives you access to all memory areas of your Commodore.  When you program, or intent to program, in machine language, the POWER CARTRIDGE is an ideal aid.
4. a PAUSE key with which you can stop any program temporarily.
5. an extensive graphic printer interface with which you can make a print of the screen (HARDCOPY) at any time and from any program.  The uniqueness of this cartridge is that afterwards you can continue the interrupted program.
6. a TOTAL BACKUP facility. This implies that you can save a program available in the memory at any time and load it again at a later time. After this you can continue the program.

Info: http://ar.c64.org/wiki/Power_Cartridge

**Comment by Alessandro1970** [comment]
This was not a very "lucky" cartridge: if you did a backup of a game or a program you could not give it to anyone (without the KCS) because the backup was compacted in a particular way and could be loaded later only with the dedicated command "BLOAD".
Better the other cartridges ...
Despite this ... all cartridges for the C64 are interesting!
Greetings :roll_eyes:

**Comment by UgoCaneFifone** [comment]
Yep, I did not know, that bad of cartridge with the BLOAD
