### ISSUE TITLE
VICII bank switch timing

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#442]
According to the output of test case split-tests/fetchsplit.prg (which I am able to interpret now), VirtualC64 has the following bugs: 

1. VICII model 65x:
Bank switch always happens one cycle too late.

2. VICII model 85x: 
Bank switching should be implemented by a timing delay table as it depends heavily on the source and target bank. Important: The timing table has to distinguish switches caused by writing into $DD00 and switches caused by writing into $DD02 (direction register). 

P.S.: Should be fixed before fixing the Krestage 3 bug (might be related to split tests).

**Comment by Alessandro1970** [comment]
With version 3.0 and the following custom configuration, I can see all the Emulamers demos perfectly (even the famous writings that can be viewed with the "USE 6569" system)
Thank you

<img width="555" alt="schermata 2018-10-13 alle 09 04 03" src="https://user-images.githubusercontent.com/34916641/46902604-52a31280-cec8-11e8-98c8-cef6bef44299.png">

**Comment by mortinus** [comment]
Great!!!
@Alessandro1970  you're right with the standard configuration MOS6569R3 adding the **Custom IC** all the Emulamers work !!!
**Thanks Dirk !!!**

**Comment by UgoCaneFifone** [comment]
Today is celebrated !!!
I also tried the standard configuration that is perfect on 3.0 version, just need to add the CUSTOM IC to read the writing in the UNDEAD demo. 
@dirkwhoffmann  why don't you set custom IC as default in standard configuration (C64 PAL) ?

All EMULAMERS demos now work

Thanks a lot Dirk !!!

**Comment by dirkwhoffmann** [comment]
Bank switch seems to be accurate now, at least I don't see a difference any more. Only the letters and numbers count at the moment, please ignore the garbage lines in between. 

VirtualC64 (V3.1 branch), Model C64 II 

<img width="952" alt="bildschirmfoto 2018-10-13 um 09 34 33" src="https://user-images.githubusercontent.com/12561945/46902825-5fc20080-cecc-11e8-936d-b49bc0b24717.png">

Reference

![fetchsplit prg-8565](https://user-images.githubusercontent.com/12561945/46902838-75372a80-cecc-11e8-8359-0e1096b3e797.png)
:

**Comment by dirkwhoffmann** [comment]
Comparison for Model "C64 PAL" (old VICII, discrete glue logic): 

<img width="952" alt="bildschirmfoto 2018-10-13 um 09 35 17" src="https://user-images.githubusercontent.com/12561945/46902853-c0e9d400-cecc-11e8-8d8d-4b3e4b8130d6.png">

Reference: 

![fetchsplit prg](https://user-images.githubusercontent.com/12561945/46902858-cba46900-cecc-11e8-9e01-9f23d9443820.png)

**Comment by dirkwhoffmann** [comment]
Findings: The contents of the first garbage line is dependent on the RAM init pattern.
