### ISSUE TITLE
EasyFlash test fails

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#448]
Hi,
I noticed that VirtualC64 does not pass the EasyFlash test (press "spacebar" too):
[EasyFlash_Test.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2531962/EasyFlash_Test.crt.zip)

<img width="798" alt="schermata 2018-10-30 alle 23 47 13" src="https://user-images.githubusercontent.com/34916641/47755455-99ea1b00-dc9e-11e8-90f5-298d82b4697d.png">
<img width="555" alt="schermata 2018-10-30 alle 23 50 51" src="https://user-images.githubusercontent.com/34916641/47755470-aa01fa80-dc9e-11e8-942b-f89717de0295.png">

**Comment by dirkwhoffmann** [comment]
Seems to be a more general issue, related to Ultimax mode. In mode 00 and 01, range $A000 - $BFFF is mapped to RAM, but the RAM is not visible in Ultimax mode. 

<img width="236" alt="bildschirmfoto 2018-11-01 um 13 30 00" src="https://user-images.githubusercontent.com/12561945/47851937-6c09f100-ddda-11e8-9ab6-871fb8b4f109.png">

Need to find out which value is returned if RAM is "BLANK".

**Comment by dirkwhoffmann** [comment]
If RAM is unmapped, one gets the most recent phi1 value (in  clock phase phi1, VICII owns the bus).

Hence, the old code 

    case M_NONE:
        // what happens if RAM is unmapped?
        return ram[addr];

needs to be replaced by: 

     case M_NONE:
        return c64->vic.getDataBusPhi1();

<img width="970" alt="bildschirmfoto 2018-11-01 um 14 05 05" src="https://user-images.githubusercontent.com/12561945/47853539-5945eb00-dddf-11e8-86d8-05f5f7e716d4.png">

**Comment by Alessandro1970** [comment]
Now it works, this issue can be closed.
