### ISSUE TITLE
Interrupts/timera.prg fails

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#449]
I noticed this test that does not work on VirtualC64 but it works on the VICESC:
Interrupts/timera.prg: 
[timera.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2531992/timera.prg.zip)

<img width="793" alt="schermata 2018-10-31 alle 00 03 08" src="https://user-images.githubusercontent.com/34916641/47756057-eb93a500-dca0-11e8-9a50-4b02935ac25d.png">
<img width="812" alt="schermata 2018-10-31 alle 00 03 20" src="https://user-images.githubusercontent.com/34916641/47756067-f4847680-dca0-11e8-9e53-ce8ae867e772.png">

**Comment by Alessandro1970** [comment]
...strange, this test does not work neither with HOXS:

![untitled 2](https://user-images.githubusercontent.com/34916641/49000599-5f1eba00-f15a-11e8-8e6f-9587258f9895.png)

**Comment by Alessandro1970** [comment]
I have found that this test is involved here:
![untitled 2](https://user-images.githubusercontent.com/34916641/49000911-511d6900-f15b-11e8-861e-4d0f848680c4.png)

Link: http://wiki.icomp.de/wiki/Chameleon_Core_Bugs

**Comment by dirkwhoffmann** [comment]
Oh, yes, it's related to stepper motor delays. VirtualC64 does not emulate this. As the exact delays seem to be drive model dependent, I think we should better ignore this test.

**Comment by Alessandro1970** [comment]
Ok, so this is no a bug.
