### ISSUE TITLE
Fldscroll test doesn't work correctly

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#450]
The fldscroll test does not behave as correctly as in VICE:
[fldscroll.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/2532010/fldscroll.prg.zip)

<img width="1093" alt="schermata 2018-10-31 alle 00 14 46" src="https://user-images.githubusercontent.com/34916641/47756437-5691ab80-dca2-11e8-813c-d53fe746b0cc.png">

**Comment by dirkwhoffmann** [comment]
Works fine in V2.5.2, broken in V3.0

**Comment by dirkwhoffmann** [comment]
Error has been introduced 25.8.18 in commit 677e49421d17df69fdaeb93e442e099ed1369c44 named "Optimized displayState handling". Will look into it later ...

**Comment by dirkwhoffmann** [comment]
Nailed it. Bug is in VIC::beginRasterline(uint16_t line)   

    // Check if this line is a DMA line (bad line)
    // Note: The value might change later if control register 1 is written to.
    badLine = badLineCondition();
    displayState |= badLine;

needs to be replaced by:

     // Check if this line is a DMA line (bad line)
     // Note: The value might change later if control register 1 is written to.
     if ((badLine = badLineCondition())) {
         delay |= VICSetDisplayState;
     } else {
         delay &= ~VICSetDisplayState;
     }


<img width="995" alt="bildschirmfoto 2018-11-04 um 10 23 29" src="https://user-images.githubusercontent.com/12561945/47962379-4409d000-e01c-11e8-8e92-9b1d794ebd9d.png">

**Comment by dirkwhoffmann** [comment]
Fixed in 3.1 which is now online.
