### ISSUE TITLE
Weird screen since version 3.1

### ISSUE THREAD

**Issue by paulsondervan** [dirkwhoffmann/virtualc64#455]
After I had installed version 3.1, I noticed the C64 screen wasn't smooth anymore.
With version 3.0.1. there was no problem.

Screenshot VirtualsC64 - version 3.0.1
![screenshot_c64_v3 0 1](https://user-images.githubusercontent.com/4964031/47998676-77be2600-e100-11e8-9194-bd93ca968d0f.png)

Screenshot VirtualsC64 - version 3.1
![screenshot_c64_v3 1](https://user-images.githubusercontent.com/4964031/47998677-77be2600-e100-11e8-90a3-f51caee0fdad.png)

**Comment by dirkwhoffmann** [comment]
It's not a bug, it's a feature. You can customize the look in the emulator preferences. If you don't like the retro look, set "Blur",  "Scanline", and "Dot Mask" to "None".

**Comment by paulsondervan** [comment]
Thank you, changing those preferences indeed gave me back the screen I preferred.
