### ISSUE TITLE
discussion menu

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#456]
Hi everyone,

I want to ask if you can add on the github, next to the issue menu, a new "discussion" menu.
it would be useful to ask for information without going to affect the menu for issue.
I write this because I would like to know the list of cartridges supported by VirtualC64 without having to open an issue, because in fact it would not be.
![untitled 2](https://user-images.githubusercontent.com/41686391/48050963-ed2f0280-e1a3-11e8-81ce-094f55aee5ab.jpg)

**Comment by Alessandro1970** [comment]
I do not know if it's possible, maybe it would be to open a page on a forum.
Now the VirtualC64 gives hard times to all the other emulators ...
... not to mention the virtual keyboard that few have and without, certain things you can not do.

_Anyway, did you try this cartridge ?_  **...on VirtualC64 works fine !**

[Fairlight Cracking Cartridge, The (198x)(Fairlight).zip](https://github.com/dirkwhoffmann/virtualc64/files/2552246/Fairlight.Cracking.Cartridge.The.198x.Fairlight.zip)

The freeze and reset keys also work (apparently similar to AR6 but... try it !).

**Comment by dirkwhoffmann** [comment]
A discussion tab would be great, but I think it's not possible inside GitHub. There are a lot of possibilities out there such as Gitter to host such a group or a forum. Can somebody recommend a special platform? I have no personal experience with any of them.

**Comment by Alessandro1970** [comment]
For github:
   https://gitq.com/

Sign it (upper dx) with github account...
![untitled 2](https://user-images.githubusercontent.com/34916641/48057982-a6e29f00-e1b5-11e8-90f8-28c36f3ef214.jpg)

**Comment by dirkwhoffmann** [comment]
GitQ for VirtualC64 is up and running: 

https://gitq.com/dirkwhoffmann/virtualc64

**Comment by mortinus** [comment]
In the main page should be reported the existence of this page/discussion group

**Comment by dirkwhoffmann** [comment]
Link has been added to the main page.

<img width="282" alt="ohne titel" src="https://user-images.githubusercontent.com/12561945/48068385-fb484780-e1d2-11e8-89e7-0d84a23c3498.png">
