### ISSUE TITLE
The Final Cartridge III hangs if freeze button is pressed twice or more

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#460]
The Final Cartridge III hangs if freeze button is pressed twice or more and the inspect windows appears:
<img width="1143" alt="schermata 2018-11-07 alle 23 55 44" src="https://user-images.githubusercontent.com/34916641/48166761-de526800-e2e9-11e8-9ba1-3697f111ee8c.png">

**Comment by dirkwhoffmann** [comment]
Fixed in 3.1.1 which is now online.
