### ISSUE TITLE
Atomic Power / Nordic Power cartridge not working properly

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#462]
I have a problem with this cartridge:
1) **Press Freeze button and enter menu** (not the start menu), than **select utility menu (F3)** : 

<img src='https://gitq.com/files/raw/9be6f9044956f03855664c980ccc384ceb929cde.png' alt='Schermata 2018-11-11 alle 09.40.40.png' width=1686 />

2) **install turbo linker (1)**

<img src='https://gitq.com/files/raw/7f1e799dc577295ce1f1ba130d48496119eeb8b8.png' alt='Schermata 2018-11-11 alle 00.52.15.png' width=1690 />

3) **exit to c64 basic (F3)**

<img src='https://gitq.com/files/raw/2612b579b53fd53d3ff68c9a3719dc9583197b59.png' alt='Schermata 2018-11-11 alle 00.52.34.png' width=1690 />

4) VirtualC64 hangs

<img src='https://gitq.com/files/raw/fcf435bbc0daf600906322ad12525b502dcf63f4.png' alt='Schermata 2018-11-11 alle 00.53.01.png' width=2302 />

<img src='https://gitq.com/files/raw/864ed04bd66284b9455b4a5c3b0c44920a3893e9.png' alt='Schermata 2018-11-11 alle 09.46.01.png' width=2294 />

---

submitted from [GitQ](https://gitq.com/dirkwhoffmann/virtualc64/topics/5/experimental-support-for-atomic-power-nordic-power-cartridge-available/3)

**Comment by dirkwhoffmann** [comment]
How can I press the freeze button in VICE for Mac? 🤔

**Comment by dirkwhoffmann** [comment]
What I found out so far:

When running the test sequence, the cart eventually runs some code in the zero page: 

    AtomicPower: PC: 00A9 setControlReg(0A)

At this time, it sets exrom and game to 1 which means it blends out the cart Roms. 

Later, the code eventually jumps (back) to 88A0 which is now 00 (RAM contents, BRK command). This is where it crashes.

**Comment by dirkwhoffmann** [comment]
I stepped through the code in VICE with the same result. When the cartridge returns from the NMI, ROML is no longer visible. A 00 is read back (BRK instruction) and executed. It seems to be the intended behavior.

**Comment by dirkwhoffmann** [comment]
I've replaced 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_ActionPower.zip

by a newer version (3.2. alpha 2) which uses a different default value for the CRT ram. Could you check if the emulator still hangs when you run the test described above? It seemed to behave like VICE when I tested it (however, the previous version showed some kind of indeterministic behavior, so I'm not sure if it's really fixed).

**Comment by Alessandro1970** [comment]
Now, with alpha 2 the problem after turbo linker is solved.
But now after restart (F3) if freeze button is pressed it hangs:

<img width="844" alt="schermata 2018-11-11 alle 22 43 09" src="https://user-images.githubusercontent.com/34916641/48318596-79598380-e603-11e8-9744-c68fced09ac0.png">
<img width="1143" alt="schermata 2018-11-11 alle 22 43 31" src="https://user-images.githubusercontent.com/34916641/48318602-7eb6ce00-e603-11e8-8fbf-bd692d3117ce.png">

**Comment by Alessandro1970** [comment]
To reproduce the problem:

insert the cartridge
reset VirtualC64
press freeze button
press F3
in the gray menu press F3 (Restart)
press freeze button...
Here it is:
<img width="847" alt="schermata 2018-11-11 alle 22 52 22" src="https://user-images.githubusercontent.com/34916641/48318705-a3f80c00-e604-11e8-9904-ef911002ce1a.png">

**Comment by dirkwhoffmann** [comment]
Yet another try: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha3.zip

Fixing the Nordic Power / Atomic Power cartridge is important, because the cartridge is based on roughly the same hardware as the Action Replay cartridge (V5 and above). Hence, all recently applied bug fixes have affected the ActionReplay class and not the AtomicPower class itself. The AtomicPower cartridge is just a handful of code lines overwriting some methods of the ActionReplay class.

**Comment by Alessandro1970** [comment]
Ok, VirtualC64_3.2alpha3 version for me works

**Comment by Alessandro1970** [comment]
Ok, VirtualC64_3.2alpha3 version for me works

**Comment by mortinus** [comment]
Alpha3 revision works for me.
We can close!
