### ISSUE TITLE
Easy Flash DonkeyKong Junior hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#465]
Hi, Easy Flash DonkeyKong Junior hangs on VirtualC64 at the main screen.

ViceSC:
<img width="589" alt="schermata 2018-11-14 alle 23 10 41" src="https://user-images.githubusercontent.com/34916641/48516133-e9b21000-e862-11e8-9464-875c523b7a88.png">

VirtualC64:
<img width="845" alt="schermata 2018-11-14 alle 23 10 03" src="https://user-images.githubusercontent.com/34916641/48516202-0cdcbf80-e863-11e8-85fb-b249184a7422.png">

GAME: 
[DonkeyKongJR.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2582866/DonkeyKongJR.crt.zip)

**Comment by dirkwhoffmann** [comment]
Alessandro, when I run the CRT in V3.1.1, it looks as follows on my machine: 

<img width="1034" alt="bildschirmfoto 2018-11-18 um 17 00 55" src="https://user-images.githubusercontent.com/12561945/48675043-db5e3f80-eb53-11e8-8f2f-d8b2ec12273d.png">

There is definitely something wrong (the text is broken). Did you also use V3.1.1? If yes, this would be an indication for uninitialized memory or something like that.

It doesn't work with the latest build either, but one can at least make the monkey glow 🙄: 

<img width="254" alt="bildschirmfoto 2018-11-18 um 17 07 35" src="https://user-images.githubusercontent.com/12561945/48675080-8d960700-eb54-11e8-825e-f4edc7e9869f.png">

**Comment by Alessandro1970** [comment]
No, I’m using alpha 3

**Comment by dirkwhoffmann** [comment]
Could you check, if the screen is still scrambled in 3.2 alpha 4? 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha4.zip

Right no, I'm trying to figure out if it's a sprite related issue or a cartridge related issue.

**Comment by Alessandro1970** [comment]
Sorry, it doesn't work yet
<img width="823" alt="schermata 2018-11-19 alle 21 31 25" src="https://user-images.githubusercontent.com/34916641/48733308-8f3df880-ec42-11e8-9140-748593cfce1c.png">

**Comment by mortinus** [comment]
the same for me on VirtualC64 alpha 4

**Comment by dirkwhoffmann** [comment]
It's actually good news that the emulator behaves differently on your machine, because this really backs my hypothesis that it's due to some uninitialized memory. Unfortunately, hunting down such issues is like searching a needle in haystac. To get a hint, I have compiled 3.2 alpha 5 as a debug executable. Could you please do the following for me? 

1. Run 3.2 alpha 5, either from the command line or in Xcode.
2. Run Donkey Kong Jr. until the scrambled screen appears.
3. Hit Edit->Debug->Dump State->C64->Expansion Port.
4. Hit Edit->Debug->Dump State->C64->VIC.

Post the debug output here (it appears in the console if you run the app from the command line or in the Xcode window if you run it from there). It should look similar to this (some values might be different): 

    VIC
    ---
    
           Chip model : 4
                  PAL : yes
                 NTSC : no
           Glue logic : 1
         Gray dot bug : yes
       is656x, is856x : 0 1
         Bank address : C000
        Screen memory : 0C00
     Character memory : 2000
    X/Y raster scroll : 0 / 3
        Control reg 1 : 33
        Control reg 2 : D8
         Display mode : Multicolor bitmap mode
                (X,Y) : (472,104)  
                   VC : F0
               VCBASE : F0
                   RC : 05
                 VMLI : 08
              BA line : high
          MainFrameFF : 0
      VerticalFrameFF : 0
         DisplayState : on
        SpriteDisplay : 00 (00)
            SpriteDma : 00 ( 0 0 0 0 0 0 0 0 )
          Y expansion : FF ( 1 1 1 1 1 1 1 1 )
    Expansion port
    --------------
     Game line (phi1 / phi2):  1 / 1
    Exrom line (phi1 / phi2):  1 / 1
    
    Cartridge
    ---------
            Cartridge type: 32
     Game line in CRT file: 0
    Exrom line in CRT file: 1
     Number of Rom packets: 0
    
    EasyFlash
    ---------
    
    bank = 3
    FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF ...
    
    
    FlashRom
    --------
    
         state: 0
     baseState: 0
    numSectors: 8
    sectorSize: 65536
    
    FlashRom
    --------
     
         state: 0
     baseState: 0
    numSectors: 8
    sectorSize: 65536

**Comment by Alessandro1970** [comment]
🖖 downloading xcode just now...

**Comment by Alessandro1970** [comment]
Only one help:
I run VirtualC64 form Terminal (Open ViertualC64.app) than "Hit Edit->Debug->Dump State->C64->Expansion Port" ...but I do not know where the dump files are saved.
Where can I find the dump files ? They are not in the desktop

**Comment by dirkwhoffmann** [comment]
There are no dump files. The info messages are (supposed to be) written to the console window in which VirtualC64.app was launched.

**Comment by Alessandro1970** [comment]
Excuse me ...console window = Terminal Window ?
This one ?
<img width="600" alt="appleterminal2" src="https://user-images.githubusercontent.com/34916641/48823112-e5ed2480-ed5f-11e8-8041-d41fbb129740.png">

I have copied VirtualC64.app on the Desktop, than I have opened the terminal. I have reached the Desktop path (pwd --> Desktop) than I have given this command: **Open VirtualC64.app**
Once launched the emulator I have loaded the Donkey.crt and when appeared the scrambled screen I have done this: _Hit Edit->Debug->Dump State->C64->Expansion Port_
None different was shown in the terminal window

Maybe there is another way for open an app in the Terminal or the console window in not the terminal...

**Comment by dirkwhoffmann** [comment]
Launch it like this (im my case, the app is in the Downloads folder):

<img width="682" alt="bildschirmfoto 2018-11-21 um 07 42 40" src="https://user-images.githubusercontent.com/12561945/48823446-28633100-ed61-11e8-85c6-12376b3d772e.png">

**Comment by Alessandro1970** [comment]
Ok, I'll try this evening
This is very interesting, thank you

**Comment by Alessandro1970** [comment]
**VIC**
---

       Chip model : 2
              PAL : yes
             NTSC : no
       Glue logic : 1
     Gray dot bug : yes
   is656x, is856x : 1 0
     Bank address : C000
    Screen memory : 0C00
 Character memory : 2000
X/Y raster scroll : 0 / 3
    Control reg 1 : 33
    Control reg 2 : D8
     Display mode : Multicolor bitmap mode
            (X,Y) : (392,311)  
               VC : 3E8
           VCBASE : 3E8
               RC : 07
             VMLI : 00
          BA line : high
      MainFrameFF : 1
  VerticalFrameFF : 1
     DisplayState : off
    SpriteDisplay : 00 (00)
        SpriteDma : 00 ( 0 0 0 0 0 0 0 0 )
      Y expansion : FF ( 1 1 1 1 1 1 1 1 )

**Comment by Alessandro1970** [comment]
**Expansion port**
--------------
 Game line (phi1 / phi2):  1 / 1
Exrom line (phi1 / phi2):  1 / 1

Cartridge
---------
        Cartridge type: 32
 Game line in CRT file: 1
Exrom line in CRT file: 0
 Number of Rom packets: 0

EasyFlash
---------

bank = 3
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 
FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 

FlashRom
--------

     state: 0
 baseState: 0
numSectors: 8
sectorSize: 65536
       rom: 0x10936c000

FlashRom
--------

     state: 0
 baseState: 0
numSectors: 8
sectorSize: 65536
       rom: 0x1093ec000

**Comment by dirkwhoffmann** [comment]
Thanks! To my shame, I contradicted rule 1 of software engineering: Use the same test case as the OP. (OK, I invented the rule number just now, but anyways ...). By comparing the output, I noted that I was simply using a different CRT. Mine only has 12 chip packets while yours has 16. Furthermore, they use a different exrom/game start configuration (this is how I noticed it). When I use your original test case which I should have done upfront, I get the same result. I'll keep you informed ...

**Comment by dirkwhoffmann** [comment]
OK, here's the thing. This is what the EasyFlash Programmer's guide tells us:

     4.1 Cartridge Boot Process

     [...] EasyFlash cartridges always start in Ultimax mode.

However, your EasyFlash version of Donkey Kong Jr. looks as follows:

<img width="477" alt="bildschirmfoto 2018-11-22 um 10 27 17" src="https://user-images.githubusercontent.com/12561945/48893999-f2e24480-ee41-11e8-9f27-b31c48c131a0.png">

Ultimax mode is a synonym for EXROM = 1 and GAME = 0, so this means that some EasyFlash CRT files simply contain wrong initial values for these lines. The custom cartridge implementation uses the values from the CRT file on startup which causes the problem. In alpha6, the default values in EasyFlash cartridges are ignored and the EXROM and GAME lines are always set to 1 and 0, respectively. 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha6.zip

Unfortunately this only solves one part of our problem. There is still the text drawing issue. I verified that the text is drawn with sprites, so this might not be an EasyFlash, but a VICII problem. On the other hand, the D64 version of Donkey Kong Jr. draws the text correctly which hints to an EasyFlash problem. Why is software sometimes so mean to us? 🤔

**Comment by Alessandro1970** [comment]
I would like to close this issue.
What's the Vic problem ? For me with alpha 6 works...
<img width="789" alt="schermata 2018-11-22 alle 22 55 58" src="https://user-images.githubusercontent.com/34916641/48922886-09bc8180-eeaa-11e8-8c37-517604bbb72e.png">

**Comment by Alessandro1970** [comment]
...the graphic defects on the main screen ?

<img width="785" alt="schermata 2018-11-22 alle 23 06 46" src="https://user-images.githubusercontent.com/34916641/48923065-84d26780-eeab-11e8-8bea-3e8a80d9bc40.png">

**Comment by Alessandro1970** [comment]
I noticed that in the vice is also shown the flashing writing "PRESS FIRE" 

![untitled 2](https://user-images.githubusercontent.com/34916641/48930346-33000080-eef0-11e8-842c-6700e5fcc418.png)

**Comment by dirkwhoffmann** [comment]
Yes, the graphics defects on the main screen. The game itself seems to work fine.

**Comment by Alessandro1970** [comment]
There is another version of this CRT:
[DonkeyKongJR.zip](https://github.com/dirkwhoffmann/virtualc64/files/2610729/DonkeyKongJR.zip)

**Comment by dirkwhoffmann** [comment]
It's not a cartridge problem. It's caused by a falsely triggered sprite-background collision interrupt.
Fix is yet to come.

**Comment by dirkwhoffmann** [comment]
Fixed in 3.2 alpha 7 (😎):

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha7.zip

Old code: 

            // Is it a sprite/sprite collision?
            if ((pixelSource[i] & 0xFF) & ((pixelSource[i] & 0xFF) - 1)) {
                
                spriteSpriteCollision |= (pixelSource[i] & 0xFF);
                triggerIrq(4);
            }
            
            // Is it a sprite/background collision?
            if ((pixelSource[i] & 0x100) && spriteBackgroundCollisionEnabled) {
                
                spriteBackgroundColllision |= (pixelSource[i] & 0xFF);
                triggerIrq(2);
            }

New code: 

            // Is it a sprite/sprite collision?
            if ((pixelSource[i] & 0xFF) & ((pixelSource[i] & 0xFF) - 1)) {
                
                // Trigger an IRQ if this is the first detected collision
                if (!spriteSpriteCollision) {
                    triggerIrq(4);
                }
                spriteSpriteCollision |= (pixelSource[i] & 0xFF);
            }
            
            // Is it a sprite/background collision?
            if ((pixelSource[i] & 0x100) && spriteBackgroundCollisionEnabled) {
                
                // Trigger an IRQ if this is the first detected collision
                if (!spriteBackgroundColllision) {
                    triggerIrq(2);
                }
                spriteBackgroundColllision |= (pixelSource[i] & 0xFF);
            }
