### ISSUE TITLE
Easy Flash Mega Apocalypse hangs and Inspect window starts

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#466]
Easy Flash Mega Apocalypse hangs and Inspect window starts:

ViceSc:
<img width="593" alt="schermata 2018-11-14 alle 23 18 46" src="https://user-images.githubusercontent.com/34916641/48516519-dbb0bf00-e863-11e8-9e03-81f0e9c87a7a.png">

VirtualC64:
<img width="1152" alt="schermata 2018-11-14 alle 23 17 59" src="https://user-images.githubusercontent.com/34916641/48516541-ee2af880-e863-11e8-8c10-bf00f5fb0ca8.png">

Game:
[ef-cc-ma-fcg-rem-v11.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2582882/ef-cc-ma-fcg-rem-v11.crt.zip)

**Comment by dirkwhoffmann** [comment]
Could you check, if it still hangs in 3.2 alpha 4? 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha4.zip

**Comment by Alessandro1970** [comment]
Sorry, it doesn't work yet
<img width="1124" alt="schermata 2018-11-19 alle 21 42 11" src="https://user-images.githubusercontent.com/34916641/48733839-0758ee00-ec44-11e8-900d-6c73a852121f.png">

**Comment by mortinus** [comment]
yes, it hangs on alpha 4

**Comment by dirkwhoffmann** [comment]
Likely a duplicate to #465.

Can you check that your version of the CRT file contains a EXROM/GAME combination other than 1/0. If   this is true and the CRT works in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha6.zip,

you can close the issue.

**Comment by Alessandro1970** [comment]
It works fine.
