### ISSUE TITLE
Business S'More Basic

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#468]
Hi everyone,

I would really like it if the possibility of using this BASIC in cartridge could be added.
In the compressed file attached there should be everything, wiring diagram, manual etc.

. Basic Extension, DOS Wedge, Tape Fast Loader
. This 24k Cartridge extends  the usable BASIC V2 space to 60k and adds quite a few commands. The  cartridge was originally created and sold by Kingsoft in Europe and by Cardco in the USA.

THANK YOU !
[Business_S'More_Basic_all_rr.c64.org_2013-05.zip](https://github.com/dirkwhoffmann/virtualc64/files/2591665/Business_S.More_Basic_all_rr.c64.org_2013-05.zip)

![business_basic](https://user-images.githubusercontent.com/41687618/48659902-e2ecee00-ea58-11e8-99b9-8ff78bef3926.gif)

**Comment by dirkwhoffmann** [comment]
This cartridges switches ultimax mode on and off in a very nasty way (depending on the accessed memory location). Anyway, I think I can get it to work with a similar trick that I used to emulate the StarDos hardware (via direct manipulation of the peek source and poke target tables).

**Comment by dirkwhoffmann** [comment]
Indeed, using my dodgy updatePeekPokeTable() cartridge hook, it was easy to implement.  However, the "business basic" seems to be all over my head. This time, I even consulted the manual first: 

<img width="536" alt="bildschirmfoto 2018-11-19 um 16 03 39" src="https://user-images.githubusercontent.com/12561945/48715460-5b98a980-ec15-11e8-998c-32c2933b5485.png">

But if I type that in, it does'n really work: 

<img width="1034" alt="bildschirmfoto 2018-11-19 um 16 02 54" src="https://user-images.githubusercontent.com/12561945/48715511-766b1e00-ec15-11e8-808e-b43d3f097b75.png">

Same in VICE:

<img width="963" alt="bildschirmfoto 2018-11-19 um 16 02 16" src="https://user-images.githubusercontent.com/12561945/48715537-8682fd80-ec15-11e8-9558-c33a942f2c4f.png">

**Comment by dirkwhoffmann** [comment]
Support is available in 3.2 alpha 4: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha4.zip

Any feedback is welcome.

**Comment by Alessandro1970** [comment]
😆  I do not know form where, this Basic dialect, pops from but it works...

<img width="825" alt="schermata 2018-11-19 alle 21 53 04" src="https://user-images.githubusercontent.com/34916641/48734466-c661d900-ec45-11e8-9d83-2244245aa7db.png">

**Comment by mortinus** [comment]
It works fine, but what kind of basic is this ?

**Comment by rossimariolee** [comment]
It works fine

**Comment by UgoCaneFifone** [comment]
It works for me, thank you.
