### ISSUE TITLE
If "NEW" from menu is pressed VirtualC64 hangs (Only in alpha release)

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#469]
Hi,
as for the OPEN command ...if I select "NEW" from menù: VirtualC64 crashes.
This is the report:
[report_new from menu.txt.zip](https://github.com/dirkwhoffmann/virtualc64/files/2597026/report_new.from.menu.txt.zip)
<img width="871" alt="schermata 2018-11-19 alle 22 00 37" src="https://user-images.githubusercontent.com/34916641/48734722-91a25180-ec46-11e8-9961-04b673b4c6d8.png">

**Comment by Alessandro1970** [comment]
This problem occurs with VirtualC64 alpha 3 and alpha 4
If I use 3.1.1 or 3.0.1 version it doesn't happen

**Comment by mortinus** [comment]
It crashes on my mac too. (alpha 4)

**Comment by rossimariolee** [comment]
If "new" is selected from menu VirtualC64 (alpha4) quit immediatly.

**Comment by dirkwhoffmann** [comment]
Duplicate to #249. Old issue has been reopened.

**Comment by dirkwhoffmann** [comment]
Should be fixed in

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha6.zip

If the problem still remains, please look at the debug messages and search for: 

    WindowDelegate<some line number>::windowDidResignMain
    WindowDelegate<some line number>::windowDidBecomeMain
    WindowDelegate<some line number>::adjustWindowSize()

My fixed is based on the assumption that these functions are called in that order, but I'm not sure if this is always true.

**Comment by Alessandro1970** [comment]
It works fine.
