### ISSUE TITLE
Duck Tales Easy Flash hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#470]
Duck Tales Easy Flash hangs.

ViceSC:
<img width="591" alt="schermata 2018-11-19 alle 23 40 49" src="https://user-images.githubusercontent.com/34916641/48739605-ca492780-ec54-11e8-9fd9-855f1c05be6d.png">

VirtualC64 alpha 4:
<img width="800" alt="schermata 2018-11-19 alle 23 40 15" src="https://user-images.githubusercontent.com/34916641/48739633-d59c5300-ec54-11e8-9424-ff730ccf3792.png">

**Comment by Alessandro1970** [comment]
Problem solved with alpha 5 release:
<img width="796" alt="schermata 2018-11-20 alle 23 09 33" src="https://user-images.githubusercontent.com/34916641/48806055-718f9280-ed19-11e8-9225-bcb62f0f2abc.png">

**Comment by dirkwhoffmann** [comment]
I didn't change anything to make it work. Another hint for uninitialized variables (or some other issue that is able to cause indeterministic behavior).

**Comment by dirkwhoffmann** [comment]
Likely a duplicate to #465.

Can you check that your version of the CRT file contains a EXROM/GAME combination other than 1/0. If   this is true and the CRT works in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha6.zip,

you can close the issue.

**Comment by Alessandro1970** [comment]
It works fine.
