### ISSUE TITLE
If ROMS are missing VirtualC64 alpha6 hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#472]
Hi, 
If the ROMS are non set VirtualC64 3.1.1 starts askings for ROMS. If there are no ROMS set before VirtualC64 alpha6 hangs:

VirtualC64 3.1.1:
<img width="929" alt="schermata 2018-11-24 alle 09 18 54" src="https://user-images.githubusercontent.com/34916641/48966079-05878580-efca-11e8-82ac-7453facc85ab.png">

VirtualC64 alpha6:
<img width="696" alt="schermata 2018-11-24 alle 09 20 00" src="https://user-images.githubusercontent.com/34916641/48966106-bc840100-efca-11e8-9ce1-63f97287d358.png">

To solve it I have to set ROMS from 3.1.1 than upgrade to alpha6,  it seems to me that the dialog ROMS does not start in the alpha6

**Comment by dirkwhoffmann** [comment]
Ups, sorry. Here's a fix:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha8.zip
