### ISSUE TITLE
VICE test sprite0move fails in V3.2 alpha 8

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#473]
VICE: 
<img width="963" alt="bildschirmfoto 2018-11-24 um 13 31 44" src="https://user-images.githubusercontent.com/12561945/48968267-5492e200-efed-11e8-8beb-663551bba446.png">
VirtualC64:
<img width="933" alt="bildschirmfoto 2018-11-24 um 13 30 31" src="https://user-images.githubusercontent.com/12561945/48968271-59579600-efed-11e8-9d3b-0776d383e44c.png">
Might be related to #387

**Comment by dirkwhoffmann** [comment]
Was broken with commit f5b416a85e8f644ea8013b7396a46cfedfc86b8b

**Comment by dirkwhoffmann** [comment]
Had to roll back one of the VICII speed optimizations. In the optimized version, the zBuffer and the pixelSource were not reset after each cycle, but only after those cycles that access these variables. Unfortunately this leads to less robust, error-prone code. To fix the issue, I replaced

    #define END_CYCLE \
     dataBusPhi2 = 0xFF; \
     xCounter += 8; \
     if (unlikely(delay)) { processDelayedActions(); }

by the previous implementation: 

    #define END_CYCLE \
     dataBusPhi2 = 0xFF; \
     xCounter += 8; \
     for (unsigned i = 0; i < 8; i++) { zBuffer[i] = pixelSource[i] = 0; } \
     if (unlikely(delay)) { processDelayedActions(); }

**Comment by dirkwhoffmann** [comment]
Bug was not related to #387

**Comment by dirkwhoffmann** [comment]
There is another bug in this test case: Move sprite to the right until X coord reaches 014E:

<img width="1029" alt="bildschirmfoto 2018-11-25 um 12 15 35" src="https://user-images.githubusercontent.com/12561945/48978466-2b855680-f0ac-11e8-9702-bb9cdd60231e.png">

Culprit is commit 3e5ef2aa5c7c669dc946554d36ae836be78e266a

**Comment by dirkwhoffmann** [comment]
3.2 alpha 10 seems to fix the issue: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha10.zip

**Comment by Alessandro1970** [comment]
Ok, this works for me too

**Comment by UgoCaneFifone** [comment]
It's ok for me too
