### ISSUE TITLE
VICE test border-mcbm.prg fails in 3.2 alpha

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#474]
VirtualC64 (C64-II hw config): 

<img width="1029" alt="bildschirmfoto 2018-11-25 um 10 03 40" src="https://user-images.githubusercontent.com/12561945/48977412-ddffee00-f099-11e8-90e1-608e1156a316.png">

VICE (C64C hw config): 

<img width="963" alt="bildschirmfoto 2018-11-25 um 10 05 38" src="https://user-images.githubusercontent.com/12561945/48977414-e6f0bf80-f099-11e8-8783-5421d071d58c.png">

Passes in V3.0
Fails in V3.0.1

**Comment by dirkwhoffmann** [comment]
Broke on Oct 14, commit d66c4e0e8b4cff4e01cfa818ee4da9520ca69c6c

**Comment by dirkwhoffmann** [comment]
Should be fixed in 3.2. alpha 9: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha9.zip

**Comment by dirkwhoffmann** [comment]
Alpha 10 most likely fixes #473 as well:

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.2alpha10.zip

**Comment by Alessandro1970** [comment]
Ok, it works for me

**Comment by UgoCaneFifone** [comment]
It's ok for me too
