### ISSUE TITLE
Add JiffyDOS to list of known Roms

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#478]
Title says it all.

**Comment by dirkwhoffmann** [comment]
<img width="449" alt="screenshot 2018-12-04 at 16 18 00" src="https://user-images.githubusercontent.com/12561945/49451851-58d6b080-f7e0-11e8-9fe7-c3ca36e75f44.png">

Hash values have been added. Please let me know if I should display different names for the Roms.

**Comment by mortinus** [comment]
They are ok

**Comment by tsupplis** [comment]
Hi Dirk, 
I get a different value for the 1541-II rom (bought through retro innovation)
./chksum JiffyDOS_1541-II_6.00.bin
F7F4D931219DBB5D

**Comment by dirkwhoffmann** [comment]
As far as I know, 'cheksum' computes a CRC code. VirtualC64 computes a FNV-1a hash value, because it's super easy to calculate (OK, CRC is not rocket science either, teaching it every semester in my class).

Can you check which hash value is displayed inside VirtualC64? It is of course possible that there are multiple JiffyDOS versions around. I would then have to add new hash values.

**Comment by dirkwhoffmann** [comment]
I've added it to the list of known VC1541 Roms. The following images are recognized by name at the moment: 

    let knownVc1541Roms : [UInt64: String] = [
        0x0000000000000000:
        "This 16 KB Rom contains the firmware of Commodore's VC1541 floppy drive.",
        0x44BBA0EAC5898597:
        "1541-II firmware released in 1987",
        0xA1D36980A17C8756:
        "1541-II firmware appearing in drives with a modern Newtronics Motor",
        0x361A1EC48F04F5A4:
        "Firmware of the old-style 1541 in white case",
        0xB938E2DA07F4FE40:
        "Upgraded firmware for the 1541C drive",
        0x47CBA55F16FB3E09:
        "1541-II firmware with relocation patch",
        0x8B2A523E29BED889:
        "1541-II firmware (JiffyDOS patch)",
        0xF7F4D931219DBB5D:
        "1541-II firmware (JiffyDOS patch 6.00)"
    ]
