### ISSUE TITLE
1541-II-relocated.bin

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#479]
Hi, I have found this 1541 II rom:
_A version of the 1541-II ROM where the modifications to older firmware have been relocated to the lower bank ($c000-$dfff), to improve compatibility with fastloader systems. Made by Wolfgang Moser._

Is it possible implement this version, I can't put it in the rom screen. Maybe this can resolve some incompatibilities with fastloaders.

[1541-II-relocated.zip](https://github.com/dirkwhoffmann/virtualc64/files/2644249/1541-II-relocated.zip)

Info: http://www.zimmers.net/anonftp/pub/cbm/firmware/drives/new/1541/hacks/1541-II-relocated.txt

**Comment by dirkwhoffmann** [comment]
I've added the Rom file signature (magic bytes), so the file is recognised as a VC1541 Rom. I've also added it's hash value to the list of known Roms:

<img width="453" alt="screenshot 2018-12-04 at 15 59 16" src="https://user-images.githubusercontent.com/12561945/49451036-989c9880-f7de-11e8-8234-3f636e1e6a02.png">

**Comment by dirkwhoffmann** [comment]
Feature is available in V3.3 alpha 1: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha1.zip

Please reopen if there is still an issue.
