### ISSUE TITLE
Emulator crashes when using RetroFun adapter

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#481]
Process:               VirtualC64 [1541]
Path:                  /Applications/Emulator/*/VirtualC64.app/Contents/MacOS/VirtualC64
Identifier:            de.dirkwhoffmann.VirtualC64
Version:               3.1.1 (3.1.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VirtualC64 [1541]
User ID:               501

Date/Time:             2018-12-07 08:56:22.750 +0100
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Bridge OS Version:     3.0 (14Y667)
Anonymous UUID:        C60FD33B-932D-1904-E5A9-3244EBB319F4

Time Awake Since Boot: 7800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1541]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   de.dirkwhoffmann.VirtualC64   	0x000000010aeef25b 0x10aec1000 + 189019
1   de.dirkwhoffmann.VirtualC64   	0x000000010af32a45 0x10aec1000 + 465477
2   de.dirkwhoffmann.VirtualC64   	0x000000010af47ef4 0x10aec1000 + 552692
3   de.dirkwhoffmann.VirtualC64   	0x000000010af44b68 0x10aec1000 + 539496
4   com.apple.framework.IOKit     	0x00007fff53dd8580 __IOHIDDeviceInputElementValueCallback + 222
5   com.apple.CoreFoundation      	0x00007fff5135de99 __CFDictionaryApplyFunction_block_invoke + 22

**Comment by rummeyer** [comment]
I am afraid it was just coincidence with the RetroFun adapter. I tried to reproduce in Xcode but failed. 

Unfortunately it just crashed again for almost no reason when opening file in second tab (sorry no Xcode).

[trace.txt](https://github.com/dirkwhoffmann/virtualc64/files/2869253/trace.txt)

**Comment by dirkwhoffmann** [comment]
Version 3.3.1 (which fixes some crashes) is now available via the update server. I am not 100% if this crash is related to the ones fixed, but I hope so.

Please reopen if the problem occurs again.
