### ISSUE TITLE
Save option for display settings

### ISSUE THREAD

**Issue by mortinus** [dirkwhoffmann/virtualc64#483]
Hello, there are many options in the video settings screen, if I find my favorite combination I would like to save it with a name and reload it when I need it. There is a need to be able to save video settings.

<img width="618" alt="48661563-ed68b100-ea73-11e8-98ff-146743fa8340" src="https://user-images.githubusercontent.com/41686391/49714389-ee44cb00-fc4c-11e8-8f67-b28b25b52618.png">

**Comment by dirkwhoffmann** [comment]
Yes, something in this direction might be useful. I'll think about a solution. As far as I know, there is no standard way of doing this in macOS (at least I didn't come across such an option in Apple's standard apps). 

BTW, I just learned that user default settings can be overridden by command line arguments. E.g.,

    VirtualC64 -VC64Autofire 1 -VC64AutofireBullets 142

overrides the corresponding entries in the user defaults database. Obviously this is only useful for power users who are willing to launch apps via the command line. 

I also learned that the user default storage can be examined in Terminal.app with the 'defaults' command: 

    defaults read de.dirkwhoffmann.VirtualC64

    ....
    VC64AutoMount = 0;
    VC64Autofire = 0;
    VC64AutofireBullets = "-3";
    VC64AutofireFrequency = "2.5";
    VC64BasicRomFileKey = "~/Dropbox/C64/RomVICE/basic";
    ....

Fun fact three: Apple saves floating point values as strings in the user default database. I bet the underlying code base is as old as Applescript.

**Comment by michellekg** [comment]
Oh, by the way, is it possible to change default settings for TFT monitors? Now Blur is Enabled and for some time I really thought that image quality in VirtualC64 is little bit worse than in VICE. Then I discovered this option, changed it to Disabled and voila - image quality got better.

**Comment by dirkwhoffmann** [comment]
A config file can be exported and imported in sub menu "VirtualC64 -> Preferences". 
Furthermore, all user defaults can be deleted in this sub menu which resets all user-definable values to their defaults.

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha3.zip

Please reopen if there are any issues.
