### ISSUE TITLE
Title bar doesn't change after eject and reset

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#487]
After eject and reset the title bar remains the same, but there is nothing to be loaded as shows the Load"$" command:

<img width="791" alt="schermata 2018-12-16 alle 23 38 41" src="https://user-images.githubusercontent.com/34916641/50059805-d1981e00-018b-11e9-9951-c2ed353584ac.png">

**Comment by dirkwhoffmann** [comment]
Ups, by cleaning up the code, I accidentally reversed the functionality 🙄. In 3.3 alpha 3, Snapshots open as 'Untitled' whereas all other types show a title. It should be the other way round as it was before. 

The old software engineering rule still applies: Fix two bugs, get one new.

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha4.zip

Please reopen if there are still issues.
