### ISSUE TITLE
User settings for Game Port not reflected in toolbar after restart

### ISSUE THREAD

**Issue by tsupplis** [dirkwhoffmann/virtualc64#489]
Version: V3.3 alpha3
Scenario:
- Set Port 2 to Keyset 1
- Toolbar looks like:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/11035456/50187187-3763e180-0315-11e9-9f37-1d49c90605f1.png">

- Verify the  " " is not working
- Restart
- Toolbar looks like:
<img width="427" alt="image" src="https://user-images.githubusercontent.com/11035456/50187193-421e7680-0315-11e9-84b2-24cecb47202a.png">
- Verify the  " " is not working (i.e. it is correct as port 2 is  actually configured with Keyset 1 but toolbar is incorrect

Same happens with Port 1 and Keyset 1 or 2 or any other setting.

An interesting thing. If after the scenario above, I change Port 1 setting, then the toolbar for Port 2 is correctly changed which demonstrate a problem in initialisation of the buttons in the toolbar.

Another small remark. The fact that Keyset 1 and 2 are the same icon makes it difficult to know what is assigned. Same applies to USB device icons.

**Comment by dirkwhoffmann** [comment]
Thanks for the detailed description how to reproduce the bug. Fix was easy (function validateToolbarItems() ) was not called on startup. 

In addition, keyset 1 and keyset 2 have two different icons now: 

<img width="153" alt="screenshot 2018-12-21 at 10 48 35" src="https://user-images.githubusercontent.com/12561945/50336313-2cc06c80-050e-11e9-8381-47589489bcab.png">

**Comment by tsupplis** [comment]
Everything working for me 😉
Just a last observation: icon L&F/similarity is also true from USB device i.e. USB 1 and USB 2 have same icon.

**Comment by dirkwhoffmann** [comment]
Now, USB icons are different, too: 

<img width="170" alt="screenshot 2018-12-21 at 12 02 19" src="https://user-images.githubusercontent.com/12561945/50339831-bffe9f80-0518-11e9-949c-312413042e2b.png">
