### ISSUE TITLE
Add support for Expert Cartridge

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#490]
Expert Cartridge by the english company Trilogic came in the middle of 1986 relatively late to the european market but got into quite a success story due to its excellent software. Expert Cartridge is a RAM only cartridge carrying 8 kbyte of RAM which can be pre-programmed just like an ISEPIC.

http://rr.c64.org/wiki/Expert_Cartridge

**Comment by mortinus** [comment]
Hello Friends, what cartridge is this? Never heard ?

**Comment by Alessandro1970** [comment]
I did not remember its existence, I found it by chance while I was chasing ISEPIC's electrical schematics.
But have you seen that software? It seems better than ISEPIC!
Freeze button, switch like ISEPIC and ESM button (I do not know this...)

![expert_cartridge_closed_top](https://user-images.githubusercontent.com/34916641/50337416-575ff480-0511-11e9-87d4-53b8d258d64c.jpg)

**Comment by UgoCaneFifone** [comment]
ESM ??? A red led ?

**Comment by Alessandro1970** [comment]
There are: (**Left**) Reset Button, in the **middle** a _tri-state Switch_ (PRG/OFF/ON), (**Right**) button FREEZE (E.S.M.) + led.
![untitled 7](https://user-images.githubusercontent.com/34916641/50340974-5b920f00-051d-11e9-9578-bead4404babf.png)

**Comment by dirkwhoffmann** [comment]
ESM ... European Stability Mechanism 🤔 ... this is what Google told me.

**Comment by Alessandro1970** [comment]
There is the need to reproduce the led, in the bottom bar, for using it

![untitled 2](https://user-images.githubusercontent.com/34916641/50343048-d7905500-0525-11e9-8520-d58eb4cd019c.png)

**Comment by dirkwhoffmann** [comment]
What about integrating the LED into the cartridge icon in the bottom bar?

<img width="386" alt="screenshot 2018-12-21 at 13 48 22" src="https://user-images.githubusercontent.com/12561945/50343450-386c5d00-0527-11e9-8e0e-45f31554b150.png">

The original icon (left) is shown for normal cartridges. The other ones are used for cartridges having a LED.

**Comment by Alessandro1970** [comment]
Great !

**Comment by dirkwhoffmann** [comment]
Martin Sikström has reengineered the cartridge. He has drawn a nice schematic which surely helps to implement it. 

https://people.kth.se/~e93_msi/c64/expert.html

I didn't dive into details yet, but I can already tell that it is quite different to ISEPIC from a hardware point of view. ISEPIC is much simpler.

**Comment by dirkwhoffmann** [comment]
The manual tells me to insert the utility disk and load a program named "N":

<img width="753" alt="screenshot 2018-12-24 at 13 41 47" src="https://user-images.githubusercontent.com/12561945/50399727-c8a5de80-0781-11e9-9005-969405a5166f.png">

Does anybody know where I can get this "utility disk"? I found a couple of disks, but none contained a program "N".

**Comment by Alessandro1970** [comment]
Hi,
If you want to try Expert in Vice **attach this cartridge** :
[Expert Cartridge (1986)(Trilogic).zip](https://github.com/dirkwhoffmann/virtualc64/files/2707432/Expert.Cartridge.1986.Trilogic.zip)


**Than press "N"**

But, Expert does not work on VICE ...as far as I found
https://sourceforge.net/p/vice-emu/bugs/939/

**Comment by dirkwhoffmann** [comment]
Any means in VICE to press Restore without page up? I've got no "page up" on my MacBook.

**Comment by dirkwhoffmann** [comment]
Got it. There must be no space after the 'Z' command...

So here is the cool stuff: Install the Expert cartridge via drag and drop. After the cart got attached, you'll see a switch and two buttons in the bottom bar. Left is "PRG" mode, middle is "OFF", right is "ON". The button next to the cart symbol is "Freeze", the other one "Reset". 

<img width="102" alt="screenshot 2018-12-26 at 15 06 31" src="https://user-images.githubusercontent.com/12561945/50448331-dc3b7b80-0920-11e9-8abd-20b5900d93dc.png">

After switching the cart on (push right), hit the 'Reset' the button to bring up the monitor.  Then type 'N' wich will do some magic (I guess some memory initialisation) and bring up the basic prompt. Now, load some game, e.g., Fort Apocalypse and insert a blank disk in drive 8. 

<img width="1032" alt="screenshot 2018-12-26 at 15 29 53" src="https://user-images.githubusercontent.com/12561945/50448748-36d5d700-0923-11e9-8003-8206c0113156.png">

After some seconds, hit the Freeze button and use the 'Z' command: 

<img width="915" alt="screenshot 2018-12-26 at 15 07 13" src="https://user-images.githubusercontent.com/12561945/50448459-b793d380-0921-11e9-86af-2f4f94d7b8f5.png">

Now watch the stunning CG effects 🤭. If you DON'T HAVE TYPED A SPACE AFTER 'Z' (which I did all the time), the cartridge indeed starts saving to disk: 

<img width="915" alt="screenshot 2018-12-26 at 15 08 04" src="https://user-images.githubusercontent.com/12561945/50448499-fe81c900-0921-11e9-9011-575da2a40c64.png">

After that, export the disk. In my case, I got the following: 

<img width="477" alt="screenshot 2018-12-26 at 15 09 28" src="https://user-images.githubusercontent.com/12561945/50448518-0fcad580-0922-11e9-8ab0-bd34be5ea9da.png">

Now, exit the emulator and launch it again. Insert the disk and type LOAD "*",8,1.

After this is done, blow up all tanks and take care that the evil blue copter doesn't get you. Maybe you also get some fuel first ...

<img width="1032" alt="screenshot 2018-12-26 at 15 10 44" src="https://user-images.githubusercontent.com/12561945/50448560-4b659f80-0922-11e9-8a65-3b77c2131cab.png">

😎

**Comment by Alessandro1970** [comment]
👍🏻👍🏻👍🏻

**Comment by Alessandro1970** [comment]
Which version of Expert Cartridge did you use?

**Comment by dirkwhoffmann** [comment]
Expert Cartridge (1986)(Trilogic).crt (the version that you mentioned in your post above)

**Comment by dirkwhoffmann** [comment]
I just froze boulder dash successfully, so it seems that the cartridge is really working. I think the VICE team didn't have the schematics by the time being and that they based their design decisions on a software review. E.g., they came up with the theory that the cart's internal flipflop toggles with each access to the IO1 space. However, Martin Sikström's schematics shows that this is wrong. Assuming that the schematics is correct, 

1. each access to IO1 space disables the cartridge (if the cart switch is in "ON" position).
2. each NMI enables it (if the cart switch is in "ON" position).

BTW, I skipped implementing the LED. It is driven by some weird analog circuitry which I don't understand, even with the schematics in front of my eyes.

**Comment by dirkwhoffmann** [comment]
If somebody wants to try, please use alpha 7: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha7.zip
