### ISSUE TITLE
When you load some games and you open the virtual keyboard from the Toolbar a bug occurs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#494]
For example, if I load the Antiriad game and open the virtual keyboard from the Toolbar the letters change consistently in lowercase to uppercase. 
This also happens with the Virtual keyboard on a floating window, regardless of where it is positioned.

<img width="784" alt="schermata 2018-12-23 alle 10 24 07" src="https://user-images.githubusercontent.com/34916641/50382351-8a36f380-069d-11e9-802e-4b34ebb2abef.png">

**Comment by dirkwhoffmann** [comment]
This is not a bug though an unwanted feature. Here is the thing: Whenever the C64 switches from uppercase character set to lowercase character set, the virtual keyboard is sent a notification message to update it's symbol map. This works pretty well in standard BASIC mode. Now, if a game switches the char set periodically (for whatever reason, many games do crazy stuff), the virtual keyboard is freaking out. I don't really know what we can do about it. We would loose the feature that the keyboard changes automatically when the user switches from upper to lower character mode or vice versa.
