### ISSUE TITLE
Tick or checkmark in the cartridge menu

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#495]
Hi, if I select Georam or Isepic a tick (checkmark) on the left should be shown.

<img width="784" alt="schermata 2018-12-24 alle 09 30 02" src="https://user-images.githubusercontent.com/34916641/50394619-0b09f400-075f-11e9-8ad4-2f10f7604bf7.png">

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3_alpha7.zip

BTW, do we really need the option "Use Battery Backed RAM". We could enable it by default and if a user really wants to clear GeoRAM during a reset, he can achieve this easily by detaching and attaching the cartridge.
