### ISSUE TITLE
MACH 5 by Access Software support

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#498]
Hello, could you please implement support for the MACH 5 by Access Software?
Many thanks

http://rr.c64.org/wiki/MACH_5

Press: <- + M for menù

**Comment by Alessandro1970** [comment]
I do not know this cartridge, but the name reminds me of a Japanese cartoon of those years 
... will it be a coincidence ? (FASTloader cartridge - Racing machine)

![mchfv](https://user-images.githubusercontent.com/34916641/50824542-29631880-1337-11e9-95b3-6b4862808b42.jpg)

![91ahq focvl _sy445_](https://user-images.githubusercontent.com/34916641/50824556-2ff19000-1337-11e9-8b4a-b336f8ad7580.jpg)

**Comment by UgoCaneFifone** [comment]
...like this one:
![untitled 2](https://user-images.githubusercontent.com/41686871/50829248-1c005b00-1344-11e9-890c-8c212b21590c.png)

**Comment by dirkwhoffmann** [comment]
I think this cartridge is an easy one. Just 8KB and a simple logic for toggling the Exrom line.

**Comment by Alessandro1970** [comment]
Mach5 is a fast loader cartridge designed for use with the Commodore C128/C64 and 1571
or 1541 or compatible disk drive, only a fast loader it has not had a reset button in c64 version ....look the real photos:

![Untitled 1](https://user-images.githubusercontent.com/34916641/61218437-517e6a80-a712-11e9-99e6-ed4e7a6e148d.jpg)

The reset button and the switch for c64/c128 mode can be found in the 128 version:

![480px-Maxx_128](https://user-images.githubusercontent.com/34916641/61218522-7e328200-a712-11e9-9dfc-96b6dfd1375b.jpg)

**Comment by mortinus** [comment]
Wow, my friend ...too nerd ! :laughing: 

![412UK5vIbWL](https://user-images.githubusercontent.com/41686391/61218923-660f3280-a713-11e9-843a-d5c3398680a6.jpg)

**Comment by Alessandro1970** [comment]
Great ...ye, that is my avatar...

Note: MAXX 128 (MACH 128 **Clone** ) from Argentina

**Comment by dirkwhoffmann** [comment]
> Wow, my friend ...too nerd !

Here comes the real nerd stuff 👍:

![mousePad](https://user-images.githubusercontent.com/12561945/61220033-c43d1500-a715-11e9-8f2d-6624a8d44dbf.png)

Actually, it needs some cleaning, but I fear that it'll come out pure black when washed 😬. Did anybody ever try to put a mouse pad in a washing machine??? 🤔

**Comment by Alessandro1970** [comment]
...not in the washing machine, but you can hang the laundry...😀🤪🤞🏻
![154D6DF4-987E-4825-8D9E-F3F011BCCB1F](https://user-images.githubusercontent.com/34916641/61236843-47bc2d80-a739-11e9-8cde-e9497dafaa99.jpeg)

**Comment by UgoCaneFifone** [comment]
Hi All,

...waiting for 3.4 final version :crying:

**Comment by Alessandro1970** [comment]
... :rofl: 

![00000010](https://user-images.githubusercontent.com/34916641/61364020-45ff8080-a885-11e9-8511-dd04838178a2.jpg)

I do not deny to you that I would also like the final version 3.4 !!!
... will come, have faith! :crystal_ball:

**Comment by mortinus** [comment]
...mortinus is crying too for the 3.4 final revision, yep !

![53590_320](https://user-images.githubusercontent.com/41686391/61364872-ef934180-a886-11e9-97b1-6cd5f7fd2d23.jpg)

**Comment by dirkwhoffmann** [comment]
Oh, boy, I knew the two of them were gonna fight someday. It was only a matter of time before VirtualC64 became jealous 😬.

<img width="530" alt="battle" src="https://user-images.githubusercontent.com/12561945/61365282-be674100-a887-11e9-9365-1cb664ebab1f.png">

**Comment by DaitarnIII** [comment]
...oh yes, I think that upgrading VirtualC64 **to 3.4** release would appease souls and **demons** ...

**Comment by UgoCaneFifone** [comment]
News ?
Any chance to see version 3.4 ?

**Comment by dirkwhoffmann** [comment]
> Any chance to see version 3.4 ?

Bad news from the frontline, all developers had to be pulled off. The whole troop has been relocated to the Amiga front to fight Blitter bugs.

**Comment by mortinus** [comment]
On the other hand, vAmiga could go on stand-by for a short time, that is for the time necessary to bring the mythical VirtualC64 to the 3.4 final release ...
Is it not so ? ... it could go even so!
Please...

**Comment by Alessandro1970** [comment]
Wow!
" Is it not so ? ... it could go even so! "

...Mortinus you are a poet!

**Comment by bluecursor** [comment]
LOL! I'm still waiting for 3.3.3 b2 to be released..

**Comment by dirkwhoffmann** [comment]
From the instruction manual: 

<img width="953" alt="Bildschirmfoto 2019-10-11 um 14 41 45" src="https://user-images.githubusercontent.com/12561945/66652198-67c69480-ec35-11e9-8c71-d95e60eccddb.png">

Which key is meant by the triangle? 🤔

**Comment by dirkwhoffmann** [comment]
I've tried Mach5 v3a in VICE, but I didn't succeed. The cart boots fine and I can list the directory by typing "$". But when I try to (warp) load a program, I get a "File not found" error. 

<img width="849" alt="Bildschirmfoto 2019-10-11 um 15 10 08" src="https://user-images.githubusercontent.com/12561945/66654138-defe2780-ec39-11e9-9cc6-9ea2757e54c6.png">

Is this cartridge known to work in VICE? If yes, which version do I have to use?

**Comment by Alessandro1970** [comment]
Triangle?
Is that the left arrow ?  <-

**Comment by dirkwhoffmann** [comment]
> Is that the left arrow ? <-

Yes, indeed 😁

<img width="916" alt="Bildschirmfoto 2019-10-11 um 19 05 09" src="https://user-images.githubusercontent.com/12561945/66670519-46c46a80-ec5a-11e9-8829-ff57cb011d85.png">

When I first tried that symbol, I had a space in between which is not allowed:

<img width="916" alt="Bildschirmfoto 2019-10-11 um 19 06 12" src="https://user-images.githubusercontent.com/12561945/66670545-5643b380-ec5a-11e9-829d-f1e105ba88b6.png">

Now, the main issue is the failure of the warp loader. We need to find out if the cartridge works in VICE.

**Comment by Alessandro1970** [comment]
In VICESC I do so:

type: 
<- +

![Schermata 2019-10-13 alle 16 05 13](https://user-images.githubusercontent.com/34916641/66716914-8ebacd00-edd3-11e9-8dfb-fc4a69db2cae.png)


So it will be enabled:
![Schermata 2019-10-13 alle 16 00 23](https://user-images.githubusercontent.com/34916641/66716919-9da17f80-edd3-11e9-8717-f774297cfe69.png)


...then load a game

**Comment by dirkwhoffmann** [comment]
> type: `<- +`

Doesn't work for me. Same "File not found error" as before (a disk was inserted, of course).

<img width="963" alt="Bildschirmfoto 2019-10-13 um 19 17 52" src="https://user-images.githubusercontent.com/12561945/66719314-6ee4d280-edee-11e9-8476-09fce18c9c3e.png">

(VICE 3.1 with MACH_5_v3a.crt)

**Comment by Alessandro1970** [comment]
ViceSC 3.2 + MACH_5_v3a.crt

![Schermata 2019-10-13 alle 16 00 23](https://user-images.githubusercontent.com/34916641/66721608-a3638900-ee04-11e9-9da1-d818dd45ea26.png)

Works fine

**Comment by Alessandro1970** [comment]
I do not know, it works for me and turn il lightblue screen while loading.
Try VICESC 3.2 on mac
You can download here the cocoa version:
https://alex.kazik.de/download/mac/vice-macosx-cocoa-x86_64-10.9-clang-3.2.dmg

**Comment by dirkwhoffmann** [comment]
VICE 3.2 (from your download link) with Falcon Control D64 and MACH_5_v3a.crt:

https://rr.pokefinder.org/wiki/MACH_5

![Bildschirmfoto 2019-10-14 um 08 11 56](https://user-images.githubusercontent.com/12561945/66731990-675b1300-ee5a-11e9-9be2-ad403eb39c43.png)

**Comment by Alessandro1970** [comment]
If you create a simply basic test ...it works:
![1](https://user-images.githubusercontent.com/34916641/66736869-b7da6c80-ee6a-11e9-82ff-f85ed69945eb.jpg)

![2](https://user-images.githubusercontent.com/34916641/66736880-bd37b700-ee6a-11e9-9f2d-f3511ed70d55.jpg)

If you try to load a game...ok it does not work !

**Comment by Alessandro1970** [comment]
In the VICE it works so ...maybe the same with VirtualC64

For loading I used this **£**

**Comment by Alessandro1970** [comment]
Strange

Try this:

<-- D
<-- + 

£ "Name game"

It works:
![3](https://user-images.githubusercontent.com/34916641/66737429-3552ac80-ee6c-11e9-9264-c0589a453ff2.jpg)

**Comment by Alessandro1970** [comment]
In ViceSc to load something with ** £* ** it is neede to disable Mach DOS  **<-- D**

But disabling DOS I do not know if we can say that there is really a Warp Mode on...

If this CRT doesn't work in VICESC ...I'll close for a while... going to 3.4 release without !

**Comment by Alessandro1970** [comment]
![Untitled 9](https://user-images.githubusercontent.com/34916641/66740831-6df68400-ee74-11e9-91ea-d2ad8250b9f0.png)

To load a game compressed or protected with mach5 before use <-- D option...
There, sometimes, a conflict with 4k basic rom too

**Comment by Alessandro1970** [comment]
16.11.3.52 51 - MACH 5
$8000-$9FFF (8Kb)
Size 	4Kb or 8Kb (1 bank of 4Kb or 8Kb)
EXROM 	active (lo) (0)
GAME 	inactive (hi) (1)
Startup mode 	8k Game
Load address 	$8000-$8FFF (4Kb),

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F       ASCII
      -----------------------------------------------  ----------------
0000: 43 36 34 20 43 41 52 54 52 49 44 47 45 20 20 20  C64?CARTRIDGE???
0010: 00 00 00 40 01 00 00 33 00 01 00 00 00 00 00 00  ???@???3????????
0020: 56 49 43 45 20 43 41 52 54 00 00 00 00 00 00 00  VICE?CART???????
0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ????????????????
0040: 43 48 49 50 00 00 20 10 00 00 00 00 80 00 20 00  CHIP????????.???
0050: AF 83 5E FE C3 C2 CD 38 30 4D 41 43 48 35 A5 93  »ƒ^....80MACH5¥.

This cart has 8Kb ROM mapped at $8000-$9FFF, the $9E00-$9EFF range is mirrored at $DE00-$DEFF and the $9F00-$9FFF range is mirrored at $DF00-$DFFF.

**Comment by dirkwhoffmann** [comment]
I've added VirtualC64 v3.4b1 to the Releases section. It should have the same Mach 5 compatibilities and incompatibilities as VICE. Can you give it a try and see if it differs?

**Comment by Alessandro1970** [comment]
As we know it works fine like in VICESC

**Comment by DaitarnIII** [comment]
Ok, it works fine with basic programs and some adventures.
Better to use other warp cartriges, but it's ok !
Thank you

**Comment by DaitarnIII** [comment]
Are we near at the final 3.4 release ? :-)

**Comment by Alessandro1970** [comment]
Do you know that @mortinus has ever loved the 3.4 release ?

**Comment by UgoCaneFifone** [comment]
Syntax error !

The 3.4 was Ugo's release, look up !

![61364020-45ff8080-a885-11e9-8511-dd04838178a2](https://user-images.githubusercontent.com/41686871/66916491-9a98d000-f01b-11e9-9da2-7e1a20f87d41.jpg)

**Comment by Alessandro1970** [comment]
You are right ...I have painted that pic !

:-D

**Comment by PakkunKinoppi** [comment]
I used last VICESC pokefinder release and **match5** (rev 2 and 3)does not load with warp engaged !
It works only with short basic files!
This screenshot is taken after loading 1943 (game) with warp mode on ( <- + )

![Untitled 2](https://user-images.githubusercontent.com/52820759/68204339-08f00300-ffc8-11e9-982f-4557de7e640c.jpg)

**Comment by UgoCaneFifone** [comment]
Hi, is here somebody still alive ???

**Comment by bluecursor** [comment]
Sorry, totally forgot about this one. Been using Jaffydos 1.3 kernel in replacement of Mach5.
Just tested mach5 and seems to be working great.

Frank Michielli
Sent with iOS Spark!📱
On Dec 6, 2019, 9:19 AM -0500, Ugo <notifications@github.com>, wrote:

Hi, is here somebody still alive ???

**Comment by rossimariolee** [comment]
Are there some news about the 3.4 final release or 3.5 ?

**Comment by dirkwhoffmann** [comment]
> Just tested mach5 and seems to be working great.

OK, I'll close this issue.
