### ISSUE TITLE
Help with Install

### ISSUE THREAD

**Issue by ValiantCuriosity** [dirkwhoffmann/virtualc64#499]
I've searched everywhere on the Internet and can't find out how to install this software on my Mac.

I can run it on Xcode, but I get the rom error message. I don't know where to place the roms. I'd like to use the emulator. Is there a Wiki "How to Install". If someone would help. I'd volunteer to create a short Wiki. 

Thank you.

**Comment by Alessandro1970** [comment]
Drag the pre-compiled app into your mac downloading it from here:
http://www.dirkwhoffmann.de/virtualc64/index.html
Version 3.3 is a great job.

**Comment by Alessandro1970** [comment]
For the roms you can read this discussion:
https://gitq.com/dirkwhoffmann/virtualc64/topics/3/where-do-i-find-compatible-rom-images

**Comment by Alessandro1970** [comment]
After downloading VirtualC64 and the roms, run the emulator and drag&drop the roms in the roms window. Remember to do not move the rom fro the folder after having selected them, the emulator will remember the path of the roms folder.

**Comment by ValiantCuriosity** [comment]
Thanks Everyone for your help. The interface is beautiful. I have the roms installed now. Next, I need to figure out how to run the games. I apologize for cluttering up git with questions, but I can’t find docs for dummies anywhere. ;-)

Does the app need to be compiled via Xcode or does it always need to be loaded through Xcode? Sure would be nice to have a .dmg for this emulator.

-Rachel

**Comment by Alessandro1970** [comment]
There are many places how to find games on the web.
Download .d64 or .t64 or .tap files, drag them in the emulator window the from the menù select first the load command then run to start game after loading.
But first you’ll have to load the commodore 64 manual from the web.

**Comment by Alessandro1970** [comment]
For the app you can use the stand alone executable without the need to compile it.

**Comment by Alessandro1970** [comment]
Look here too:
https://github.com/dirkwhoffmann/virtualc64/releases

**Comment by dirkwhoffmann** [comment]
Alessandro, thank you for the detailed answer. I think it's solved and can be closed.
