### ISSUE TITLE
OpenEMU Macbook Help

### ISSUE THREAD

**Issue by Somuchfun** [dirkwhoffmann/virtualc64#500]
Hi! 
I just installed OpenEMU for the second time after reinstalling my MacBook Pro late 2015 w Touchbar. When I'm trying do download ROMs they appear like a DMG file and if I press the dmg file an installer will open. I can't unzip this file like it says on the rom webpages. If I run the installer it says in the end "successfully installed "Colin McRae" and then nothing more happens? Didn't have any of these problems when I first installed the OpenEMU and started to download roms and other to play my favorite retro games. What am I doing wrong? I have tried to download a couple of different roms and from different webpages with no success. I have no problem with NES games because you just simply drag them into the emulator and it will work just fine. This is just the cd based games and especially my favorite console Sony Playstation 1. Any suggestions? 

/ Somuchfun

**Comment by mortinus** [comment]
Sony Playstation, NES, OPENEmu ?
If you want to play C64 games download them (.d64, .T64, .TAP) and run them in VirtualC64 !

Release V 3.3 for Mac is here:
https://github.com/dirkwhoffmann/virtualc64/releases

**Comment by dirkwhoffmann** [comment]
Can I close?

**Comment by Somuchfun** [comment]
Sorry. Yeah ofc. Problem solved mate.
