### ISSUE TITLE
Virtual 64 Menu Bar  File>'Open Recent' does not list recently game files

### ISSUE THREAD

**Issue by neosquid** [dirkwhoffmann/virtualc64#507]
As title, Under Virtual 64's Finder Menu Bar, File>'Open Recent' does not list recently game files recently played.

Also, Drive 8/9> 'Insert Recent Disk' doesn't seem to remember recently inserted disks.

Virtual 64 3.3
10.13.6 High Sierra

**Comment by dirkwhoffmann** [comment]
The "File->Open Recent" list shows recently opened snapshot files only (no D64, T64, etc.). I guess this is the reason why it remained empty. 

The "Disk->Insert Recent" lists were originally designed to be local to the current document. If you open another emulator window, the list is empty. If you switch back, the original list appears again. I think myself that this is confusing for the user, so I changed it. All emulator instances now use the same URL lists:

http://dirkwhoffmann.de/virtualc64/VirtualC64_3.3.1b2.zip

Can you give it a try? 

There might also be a bug that doesn't show up on my machine. Therefore, please let me know, if the URL lists still behave in a strange way on your machine.

**Comment by neosquid** [comment]
Maybe I was mistaken, but I had the impression that 'File->Open Recent' remembered .d64 files in previous versions. I'm sure I used to load games via that route, but maybe they were snapshots like you said.

The version you  asked to test seems to work as you expected, the disk appears in the disk>insert recent list in each new emulator tab.

**Comment by dirkwhoffmann** [comment]
Thanks a lot for your feedback!

**Comment by dirkwhoffmann** [comment]
Version 3.3.1 is now available via the update server.
