### ISSUE TITLE
audio crash upon exit

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#510]
**To Reproduce**
- Open VirtualC64
- run a .prg/.d64 (must play music).
- click on close X in top left

![Screenshot 2019-05-22 at 23 52 44](https://user-images.githubusercontent.com/3512672/58214199-ccb43900-7cec-11e9-8f42-3c56ad08c791.png)

**Observation:**
The window closes however a loud buzzing sound is audible.This continues until VirtualC64 is quit.

Video attached [Screen Recording.mov.zip](https://github.com/dirkwhoffmann/virtualc64/files/3209646/Screen.Recording.mov.zip)

**Additional information**
- VirtualC64 Version 3.3.1 (3.3.1)
- Mac OS X 10.14.5 Beta (18F127a) (would be interested to see if this happens in a non beta version).

**Comment by dirkwhoffmann** [comment]
Really annoying. I was able to reproduce it and my ears still hurt 🥴.

It should be fixed in 3.3.2 beta 1 which can be downloaded here: 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.2b1.zip

Can you give it a try?

**Comment by DannyCork** [comment]
Confirmed fixed on Mohave 10.14.5 (18F132).
Excellent work.
