### ISSUE TITLE
HOME/CLR on german iso-keyboard /w symbolic key assignment?

### ISSUE THREAD

**Issue by vasquesbc** [dirkwhoffmann/virtualc64#511]
i've tried a lot but i did not succeed in finding the "HOME/CLR" key on my german iso-keyboard while using symbolic key assignment.
got a hint?

**Comment by dirkwhoffmann** [comment]
HOME and CLR are not mapped symbolically, because there don't seem to be reasonable replacements on the Mac keyboard. 

The available options are: 

- Use the virtual keyboard and press HOME or CLR with the mouse.
- Use positional mapping.
- Use a MacBook Pro with a Touch Bar.

**Comment by vasquesbc** [comment]
considering the use of a full-size keyboard i would recommend POS1 (code 73) as HOME/CLR
thank you!

**Comment by dirkwhoffmann** [comment]
Do you mean that one?

![kb](https://user-images.githubusercontent.com/12561945/58545014-b59cac00-8202-11e9-9eeb-7ffcaad6bb36.png)

**Comment by vasquesbc** [comment]
exactly

**Comment by dirkwhoffmann** [comment]
Now, VirtualC64 uses the following symbolic mapping: 

![Bildschirmfoto 2019-05-29 um 17 31 25](https://user-images.githubusercontent.com/12561945/58570436-4772dc00-8238-11e9-958d-2c10fe28a47b.png)

If you use Xcode, you'll find the code fix check into the master branch.

**Comment by vasquesbc** [comment]
works just fine!
sincere thanks.
