### ISSUE TITLE
Take a snapshot every -3 seconds

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#512]
In Settings/Emulator.

![Screenshot 2019-05-28 at 21 47 23](https://user-images.githubusercontent.com/3512672/58511462-c31a4d80-8192-11e9-8050-2bd6706b6be3.png)

This setting seems odd.

**Comment by dirkwhoffmann** [comment]
🤔 Works correctly on my machine:

<img width="314" alt="Screenshot 2019-05-29 at 10 40 12" src="https://user-images.githubusercontent.com/12561945/58542734-65234f80-81fe-11e9-9f37-83734fad6a7e.png">

Does it change to (+)3 if you hit "Restore factory settings"?

Background: In older releases, snapshot behaviour was coded in a single variable. The sign indicated if snapshots should be taken at all and the magnitude coded the interval in seconds. It could therefore be that VirtualC64 reads a value from the user default storage that had once been written with an older version. Newer versions should store positive numbers, only.

**Comment by dirkwhoffmann** [comment]
I'll close this hoping it's fixed. If not, please open again.
