### ISSUE TITLE
Sound stops when audio filter changed

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#513]
**Steps to reproduce**
- load an disk//tape image which plays audio
- click on Inspect(Inspect C64 hardware)
- click on sid
- Change audio filter/ filter type from None to any of low/band/high pass.

**Observation**
- All audio stops.
- Changing back to none does not restore the audio.

**Couple of log file entries during this**
default	23:04:30.558819 +0100	VirtualC64	Removing presenter BE2D98E2-B502-4DE5-AE72-4943BDE0CB3F
default	23:04:30.558984 +0100	VirtualC64	Removing presenter BE2D98E2-B502-4DE5-AE72-4943BDE0CB3F
default	23:04:30.564605 +0100	hidd	Connection removed: IOHIDEventSystemConnection uuid:0ECA4E3B-67AB-48F1-9C53-A53C51E9A7A3 pid:1691 process:VirtualC64 type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) inactive:0

I tested this using 1942 (1986)(Elite).tap.zip
[1942 (1986)(Elite).tap.zip](https://github.com/dirkwhoffmann/virtualc64/files/3229927/1942.1986.Elite.tap.zip)

### **Video (4MB) https://gofile.io/?c=NODb5t** 

**Specifications**
Mac OS X 10.14.5 (18F132)
VirtualC64 Version 3.3.2 (3.3.2)

**Comment by dirkwhoffmann** [comment]
This is a known issue with the reSID engine which I shamelessly copied from the VICE emulator. 

There is already a longer discussion in thread #353. I'm pretty sure there is a bug in the reSID filter implementation. Unfortunately, I don't understand reSID well enough to debug it myself. I hope that the VICE team is going to fix it in a future release. In the meantime, I guess we have to live with it (if we don't want to disable filter emulation at all).

**Comment by dirkwhoffmann** [comment]
I'll close this until VICE releases a new reSID version.
