### ISSUE TITLE
Suggestion: Save image (screen RAM) in a native format

### ISSUE THREAD

**Issue by sdsnatcher** [dirkwhoffmann/virtualc64#515]
It would be nice to have the ability to save the screen RAM contents in a native C64 image format, like [any of those supported by RECOIL](http://recoil.sourceforge.net/formats.html#Commodore-64).

**Comment by dirkwhoffmann** [comment]
Is there a common graphics format for C64 images? RECOIL lists a lot of formats I never heard of before.

**Comment by sdsnatcher** [comment]
AFAIK, no. Each C64 image format seem to support only one specific mode.
But I'm no C64 specialist.

Probably the best approach would be to support the most popular format each mode, then have some heuristic to choose the correct file format to save the image based on the current VIC-II register settings.

**Comment by sdsnatcher** [comment]
Also, it would make sense to implement the easier by-the-book formats (IOW, without any software tricks) first: multicolor and HiRes.

**Comment by sdsnatcher** [comment]
I found [this page](https://codebase64.org/doku.php?id=base:c64_grafix_files_specs_list_v0.03), that describes the .OCP and .ART file format structure.

**Comment by dirkwhoffmann** [comment]
>I found this page ...

If I have understood correctly, the page lists different formats of C64 tools. But what is the purpose of exporting a screenshot to these formats? Which Mac application do you want to use to edit the exported files? At the moment, I can't imagine a decent use case for that.

**Comment by sdsnatcher** [comment]
The use case would be digital preservation. Let me explain the idea with an analogy with the soundtrack preservation that's long well stablished.    :)

The SID format is widely used to store C64 soundtracks in its native format. Why is it used instead of modern PC formats like WAV, MP3, M4A, Flac, etc? 

1) Those formats tend to be manipulated over time (recompressed, resampled etc) and this way, the quality goes down the drain
2) Modern PC formats have trends. What was an acceptable mp3 recording quality 15 years ago doesn't qualify anymore. Re-recording them again and again is a waste of time. SID files are timeless.
3) The SID files can be played both on modern PCs/Smartphones or on the real C64. WAV/MP3/M4A make the content out of reach for the real C64 machine.

Now, exactly the same problems exist in the image (PixelArt) scenario. But sadly, there's a divide: C64 image files are mostly being stored in two formats: PRG (sometimes inside a D64 or T64 file) or modern image files (PNG, GIF and JPG). 

Then the following problems occur:
1) Same as the soundtracks problem-1. This problem is even worse here, because people tend to do (a) stretching to fake the pixel aspect ratio, (b) tonal adjust to their liking, (c) recompress again and again with lossy formats like JPG. To the point that is not possible to try to reconstruct the native file from the PNG/JPG image anymore. I.e.: Just compare the [screenshot here](http://tomseditor.com/gallery/i/3223/weeee-by-mermaid) with its native file.
2) Modern PC image quality have trends. What was an acceptable rendering quality 15 years ago doesn't qualify anymore. Modern PCs have much higher resolution, so people tend to stretch the image to become bigger, sometimes with poor interpolation
3) Native C64 image formats would be device independent. They can be viewed either on modern PCs/smartphones and on the real C64 machines. But PNG/JPG/GIF is out of reach of the real C64 hardware
4) Images stored in PRG/D64/T64 format are clumsy to handle. You can't easily browse a folder full of images either on a modern PC/Smartphone, neither on C64.

That said, there are just too many redundant file formats in [that page](https://codebase64.org/doku.php?id=base:c64_grafix_files_specs_list_v0.03), so it would be reasonable to implement only the best image format for a single mode.

My suggestion would be to implement only:
- HiRes mode: Art Studio 1.1 (.ART extension)
- Multicolor mode: Art Studio 2.0 (.OCP extension)
- PETSCII: Maybe the .pe format saved by [this editor](http://petscii.krissz.hu)?

As for the advanced trickery modes (those with flicker/interlace/raster tricks), maybe it would be better to not worry about them right now. I'm not even sure if there's a way to save them via an emulator.

As for the Mac applications, there are many multi-platform tools available nowadays:
- [RECOIL](http://recoil.sourceforge.net) is a multiplatform library/image viewer that supports hundreds of legacy image formats
- [XnView MP](https://www.xnview.com/en/) is an image viewer that supports RECOIL as a plugin
- [XnConvert](https://www.xnview.com/en/xnconvert/) is an image converter that supports RECOIL as a plugin
- [MultiPaint](http://multipaint.kameli.net) is an image editor with support for many legacy platform formats, including C64's .OCP and .ART
- [PixelPolizei](http://www.kameli.net/marq/?page_id=4557) lets you automatically check whether an image conforms to the color limits of a particular oldschool platform and save the result in certain native formats. The underlying idea is that you can use whatever paint program you happen to prefer for creating the images and observe – almost real-time – if you’ve made a mistake somewhere. For the C64, it has support for .OCP and .ART.

The [Retro Gallery](http://tomseditor.com/gallery) is a project that aims to preserve images from legacy platforms in their native formats. But guess what platform the biggest amount of [missing native files](http://tomseditor.com/gallery/wanted?lang=en) there? 

I've been doing my best to help to supply all missing native files I can, but it would be *way faster* if VirtualC64 had this feature to save the screen RAM as directly to a native file.     :)

**Comment by dirkwhoffmann** [comment]
Hi sdsnatcher,

thank you for the detailed explanation, this clarifies a lot!

 I'll have a look at the .ART, .OCP, and .pe format. However, it might take a while, because I'm pretty busy with Amiga stuff at the moment.

**Comment by dirkwhoffmann** [comment]
If I am right, .ART and .OCP are native file formats used by ArtStudio. Even if it was possible to export to these formats, I don't see how a digital preservation project would benefit from it. The only thing we can export is the emulator texture (there is no such thing as screen RAM inside the C64). Hence, the exported target file would always contain all mismatches produced by the emulator (e.g., color mismatches when compared to a real C64 monitor). And if the emulator texture is exported as TIFF, there can never be any quality loss (basically, TIFF is a plain bitmap representation of the image it contains).

**Comment by sdsnatcher** [comment]
According to this site, .ART and .OCP are just dumps from the C64 memory areas that compose the screen:

**Hires mode: .ART**
- $2000 - $3f3f: Bitmap
- $3f40 - $4327: Screen RAM
- $4328: Border

**Standard Multicolor**
- $6000 - $7F3F: Bitmap
- $7F40 - $8327: Screen RAM
- $8328 - $870F: Color RAM
- $8710: Background


Yes, I'm aware that these addresses can be changed on the VIC-II. When saving such files, it's just a matter for the emulator to look where the VIC-II registers to get the video mode, and where they're pointing to each of these areas in the C64 RAM, then copy their contents to the respective areas of the file accordingly.

It's not that different from an MSX1/2/2+ computer. Here's how the openMSX emulator does this:
https://github.com/openMSX/openMSX/blob/master/share/scripts/_save_msx_screen.tcl

**Comment by sdsnatcher** [comment]
Here's a screenshot highlighting the VIC-II registers that can be used to get the video-mode, and where each buffer is present on the C64 RAM:

![VIC2registers](https://user-images.githubusercontent.com/13080763/93137693-42979d00-f6b4-11ea-9c31-8ec73ba20f8e.png)

**Comment by dirkwhoffmann** [comment]
I'll close this issue for now. It's not that I don't want to see other formats supported, but it's simply a matter of priority. My free time is limited, like everyone else's, and there are tons of open issues with higher priority. This issue would probably be open forever.
