### ISSUE TITLE
Character Sets

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#516]
Please add the ability to change/load in a character set rom.

**Comment by dirkwhoffmann** [comment]
Not sure if I understand your request correctly. You can change the CharRom in the preferences panel.

**Comment by bluecursor** [comment]
The recent roms released on csdb.dk don’t get accepted in virtualc64
On Jun 20, 2019, 3:12 PM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

Not sure if I understand your request correctly. You can change the CharRom in the preferences panel.

**Comment by dirkwhoffmann** [comment]
Ah, OK, now I get it. I'll add those to the list of known Roms in the next release.

https://csdb.dk/release/?id=178873

**Comment by Alessandro1970** [comment]
Great! 
🤗

**Comment by Alessandro1970** [comment]
...please...
Alternate CHARGEN: Amstrad CPC : https://csdb.dk/release/?id=178697
and
Alternate CHARGEN: ZX Spectrum : https://csdb.dk/release/?id=178693

Thanks

**Comment by bluecursor** [comment]
As well as the amiga ones too. Please.
On Jun 21, 2019, 4:53 AM -0400, Alessandro <notifications@github.com>, wrote:

...please...
Alternate CHARGEN: Amstrad CPC : https://csdb.dk/release/?id=178697
and
Alternate CHARGEN: ZX Spectrum : https://csdb.dk/release/?id=178693

Thanks

**Comment by rossimariolee** [comment]
9 charsets:
https://csdb.dk/search/?seinsel=all&search=Alternate+CHARGEN&Go.x=0&Go.y=0

**Comment by mortinus** [comment]
Wonderful

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b1.zip
