### ISSUE TITLE
Cockroach_Turbo-ROM is not recognized by VirtualC64 but works correctly

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#517]
Hi,
can you add the rom recognition in question?
It works properly in VirtualC64!
Manual:
[Cockroach_Turbo-ROM_Manual.pdf.zip](https://github.com/dirkwhoffmann/virtualc64/files/3316635/Cockroach_Turbo-ROM_Manual.pdf.zip)
Kernal Rom:
[kernal.rom.zip](https://github.com/dirkwhoffmann/virtualc64/files/3316636/kernal.rom.zip)

<img width="790" alt="Schermata 2019-06-22 alle 09 55 27" src="https://user-images.githubusercontent.com/34916641/59961222-3cc50300-94d5-11e9-9e7d-01da20c81173.png">

Thanks
Bye

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b1.zip

**Comment by PakkunKinoppi** [comment]
Thanks, it works great !
