### ISSUE TITLE
Datel Turbo ROM is not recognized by VirtualC64 but works correctly

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#518]
Hi,
can you add the rom recognition in question?
It works properly in VirtualC64!

Manual:
[Turbo_ROM_II_Manual.txt.zip](https://github.com/dirkwhoffmann/virtualc64/files/3316638/Turbo_ROM_II_Manual.txt.zip)

Kernal:
[kernal.rom.zip](https://github.com/dirkwhoffmann/virtualc64/files/3316639/kernal.rom.zip)

<img width="784" alt="Schermata 2019-06-22 alle 10 01 05" src="https://user-images.githubusercontent.com/34916641/59961278-dab8cd80-94d5-11e9-89bc-ae33dcf4f906.png">

Thanks
Bye

**Comment by mortinus** [comment]
Great, it is working for me too. :bye

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b1.zip
