### ISSUE TITLE
Exos ROM is not recognized by VirtualC64 but works correctly

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#519]
Hi,
can you add the rom recognition in question?
It works properly in VirtualC64!

Manual:
[64er_86_12_Exos_v3.pdf.zip](https://github.com/dirkwhoffmann/virtualc64/files/3331918/64er_86_12_Exos_v3.pdf.zip)

Rom:
[exos-v3_fertig.rom.zip](https://github.com/dirkwhoffmann/virtualc64/files/3331921/exos-v3_fertig.rom.zip)

<img width="782" alt="Schermata 2019-06-26 alle 23 11 07" src="https://user-images.githubusercontent.com/34916641/60215384-c8d58280-9867-11e9-84f0-137d3127b5ab.png">

Thanks
Bye

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b1.zip
