### ISSUE TITLE
Turbo Tape ROM is not recognized by VirtualC64 but works correctly

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#520]
Hi,
can you add the rom recognition in question?
It works properly in VirtualC64!

Rom:
[TT-Rom.bin.zip](https://github.com/dirkwhoffmann/virtualc64/files/3341716/TT-Rom.bin.zip)

<img width="787" alt="Schermata 2019-06-29 alle 11 28 10" src="https://user-images.githubusercontent.com/34916641/60382366-714f3680-9a62-11e9-9a2a-93608b354e17.png">

Thanks
Bye

**Comment by dirkwhoffmann** [comment]
Fixed in 

http://www.dirkwhoffmann.de/virtualc64/VirtualC64_3.3.3b1.zip
