### ISSUE TITLE
Menù Cartridge ISEPIC does't Work !

### ISSUE THREAD

**Issue by Haroldo64** [dirkwhoffmann/virtualc64#523]
Hello everyone, I have installed the last beta version of the Virtual C64 but I can't add any ROM image to make the ISEPIC Cartridge command work.
Can any of you tell me how to upload or where to find the ROM for ISEPIC to work ?
Thank you all.
Harold

**Comment by mortinus** [comment]
![Screen Shot 2013-04-05 at 22 20 52](https://user-images.githubusercontent.com/41686391/61632383-01ad1f80-ac8d-11e9-886e-f7b8e2a8e1df.png)

**Comment by PakkunKinoppi** [comment]
Sorry, I don't understand !

**Comment by mortinus** [comment]
Read this:
https://github.com/dirkwhoffmann/virtualc64/issues/413

**Comment by rossimariolee** [comment]
Perhaps in version 3.3.3 it would be better to remove, temporarily, from the menu the word ISEPIC !!!
Otherwise, confusion arises, as noted in this issue.
Bye

**Comment by dirkwhoffmann** [comment]
>  it would be better to remove, temporarily, from the menu the word ISEPIC !!!

Yes, I agree. It should be removed until the cartridge is fully supported.

**Comment by dirkwhoffmann** [comment]
The cartridge should work now. Please see #413 for details.

**Comment by PakkunKinoppi** [comment]
Thanks, ISEPIC cartridge works well !
