### ISSUE TITLE
Thing on a Spring - Transporter Point / Escalators not working

### ISSUE THREAD

**Issue by cfwdman** [dirkwhoffmann/virtualc64#524]
Assumption for filing this issue that it might be related to an issue with collision detection with the background or/and sprites. 

When "Thing on a spring" is played to the second room on the right the escalator which usually leads to the thing going up is not working. Thing on a spring stays on the floor. 
Also touching the "transporter" button which leads to the thing being moved to the end of the room has no effect.

Correct behavior can not be seen in any available emu but on a gameplay video available e.g. at https://youtu.be/QhkFF0c-gUo?t=43.

**Comment by Alessandro1970** [comment]
Is this ?

![Untitled 2](https://user-images.githubusercontent.com/34916641/61690200-13dc9b80-ad29-11e9-8fda-52b5ec100a27.png)

**Comment by Alessandro1970** [comment]
Using the ladder on emulators:
![Untitled 2](https://user-images.githubusercontent.com/34916641/61694147-31adfe80-ad31-11e9-82b2-8c165bc4ebc3.png)

**Comment by Alessandro1970** [comment]
...go left from the main screen and pick up the gift (see arrow), you cannot use the ladders or escalators if you do not pick up gifts !!! This is not an emulation problem or other, only a playing rule !

![Untitled 4](https://user-images.githubusercontent.com/34916641/61694355-8f424b00-ad31-11e9-867e-4a333f971c0a.png)

**Comment by cfwdman** [comment]
Thank you so much - will close this issue as quick as possible... 
saved my day to show this to my kids...

**Comment by dirkwhoffmann** [comment]
> Thank you so much - will close this issue as quick as possible...

Don't worry. Please open up issues if you experience problems. We are happy about all bug reports. If it turns out that a bug is a not a bug, it's not a problem.

**Comment by PakkunKinoppi** [comment]
Too difficult game, but it works well on VirtualC64, thank you
