### ISSUE TITLE
GitQ forum needed? 

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#525]
I am thinking about closing the VirtualC64 GitQ forum, because

- it is not really used by many people (including me).
- the GitHub issue section is more convenient. E.g., I can simply drag and drop images here,  whereas in GitQ, the size is always wrong and has to be edited manually.
- it seems like GitQ has not valid certificate any more. Since a couple of days, my browser warns me to go there. 

What do you think? 

It's totally fine for me if discussion are part of the GitHub issue section, although the section was meant to track bugs only.

**Comment by Alessandro1970** [comment]
Ok, close them. People read only here...

**Comment by Haroldo64** [comment]
Better to use GitHub
Thank you

**Comment by rossimariolee** [comment]
Close them !

**Comment by PakkunKinoppi** [comment]
GitQ forum not needed, better to write here

**Comment by dirkwhoffmann** [comment]
VirtualC64 is no longer on GitQ.
