### ISSUE TITLE
Screenshots without borders

### ISSUE THREAD

**Issue by sdsnatcher** [dirkwhoffmann/virtualc64#528]
When the "Emulator Texture" is selected for screenshots, it would be nice to have a checkbox to allow to select if the screenshot will be taken with or without the border.

**Comment by dirkwhoffmann** [comment]
This one is tricky, because many demos and games open the border and create a bigger screen by using sprites (e.g., Wizball and many others). Furthermore, the border can be smaller or bigger and it's not always possible to detect this correctly (it's impossible if a game or demo changes the border size within a frame). Therefore, I am not sure if such a feature can be implemented reliably.

**Comment by sdsnatcher** [comment]
It could be a checkbox then. Buy "border", I mean the area outside of the tiles that compose the screen without any raster tricks. VirtualC64 must know where are the borders of this area, as it switches to the border color when drawing a frame.

**Comment by dirkwhoffmann** [comment]
I went for a more flexible approach by expanding the options in the "Screenshot Source" popup box (Preferences panel).

<img width="303" alt="Bildschirmfoto 2020-09-15 um 12 52 02" src="https://user-images.githubusercontent.com/12561945/93202161-8f31b580-f752-11ea-981a-22a1ce5d4787.png">

To take a borderless screenshot, select "Visible Texture" or "Visible Texture (Upscaled)". This will save the currently visible texture part and not the entire texture. Now, to get rid of the border, zoom in as much as you like in the video settings:

<img width="970" alt="Bildschirmfoto 2020-09-15 um 12 50 19" src="https://user-images.githubusercontent.com/12561945/93202417-f51e3d00-f752-11ea-86ef-ea46acc3cb79.png">

Now, take a screenshot and watch it in the screenshot browser. It's now borderless:

<img width="590" alt="Bildschirmfoto 2020-09-15 um 12 51 34" src="https://user-images.githubusercontent.com/12561945/93202492-0ff0b180-f753-11ea-9879-851ed834c886.png">

(The one to the left has been taken with option "Entire Texture")

**Comment by mithrendal** [comment]
that is a really clever approach  (... I like to take this approach one day to vc64web snapshots too.  Then we would also like to persist the adjusted visible area per app title ... no?)

**Comment by dirkwhoffmann** [comment]
>  I like to take this approach one day to vc64web snapshots too.

🤤

> Then we would also like to persist the adjusted visible area per app title ... no?)

Not sure yet. Users may be surprised to see a different texture area depending on the selected title. I would expect users to want the same texture cutout for all titles, but I could well be wrong.
