### ISSUE TITLE
Skew1 test: strange result

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#529]
Hi,
I have saved the skew1 test into a d64 image and I have run in on the two emulators:

[Test.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/3488618/Test.d64.zip)

Vice Sc:
<img width="719" alt="Schermata 2019-08-10 alle 09 05 23" src="https://user-images.githubusercontent.com/34916641/62818915-5d611f00-bb4e-11e9-8066-d89187166cdc.png">

VirtualC64:
<img width="784" alt="Schermata 2019-08-10 alle 09 07 23" src="https://user-images.githubusercontent.com/34916641/62818916-66ea8700-bb4e-11e9-8f5b-9dd32408ecf8.png">

**Comment by dirkwhoffmann** [comment]
I don't really know what this test is doing, but VirtualC64 seems to pass 🥳. 

I remember that I did run the test myself a couple of month ago and it was failing first, but I don't remember the details. When I was working on it, I tried to mimic what Hoxs64 is doing.

I assume that the test is supposed to pass on a real C64, so we are good here, I think. 

It would be interesting to see how it looks in Hoxs64. If Hoxs64 shows the brown screen as VICE does, VirtualC64 is most likely wrong.

**Comment by Alessandro1970** [comment]
This test works only with VirtualC64 !
This is the test with HOSX64 last release:
<img width="763" alt="Schermata 2019-08-11 alle 09 28 32" src="https://user-images.githubusercontent.com/34916641/62831126-9070e480-bc1a-11e9-8f5a-a0595132ae34.png">

**Comment by Alessandro1970** [comment]
You can close...
