### ISSUE TITLE
Cartridge test "Supergames" fails

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#530]
Hi,

the cartridge test "Supergames" fails:

[supergames.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/3536989/supergames.crt.zip)

VirtualC64:
<img width="641" alt="Schermata 2019-08-24 alle 10 09 22" src="https://user-images.githubusercontent.com/34916641/63634503-adb0a480-c657-11e9-9dfb-1099f1880ce7.png">

ViceSC:
<img width="719" alt="Schermata 2019-08-24 alle 10 09 34" src="https://user-images.githubusercontent.com/34916641/63634508-b4d7b280-c657-11e9-9974-d65729e1ca29.png">

**Comment by dirkwhoffmann** [comment]
Will be fixed in v4.0: 😎

<img width="986" alt="Bildschirmfoto 2020-09-01 um 16 37 40" src="https://user-images.githubusercontent.com/12561945/91865340-94cace00-ec71-11ea-8eb2-44de08994fbf.png">
