### ISSUE TITLE
Drive/cassette error

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#531]
Hi,
[Doomdark's Revenge (1986)(Beyond Software)[cr Jedi].t64.zip](https://github.com/dirkwhoffmann/virtualc64/files/3536997/Doomdark.s.Revenge.1986.Beyond.Software.cr.Jedi.t64.zip)

it maybe a cassette loader error:
if I insert in ViceSC this tape and I Type LOAD "",8,1 I obtain an error because there is a tape inserted and not a Floppy disk:
<img width="717" alt="Schermata 2019-08-24 alle 10 26 27" src="https://user-images.githubusercontent.com/34916641/63634642-b1452b00-c659-11e9-8053-0e2fc0002056.png">

...but on VirtualC64 that .t64 is seen a floppy disk and the LOAD "",8,1 works:
<img width="634" alt="Schermata 2019-08-24 alle 10 22 08" src="https://user-images.githubusercontent.com/34916641/63634655-cde16300-c659-11e9-94fd-21b2dcb7b610.png">

**Comment by dirkwhoffmann** [comment]
It's clearly a T64 file. It has ".t64" as suffix and the T64 signature header inside: 

    00000000  43 36 34 20 74 61 70 65  20 69 6d 61 67 65 20 66  |C64 tape image f|
    00000010  69 6c 65 00 00 00 00 00  00 00 00 00 00 00 00 00  |ile.............|
    00000020  00 01 1e 00 01 00 00 00  49 4d 50 4f 52 54 45 44  |........IMPORTED|
    00000030  20 46 49 4c 45 53 20 20  20 20 20 20 20 20 20 20  | FILES          |
    00000040  01 82 01 08 33 bf 00 00  00 04 00 00 00 00 00 00  |....3...........|
    00000050  44 4f 4f 4d 4e 41 52 4b  27 53 20 52 45 56 45 4e  |DOOMNARK'S REVEN|
    00000060  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................

It'll work in VICE if you type `LOAD "*",8,1` instead of `LOAD "",8,1`

**Comment by Alessandro1970** [comment]
Ok, I'll close
