### ISSUE TITLE
Mikro Assembler .crt

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#535]
Mikro Assembler .crt is not supported.
[Mikro_Assembler_Manual.pdf](https://github.com/dirkwhoffmann/virtualc64/files/3692688/Mikro_Assembler_Manual.pdf)

**Comment by dirkwhoffmann** [comment]
Should be easy to support. 

Functional description in VICE: 

>    Mikro Assembler" Cartridge
>     This cart has 8Kb ROM mapped at $8000-$9FFF.
>     The $9E00-$9EFF range is mirrored at $DE00-$DEFF.
>     The $9F00-$9FFF range is mirrored at $DF00-$DFFF.

It's just a resource problem. Very busy at the moment...

**Comment by dirkwhoffmann** [comment]
Does anybody have the .crt? 🙄

**Comment by bluecursor** [comment]
I attached it along with the manual when I posted it. If not a it's a easy google search.
On Oct 11, 2019, 9:24 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

Does anybody have the .crt? 🙄

**Comment by Alessandro1970** [comment]
My friends I have the crt
This night I’ll post it here

**Comment by Alessandro1970** [comment]
Hi,
Try this:
[Mikro Assembler.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/3719260/Mikro.Assembler.crt.zip)

**Comment by dirkwhoffmann** [comment]
OK, let’s check this cartridge out. As always, we need to attach it to the emulator first…

<img width="800" alt="Bildschirmfoto 2019-10-12 um 08 49 18" src="https://user-images.githubusercontent.com/12561945/66696551-34cfdf80-eccd-11e9-96f7-109332e2ed02.png">

Now, let’s *RTFM*…

<img width="584" alt="Bildschirmfoto 2019-10-12 um 08 34 53" src="https://user-images.githubusercontent.com/12561945/66696552-3ac5c080-eccd-11e9-902e-8dd234b6c6b2.png">

As a side note, I am wondering how many hours of our lives we wasted by typing in programs manually back in the day 😂.  Must be a tremendous amout 😬. Anyway…

<img width="916" alt="Bildschirmfoto 2019-10-12 um 08 50 20" src="https://user-images.githubusercontent.com/12561945/66696562-5f219d00-eccd-11e9-92a3-ae47cce19c50.png">

😳 Oups, we enter the debugger??? Something is broken… 😠

THINK THINK THINK

😁 Nailed it.

Let’s have a closer look at the cartridge dialog. 

<img width="477" alt="Bildschirmfoto 2019-10-12 um 08 51 39" src="https://user-images.githubusercontent.com/12561945/66696581-92fcc280-eccd-11e9-915f-2e7fa67032c6.png">

Alessandro’s crt has type ID 0000 which means „normal cartridge“. Hence, the emulator treats it as a standard cartridge and doesn’t emulate the custom hardware on board (which is pretty simple in that case BTW). Seems like the creator of the cartridge didn’t use the correct conversion parameters (I.e., he didn’t mark the crt as „special“).

We can fix that by editing the cartridge type manually. iHex from the Appstore can help us out here. The Mikro Assembler cartridge has ID $1C and we need to put that value right here:

<img width="766" alt="Bildschirmfoto 2019-10-12 um 08 52 46" src="https://user-images.githubusercontent.com/12561945/66696598-baec2600-eccd-11e9-9d47-e3d22de9268a.png">

Time to try again...

😎 Awesome: "It just works". 

<img width="916" alt="Bildschirmfoto 2019-10-12 um 08 31 42" src="https://user-images.githubusercontent.com/12561945/66696603-c93a4200-eccd-11e9-8b95-72e92aed8ed8.png">

<img width="916" alt="Bildschirmfoto 2019-10-12 um 08 33 06" src="https://user-images.githubusercontent.com/12561945/66696604-cb9c9c00-eccd-11e9-937f-3255a6132efc.png">

<img width="916" alt="Bildschirmfoto 2019-10-12 um 08 33 58" src="https://user-images.githubusercontent.com/12561945/66696664-36e66e00-ecce-11e9-9101-9ab761064c67.png">

This cartridge is really cool. I wish I had one of them when I started learning assembler programming as a child. I remember that I wrote all my assembler programs on a sheet of paper and translated them manually to numbers afterwards. Finally, I inserted them as DATA statements into my BASIC programs.

**Comment by bluecursor** [comment]
Awesome! Can we get a copy of the working .crt?
On Oct 12, 2019, 2:57 AM -0400, Dirk Hoffmann <notifications@github.com>, wrote:

OK, let’s check this cartridge out. As always, we need to attach it to the emulator first…

[Bildschirmfoto 2019-10-12 um 08 49 18]<https://user-images.githubusercontent.com/12561945/66696551-34cfdf80-eccd-11e9-96f7-109332e2ed02.png>

Now, let’s RTFM…

[Bildschirmfoto 2019-10-12 um 08 34 53]<https://user-images.githubusercontent.com/12561945/66696552-3ac5c080-eccd-11e9-902e-8dd234b6c6b2.png>

As a side note, I am wondering how many hours of our lives we wasted by typing in programs manually back in the day 😂. Must be a tremendous amout 😬. Anyway…

[Bildschirmfoto 2019-10-12 um 08 50 20]<https://user-images.githubusercontent.com/12561945/66696562-5f219d00-eccd-11e9-92a3-ae47cce19c50.png>

😳 Oups, we enter the debugger??? Something is broken… 😠

THINK THINK THINK

😁 Nailed it.

Let’s have a closer look at the cartridge dialog.

[Bildschirmfoto 2019-10-12 um 08 51 39]<https://user-images.githubusercontent.com/12561945/66696581-92fcc280-eccd-11e9-915f-2e7fa67032c6.png>

Alessandro’s crt has type ID 0000 which means „normal cartridge“. Hence, the emulator treats it as a standard cartridge and doesn’t emulate the custom hardware on board (which is pretty simple in that case BTW). Seems like the creator of the cartridge didn’t use the correct conversion parameters (I.e., he didn’t mark the crt as „special“).

We can fix that by editing the cartridge type manually. iHex from the Appstore can help us out here. The Mikro Assembler cartridge has ID $1C and we need to put that value right here:

[Bildschirmfoto 2019-10-12 um 08 52 46]<https://user-images.githubusercontent.com/12561945/66696598-baec2600-eccd-11e9-9d47-e3d22de9268a.png>

Time to try again...

😎 Awesome: "It just works".

[Bildschirmfoto 2019-10-12 um 08 31 42]<https://user-images.githubusercontent.com/12561945/66696603-c93a4200-eccd-11e9-8b95-72e92aed8ed8.png>

[Bildschirmfoto 2019-10-12 um 08 33 06]<https://user-images.githubusercontent.com/12561945/66696604-cb9c9c00-eccd-11e9-937f-3255a6132efc.png>

[Bildschirmfoto 2019-10-12 um 08 33 58]<https://user-images.githubusercontent.com/12561945/66696664-36e66e00-ecce-11e9-9101-9ab761064c67.png>

This cartridge is really cool. I wish I had one of them when I started learning assembler programming as a child. I remember that I wrote all my assembler programs on a sheet of paper and translated them manually to numbers afterwards. Finally, I inserted them as DATA statements into my BASIC programs.

**Comment by bluecursor** [comment]
using 3.3.3. b1 and this does not work for me...

**Comment by dirkwhoffmann** [comment]
> using 3.3.3. b1 and this does not work for me...

To make it work, you need the latest VirtualC64 code, because 3.3.3b1 doesn't emulate the custom hardware of this cartridge. 

The good news is that you don't need the patched Rom anymore. In v3.4, when a CRT file is dragged into VirtualC64, it computes a fingerprint and compares it against a list of files that are known to be broken (the list contains a single entry at the moment: the fingerprint of the broken Mikro Assembler crt). If a match is found, it rectifies the header on the fly (only in memory, the file itself remains untouched).

Until 3.4 is released, simply download the project and compile it in Xcode 11. The project is supposed to compile without further configuration.

**Comment by bluecursor** [comment]
When is 3.4 expected to be released? I don’t have the knowledge or ability to compile my self.

**Comment by dirkwhoffmann** [comment]
v3.4b1 can be downloaded in the Releases section

**Comment by bluecursor** [comment]
Awsome! Thanks as always!

**Comment by Alessandro1970** [comment]
Ok !

**Comment by DaitarnIII** [comment]
Thanks great cartridge !

**Comment by PakkunKinoppi** [comment]
It works for me too

**Comment by UgoCaneFifone** [comment]
It works ...still open ?

**Comment by bluecursor** [comment]
Working, thanks!

Frank Michielli
Sent with iOS Spark!📱
On Dec 6, 2019, 9:21 AM -0500, Ugo <notifications@github.com>, wrote:

It works ...still open ?
