### ISSUE TITLE
Initial install: Rom warning window is not a drop target

### ISSUE THREAD

**Issue by wilmorrtr** [dirkwhoffmann/virtualc64#539]
I am unable to drag the base roms into the application in any way that I've been able to find.  I'm on OS X 10.14.5.

Where are the roms moved to after the import process? I can just move them into place as a fix for now if possible.

Thanks for what looks like a great emu!

**Comment by dirkwhoffmann** [comment]
You need to drop the Rom images right over the chip icons. Only those are drop targets.

<img width="916" alt="Bildschirmfoto 2019-10-25 um 18 49 04" src="https://user-images.githubusercontent.com/12561945/67589283-5a8ec700-f758-11e9-96fd-4f282a5e8202.png">

**Comment by wilmorrtr** [comment]
In hindsight, it was obvious, and I've just tested it successfully. Thank you very much!
