### ISSUE TITLE
1581 Add Support

### ISSUE THREAD

**Issue by PakkunKinoppi** [dirkwhoffmann/virtualc64#541]
Hi, could you add the support for Commodore 1581 Disk Drive (reading/writing/formatting), please ?

I cannot load this game:
[The_Simpsons_Arcade_Game.zip](https://github.com/dirkwhoffmann/virtualc64/files/3818170/The_Simpsons_Arcade_Game.zip)

Bye

**Comment by dirkwhoffmann** [comment]
Sorry, won't be able to do that with my limited development resources. It would be a huge project.
