### ISSUE TITLE
Arrow keys not moving cursor

### ISSUE THREAD

**Issue by jtsom** [dirkwhoffmann/virtualc64#543]
Trying to use the arrow keys to move the cursor doesn't seem to be working. Results of hitting the keys:
Up arrow: Nothing
Left: Move cursor right
Right: "2" character (sometimes "0", sometimes "4")
Down: Left arrow character.

Strangely, on another system, the arrow keys work just fine. My preferences are their default, and I tried toggling the "Disconnect emulation keys from the C64 keyboard" with no difference.

Tried both release V3.3 and v3.4 beta.

**Comment by dirkwhoffmann** [comment]
A look into my crystal bowl tells me that you emulated a joystick in control port 1 with keyset 1. Control port 1 interacts with the keyboard. What you see is the result of a joystick movement in control port 1. You would get the same output with a "real" joystick in that port.

**Comment by jtsom** [comment]
Well, look at that... I changed the option at the top of the window to None and it's all good again. I guess I don't recall setting it.

Thanks!
