### ISSUE TITLE
Vice 3.4 released

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#545]
Hi, 
a new release of Vice is on-line:

** SID fixes
------------

- use model dependent floating output ttl values like in residfp

Merry Christmas
Bye

**Comment by dirkwhoffmann** [comment]
They released it just today. A Christmas special so to say... Cheers!

![badsanta](https://user-images.githubusercontent.com/12561945/71404309-7ddbd280-2632-11ea-9960-a87d7b64af8a.jpg)

Maybe they fixed the reSID filter initialisation problem. Would be awesome.

**Comment by bluecursor** [comment]
Does this mean there is a link to a OS X version of VICE 3.4? and where?

**Comment by rossimariolee** [comment]
Vice 3.4 for MacOS [new SDL Version]
http://vice-emu.sourceforge.net/macosx.html

**Comment by rossimariolee** [comment]
...SHIFT + F10 for the menù. 
The GTK version has problems, do not use for this.

**Comment by bluecursor** [comment]
VICE 3.4 r37371 is now out for OSX

**Comment by dirkwhoffmann** [comment]
> VICE 3.4 r37371 is now out for OSX

Sadly, I haven't had time to take over the new reSID code in VirtualC64 yet. I'm bad in multi-tasking and my brain's filled with Amiga stuff at the moment. Paula's interrupt timing is giving me a hard time and I need this fixed first...

**Comment by dirkwhoffmann** [comment]
reSID code from VICE 3.4 has been ported over.
