### ISSUE TITLE
Zip-Code Disk unPacker Not working

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#549]
[Archive.zip](https://github.com/dirkwhoffmann/virtualc64/files/4162889/Archive.zip)
Unable to unpack a disk image for files downloaded from bbs. instructions are attached.
Works up to when it has to read the 2/4 zip files.
[Archive 2.zip](https://github.com/dirkwhoffmann/virtualc64/files/4162894/Archive.2.zip)

**Comment by dirkwhoffmann** [comment]
I've come this far:

<img width="916" alt="Bildschirmfoto 2020-02-06 um 10 15 06" src="https://user-images.githubusercontent.com/12561945/73922679-da850b00-48c9-11ea-8cf9-de5a720d5cdc.png">

There is still animation in the upper part, but it doesn't proceed to other sectors.

Did you check if it works in VICE?

**Comment by bluecursor** [comment]
cant get it to work in vice either....
