### ISSUE TITLE
Krestage 3 demo doesn't run

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#552]
Krestage3 demo doesn't run, we need to use, instead, the emufix version.
Krestage 3 (full version) starts and works on VICE.

https://csdb.dk/release/download.php?id=58941

**Comment by Alvarez81** [comment]
Yes, KRESTAGE3 (integral version) does not run

**Comment by Alessandro1970** [comment]
I do not remember !
Only Emufixed version works on our great VirtualC64 ?

This night I will download the full CSDB version. I remember that David Horroks had fixet VIC timing for this demo, there was a precide VIC detection timing and:
 _The VIC emulation as been enhanced to include a 4 pixel delay before responding to
changes to the sprite multicolor register. Stray pixels have been removed from the
"Krestage 3" Demo by Crest 50 pixel sprite upper border._

**Comment by Alessandro1970** [comment]
Krestage 3 emufixed or not work on VirtualC64 3.4b
Try this configuration:
<img width="691" alt="Schermata 2020-02-25 alle 23 32 47" src="https://user-images.githubusercontent.com/34916641/75293765-2e2ea880-5827-11ea-82dc-10dcc2b6c4eb.png">

<img width="702" alt="Schermata 2020-02-25 alle 23 30 56" src="https://user-images.githubusercontent.com/34916641/75293790-3a1a6a80-5827-11ea-90cd-e1b3f4ef51c0.png">

**Comment by Alessandro1970** [comment]
<img width="704" alt="Schermata 2020-02-25 alle 23 34 01" src="https://user-images.githubusercontent.com/34916641/75293834-53231b80-5827-11ea-956c-c0f8f895fd63.png">

**Comment by Alessandro1970** [comment]
This issue can be closed...

**Comment by rossimariolee** [comment]
Ok, you are right

**Comment by dirkwhoffmann** [comment]
> Try this configuration:

which config item made the difference?

**Comment by Alessandro1970** [comment]
Hi, I haven’t had wiritten that to say they is the right configuration, I only have had written so becouse that is my configuration and that demo works well for me.

**Comment by dirkwhoffmann** [comment]
> that is my configuration and that demo works well for me.

@rossimariolee What is difference between your configuration and Alessandros?

**Comment by rossimariolee** [comment]
I don't remeber, it was quite entirely different, but now with Alessandro1970's configuration also the Undead demo is working.
