### ISSUE TITLE
VirtualC64 Demo - Comparison Test

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#553]
_Can we try to complete this prebuilt matrix ?_
I have added the empty VirtualC64 column (not all tested yet):

**The updated emu check list:**

**Y** - test passed, **N** - emu detected/failed

--------------------------CCS------VICESC-----Hoxs64-----VirtualC64 

Cucumber Juice 2--------Y-----------Y-----------Y----------Y.
Deus Ex Machina---------Y-----------Y-----------Y----------Y.
Demus Interruptus-------Y-----------Y-----------Y-----------Y.
(+)h Emu-Fuxx0r v1------N----------N-----------Y-----------Y.
(+)h Emu-Fuxx0r v2------Y-----------N-----------Y----------Y.
Aurora (90%)-------------N-----------?N-----------Y----------Y.
Krestage 3notfixed-------Y-----------Y-----------Y----------Y.
Errata (emulamers)-------nd----------Y-----------Y-----------**Y**.
Undead (emulam)--------nd----------Y-----------Y-----------**Y**.
Conclusion (emulam)-----nd---------Y-----------Y-----------**Y**.
We come in peace--------nd---------Y-----------Y-----------**Y**.
Demo IV-------------------nd---------Y-----------Y----------Y.
TRC+TBI Intro 10----------nd---------Y-----------Y----------N.

Info:
+) **Demo IV** - star expedition  -   https://csdb.dk/release/?id=30802
+)  **TRC+TBI Intro 10**  -  https://csdb.dk/release/index.php?id=54242
+) **Aurora 90%** - https://csdb.dk/release/?id=41457
+) **Emu-Fuxx0r v1** - https://csdb.dk/release/?id=55743
+) **Emu-Fuxx0r v2** - https://csdb.dk/release/?id=55745
+) **Demus Interruptus** - https://csdb.dk/release/?id=2550
+) **Krestage 3** - https://csdb.dk/release/?id=48577
+) **Cucumber Juice 2** - https://csdb.dk/release/?id=469
+) **Deus Ex Machina** - https://csdb.dk/release/?id=11585
+) **We come in peacd** - https://csdb.dk/release/?id=163427
+) **Errata** - https://csdb.dk/release/?id=104805 (not C64C for the written)
+) **Conclusion** - https://csdb.dk/release/?id=112413
+) **Undead** - https://csdb.dk/release/?id=109618 ( needs **glue logic custom** )

...some demos probably work **now** in VICESC 3.4

_Note for Aurora demo (found on the web/David Horrock):
Aurora 90% ($01 fading corrected, passes the emu check, there's no need to press run/stop to proceed at the beginning anymore)_
With VICESC 3.4 for me Aurora does not run... only red/brown vertical coloumns (?)

**Comment by Alessandro1970** [comment]
Aurora (90%) on VICESC  press run/stop ?
![Untitled 2](https://user-images.githubusercontent.com/34916641/75257830-d4f25500-57e5-11ea-95b1-d9e98e61f5f7.png)

**Comment by Alessandro1970** [comment]
oh yes ...Aurora on HOXS 64 better than VICE ...we have to...

![Untitled 2](https://user-images.githubusercontent.com/34916641/75258377-a88b0880-57e6-11ea-8da6-f1bbbd9b4d16.png)

**Comment by Alessandro1970** [comment]
Ahahah! VirtualC64:
<img width="703" alt="Schermata 2020-02-25 alle 23 12 19" src="https://user-images.githubusercontent.com/34916641/75292389-5bc62280-5824-11ea-99a1-258d94b7eb7a.png">

**Comment by dirkwhoffmann** [comment]
> Ahahah! VirtualC64: ...

Level 64. Which demo is that?

**Comment by Alessandro1970** [comment]
This demo does not work on VICE !
It's Aurora

**Comment by Alessandro1970** [comment]
Now I'm trying the others
And I will update the matrix

**Comment by Alessandro1970** [comment]
Cucumber Juice test ...PASSED by VirtualC64 ...like a REAL C64 :-)

<img width="697" alt="Schermata 2020-02-25 alle 23 21 37" src="https://user-images.githubusercontent.com/34916641/75293062-aeeca500-5825-11ea-9311-f1e33b07e239.png">

**Comment by dirkwhoffmann** [comment]
Hoxs64 really has awesome compatibility. And the source code is much easier to read compared to VICE. I remember stealing some CIA code lines from David's emulator some time ago. OMG, now everybody knows 🤭.

**Comment by Alessandro1970** [comment]
The only demo of that serie that does not work is TRC+TBI Intro 10,
other issue opened for...
