### ISSUE TITLE
Visible texture area is too small

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#555]
It seems to me that the bottom line text is cutted:
Demo: 
[FlexibleDemoShow.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/4303043/FlexibleDemoShow.d64.zip)

VirtualC64
<img width="706" alt="Schermata 2020-03-08 alle 10 20 58" src="https://user-images.githubusercontent.com/34916641/76160091-43f57500-6127-11ea-9d77-acd7f6f4b53d.png">

ViceSc
<img width="716" alt="Schermata 2020-03-08 alle 10 20 24" src="https://user-images.githubusercontent.com/34916641/76160095-4d7edd00-6127-11ea-83c4-c7314760ec9b.png">

**Comment by dirkwhoffmann** [comment]
I’ve reworked the whole thing. Similar to vAmiga, v4.0 will draw the texture without cropping or shifting anything.

In debug mode, the new texture can be displayed as a whole (checkerboard pattern = HBLANK / VBLANK area, black = unused texture space). 

PAL:

<img width="942" alt="Bildschirmfoto 2020-09-02 um 15 06 10" src="https://user-images.githubusercontent.com/12561945/91988601-bbe7d500-ed2f-11ea-92ed-81b9188e833e.png">

NTSC:

<img width="986" alt="Bildschirmfoto 2020-09-02 um 15 06 25" src="https://user-images.githubusercontent.com/12561945/91988613-bee2c580-ed2f-11ea-84e9-a52c24170a62.png">

The video settings already allow the user to adjust the visible part of the drawing area. If V ZOOM is set to 0 (minimal value), the demo is fully visible now: 

<img width="942" alt="Bildschirmfoto 2020-09-02 um 15 08 24" src="https://user-images.githubusercontent.com/12561945/91988628-c4d8a680-ed2f-11ea-8711-f8ff7a238d10.png">
