### ISSUE TITLE
ZipCode 2 working.

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#558]
I finally got this to work now. It only works when the destination disk is not a pre-created ..d64 image.
If you do a New Disk and  execute and Export DIsk, it will unpack.

This does not work in VICE!

I dont know if the source disk matters, But i have been using v1541commander-1.1 (Windows) to create the source disk as i cant find a osx file/disk manager that works in OSX Catalina.

I just wanted to let you know, if this breaks in the future...
[Archive.zip](https://github.com/dirkwhoffmann/virtualc64/files/4303986/Archive.zip)

**Comment by dirkwhoffmann** [comment]
> I just wanted to let you know, if this breaks in the future...

There is nothing to do here, right? Can I close?

**Comment by bluecursor** [comment]
Sure

Frank Michielli
Sent with iOS Spark!📱
