### ISSUE TITLE
skramble 2020 preview doesn't scroll smoothly

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#560]
[skramble 2020 preview.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/4321313/skramble.2020.preview.d64.zip)
skramble 2020 preview (PAL Release ) works fine in VICE.
In Virtual64 it fast fowards the games every five seconds....

**Comment by dirkwhoffmann** [comment]
My crystal bowl tells me that option "Enable warp mode during file transfers" is enabled on your machine:

<img width="639" alt="Bildschirmfoto 2020-03-12 um 23 44 45" src="https://user-images.githubusercontent.com/12561945/76573453-f167e000-64bb-11ea-8548-8d8d28e69192.png">

Disable it and the "fast forward" goes away (Skramble accesses the disk every five seconds for whatever reason).

**Comment by bluecursor** [comment]
Case Closed. Thanks
