### ISSUE TITLE
RAM Expansion Unit (REU)

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#562]
Enhancement: Add RAM Expansion Unit (REU) emulation

**Comment by Archetrix** [comment]
![image](https://user-images.githubusercontent.com/6747271/87518682-df23cb80-c680-11ea-927e-0f0a1cca6b20.png)
Isn't this the same ?

**Comment by dirkwhoffmann** [comment]
I think @bluecursor means this REU: 

![REU1764_01](https://user-images.githubusercontent.com/12561945/87523131-cb7b6380-c686-11ea-9220-6bfec1256ce2.jpg)

From a users point of view, there are no big differences between this REU and the GEO/NEO (I think). However, they are very different internally. The REU uses DMA to transfer data into memory. This is pretty difficult to implement and that's the reason I went for the GEO/NEO. Considering the high development time needed for supporting the REU, I don't really think that we should go for it at the moment.
