### ISSUE TITLE
Platoon Easy Flash doesn't start

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#564]
Hi, Platoon EF version doesn't start on VirtualC64:
[268_Platoon_1987_Ocean.crt.zip](https://github.com/dirkwhoffmann/virtualc64/files/4398601/268_Platoon_1987_Ocean.crt.zip)

<img width="714" alt="Schermata 2020-03-29 alle 12 05 07" src="https://user-images.githubusercontent.com/34916641/77846385-fd3eec00-71b5-11ea-939e-c3a82532ed88.png">

On ViceSC it starts:
<img width="721" alt="Schermata 2020-03-29 alle 12 05 48" src="https://user-images.githubusercontent.com/34916641/77846394-10ea5280-71b6-11ea-8c37-f2cefd7944e7.png">

**Comment by sarnau** [comment]
This might be a cartridge, which was created for EasyFlash. It seems a bunch of games were converted into CRT for EasyFlash to allow quick loading, while still supporting save (into EasyFlash). See the article on the [C64 wiki](https://www.c64-wiki.de/wiki/EasyFlash³)

The cartridge hardware type for both cartridges is 0x20. Virtual C64 probably expects 0…27. 32 is CART_TYPE_EASYFLASH and 33 is CART_TYPE_EASYFLASH_XBANK. The cartridge name for both seems is "EasyFlash".

**Comment by dirkwhoffmann** [comment]
Cartridge type is accepted: 

<img width="875" alt="Bildschirmfoto 2020-09-01 um 11 51 27" src="https://user-images.githubusercontent.com/12561945/91835373-95e80500-ec49-11ea-8024-5224dc3be2b3.png">

Intro scene works now 😎. I didn't test the whole game though...

<img width="986" alt="Bildschirmfoto 2020-09-01 um 11 50 24" src="https://user-images.githubusercontent.com/12561945/91835426-a8fad500-ec49-11ea-88e9-21bf9734e87e.png">
