### ISSUE TITLE
Virtual Keyboard on-screen and arrow keys

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#565]
Hi,
If I press C= key (like in photo) and I use the arrow key the cursor goes in the opposite direction of the symbols on the virtual keyboard.

Or the keys on the keyobard don't change image as like when SHIFT is pressed or the C= key gives an error changing the arrows directions like the SHIFT key.

<img width="959" alt="Schermata 2020-04-14 alle 09 51 08" src="https://user-images.githubusercontent.com/34916641/79199910-f3fc8300-7e35-11ea-9fb3-9e075c5bdede.png">

bye

**Comment by dirkwhoffmann** [comment]
This was an easy one. The keycap images are computed in function `plainKeyImage` in `C64Key.swift`. I only had to add `|| commodore' to the two last statements:

```
      // Check for keys with a predrawn image
        switch nr {
        case 17: return NSImage.init(named: pressed ? .key_ctrl_pressed : .key_ctrl)!
        case 31: return NSImage.init(named: .key_restore)!
        case 33: return NSImage.init(named: .key_runstop)!
        ...
        case 14: return NSImage.init(named: shift ? .key_clr : .key_home)!
        case 15: return NSImage.init(named: shift ? .key_inst : .key_del)!
        case 62: return NSImage.init(named: shift  || commodore ? .key_crsr_up : .key_crsr_down)!
        case 63: return NSImage.init(named: shift  || commodore ? .key_crsr_left : .key_crsr_right)!
        default: break
        }
```

> or the C= key gives an error changing the arrows directions like the SHIFT key.

I double-checked with positional key mapping. Pressing Commodore does alter the cursor direction. I wasn't aware of this either. Code fix has been checked into the main branch.

**Comment by Alessandro1970** [comment]
Hi, Thank you !
