### ISSUE TITLE
Compile VirtualC64

### ISSUE THREAD

**Issue by rossimariolee** [dirkwhoffmann/virtualc64#566]
...excuse me...

if I should like to compile by myself the VirtualC64...
...how can I make it ? ...ehm step by step ...please 

I have installed on my MBP the last Xcode.

**Comment by Alessandro1970** [comment]
Never done it before.
I'd like to try me too, I'll follow this discussion.

**Comment by dirkwhoffmann** [comment]
The standard way is to clone the project directly from GitHub.

First, grab the link to the project from here:

<img width="459" alt="Bildschirmfoto 2020-04-14 um 10 59 52" src="https://user-images.githubusercontent.com/12561945/79206427-9b31e800-7e3f-11ea-9e9f-4b0ad80c354b.png">

After that, open Xcode and select to clone an existing project:

<img width="490" alt="Bildschirmfoto 2020-04-14 um 10 59 00" src="https://user-images.githubusercontent.com/12561945/79206456-a7b64080-7e3f-11ea-9568-4de1e5ce5d25.png">

On the next page, you'll be requested to type in the project link. Once this is done, Xcode comes up. To compile and run the project, simply click the "Play" button. That's all you need to do. 

<img width="1174" alt="Bildschirmfoto 2020-04-14 um 11 01 49" src="https://user-images.githubusercontent.com/12561945/79206769-1e533e00-7e40-11ea-8435-cd989d2363c0.png">

Please note that the standard configuration compiles the project in debug mode. The executable will be slower, but it will provide useful debug information if the app crashes. If you want to compile a version for productivity, select "Archive" from the "Product" menu and follow the instructions. 

Please let my if something goes wrong.

**Comment by Alessandro1970** [comment]
Wow ! Just compiled and exported as archive.

It works, you have just removed the keyboard C= bug that I told before ! Now Virtual Keyboard fully works !
Thanks

**Comment by bluecursor** [comment]
Can you please share the compiled version then?

**Comment by Alessandro1970** [comment]
[VirtualC64.zip](https://github.com/dirkwhoffmann/virtualc64/files/4498542/VirtualC64.zip)

@bluecursor 
Hi, this is my compiled VirtualC64 from GitHub with last improvements from master.

**Comment by bluecursor** [comment]
Thanks!

**Comment by rossimariolee** [comment]
I succeed in compiling it !!!
Thank you.
