### ISSUE TITLE
Fix it Felix Jr Voices

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#567]
Fix it Felix Jr Voices in VICE & DENISE emulators are clean and clear.
In V64, They sound distorted and dirty

**Comment by dirkwhoffmann** [comment]
If the issue is related to the following demo, I think it's no longer an issue in v4.0. Could you doublecheck? 

<img width="922" alt="Bildschirmfoto 2021-01-16 um 15 34 52" src="https://user-images.githubusercontent.com/12561945/104814708-bf788600-5810-11eb-87f1-97958f06ebdc.png">

**Comment by bluecursor** [comment]
It wasn't from a Sid player, it was the actual game.

**Comment by bluecursor** [comment]
Tested, Working clear now in v4.0b3
