### ISSUE TITLE
VirtualC64 won't save game for Legacy of the Ancients

### ISSUE THREAD

**Issue by TefJLives** [dirkwhoffmann/virtualc64#569]
Hello,

I'm trying hard to get Legacy of the Ancients going, to enjoy with my kids. I got VirtualC64 working, and it works beautifully, with only one problem. I can't save a game. In the readme file it says that if you save a game it saves on the game disk, but when I start it up again there is no saved character. Any advice on this?

Greg

**Comment by rossimariolee** [comment]
Hi,

Try to export disk to a new one before you quit, so you'll have a new modified and saved disk.
