### ISSUE TITLE
Proposed changes for VirtualC64 4.0

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#575]
I've opened this thread to describe and discuss some changes planned in VirtualC64 4.0. My main goal for version 4 is to bring vAmiga and VirtualC64 closer together. I've already ported back the way Roms are handled. Here is a comparison of the Rom panels of vAmiga 0.9 and VirtualC64 4.0: 

<img width="640" alt="Bildschirmfoto 2020-07-16 um 15 21 40" src="https://user-images.githubusercontent.com/12561945/87677903-93554d00-c77a-11ea-9159-840d5f8edbea.png">

In vAmiga, the user can opt to install the free Aros Kickstart replacement if he doesn't own the original Roms. In VirtualC64 v4.0, I want to do the same with the MEGA65 OpenROMs. 

<img width="640" alt="Bildschirmfoto 2020-07-16 um 15 01 27" src="https://user-images.githubusercontent.com/12561945/87678584-69505a80-c77b-11ea-8913-511f79ee6203.png">

By clicking "Install OpenRoms", the three MEGA65 Roms are installed automatically (they will ship with the emulator).

<img width="640" alt="Bildschirmfoto 2020-07-16 um 15 01 59" src="https://user-images.githubusercontent.com/12561945/87678096-d3b4cb00-c77a-11ea-8184-ab599ac56ca5.png">

<img width="931" alt="Bildschirmfoto 2020-07-16 um 13 12 49" src="https://user-images.githubusercontent.com/12561945/87678109-d6afbb80-c77a-11ea-8050-07d7811d7c4c.png">

Because there is no openROM for the disk drive, VirtualC64 4.0 won't require the disk Rom to be present. Of course, a disk drive can only be attached if the Rom is there, but the user will still be able to use PRG files, load from tapes, or attach a cartridge. 

Some other stuff will go away in v4. E.g., VirtualV64 3.4 has a (limited) AppleScript API. AppleScript really seems to be a dead horse by now and won't be supported any longer by the emulator.

**Comment by dirkwhoffmann** [comment]
This is how the new hardware configuration panel will look like in v4.0: 

<img width="931" alt="Bildschirmfoto 2020-07-21 um 10 11 08" src="https://user-images.githubusercontent.com/12561945/88029719-a54c3c80-cb3a-11ea-9e74-a2ac51f377cc.png">

The new layout is closer to what we have in vAmiga.

Some features of the status bar have also been ported. Now, the status bar shows the current track number for all connected drives:

<img width="274" alt="Bildschirmfoto 2020-07-21 um 09 54 53" src="https://user-images.githubusercontent.com/12561945/88029886-d7f63500-cb3a-11ea-98f6-d31a053624ed.png">

**Comment by dirkwhoffmann** [comment]
In v4.0 we have to say goodbye to the debug drawer. Although I believe a drawer was a suitable UI element for the debugger, drawers have been deprecated since a few macOS versions. Hence, it's time to go for something new. The old debugger will be replaced by an inspector similar to the one in vAmiga. Here is what the CPU panel is likely to look like: 

<img width="980" alt="Bildschirmfoto 2020-08-07 um 17 21 09" src="https://user-images.githubusercontent.com/12561945/89662888-04e56e80-d8d5-11ea-9a6f-644296dc24df.png">

For comparison, here is the corresponding panel in vAmiga:  

<img width="980" alt="Bildschirmfoto 2020-08-07 um 17 34 15" src="https://user-images.githubusercontent.com/12561945/89663029-32321c80-d8d5-11ea-93bf-77e5799621a9.png">

**Comment by dirkwhoffmann** [comment]
CIA panel has been ported from vAmiga to VirtualC64: 

<img width="980" alt="Bildschirmfoto 2020-08-11 um 13 22 27" src="https://user-images.githubusercontent.com/12561945/89891740-e5508d80-dbd5-11ea-84d8-1aa9b23930ca.png">

**Comment by dirkwhoffmann** [comment]
Memory panel has been updated. Both emulators use a similar design now:

VirtualC64: 

<img width="980" alt="Bildschirmfoto 2020-08-11 um 16 59 58" src="https://user-images.githubusercontent.com/12561945/89913750-60c13780-dbf4-11ea-8cc6-84b9298fef76.png">

vAmiga:

 
<img width="980" alt="Bildschirmfoto 2020-08-11 um 17 01 20" src="https://user-images.githubusercontent.com/12561945/89913797-6dde2680-dbf4-11ea-9b90-3b83449f09ee.png">

**Comment by dirkwhoffmann** [comment]
Preliminary layout of the new VIC panel: 

<img width="980" alt="Bildschirmfoto 2020-08-12 um 16 18 23" src="https://user-images.githubusercontent.com/12561945/90026471-9da23280-dcb7-11ea-9744-4f4676bcf621.png">

**Comment by dirkwhoffmann** [comment]
The last debug panel has been updated 🥵. Here is how the new SID panel looks like:

<img width="980" alt="Bildschirmfoto 2020-08-13 um 09 25 19" src="https://user-images.githubusercontent.com/12561945/90106077-2f0cb580-dd47-11ea-9698-e9c6201fbab1.png">

**Comment by mithrendal** [comment]
this is all so cool 😍 ... I want to have that all in vc 64 WebEdition too 😳 ... But it is a ton of work ... this would take months for me to port all that stuff over to HTML5 😔 ... you do an amazing job for the mac version  👌

**Comment by dirkwhoffmann** [comment]
>  I want to have that all in vc 64 WebEdition too
>  this would take months for me to port all that stuff over to HTML5

I think it's OK to not have a debugger in the web edition. Otherwise, there would be no reason to install the desktop version. 
The web edition has other cool stuff such as action buttons 😎.

**Comment by dirkwhoffmann** [comment]
This is how the disk inspector looks in v3.4: 

<img width="931" alt="Bildschirmfoto 2020-08-26 um 10 56 45" src="https://user-images.githubusercontent.com/12561945/91283432-e1526d00-e78a-11ea-8d07-40c6a936064e.png">

In v4.0, the disk inspector is a single panel inside the new inspector: 

<img width="980" alt="Bildschirmfoto 2020-08-26 um 10 45 14" src="https://user-images.githubusercontent.com/12561945/91283520-fcbd7800-e78a-11ea-8c13-ba74ca184467.png">

The track scanner (error log) is still there, but less obtrusive for the user. Whenever a new track is selected, a check is performed in the background. If errors were found, a warning message shows up and clicking the info button opens a separate sheet exhibiting the errors.

<img width="980" alt="Bildschirmfoto 2020-08-26 um 10 45 46" src="https://user-images.githubusercontent.com/12561945/91283538-0050ff00-e78b-11ea-9421-53c300e823f8.png">

**Comment by dirkwhoffmann** [comment]
I've started to port over vAmiga's screenshot code to VirtualC64. It's not complete, but looks very promising so far...

<img width="931" alt="Bildschirmfoto 2020-08-30 um 13 11 44" src="https://user-images.githubusercontent.com/12561945/91657604-90ac7e00-eac2-11ea-9b9c-ffffff460f19.png">

Also, I want to simplify things a bit. My experience in vAmiga with automatically taken screenshots hasn't been so good. Usually, the result is lots of blank screens or other boring stuff. Therefore, I decided not to port auto-screenshots to VirtualC64 and I am going to remove this feature from vAmiga, too.

**Comment by dirkwhoffmann** [comment]
VirtualC64 4.0 will get a revamped media dialog similar to the one in vAmiga.

vAmiga:

<img width="856" alt="Bildschirmfoto 2020-08-31 um 10 23 38" src="https://user-images.githubusercontent.com/12561945/91699854-328ca300-eb75-11ea-8f60-c687ce21a0cd.png">

VirtualC64 v4.0:

<img width="873" alt="Bildschirmfoto 2020-08-31 um 10 19 47" src="https://user-images.githubusercontent.com/12561945/91699878-3b7d7480-eb75-11ea-972f-79fe3b16f375.png">

The directory view is still there, but less obtrusive to the user (it’s a pop up button now). Selecting an item flashes it into memory (only PRG files are flashable). 

<img width="863" alt="Bildschirmfoto 2020-08-31 um 10 34 12" src="https://user-images.githubusercontent.com/12561945/91700101-a2029280-eb75-11ea-86cd-dbdd3ce1fbdf.png">

I’ve also incorporated an iCarousel view providing some eye candy if screenshots for the selected media file are found in the Application Defaults folder. This feature is also coming from vAmiga.

<img width="986" alt="Bildschirmfoto 2020-08-31 um 10 18 38" src="https://user-images.githubusercontent.com/12561945/91700123-aa5acd80-eb75-11ea-82da-0735b0e77745.png">

The TAP view is somewhat simpler than the one in v3.4. Auto-load is the only option in v4.0 whereas v3.4 has auto-load and auto-press-play-on-tape. Auto-load in v4.0 is the same as enabling both options in v3.4.

**Comment by bluecursor** [comment]
All these changes look awesome. Cant wait for the final beta or release of V4

**Comment by dirkwhoffmann** [comment]
The virtual keyboard has been reworked and is now „vAmiga style“. 

<img width="854" alt="Bildschirmfoto 2020-09-05 um 09 56 11" src="https://user-images.githubusercontent.com/12561945/92300998-f46df580-ef5f-11ea-9215-578c28e73be5.png">

The left mouse button presses a key for a short period of time whereas the right mouse button toggles the key state. Hence, with the use of the right button, arbitrary key combinations can be pressed.

<img width="854" alt="Bildschirmfoto 2020-09-05 um 09 57 36" src="https://user-images.githubusercontent.com/12561945/92301000-f768e600-ef5f-11ea-991b-aec03533acb2.png">

There are some internal API changes, too. Now, all functions for pressing keys have an optional parameter that can be used to automatically release a key after a certain numbers of frames:

    void press(long nr, i64 duration = 0);
    void pressRowCol(u8 row, u8 col, i64 duration = 0);

Changing disks is easier in v4.0, too. A call to insertDisk(…) is enough to insert a disk. It takes care of all necessary actions, namely: Blocking the light barrier by pulling the old disk halfway out, pulling the old disk out, blocking the light barrier again by pushing the new disk halfway in, etc.

**Comment by mithrendal** [comment]
>There are some internal API changes, too. 


These API changes are great. Looking ahead to integrate the v4 core into vc64web !!! That will be fun!!! 🤤

I also want to do that amazing keyboard... still a lot of work to do on the Web Edition side😅

**Comment by dirkwhoffmann** [comment]
vAmiga has the ability to cut out certain graphics layers for debugging. VirtualC64 v4.0 will offer something similar:

<img width="715" alt="Bildschirmfoto 2020-09-07 um 16 46 08" src="https://user-images.githubusercontent.com/12561945/92399214-36e32e00-f12a-11ea-88a7-bad690fd9791.png">
<img width="970" alt="Bildschirmfoto 2020-09-07 um 16 46 05" src="https://user-images.githubusercontent.com/12561945/92399223-3ba7e200-f12a-11ea-9e13-f010e742e8a9.png">

<img width="715" alt="Bildschirmfoto 2020-09-07 um 16 48 19" src="https://user-images.githubusercontent.com/12561945/92399233-419dc300-f12a-11ea-88a9-dcbf77705991.png">
<img width="926" alt="Bildschirmfoto 2020-09-07 um 16 48 14" src="https://user-images.githubusercontent.com/12561945/92399241-46fb0d80-f12a-11ea-97e7-ee24b5a0bf1d.png">

**Comment by sdsnatcher** [comment]
When sprites are disabled, shouldn't the background behind them be shown instead of the checkerboard?

**Comment by dirkwhoffmann** [comment]
> When sprites are disabled, shouldn't the background behind them be shown instead of the checkerboard?

Option "Hide Sprites" would do that. The stencil feature analyzed the final texture w.r.t. where each pixel comes from (border, foreground, background, sprites). If the source matches the filter, the pixel is "removed" and the checkerboard shines through.

**Comment by bluecursor** [comment]
So the stencil options are not a  multi select but are single select?
I would think you have select the last 3 options to achieve the checkerboard to show through?

Frank Michielli
Sent with iOS Spark!📱

**Comment by sdsnatcher** [comment]
> Option "Hide Sprites" would do that. 

Ok. I thought the "sprite cutout" would replace the "hide sprites" feature.

**Comment by dirkwhoffmann** [comment]
> So the stencil options are not a  multi select but are single select?

You can filter out as many layer as you want. If you check all options, you get a plain checkerboard. In vAmiga, this feature has proven to be useful for debugging.

**Comment by sdsnatcher** [comment]
Another topic: pretty please with sugar on top, add #515 to the list of changes on v4.0.     :)

**Comment by bluecursor** [comment]
Awsome, Thanks!

**Comment by dirkwhoffmann** [comment]
v4.0 will have a "DMA debugger" similar to the one in vAmiga. The DMA debugger visualizes all VICII memory accesses with different colors for different access types.

<img width="714" alt="Bildschirmfoto 2020-09-12 um 10 59 22" src="https://user-images.githubusercontent.com/12561945/92991966-6ce82f80-f4e7-11ea-9f7e-34ef9abc7046.png">

<img width="926" alt="Bildschirmfoto 2020-09-12 um 10 59 08" src="https://user-images.githubusercontent.com/12561945/92991972-770a2e00-f4e7-11ea-921d-fd04182f2540.png">

Obviously, it's less spectacular than the one in vAmiga, because bus sharing between the CPU and VICII is rather simple compared to what's going on inside the Amiga. But hey, why not.

**Comment by dirkwhoffmann** [comment]
The new debugging tools are cooler than expected. E.g., they reveal that Lemmings uses tons of sprites. They are not used for drawing the lemmings though (there are too many of them). Interestingly, the whole scenery is drawn with sprites:

<img width="970" alt="Bildschirmfoto 2020-09-12 um 13 46 50" src="https://user-images.githubusercontent.com/12561945/92994904-cf005f00-f4fe-11ea-8302-f629014eb104.png">
<img width="926" alt="Bildschirmfoto 2020-09-12 um 13 47 03" src="https://user-images.githubusercontent.com/12561945/92994914-d6c00380-f4fe-11ea-8901-dc4db6146e96.png">

**Comment by emoon** [comment]
It's always interesting it inspect what is going on. I love doing it (esp for Amiga stuff)

**Comment by mithrendal** [comment]
Deep scientific inspection 🤓🤤🤤🤤

**Comment by Alessandro1970** [comment]
Hi everyone,

after a long move to new house I was able to turn my old MBP back on waiting for a new MBP with Chip M1 to arrive in the spring ...
It is nice to reread and learn these changes that bring certain VirtualC64 settings closer to vAmiga.
Good idea.
Greetings to all of you.

**Comment by mithrendal** [comment]
Hi @Alessandro1970 good to hear from !

**Comment by dirkwhoffmann** [comment]
@Alessandro1970: Welcome back!
