### ISSUE TITLE
Joystick up and down reversed

### ISSUE THREAD

**Issue by 33dreams** [dirkwhoffmann/virtualc64#576]
Using a Nimbus Steelseries bluetooth controller on MacBook Air running 10.15.16. 
Up and down are reversed, but left and right and fire are okay.
Is there anyway to map joystick directions in Virtual C64? or is this a bug?

**Comment by dirkwhoffmann** [comment]
No, joystick directions are not customizable at the moment. When a USB or wireless joystick is detected, VirtualC64 uses a default mapping and adjusts some internal values if a known device is detected. If somebody has an old Nimbus controller and is willing to donate it, I can add the necessary parameters to the database. Unfortunately they are very expensive when bought new.

**Comment by dirkwhoffmann** [comment]
In v4 beta, joysticks are customizable in the Devices Preferences. Could you check if you can make the Nimbus work by changing one of the adjustable parameters?

<img width="639" alt="Bildschirmfoto 2021-01-15 um 15 32 46" src="https://user-images.githubusercontent.com/12561945/104739438-000bcd00-5747-11eb-8093-382cc9092495.png">

If you find a working combination, it'll be great if you post a screenshot here. I can then add the parameters to the internal database.

**Comment by 33dreams** [comment]
Hi there,

Where do I download the v4 beta?

**Comment by dirkwhoffmann** [comment]
You can download the latest version from the VirtualC64 home page which is now hosted on GitHub, too:

https://dirkwhoffmann.github.io/virtualc64/

**Comment by 33dreams** [comment]
Hi there,

Unfortunately, it’s the same as before. Left and right are correct on all sticks (irrespective of whether I select standard or rotated). Up and down are reversed, irrespective of whether I select standard or switched.

Cheers,

Chris





On 16 Jan 2021, at 12:34 am, Dirk Hoffmann <notifications@github.com> wrote:


In v4 beta, joysticks are customizable in the Devices Preferences. Could you check if you can make the Nimbus work by changing one of the adjustable parameters?

 <https://user-images.githubusercontent.com/12561945/104739438-000bcd00-5747-11eb-8093-382cc9092495.png>
If you find a working combination, it'll be great if you post a screenshot here. I can then add the parameters to the internal database.

**Comment by dirkwhoffmann** [comment]
I'll close this issue for now. I'll reopen it once such a controller is available.

**Comment by dirkwhoffmann** [comment]
Just ordered that thing. I am curious why this controller is so different.

**Comment by dirkwhoffmann** [comment]
Code has been ported.

**Comment by 33dreams** [comment]
Hi there, So when will it work with VirtualC64?
I just downloaded 4.0.1 and it still doesn’t work

By the way, thank you for making the effort with this. I really appreciate it.



On 9 May 2021, at 9:19 pm, Dirk Hoffmann ***@***.***> wrote:


Closed #576 <https://github.com/dirkwhoffmann/virtualc64/issues/576>.

**Comment by dirkwhoffmann** [comment]
> So when will it work with VirtualC64?

The fix will be part of v4.1.
