### ISSUE TITLE
Unable to properly load a .prg for some reason

### ISSUE THREAD

**Issue by Lohoris** [dirkwhoffmann/virtualc64#580]
I'm trying to load a .prg I created into VirtualC64, but it's not working. Let's say the file is called `A.PRG`.

On Vice it works, here's what I did there:

- I mounted the directory where the file resides as a virtual drive 9.
- On the emulator, I run `LOAD "A.PRG",9`, then `RUN`, and it works.
- Here I've tried to set the "drag a PRG" action to "insert into drive 8", but if I then run `LOAD "A.PRG",8` it says file not found.

I don't really know what I'm supposed to do to make it work.

The header of the file is a simple:

```
*=$0801

	BYTE    $0E, $08, $0A, $00, $9E, $20, $28,  $32, $30, $36, $34, $29, $00, $00, $00  ;Start at $0810

*=$0810
```

Which should basically translate to a "10 SYS 2064" if I recall correctly.

**Comment by dirkwhoffmann** [comment]
When a PRG is dragged in, it creates a disk with a single file on it. The file is named "FILE". In the following example, I've dragged in Galaxy.PRG: 

<img width="931" alt="Bildschirmfoto 2020-08-25 um 09 51 42" src="https://user-images.githubusercontent.com/12561945/91147650-d5967600-e6b8-11ea-81ca-d89f2fc4f195.png">

**Comment by Lohoris** [comment]
Ok that's quite helpful, thanks!

I'll start using this emulator for debugging then :D
