### ISSUE TITLE
Compiling VICE 3.4 on macOS Catalina

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#581]
I am trying to compile the latest VICE release on Catalina. Sounds easy, but... 😖

I executed the following commands:

```
./configure
make x64sc bindist 

```

It hangs here: 

```
Moving app to destination 'VICE-macOS-SDL2-x86_64-3.4/vsid.app'
Registering app with Launch Services
Done
cp: /usr/local/lib/libmp3lame.dylib: No such file or directory
make: *** [bindist] Error 1
```

Anybody an idea how I get this dylib onto my machine?

**Comment by mithrendal** [comment]
hmm you need that external lib ... but how to install it ?

🙋🏻 maybe with homebrew ?

https://formulae.brew.sh/formula/lame


🙋🏿or directly load it from the lame site ?

https://lame.sourceforge.io/download.php

**Comment by dirkwhoffmann** [comment]
Strange. It seems to build x64sc (I get compile errors if I add bogus code), but the final executable has a date lying way in the past: 

```
vice-patched % ls -al VICE-macOS-SDL2-x86_64-3.4/x64sc.app/Contents/MacOS/x64sc
-rwxrwxrwx@ 1 hoff  staff  109580 25 Nov  2018 VICE-macOS-SDL2-x86_64-3.4/x64sc.app/Contents/MacOS/x64sc
```

And the executable doesn't seem to have my debug code in it. 

Tracing the Makefile is complicated. The VICE Makefiles alone are as complex as the whole VirtualC64 project (at least it feels that way).

**Comment by dirkwhoffmann** [comment]
> or should we ask Zak McKracken ?💂🏿

Seems like he's the last hope. Any Zak McKracken's out there who want to give it a try? I mean it's just compiling a piece of software 🙄.

**Comment by mithrendal** [comment]
what is the intention of compiling it ? I mean if you only want any vice you could download the scene browser 1.3.2 from https://csdb.dk/release/?id=171112 . It uses not the version 3.4 but an older version of vice, but if it is suffient for a debug test or so it will be at least very easy to compile in Xcode. Because it is a XCode project with a vice emulator inside...

**Comment by dirkwhoffmann** [comment]
> what is your intention of compiling it ?

I'd like to add some `printf` statements inside the EasyFlash cartridge implementation to generate a trace which I can compare to the trace created by VirtualC64.

>  if you only want any vice you could download the scene browser 1.3.2
> it will be at least very easy to compile in Xcode

Sounds great! I'll give it a try. I hope "very easy" means to push a button called "Compile" and probably another one named "Run". 🤓 Version 3.4 is not required. I just need some VICE that is capable of emulating the Ultima EasyFlash CRT.

**Comment by mithrendal** [comment]
>I hope "very easy" means to push a button called "Compile" and probably another one named "Run". 

more or less ... yes...

I think because it is two years old and a recent XCode evolves in what it likes or not likes ... there are the usual 3 to 4 complaints in some code lines ... which are easy to repair ...

w.r.t. debugging ... you ma run it in a ipad / iphone simulator or remotely on you iPhone...

maybe the simulator is sufficient for your needs ... not sure how to get a easyflash into the simulator though, but hey you can try to browse one ... because it is a scene browser... 

I only tried the latter... put that puppy onto iPhone ... in which case you have to change/generate the free provisioning certificate under XCode "projects - general" ... don't panic ... its just a button click and it will generate a free certificate which is valid for 7 days and has to be renewed again with a button click after the 7 days have passed... 

also you have to alter the I think is called bundle identifier or dev team id ... change it to something you like for example bundleidentifier = "de.zakmacKraken.SceneBrowser" .... because the original bundle id which you will find in the source code is the one from Mr.Sid the original developer and it is probably already registered at Apple with his dev certificate ...

**Comment by mithrendal** [comment]
I tested the scene browser in the simulator and ... it started immediately nice ... but only the browser interface ... as soon as I start a title ... black screen...

Then I tested XCode remote debugging on real iPhone ... and that works fine


But now the bummer... the scene browser can’t start easyflash crt files


See here

![7E5F0613-E7C0-4601-9803-F03A6819DF33](https://user-images.githubusercontent.com/17108995/92639813-a6991a80-f2dc-11ea-9032-b68bf81ef8f9.png)



Play button is missing... I was looking for other EF titles ... also no play button.  Seems as if EF format is not supported by this software 🤭

**Comment by mithrendal** [comment]
that is unfair ... look ... when I look inside the scene browser then I find this 


![grafik](https://user-images.githubusercontent.com/17108995/92640814-1eb41000-f2de-11ea-8ce9-abb77e272249.png)


the underlying vice certainly knows how to handle easyflash crts ... but the browser interface maybe does not implemented the attach of the core

**Comment by mithrendal** [comment]
I will look into it maybe I can repair it ... I give it an hour not more ...

**Comment by mithrendal** [comment]
ok I got the play button now ... embarrassing ... I used always the version 1.3.1 which had maybe a bug ... now I downloaded freshly the version 1.3.2 from csdb.dk and that one shows the play button on easy flash ...

**Comment by mithrendal** [comment]
![89B4CB5F-E0AE-4606-A9DE-CFADA69AB805](https://user-images.githubusercontent.com/17108995/92646534-e238e200-f2e6-11ea-9259-a4da7214e05f.png)

![B6066C7C-E653-4621-89C3-89B5F0B582A7](https://user-images.githubusercontent.com/17108995/92646563-ea911d00-f2e6-11ea-9f06-7f63a6973403.png)

**Comment by mithrendal** [comment]
Maybe you are curious why it is not working in the Xcode simulator but only on iOS hardware ... that is because it is a simulator not an emulator. The source code (that is the vice) is translated to ARM ABI in case of iPhone/iPad and to x86/x64 ABI In case of the simulator. Some devs are a bit lazy w.r.t simulator and only care to the ARM ABI. It could also be some project build settings...

**Comment by dirkwhoffmann** [comment]
> On a AppleSilicon mac it should also work in the simulator...😎 ... Apple I want to have one ...

Not sure if I want to have an Apple computer at all any more... feels more and more like Microsoft. I am still struggling with the profile stuff, because my Apple ID is still connected with an old dev account of my university. As a result, I don't have permissions to do anything at the moment... 😡 It's all solvable, but it costs tons a time, wasted for nothing.

**Comment by mithrendal** [comment]
set up a fresh new user profile on your mac and start into it which does not not your apple old apple id ...

or alternatively 


I could also do everything for you if you like ... hat means insert printf and post the log output here ... you only have to tell me the printf statements ...

**Comment by dirkwhoffmann** [comment]
> set up a fresh new user profile without specifying your apple id 

Good idea, I'll try that later... need to do some real work first...

**Comment by mithrendal** [comment]
>need to do some real work first...

![grafik](https://user-images.githubusercontent.com/17108995/92697340-7e94d000-f34b-11ea-94d4-357f71f975e2.png)

**Comment by dirkwhoffmann** [comment]
To create a profile, I need a certificate? And to create the certifcate, I need a "Certificate Signing Request" which is a file I need to upload? True?

**Comment by mithrendal** [comment]
No with user profile I meant to create a new user account on your mac which is not connected to your apple id. For that account on your macbook you don’t need anything. 

Then on Xcode startup with the scenebrowser all should be clean and empty ... no old appleid which blocks you ...

**Comment by mithrendal** [comment]
but then at that point maybe it asks you again for an apple id ... when you insert your current apple id maybe it again thinks that one belongs to a certificate which is stored on another computer of your university ... I think it created some sort of private key which is inside the cert file on the other computer... and because you don't have it at home, it  blocks you and anyone who don't owns the key from using that signing certificate ...

two possibilities ..

first try to create a new free provisioning dev cert with your current apple id 


second create a new apple id ... (uh thats ... not so cool .. no?)

third run at university and get that private key cert ...

 

I would try the first way ... go to XCode -> preferences->Accounts

look at the third paragraph of this help page ... if a developemtn cert is missing a private key ...

<img width="785" alt="grafik" src="https://user-images.githubusercontent.com/17108995/92726609-21f6dc80-f36e-11ea-813b-8c5ae744036c.png">


It seems you have to reset everthing by deleting all certs in there ... no ?

**Comment by dirkwhoffmann** [comment]
> first try to create a new free provisioning dev cert with your current apple id

That's what I wanted to do. It first wants me to select an App ID. I've found an old app ID which I created years ago and I selected that: 

<img width="1172" alt="Bildschirmfoto 2020-09-10 um 14 00 55" src="https://user-images.githubusercontent.com/12561945/92726684-3fc44180-f36e-11ea-8ddd-41b2927c6731.png">

In the next step, they want me to upload something: 

<img width="1172" alt="Bildschirmfoto 2020-09-10 um 14 01 04" src="https://user-images.githubusercontent.com/12561945/92726715-4e125d80-f36e-11ea-804c-5e1c160eeae7.png">

**Comment by mithrendal** [comment]
Uhh what is an app id ? Can you just instead try this simple way ?


https://osxdaily.com/2016/01/12/howto-sideload-apps-iphone-ipad-xcode/

**Comment by dirkwhoffmann** [comment]
> We want no app id as we don't want to upload to the app store ..

No, we don't. We only want to compile a program. Apple, anybody home? 😖

BTW, this reminds me on a funny day years ago in Silicon Valley when a new Indian coworker got his first culture shock. He went into some Mexican store to eat a burrito. It wasn't so easy though. He was asked the usual two thousand questions (which meat, what sauce, do you have a club cart, do you have a coupon, do you have this, do you want that?). I think he got an internal overflow error, because the only words he was able to say in the end were: "I want to eat". I think he was deeply traumatized.

**Comment by mithrendal** [comment]
but thats a bit unfair because  for the simulator you don’t need the signing step or do you 😬?

On real iOS hardware every app is signed so if you want to bring an app onto iPhone it has to be signed too ...

**Comment by dirkwhoffmann** [comment]
> Just compiling and starting it up in simulator works ?

No. I get the following error messages now:

<img width="378" alt="Bildschirmfoto 2020-09-10 um 14 46 35" src="https://user-images.githubusercontent.com/12561945/92730839-9e8cb980-f374-11ea-81be-a28b8ebacde7.png">

I've plugged in my old iPhone. What exactly does Apple mean with "select"? Select it in Finder, select it in Xcode??? It doesn't do anything with my connected iPhone.

**Comment by mithrendal** [comment]
https://stackoverflow.com/questions/39603667/failed-to-create-provisioning-profile

**Comment by mithrendal** [comment]
select means select it in the top left right ... look at mine ... iPhone Baba

**Comment by mithrendal** [comment]
you can also **select** it via the menu like so 

![grafik](https://user-images.githubusercontent.com/17108995/92739923-a0a74600-f37d-11ea-9006-9dc705930559.png)

**Comment by dirkwhoffmann** [comment]
I finally managed to get Xcode my real iPhone accepted 🥵. My phone had trust issues which went away after restarting Xcode a couple of times (didn't I say Apple is the new Microsoft? 🤔) Anyway... after having a real iPhone connected, the emulator suddenly works (the real iPhone is needed for nothing, just to get rid of the error messages). Now, it's running in the emulator:

<img width="408" alt="Bildschirmfoto 2020-09-10 um 16 03 05" src="https://user-images.githubusercontent.com/12561945/92742070-8f5f3900-f37f-11ea-8182-4a2fa19047e6.png">

Now, the big question is: How do I get the Ultima cartridge into that thing?

**Comment by mithrendal** [comment]
first way is drag that screen down a bit then in the first row a search input field appears ... type in there "Ultima" ... it then searches csdb for ultima ...

**Comment by dirkwhoffmann** [comment]
> it then searches csdb for ultima ...

this means I have to patch the app to use a cartridge that is not on csdb?

**Comment by mithrendal** [comment]
no ... the other way is ... deploy on iPhone ... download the cartigde in Safari if you like ... and go to the files app click on the ultima_crt.zip file and choose share then the share sheets opens and you can choose c64SceneBrowser which opens it then ... then you can look at the Xcode console for the debug statements

**Comment by dirkwhoffmann** [comment]
Perfect: "Internal launch error". It only works in the emulator.

<img width="408" alt="Bildschirmfoto 2020-09-10 um 16 40 21" src="https://user-images.githubusercontent.com/12561945/92747358-67260900-f384-11ea-8500-419f8e6f111a.png">

**Comment by mithrendal** [comment]
dont panic go on your iphone -> settings -> Allgemein -> Geräteverwaltung ->AppleDevelopment ->C64Scene and trust it

**Comment by dirkwhoffmann** [comment]
> go to the files app click on the ultima_crt.zip file and choose share then the share sheets opens and you can choose c64SceneBrowser which opens it then

OK, this launches the app on my iPhone and I can see the debug messages in Xcode. This is what I see 🙈:

```
CART: could not attach '/var/mobile/Containers/Data/Application/461EFD71-EFFC-496A-A67D-C8E564911D94/Documents/45DD9476-C5F9-469F-8BBC-FDA80269E920/__MACOSX/._u5remastered.crt'.
Argument '/var/mobile/Containers/Data/Application/461EFD71-EFFC-496A-A67D-C8E564911D94/Documents/45DD9476-C5F9-469F-8BBC-FDA80269E920/__MACOSX/._u5remastered.crt' not valid for option `-cartcrt'.
Error parsing command-line options, bailing out. For help use '-help'
```

**Comment by mithrendal** [comment]
is it a pure crt file try to put it in a zip file ...

**Comment by mithrendal** [comment]
is it this https://csdb.dk/release/?id=187483 ? Then try to filter that thing in the scene browser

**Comment by mithrendal** [comment]
![D3647DB2-5B64-4D3A-8C7A-82EE27CDDDBB](https://user-images.githubusercontent.com/17108995/92750507-693d9700-f387-11ea-8d62-189012679654.png)

![C15EF657-D6FA-4821-AFF4-4C0656E1A2A7](https://user-images.githubusercontent.com/17108995/92750543-722e6880-f387-11ea-9387-61d732f53863.png)


![DC328484-568E-4DF3-AD0B-FE80A2073333](https://user-images.githubusercontent.com/17108995/92750566-7a86a380-f387-11ea-86b1-c857e112bd7d.png)

**Comment by dirkwhoffmann** [comment]
Yes, that's exactly the cartridge I want to debug. But in my emulator, it looks like this: 😮

<img width="398" alt="Bildschirmfoto 2020-09-10 um 17 03 41" src="https://user-images.githubusercontent.com/12561945/92750905-cb969780-f387-11ea-867e-706ec2fe0a57.png">

Oups, your Email notification came in just when I made the screenshot.

**Comment by mithrendal** [comment]
dirk you are too  fast .... did you read this ?

>you can try this in simulator but as I stated above the vice was not running in simulator on my machine due to x86/x64 ABI problems in the build settings I guess ... only the ARM build worked

>Maybe you are curious why it is not working in the Xcode simulator but only on iOS hardware ... that is because it is a simulator not an emulator. The source code (that is the vice) is translated to ARM ABI in case of iPhone/iPad and to x86/x64 ABI in case of the simulator. Some devs are a bit lazy w.r.t simulator and only care to the ARM ABI. This is probably only a problem in the project build settings ... maybe the vice code needs x86 but builds x64 or something like that ...

the screenshots 7 minutes ago where from real iPhone..  not from the simulator

**Comment by dirkwhoffmann** [comment]
> did you read this ?

It was a long text and you only posted it four or five times... 🙄

Finally 🥵

![IMG_0703](https://user-images.githubusercontent.com/12561945/92753808-8889f380-f38a-11ea-9789-5bfc7b1858ed.jpeg)

> if you only want any vice you could download the scene browser 1.3.2
> it will be at least very easy to compile in Xcode

Yeah, piece of cake 😎.

Tomorrow, I'll generate the debug trace...

**Comment by mithrendal** [comment]
>it will be at least very easy to compile in Xcode

😱 did I say this ? 😂
