### ISSUE TITLE
Drive device numbering appears wrong in version 4

### ISSUE THREAD

**Issue by rjpontefract** [dirkwhoffmann/virtualc64#582]
I was playing with the latest commits and it's looking really nice, good work!

I notice that when enabling both drives 8 & 9, they both respond as device 8 and device 9 is not present.  I can change drive 9 to device 9 by powering of drive 8 and using:

10 OPEN 15, 8, 15 
20 PRINT# 15, "M-W" CHR$(119) CHR$(0) CHR$(2) CHR$(9+32) CHR$(9+64)

But I was expecting it to be set in the emulator using the equivalent of switches or jumpers.  It does seem to work OK in 3.4.

**Comment by rjpontefract** [comment]
I got curious and had a look at the code.  This looks to be the cause:

    if (drive.getDeviceNr() == 2) {
        external |= 0x20; /* device number 9 */
    }

The code uses 8 and 9 for the device numbers, so should that 2 be a 9 or, better, DRIVE9:

    if (drive.getDeviceNr() == DRIVE9) {
        external |= 0x20; /* device number 9 */
    }

**Comment by dirkwhoffmann** [comment]
Thanks a lot for having a look at the current dev code, for finding this bug, and for providing the fix! I expect even more bugs of this kind, because I've changed so much in v4.0 🙄. 

I've just checked in your fix on the dev branch and merged it back into the main branch.

**Comment by rjpontefract** [comment]
My pleasure, if I find any more, I'll let you know.  Next time I'll be less lazy and fork and open a pull request.
