### ISSUE TITLE
Remembering Port 1/2 Settings 

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#583]
Add in settings to remember port1/2 settings.
Also settings are remembered/stored into when using Saving/Save As

**Comment by mithrendal** [comment]
... and what should happen when the user reloads a game and the remembered usb joystick has been disconnected ?

I bet I will have the same question in the web version ... no ? 

see here
https://github.com/dirkwhoffmann/virtualc64web/issues/54

**Comment by dirkwhoffmann** [comment]
In v4.0 (as well as in vAmiga), the port settings are part of the virtual machine configuration. As such the settings are part of snapshot files. This means that the settings revert to the saved ones if you open a snapshot file via "Open...".

<img width="970" alt="Bildschirmfoto 2020-09-11 um 11 51 12" src="https://user-images.githubusercontent.com/12561945/92907373-8cb71f00-f425-11ea-867c-86f36ef4d60b.png">

**Comment by mithrendal** [comment]
>... and what should happen when the user reloads a game and the remembered usb joystick has been disconnected in the meanwhile?

what should then happen ?

switch to NONE ... maybe ?🤔

**Comment by dirkwhoffmann** [comment]
>... and what should happen when the user reloads a game and the remembered usb joystick has been disconnected in the meanwhile?

My response time is improving. You only posted this twice, yet 😉.

Just looked at the code. The port settings are *not* part of snapshot, and I did this purposely. I expect that most users want to keep the current input configuration if they switch between snapshots. Hence, a remapping to "no device" is not necessary. 

However, the port mapping is saved in the user defaults (by the Swift GUI). This means that VirtualC64 remembers the port settings if the "Use as default" button is pressed in the hardware config panel. When VirtualC64 launches, the GUI loads all user defaults and checks if a USB joystick is connected. If not, it remaps it to "no device".

**Comment by dirkwhoffmann** [comment]
> When VirtualC64 launches, the GUI loads all user defaults and checks if a USB joystick is connected. If not, it remaps it to "no device".

I've just seen that if a port is mapped to a USB joystick and this setting has been saved into the user defaults, the port is nevertheless remapped to "no device". This is because loading user defaults happens before the USB handler detects connected devices. In other words: At the time the user default are loaded, no USB devices are visible for the GUI. This would be hard to change, but I think we can live with that behavior.

**Comment by bluecursor** [comment]
I think the port settings should be apart of a snapshot. If one snapshot uses port 1 and another uses port 2. If I go back to my first one after a week later of other game playing, I would like ito to remember that this snap uses port 1.

Frank Michielli
Sent with iOS Spark!📱

**Comment by bluecursor** [comment]
Which bring me to another request feature, the ability to restart a snapshot?

Frank Michielli
Sent with iOS Spark!📱

**Comment by dirkwhoffmann** [comment]
What do you mean by "restarting" a snapshot?

**Comment by bluecursor** [comment]
Like as if I opened the snapshot the first time. it could just restart from the beginning of the original state of the snapshot.

Frank Michielli
Sent with iOS Spark!📱

**Comment by mithrendal** [comment]
I am just implementing „action script“ in vc64web where I already defined the action „restore_last_snaphot“ of current game I bet you are dreaming of this no?



![](https://user-images.githubusercontent.com/17108995/92332054-29229f80-f07b-11ea-8cb2-33eaeed9c3e6.png)


Zak MacKraken wrote that we will be able to put our hands on it soon. 

Look 👀 here https://github.com/dirkwhoffmann/virtualc64web/issues/57

**Comment by dirkwhoffmann** [comment]
> Like as if I opened the snapshot the first time. it could just restart from the beginning of the original state of the snapshot.

If a snapshot is opened via the "Open..." menu, isn't your requested feature the same as what "Revert" is doing? If yes, it's already there.

Regarding the quick-save snapshots, the leftmost toolbar button in the snapshot section reverts to the latest quick-saved snapshot.

**Comment by bluecursor** [comment]
Yes you are correct!

Frank Michielli
Sent with iOS Spark!📱

**Comment by bluecursor** [comment]
In 3.4 doesn’t work, It does not restart the save state

Frank Michielli
Sent with iOS Spark!📱

**Comment by mithrendal** [comment]
dirk it tried it too in 3.4 vc64mac ... I had also no sucess ... or I don't know how to operate it ..


1. saved a snapshot xxx.VC64
2. closed vc64mac
3. double clicked the snapshot in the finder 
4. I was where I were when saving the snapshot ... good
5. I gamed on and pressed the leftmost toolbar button in the snapshot section ... nothing happend it don't goes back to the original state of the snapshot ...

**Comment by bluecursor** [comment]
Also once this features is working, please add a keyboard shortcut….

Frank Michielli
Sent with iOS Spark!📱

**Comment by dirkwhoffmann** [comment]
>  gamed on and pressed the leftmost toolbar button in the snapshot section

The icons are different in v3.4. It works as follows:

1. Launch VirtualC64
2. Press the button with the "database burger" and the down arrow (quick-save snapshot)
3. Play Zak MacKraken or simply change the background color
4. Press the button with the "database burger" and the up arrow (revert to latest quick-saved snapshot)

It has nothing to do with the original snapshot (the one you double-clicked). To get to the initial state of that one,  "Revert" from the file menu is supposed to do the job.

**Comment by bluecursor** [comment]
Its easier to quit C64 and double click the snapshot file and then change the port settings….

Frank Michielli
Sent with iOS Spark!📱

**Comment by mithrendal** [comment]
>To get to the initial state of that one, "Revert" from the file menu is supposed to do the job.

this is not working at my machine in 3.4 ... when I choose File->Revert it asks me whether I really want it or not ... when clicking yes ... nothing happens ... seems a bit buggy no ?

>Its easier to quit C64 and double click the snapshot file and then change the port settings….
  
I fear ... yes

**Comment by mithrendal** [comment]
![grafik](https://user-images.githubusercontent.com/17108995/92935877-aff3c580-f449-11ea-87bb-2d8f0375e19e.png)

in the pic above you see the revert ... that one is not working I think ...

"restoring to the last temporary snapshot" is indeed working ... when doing what dirk writes above ...

one must keep in mind or differentiate though that it is only working on temporary "non persistent" snapshots, that is snapshots which are not saved to disk ... I found this differentiation irritating too ... when doing the [vc64web brother](https://dirkwhoffmann.github.io/virtualc64web/) I decided to go only with "persistent" snapshots ... in this case the user does not have to think too much ... when pressing the snapshot-managment-buttons because there is only one type of snapshots...

**Comment by mithrendal** [comment]
I have an easy idea to heal the above dilemma ... of the two storage types in vc64mac ...

when the user loads a snapshot file from file system then dirk can call the  "take snapshot" automatically one time immediatley after loading has completed ... that way the user can see the snapshot in the snapshot browser and the user can jump back via the "database hamburger arrow up"

**Comment by dirkwhoffmann** [comment]
>  dirk can call the "take snapshot" automatically one time immediatley after loading 

Sound like a cool idea to me.

**Comment by mithrendal** [comment]
> in the pic above you see the revert ... that one is not working I think ...

@dirkwhoffmann on your side too ? 🙄

> Sounds like a cool idea to me.

😊Should be „very“ easy and straight forward to implement and user friendly too

**Comment by dirkwhoffmann** [comment]
> in the pic above you see the revert ... that one is not working I think ...

You're right. It's broken.

**Comment by dirkwhoffmann** [comment]
"Revert" is working again (in v4.0)
