### ISSUE TITLE
Screen flicker in full screen mode during disk access.

### ISSUE THREAD

**Issue by karnov77** [dirkwhoffmann/virtualc64#584]
Screen flickers ( goes from normal to slightly brighter ) rapidly during disk access in full screen mode.

**Comment by karnov77** [comment]
Also, screen gets brighter when VirtualC64 menu bar appears when placing the mouse cursor at the top of the screen in full screen mode.

**Comment by dirkwhoffmann** [comment]
I double-checked fullscreen mode in v3.4 and wasn't able to reproduce something like that.

Do you mind posting a screenshot or video to demonstrate the behavior?

**Comment by karnov77** [comment]
I just tried to record the screen using the screen recording tool built
into macOS.
Once I recorded, the issue went away! It's working properly now and not
dimming anymore.

Very strange...

Thank you anyway! VirtualC64 is amazing! Thank you for making it! :-)

Andrew
