### ISSUE TITLE
Missing cartridges

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#585]
I'd like to expand the range of supported cartridges in v4.0 a bit. For doing this, I am looking for the following cartridges in form of .crt files:

- ~~Moonspire~~
- ~~GameKiller~~

Maybe someone can help out (without posting them here).

BTW, v4.0 will support cartridges of type "Dinamic" (which is an extremely simple cartridge, to be honest):

<img width="970" alt="Bildschirmfoto 2020-09-15 um 17 16 19" src="https://user-images.githubusercontent.com/12561945/93230608-265d3400-f778-11ea-9da0-e179a891daa7.png">

**Comment by Shrapnel21** [comment]
I have Moonspire, how can I help?

**Comment by dirkwhoffmann** [comment]
First findings: Moonspire identifies itself as a cartridge of type "Magic Desk" 😳:

<img width="597" alt="Bildschirmfoto 2021-01-03 um 14 10 55" src="https://user-images.githubusercontent.com/12561945/103479411-b8438800-4dcd-11eb-9367-f886592e3949.png">

**Comment by Alessandro1970** [comment]
Hi,

...I have missed something in this times!

I have a copy of GAME_KILLER.CRT.
If it is still needed How can I send it ?
Bye
![Untitled 2](https://user-images.githubusercontent.com/34916641/106896788-52ab2a00-66f2-11eb-9d12-d47112a13438.png)

**Comment by Alessandro1970** [comment]
Hi,

...I have missed something in this times!

I have a copy of GAME_KILLER.CRT.
If it is still needed How can I send it ?
Bye

![Untitled 1](https://user-images.githubusercontent.com/34916641/106896962-93a33e80-66f2-11eb-9e94-7633d7ada2b0.png)

**Comment by dirkwhoffmann** [comment]
>  How can I send it ?

Email 😎.

**Comment by Alessandro1970** [comment]
Ahh!
Oh yes, Eh! ...I'm getting older than I think I am...  :sob: 

I sent it at your contac @hs-karlsruhe.de

**Comment by dirkwhoffmann** [comment]
![Unknown](https://user-images.githubusercontent.com/12561945/106899759-07931600-66f6-11eb-924e-a9ab402392a2.png)

Thanks!
