### ISSUE TITLE
C64 refuses to quit on macOS 10.15.7

### ISSUE THREAD

**Issue by kghose** [dirkwhoffmann/virtualc64#588]
Thank you for creating an upto date C64 emulator. The latest release has an odd problem that it refuses to quit on macOS. The quit option is greyed out in the File menu. The only way is to kill the process using the activity monitor. 

Thanks.

**Comment by dirkwhoffmann** [comment]
With "latest release", are you referring to v3.4 or v4.0 (alpha)?

**Comment by kghose** [comment]
v3.4. That is labeled as latest release is it not.

**Comment by dirkwhoffmann** [comment]
> v3.4. That is labeled as latest release is it not.

Thanks. Yes, v3.4 ist the latest stable release. v4.0 is in the works.

**Comment by dirkwhoffmann** [comment]
Could you check if the problem still occurs in v4.0b2?

**Comment by kghose** [comment]
Yes! This release fixes this problem, thank you. I see you also have it work with the mac's touch bar, very nice.
