### ISSUE TITLE
download link broken

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#589]
When I click on 
![image](https://user-images.githubusercontent.com/3512672/95399320-d6e5d000-08ff-11eb-8b06-019404e50599.png)

I get at the error below :(

Multiple Choices

The document name you requested (/software/VirtualC64_3.4.zip) could not be found on this server. However, we found documents with names similar to the one you requested.
Available documents:

/software/VirtualC64_3.3.2.zip (common basename)
Please consider informing the owner of the referring page http://www.dirkwhoffmann.de/software/virtualc64.html about the broken link.

**Comment by dirkwhoffmann** [comment]
The downloading link should work now. Thanks for reporting this.
