### ISSUE TITLE
About VAmiga : Incorrect version

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#590]
When I click on About VAmiga  I see that the version is Version 0.9.10.1 (0.9.10.1)

![image](https://user-images.githubusercontent.com/3512672/95399410-0b598c00-0900-11eb-9c8a-1e63cad86a49.png)

The website however lists 3.4 as the latest.

**Comment by dirkwhoffmann** [comment]
The latest (stable) version of VirtualC64 is v3.4. The latest version of vAmiga is 0.9.12. I haven't spotted a place on the web site where vAmiga is labelled v3.4.
