### ISSUE TITLE
Keyboard does not repeat key while holding down

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#591]
Either the Virtual Keyboard or regular inputs does not allow for key repeats. There should be a option for this.

Also, Id like the see the ability to map your keyboard, as can never/find the right key for <- or C= on my MBP.
And Also, to see the virtual key to display what key has pressed.

**Comment by dirkwhoffmann** [comment]
> Either the Virtual Keyboard or regular inputs does not allow for key repeats

I can't influence this, because it's controlled by the C64 Roms. The C64 only allows key repeats for the SPACE key.

**Comment by bluecursor** [comment]
OK
