### ISSUE TITLE
Freezes on m1 cpu

### ISSUE THREAD

**Issue by Optic00** [dirkwhoffmann/virtualc64#592]
Tried running virtualc64 on Mac m1 hardware today. Getting a blue screen and than virtualc64 freezes up. Seems to have issues with rosetta translation I assume. Although to be expected(?) I wanted to get this added as an issue anyways.

**Comment by mithrendal** [comment]
I have read anywhere that the mach time resolution is different on AppleSilicon. As vc64mac depends on it for synchronisation it might be the issue here.

**Comment by dirkwhoffmann** [comment]
Thank you very much for reporting the compatibility issue with the new Mac ARMada. I didn't really expect this kind of incompatibility, but it doesn't surprise me either. Unfortunately, I can't do anything myself at the moment, because I would need an ARM machine at hand.

I don't think it's related to the mach resolution. If it was, the emulator should just run much faster or much slower, but it shouldn't freeze. Unfortunately, it could be nearly anything. E.g., something like the issue we have with vAmiga on Linux where the sheer size of a single emulator instance crashes the stack.

**Comment by mithrendal** [comment]
@Optic00 have you tried dirks vAmiga ? Does it crash too on ARM ?

**Comment by Optic00** [comment]
not yet, I got a few hours on my hand, will do that now

@dirkwhoffmann if you like I can offer a quick remote teamviewer/anydesk session if you'd like to have a look, i am same timezone/country so no problem from my side. Nothing urgent here from my side, just an offer :-)

**Comment by Optic00** [comment]
vAmiga works, I just ran "Arte" Demo on it with up to 60Mhz (showing in the lower right), I haven't used this Emulator before, maybe didn't put some settings up that are needed.

**Comment by dirkwhoffmann** [comment]
> Edit: what I mean is, it runs but just way to fast ;-)

This could well be related to the Mach timing issue mentioned by @mithrendal. If it is, it should be fixed in the next release (the timing code has been cleaned up recently to make vAmiga compatible with gcc).

**Comment by Optic00** [comment]
@mithrendal web version works, thanks! 

and if anyone wants to test something on this box just let me know.

**Comment by mithrendal** [comment]
the article above says ...
`For macOS running on Intel processors, the numerator and denominator of mach_timebase_info are the same, and have often been omitted.`

now on ARM its nt the same anymore we have to calculate like this ...
```
var info = mach_timebase_info()
mach_timebase_info(&info)
then
((secondTicks - firstTicks) * UInt64(info.numer)) / UInt64(info.denom)
``` 

hang on I check the code ...

**Comment by dirkwhoffmann** [comment]
The latest vAmiga code does exactly that 😎 (part of the new Oscillator class):

```
// Information about the Mach system timer
static mach_timebase_info_data_t tb;

// Converts kernel time to nanoseconds
static u64 abs_to_nanos(u64 abs) { return abs * tb.numer / tb.denom; }
```

This class needs to be ported back to VirtualC64.

**Comment by mithrendal** [comment]
the v4 Core of vc64mac also does it no ?

found this ...
```

  // Converts kernel time to nanoseconds
    u64 abs_to_nanos(u64 abs) { return abs * timebase.numer / timebase.denom; }
    
    // Converts nanoseconds to kernel time
    u64 nanos_to_abs(u64 nanos) { return nanos * timebase.denom / timebase.numer; }
```

**Comment by dirkwhoffmann** [comment]
> the v4 Core of vc64mac also does it no ?

Yes and no. In the old code, calls to the Mach timing routines were spread all over the place. At some places, it did the scaling, at others, it did not 🙄.

**Comment by Optic00** [comment]
if it helps, FS-UAE works at 100% on m1

**Comment by dirkwhoffmann** [comment]
I just tried to compile VirtualC64 as a universal binary. It failed, because it has no ARM version of the Sparkle framework to link against (I need to check if Sparkle is ready for ARM by now...). 

Can you do me a favor and check if the timing issue is fixed in the latest version of vAmiga (0.9.15)? 
https://github.com/dirkwhoffmann/vAmiga/releases

v0.9.15 is a universal binary and should run pretty fast on your machine (It'll be interesting to know how many MHz the virtual Amiga reaches in warp mode). If the timing issue turns out to be fixed in vAmiga, I'll port the new Oscillator class over to VirtualC64.

**Comment by Optic00** [comment]
thanks for the update! unfortunately 0.9.15 doesn't work native - I can start the app, use settings etc, but I have to check "use rosetta" otherwise the emulation doesn't start. Just a black screen, no emulated disk sound etc when I run it native.

**Comment by dirkwhoffmann** [comment]
> thanks for the update! unfortunately 0.9.15 doesn't work native

OK, thanks. This means the transition to ARM isn't as simple as Apple has suggested in their keynote (advertising) video 🙄.

**Comment by Optic00** [comment]
my offer again if you'd like to have a quick look I can load up teamviewer/anydesk on this box.
My naive thinking is it might just be a little thing to switch you can see in debugging ;-) 

Already loaded it up in Xcode - nothing showing up in debugging other than the zooming in taking place, than stop.

**Comment by Optic00** [comment]
> I just tried to compile VirtualC64 as a universal binary. It failed, because it has no ARM version of the Sparkle framework to link against (I need to check if Sparkle is ready for ARM by now...).

sparkle is available for ARM, I used it to compile an arm version of Tunnelblick since it would hang up every 20-40 Minutes, I could just replace the existing sparkle, was just simple as that (I am not a programmer, just thought I'd give it a shot hehe)

**Comment by dirkwhoffmann** [comment]
Could somebody give v4.0b1 a try on  M1 hardware? Since it utilises the same new "Oscillator" code as vAmiga, there is a big change that it'll work.

**Comment by Optic00** [comment]
works great on m1! thanks for the work on it!

**Comment by dirkwhoffmann** [comment]
> works great on m1!

Very good news! 😎
