### ISSUE TITLE
PSID/MUS player

### ISSUE THREAD

**Issue by chris70c** [dirkwhoffmann/virtualc64#598]
Would it be possible to add a PSID/MUS player?
Thanks
Chris

**Comment by dirkwhoffmann** [comment]
Could you please describe a user scenario (use case) for this? How exactly would you use such a feature? What is the emulator supposed to do?

**Comment by bluecursor** [comment]
This would just make life easier to play music/sid files rather than loading a player first. No other emulator has this feature so I see no reason for it. Just my two cents...
