### ISSUE TITLE
latest kernal from open-roms is not recognized

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#599]
https://github.com/MEGA65/open-roms/blob/master/bin/kernal_generic.rom

**Comment by dirkwhoffmann** [comment]
Fixed (on dev branch)

**Comment by mithrendal** [comment]
The new v4 core is still working with magic header bytes for the open-roms ? 

I thought at open-roms they invented some srt of signature which is more stable than the magic header ... me was it that I read it somewhere ....

but today I only found this ...
 
https://github.com/MEGA65/open-roms/issues/55

**Comment by dirkwhoffmann** [comment]
It's a two pass process at the moment:

- Check the magic header bytes to see if the file can be considered as (any) Rom.
- Check the CRC checksum (Original Roms) or some special bytes (Open Roms) to get precise revision infos.

**Comment by mithrendal** [comment]
can we get rid of check 1 ? Each time they change the header ... and they do it often .. we have to adapt ...
