### ISSUE TITLE
Big Sur Icons

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#600]
For Big Sur, a new icon is needed.

<img width="1020" alt="86369529-3f7d3b00-bc87-11ea-9e61-a90853b7d598" src="https://user-images.githubusercontent.com/12561945/102476117-02e9a400-405b-11eb-9e13-98aafd591415.png">

**Comment by dirkwhoffmann** [comment]
![bigsur_icon](https://user-images.githubusercontent.com/12561945/102478901-78a33f00-405e-11eb-9dac-32d410415bc5.png)

**Comment by dirkwhoffmann** [comment]
In case we also need a rectangular style vc64web icon...

![web_icon](https://user-images.githubusercontent.com/12561945/102480640-d59ff480-4060-11eb-97ec-7e366b759d2a.png)

**Comment by bluecursor** [comment]
![iconfinder_Monitor_CRT_1218800](https://user-images.githubusercontent.com/31462938/104511564-ec336000-55ba-11eb-843f-3e5296c659f3.png)

**Comment by dirkwhoffmann** [comment]
Nice icon. Just a side note: The Commodore logo is still used today (in legal terms: it is in "active use"). That is, if we use it, we expose ourselves to the risk of trademark infringement. In case of the Amiga, the situation is twofold: The coloured hook is no longer in active use which means it's safe to use it in our own artwork. The red and white Amiga ball is different. It is under protection, because it's still in active use. It's explained nicely in the following document: 
 
https://ftp.fau.de/aminet/docs/misc/Amiga-Trademarks.pdf
