### ISSUE TITLE
4.0b1 - fuzzy borders in full screen with the original aspect ratio

### ISSUE THREAD

**Issue by kyods** [dirkwhoffmann/virtualc64#605]
If "Keep aspect ratio" is selected the borders in full screen mode have the same fuzzy texture as the main screen when powered off - although static. It would be nice to have a clean black background, or a smooth gradient like in vAmiga.

<img width="1680" alt="Screenshot 2021-01-13 at 17 11 50" src="https://user-images.githubusercontent.com/66119492/104478767-f8232000-55c2-11eb-822e-40772dbd7d65.png">

Also there's a typo in the Warp Mode selection. It currently says "Activatation", I'm sure you wanted "Activation" instead.

**Comment by dirkwhoffmann** [comment]
This looks much better now. I've ported the gradient texture code from vAmiga: 

<img width="240" alt="Bildschirmfoto 2021-01-14 um 17 47 04" src="https://user-images.githubusercontent.com/12561945/104621675-a9dc5280-5690-11eb-8d63-7176dc44e0f3.png">

**Comment by dirkwhoffmann** [comment]
Should be fixed in v4.0b2.
