### ISSUE TITLE
4.0b1 - Insert Recent

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#614]
Selecting recent flashed file can be shown in a directory on a disk but will not reload.
Selecting recent .d64 sometimes doesn't work consistently.

**Comment by dirkwhoffmann** [comment]
I wasn't able to reproduce that. I need a step-by-step instruction how to reproduce the bug.

**Comment by bluecursor** [comment]
Cant reproduce error in 4.0b2 as nothing I have loaded/used doesn't show up in the recent used list any more...

**Comment by dirkwhoffmann** [comment]
> as nothing I have loaded/used doesn't show up in the recent used list any more...

The recently used files list is not saved. It is only valid for the current session.

**Comment by bluecursor** [comment]
When Testing, I am only using the power on/off and reset and it still doesn’t show recently used.
Using Save As showed up on the list...

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by bluecursor** [comment]
I understand now, as the drives have recent list where last insert are...
