### ISSUE TITLE
Crashing Issues

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#617]
Crashed Thread:        13

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (abs(l) < 0.15), function mixSingleSID, file /Users/hoff/virtualc64/Emulator/SID/SIDBridge.cpp, line 792.

[Archive.zip](https://github.com/dirkwhoffmann/virtualc64/files/5816569/Archive.zip)

**Comment by dirkwhoffmann** [comment]
Should be fixed in v4.0b2.
