### ISSUE TITLE
4.0b2- Warp Mode still not working properly

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#618]
Warp mode set to when disk activity and when trying a load dir and load prg, the warp mode never turned on

![Screen Shot 2021-01-15 at 9 51 46 AM](https://user-images.githubusercontent.com/31462938/104742016-edc66a80-5717-11eb-835e-9aba7f2d3899.png)

**Comment by dirkwhoffmann** [comment]
Confirmed. I accidentally deleted function 

    @property (readonly) BOOL busy;

from the ObjC proxy. It'll work again in the next beta.

**Comment by dirkwhoffmann** [comment]
Fixed in v4.0b3.
