### ISSUE TITLE
4.0b2- Crash Issue is now a Freeze Issue

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#619]
Same Demo as before, but now VC doesn't get as far as v4.0b1 and screen dims and sits there...

![Screen Shot 2021-01-15 at 10 25 39 AM](https://user-images.githubusercontent.com/31462938/104746083-cfaf3900-571c-11eb-8a8b-f0b874c3aa43.png)

[Archive.zip](https://github.com/dirkwhoffmann/virtualc64/files/5821404/Archive.zip)

**Comment by bluecursor** [comment]
Same 2nd Demo doesn't run anymore either

[2-Shape.zip](https://github.com/dirkwhoffmann/virtualc64/files/5821447/2-Shape.zip)

**Comment by dirkwhoffmann** [comment]
Works here: 

<img width="922" alt="Bildschirmfoto 2021-01-15 um 16 46 39" src="https://user-images.githubusercontent.com/12561945/104747849-4a924700-5751-11eb-8e14-b2b30a2d4cdf.png">

Is it probably a Rom issue? From your screenshot, it seems that you're not using the original Roms.

**Comment by bluecursor** [comment]
Using a JiffyDOs Kernel upgraded to JaffyDos.

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by bluecursor** [comment]
Not a rom issue, used original rom, same error


Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
Here it works with the following HW config: 

<img width="638" alt="Bildschirmfoto 2021-01-15 um 17 00 32" src="https://user-images.githubusercontent.com/12561945/104751067-29335a00-5755-11eb-8c1d-22c6a6c92dc6.png">

Maybe you need to turn off the second drive, don't know.

**Comment by bluecursor** [comment]
Second drive is switched off.
Tried a NTSC model still the same issue.
Tried using jiffydos 1541 kernel, still the same issue
I don’t know either….

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
> screen dims

For some reasons, your emulator is in pause mode: 

<img width="319" alt="Bildschirmfoto 2021-01-15 um 17 24 50" src="https://user-images.githubusercontent.com/12561945/104752198-aca17b00-5756-11eb-810d-783e704b335f.png">
