### ISSUE TITLE
V4.0b2 - Crash Issues

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#620]
Crashed Thread:        28

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (!isFull()), function write, file /Users/hoff/virtualc64/Emulator/Foundation/Buffers.h, line 97.

**Comment by bluecursor** [comment]
I created 5 tabs of the same game. I Loaded each tab by double clicking on  a Saved Game/ File

**Comment by dirkwhoffmann** [comment]
Should no longer crash in v4.0b3.
