### ISSUE TITLE
4.0b3 - 2nd SID @ $d500 not playing properly

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#624]
2nd SID @ $d500 not playing properly
[$D500 - ALD_Sad_Song_2SID_8580_Stereo.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/5826960/D500.-.ALD_Sad_Song_2SID_8580_Stereo.prg.zip)

**Comment by bluecursor** [comment]
Playing around with it more, I think there is a issue of how Many times you close windows that VirtualC64 starts to show signs of slowness and chipping processing. That it might not clear memory or something when you close the window (not Quit)

**Comment by dirkwhoffmann** [comment]
Confirmed. When a a window gets closed, the underlying emulator instance is not deleted correctly (it keeps on running in the background).

**Comment by dirkwhoffmann** [comment]
Should be fixed in v4.0b4.
