### ISSUE TITLE
Loading in a .D64

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#625]
I never seen this option before when trying to load a .D64?

[Oyup!_101%_(+)_LAXITY.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/5840303/Oyup._101._.%2B._LAXITY.d64.zip)
![Screen Shot 2021-01-20 at 12 19 31 AM](https://user-images.githubusercontent.com/31462938/105130681-7bf27600-5ab5-11eb-94e8-e3dff7213e09.png)

**Comment by dirkwhoffmann** [comment]
The images appear because you've taken some screenshots in a previous session with this D64 inserted. When the dialog opens, it scans the screenshot cache and displays what it finds.

**Comment by bluecursor** [comment]
When I go check for screenshots, there is nothing there?

**Comment by bluecursor** [comment]
Menu repeats itself...
![Screen Shot 2021-01-20 at 9 36 24 AM](https://user-images.githubusercontent.com/31462938/105189562-15944480-5b03-11eb-9ea5-8787bad3a5f6.png)

**Comment by dirkwhoffmann** [comment]
> Menu repeats itself...

One menu is for snapshots, the other one for screenshots.

To access screenshots, first open the screenshot browser:

<img width="922" alt="Bildschirmfoto 2021-01-20 um 16 19 53" src="https://user-images.githubusercontent.com/12561945/105196082-8e16f780-5b3b-11eb-9404-97418ade86c8.png">

Now, click here: 

<img width="922" alt="Bildschirmfoto 2021-01-20 um 16 19 13" src="https://user-images.githubusercontent.com/12561945/105196145-9f600400-5b3b-11eb-8171-9b0b904e81f0.png">

This opens up a Finder window which lets you access to the image files:

<img width="852" alt="Bildschirmfoto 2021-01-20 um 16 19 43" src="https://user-images.githubusercontent.com/12561945/105196309-c7e7fe00-5b3b-11eb-89e4-068bd3751e02.png">

**Comment by bluecursor** [comment]
ok
