### ISSUE TITLE
4.0b4 Joystick Control

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#626]
Game play is impossible as it does/doesn't register joystick movements (using Keyboard Keyset). 
Works fine in Denise and VICE

[spike_plus2_SWIMMERS.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/5851677/spike_plus2_SWIMMERS.d64.zip)

**Comment by dirkwhoffmann** [comment]
I had to press the joystick in port 1 first. After that, I was able to play the game with the joystick in port 2:

<img width="922" alt="Bildschirmfoto 2021-01-21 um 21 26 10" src="https://user-images.githubusercontent.com/12561945/105408556-699c4780-5c2f-11eb-88b4-a39954c0364b.png">

**Comment by bluecursor** [comment]
Tried that, Still not working from me. I have to tap the keys just to get it moving pixel by pixel

**Comment by dirkwhoffmann** [comment]
> Tried that, Still not working from me. I have to tap the keys just to get it moving pixel by pixel

Did you enable "Disconnect emulation keys from keyboard"?

**Comment by bluecursor** [comment]
No, working now.. Can this option be placed either on the bottom bar or top bar?

**Comment by bluecursor** [comment]
At boot and joystick in port 2 on, the arrow keys move the cursor except for arrow up. SHiFT arrow was working, but
now since enable/disable "Disconnect emulation keys from keyboard" it doesn't work anymore.

**Comment by bluecursor** [comment]
Would be also nice if we could map the keys for C=, Runstop, Restore, Clr, etc....

**Comment by bluecursor** [comment]
I just tested on a real hardware with a joystick in port 2 and all the cursor keys work. Just need arrow up fixed.
