### ISSUE TITLE
Game Killer cartridge partly working

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#634]
The good:
- Game Killer intro is working well.
- I've testes the CRT with Fast Eddy and it worked as expected (sprite collisions got disabled).

The bad:
  - When the cartridge is used just after boot, the C64 freezes most of the time.
  - This doesn't happen in VICE.

The ugly:
  - Not sure if this is a bug.

    https://rr.pokefinder.org/wiki/Game_Killer
    „Kernal ROM routines are often hit hard and taken to a crash when trying to use Game Killer. Normal program routines are not that easily being crashed.“

This quote fits well with what I see in VirtualC64, but I cannot explain why it doesn’t crash in VICE.

<img width="998" alt="Bildschirmfoto 2021-02-04 um 16 10 20" src="https://user-images.githubusercontent.com/12561945/106925750-ad537e80-6710-11eb-9a4e-900bd1164aaf.png">

**Comment by dirkwhoffmann** [comment]
Found it:

```C++
void
GameKiller::pressButton(unsigned nr)
{
        suspend();
        ...
        cpu.pullDownNmiLine(INTSRC_EXP);
        resume();
}
```

The problem is causes by the suspend() / resume() block which is needed, because this function is called from outside the emulator thread. suspend() halts the emulator thread at the end of the current frame which means that the button press gets synchronized with VSYNC. I guess this is exactly the point in time where the button should not be pressed. The new code signals the NMI in a more sophisticated way and the problem went away. Bottom line: We can add this cartridge to the list of supported cartridges.

**Comment by Alessandro1970** [comment]
I did not know this cartridge:
Is it true all what is written here ? does It work with VirtualC64 the sprite collision remover ?

![Commodore_Horizons_Issue_27_1986_Mar_Game_Killer_Functions](https://user-images.githubusercontent.com/34916641/107006989-32cb4300-6792-11eb-9fb2-f0c477cbb1b0.jpg)

**Comment by dirkwhoffmann** [comment]
> Is it true all what is written here ? does It work with VirtualC64 the sprite collision remover ?

Yes, it worked as expected with "Fast Eddie". I didn't test with other titles though. 

In fact, this cartridge is pretty meaningless because there are better and easier ways to disable collision detection in an emulator.
