### ISSUE TITLE
BCD mode flags, detection of WD65C802/816

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#639]
This was posted in a German C64 forum. I quote it here so it won't be forgotten:

> Nun zu etwas Technischem: Ich habe mir die CPU-Emulation ein bisschen angesehen, https://github.com/dirkwhoffma…r/CPU/CPUInstructions.cpp
> 
> Bei der BCD-Arithmetik ist mir aufgefallen, dass bei ADC und SBC die Flags Z, N und V so gesetzt werden, als wären es keine BCD-Operationen. Nur der 6502/6510 setzt die Flags im BCD-Modus eben nicht richtig (soweit ich weiß wird nur C korrekt gesetzt). Erst die WD 65C802/816 machen es richtig, weswegen die CPU-Erkennung an dem auch scheitern dürfte. Die geht nämlich so:
> 
> ```
> Code
>         SED
>         LDA #$99
>         CLC
>         ADC #1
>         CLD
>         BEQ HV816
> ; 6502 here           ;flags show N set, and Z clear, even though A=0
> HV816                 ;816 here
> ```
> Soweit ich das sehe würde der Code beim Emulator einen 802/816er erkennen. ;)
> 
> Bei PLA dachte ich erst, dass die Flag-Behandlung nicht stimmt. PLA setzt nämlich das Z- und N-Flag entsprechend dem vom Stapel geholten Wert. Im Kommentar zum PLA-Befehl steht es jedenfalls falsch. Aber glücklicherweise verwendet PULL_A das Makro LoadA und das setzt implizit Z und N richtig. :)
> Ich hab das in meiner Grafikerweiterung einige Male in Verwendung ...
> Code
> PLA
> BNE ...
> Kommt auch im BASIC-Interpreter vor, z.B. bei $A45F oder bei $A9C1 ... da wär das wohl auch unangenehm aufgefallen.
> Somit passt es also, nur die Doku im Source stimmt nicht ganz. ;)

**Comment by JeeeK** [comment]
According to [Graham](http://www.oxyron.de/html/opcodes02.html):

- N will always carry bit 7.
- V will always be ((U eor N) nand (U eor V)) (while U is bit 7 of operand 1, V is bit 7 of operand 2 and N is the N flag after the ADC is performed).
- Z will be 0 when the non-BCD operation WOULD have resulted in $00, no matter what value the result of the BCD operation is.

Example to Z:
        SED
        CLC
        LDA #$80
        ADC #$80
   ... results in A=$60, but the Z flag is 1.

**Comment by dirkwhoffmann** [comment]
> Somit passt es also, nur die Doku im Source stimmt nicht ganz. ;)

Just to make sure we're on the same page: You are saying the code is fine, but the comments are wrong?

I am asking, because I did run all CPU related VICE tests and they all pass. However, I am not sure if the VICE tests cover this specific feature at all. Do you happen to know a small test program (D64 or PRG) that can be used to check this particular CPU feature?

**Comment by Alessandro1970** [comment]
...perhaps something can be found here:
https://stardot.org.uk/forums/viewtopic.php?t=8793

**Comment by JeeeK** [comment]
> Just to make sure we're on the same page: You are saying the code is fine, but the comments are wrong?

This is just regarding the PLA opcode, not the BCD issue. There was to much of my initial comment copied in. ;)

**Comment by dirkwhoffmann** [comment]
OK, just double checked the code with a small Turbo Assembler program. We're all good: 

<img width="894" alt="Bildschirmfoto 2021-05-14 um 13 07 39" src="https://user-images.githubusercontent.com/12561945/118262666-81852900-b4b5-11eb-8dd3-fb6d6c0b8575.png">

<img width="894" alt="Bildschirmfoto 2021-05-14 um 13 07 47" src="https://user-images.githubusercontent.com/12561945/118262676-8518b000-b4b5-11eb-990c-06fc3a10293a.png">
