### ISSUE TITLE
v4.0.1 multi shot broken??

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#641]
Not completely sure but I do see the difference when multi shot is on or off?

[gyruss.d64.zip](https://github.com/dirkwhoffmann/virtualc64/files/5976160/gyruss.d64.zip)

**Comment by dirkwhoffmann** [comment]
The spaceship always fires a couple of shots (not just one, checked with VICE). With auto-fire, it fires constantly. 

If you like to try again, please compile the latest version from the master branch (because I've already reworked the multi-shot code for v4.1)
