### ISSUE TITLE
Default behaviour of drag & drop loading like version 3.4

### ISSUE THREAD

**Issue by guyfromouttaspace** [dirkwhoffmann/virtualc64#643]
The loading behaviour of the old 3.4 version was more convenient and for new users easier to understand: just starting to load a file of a disk or tape without prompting for further selection.
Since version 4 this is way more complicated. I would suggest to set the drag & drop loading behaviour to the old default one for a more convenient usability.

**Comment by dirkwhoffmann** [comment]
The next release will have the "Drop target" feature from vAmiga. If a drive is selected as "drop target", any disk file added via drag and drop is inserted directly into that drive.

![menu](https://user-images.githubusercontent.com/12561945/117243179-ffeb2680-ae36-11eb-9114-85556f81bb82.png)

I've also experimented with automatically appearing overlays when starting a drag operation. This didn't work out, so I jeopardised this idea.
