### ISSUE TITLE
Vice Test: border-bm-ysh2

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#644]
Hi,
I wonder if this difference could be a bug:
<img width="720" alt="Schermata 2021-02-20 alle 10 52 31" src="https://user-images.githubusercontent.com/34916641/108591714-5f728380-736a-11eb-948c-07bbe5fe29ec.png">

<img width="795" alt="Schermata 2021-02-20 alle 10 52 46" src="https://user-images.githubusercontent.com/34916641/108591717-65686480-736a-11eb-8a84-e7d9391e7841.png">

[border-bm-ysh2.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014562/border-bm-ysh2.prg.zip)

**Comment by dirkwhoffmann** [comment]
Not a bug. It's just that VirtualC64 displayed a slightly smaller part of the texture:

<img width="917" alt="Bildschirmfoto 2021-05-02 um 12 44 50" src="https://user-images.githubusercontent.com/12561945/116810481-48a79480-ab44-11eb-89e6-c90d561e3bde.png">
