### ISSUE TITLE
Vice Test sbsprf24-163

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#645]
There is a part of the image out of the screen on the right (blu square)
<img width="796" alt="Schermata 2021-02-20 alle 11 06 15" src="https://user-images.githubusercontent.com/34916641/108592007-e96f1c00-736b-11eb-9a45-8707cdec960b.png">

<img width="718" alt="Schermata 2021-02-20 alle 11 05 58" src="https://user-images.githubusercontent.com/34916641/108592010-ed9b3980-736b-11eb-926b-c78b040679ec.png">

[sbsprf24-163.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014572/sbsprf24-163.prg.zip)
These too:
[sbsprf24.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014585/sbsprf24.prg.zip)
[sbsprf24-164.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014587/sbsprf24-164.prg.zip)

**Comment by dirkwhoffmann** [comment]
In VirtualC64, the last line of the blue sprite is missing.

Note: The sprite can be moved by pressing certain function keys.

```
Test Prog(s) for Sprite Data Fetch in sideborder
------------------------------------------------

If Sprite X-Position is >=$164, the sprite data that was fetched during the 
sprite fetch cycles on the very same raster line will be shown.

This test prog was done to show how the sprite x position influences the sprite 
data shown on the screen.

sbsprf24.prg:
-------------

F1/F3 to move the selected sprite
F5/F7 to change the selected sprite
```

**Comment by dirkwhoffmann** [comment]
Fixed. The error was due to an issue in `VICII::cycle63()`. Background: Each call to `drawSprites()` is guarded by a condition that checks if the call is really necessary. In `cycle63()`, this condition was too weak.
