### ISSUE TITLE
Vice Test: Modespilt

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#647]
<img width="839" alt="Schermata 2021-02-20 alle 11 44 13" src="https://user-images.githubusercontent.com/34916641/108592959-0a863b80-7371-11eb-8e71-9706576d95fb.png">

<img width="836" alt="Schermata 2021-02-20 alle 11 44 21" src="https://user-images.githubusercontent.com/34916641/108592964-107c1c80-7371-11eb-9583-788f61727409.png">

[modesplit.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014686/modesplit.prg.zip)

**Comment by dirkwhoffmann** [comment]
The modesplit tests are now part of the automatic regression testing suite. Note: The outcome of these tests are dependent on the C64 model (C64, C64C, old C64).
