### ISSUE TITLE
Vice Test: fetchsplit

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#648]
White lines

<img width="833" alt="Schermata 2021-02-20 alle 11 49 53" src="https://user-images.githubusercontent.com/34916641/108593083-f0992880-7371-11eb-9138-422329401c7b.png">

<img width="839" alt="Schermata 2021-02-20 alle 11 49 45" src="https://user-images.githubusercontent.com/34916641/108593085-f262ec00-7371-11eb-839d-8d2e8c225bc3.png">

[fetchsplit.prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/6014705/fetchsplit.prg.zip)

**Comment by dirkwhoffmann** [comment]
This test is now part of the automatic regression test suite:

https://github.com/dirkwhoffmann/virtualC64TS/tree/main/VICII/split-tests

The white lines can be neglected (if I remember correctly, they come from uninitialised memory). The important information is the distribution of numbers and characters. I run the test for all three supported PAL models  (PAL, PAL_II, PAL_OLD). For all models, the mapping seems alright.
