### ISSUE TITLE
Crash upon first joystick button click

### ISSUE THREAD

**Issue by dmotowylak** [dirkwhoffmann/virtualc64#649]
First off, I love this software, I use it every day!
I was looking forward to v4, as I have experienced constant crashes in prior versions. While the new version seems more stable, I still see a lot of crashes when using either a joystick either connected via USB or Bluetooth.  

I am not a developer, but I want to do what I can to help. I do see a crash log when it occurs, but I'm not sure it is helpful.  As a note, I did NOT see this issue in earlier beta version of 4.0.  It resurfaced near the final build. 

I doubt this is helpful, but below is the crash log I receive when it happens.  Is there something I can do to further troubleshoot?  

rocess:               VirtualC64 [3533]
Path:                  /Users/USER/*/VirtualC64_4.0.1.app/Contents/MacOS/VirtualC64
Identifier:            de.dirkwhoffmann.VirtualC64
Version:               4.0.1 (4.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VirtualC64 [3533]
User ID:               501

Date/Time:             2021-02-21 18:59:27.147 -0500
OS Version:            macOS 11.2.1 (20D74)
Report Version:        12
Anonymous UUID:        4905612E-F8DF-C202-AC36-BC3F29EA0CFA

Time Awake Since Boot: 32000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [3533]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   de.dirkwhoffmann.VirtualC64   	0x0000000106f6de4f 0x106ea9000 + 806479
1   de.dirkwhoffmann.VirtualC64   	0x0000000106f6ed34 0x106ea9000 + 810292
2   de.dirkwhoffmann.VirtualC64   	0x0000000106f6b946 0x106ea9000 + 796998
3   com.apple.framework.IOKit     	0x00007fff22b2e786 __IOHIDDeviceInputElementValueCallback + 217
4   com.apple.CoreFoundation      	0x00007fff20418022 __CFDictionaryApplyFunction_block_invoke + 22
5   com.apple.CoreFoundation      	0x00007fff203dfdde CFBasicHashApply + 110
6   com.apple.CoreFoundation      	0x00007fff203d24df CFDictionaryApplyFunction + 131
7   com.apple.framework.IOKit     	0x00007fff22b32991 __IOHIDQueueValueAvailableCallback + 70
8   com.apple.iokit.IOHIDLib      	0x000000011857ee07 0x118577000 + 32263
9   com.apple.CoreFoundation      	0x00007fff204436aa __CFMachPortPerform + 288
10  com.apple.CoreFoundation      	0x00007fff20417188 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
11  com.apple.CoreFoundation      	0x00007fff20417065 __CFRunLoopDoSource1 + 595
12  com.apple.CoreFoundation      	0x00007fff20415709 __CFRunLoopRun + 2402
13  com.apple.CoreFoundation      	0x00007fff204146ce CFRunLoopRunSpecific + 563
14  com.apple.HIToolbox           	0x00007fff2869c630 RunCurrentEventLoopInMode + 292
15  com.apple.HIToolbox           	0x00007fff2869c42c ReceiveNextEventCommon + 709
16  com.apple.HIToolbox           	0x00007fff2869c14f _BlockUntilNextEventMatchingListInModeWithFilter + 64
17  com.apple.AppKit              	0x00007fff22c349b1 _DPSNextEvent + 883
18  com.apple.AppKit              	0x00007fff22c33177 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1366
19  com.apple.AppKit              	0x00007fff22c2568a -[NSApplication run] + 586
20  com.apple.AppKit              	0x00007fff22bf996f NSApplicationMain + 816
21  de.dirkwhoffmann.VirtualC64   	0x0000000106f26149 0x106ea9000 + 512329
22  libdyld.dylib                 	0x00007fff20339621 start + 1

**Comment by dirkwhoffmann** [comment]
I had the very same crash today:

<img width="1112" alt="Bildschirmfoto 2021-05-06 um 10 08 38" src="https://user-images.githubusercontent.com/12561945/117265750-d7722500-ae54-11eb-89d1-c180bc8c8f7c.png">

It's similar to a crash I had yesterday (reference to the C64 proxy object is NULL). Totally unsure how this can happen.

**Comment by dirkwhoffmann** [comment]
I think I found a way to reproduce it:

1. Plug in USB joystick
2. Open VirtualC64
3. Close the emulator instance (by clicking the red window icon)
4. Open another window by clicking the dock icon
5. Push joystick button
6. The emulator crashes

I think the problem is that the HID callbacks of the first emulator instance are still active. V4.1 uses a different shutdown sequence, and I was not able to reproduce it with the latest build. Hence, with some luck, the issue is gone in V4.1.

**Comment by dmotowylak** [comment]
I just download the new version and tried a few games and NO crashes :-)
Typically the emulator would have crashed several times by now, so I think it is fixed.  THANK YOU!!
