### ISSUE TITLE
Background in fullscreen

### ISSUE THREAD

**Issue by blar** [dirkwhoffmann/virtualc64#651]
Can you remove the gradient from the background or sync the background color with the border color?

<img width="435" alt="Bildschirmfoto 2021-03-04 um 13 48 12" src="https://user-images.githubusercontent.com/111508/109966283-60070480-7cf0-11eb-8429-2af947874d42.png">

**Comment by dirkwhoffmann** [comment]
In the next version, there will be a black border in fullscreen mode.

**Comment by blar** [comment]
Sync the background color in fullscreen with the border color is not possible or does it look bad?

**Comment by dirkwhoffmann** [comment]
> Sync the background color in fullscreen with the border color is not possible or does it look bad?

This is difficult, because the background color is one solid color and many programs change to border color  multiple times per frame.
