### ISSUE TITLE
Asks for ROM files every time I open the app...

### ISSUE THREAD

**Issue by eighteentee** [dirkwhoffmann/virtualc64#652]
Just installed V4.01 and have Commodore ROM files I used in the previous version. Every time I open v4.1 it opens a window asking me to drag in the ROMs. If I drag them in, it works until I quit. When I restart, it asks for the ROMs again.

**Comment by mithrendal** [comment]
There is a „use as default“ option.  Did you pressed it?

**Comment by dirkwhoffmann** [comment]
This should no longer be an issue in the next release. I guess it is a duplicate of this one:

https://github.com/dirkwhoffmann/vAmiga/issues/469

I double-checked with the latest code on the main branch. The code matches the one in vAmiga. Missing folder are created on-the-fly on my machine.
