### ISSUE TITLE
Question: left Arrow key on key mapping = symbolic?

### ISSUE THREAD

**Issue by discmix** [dirkwhoffmann/virtualc64#653]
Hi, its more a question. I work with macro assembler. a lot of commands started with the left arrow key. how I can use this key on key mapping = symbolic? I don't want to switch to positional because all other mapping are fine for me. at the moment I klick the keyboard button (is there a short cut?) and us it with the mouse (not really satisfied 😉)

thanks
Marco

**Comment by dirkwhoffmann** [comment]
Right now, the left arrow key is bound to one of the three German umlauts:

- 'ü' maps to „left arrow“
- 'ö' maps to @
- 'ä' maps to „up arrow“

I know this doesn't really help on machines with non-german keyboards.

**Comment by discmix** [comment]
Hi Dirk, thanks a lot. Thats help me so much! Im now faster then the light! 😊👍
