### ISSUE TITLE
V4.01 CRASH: Closing a saved machine state

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#654]
Topbar menu: Close 

Time Awake Since Boot: 240000 seconds
Time Since Wake:       5600 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [19643]

**Comment by dirkwhoffmann** [comment]
TODO: Double check if VirtualC64 is already using the new shutdown sequence which I implemented for vAmiga a couple of weeks ago.

**Comment by dirkwhoffmann** [comment]
I'll close this issue, because the stack trace doesn't contain enough information to debug the issue.
