### ISSUE TITLE
Tapes do not seem to work

### ISSUE THREAD

**Issue by sy2002** [dirkwhoffmann/virtualc64#655]
I tried the attached tapes in the newest version on the web and ended up with a black screen.

[sample-tapes.zip](https://github.com/dirkwhoffmann/virtualc64/files/6183950/sample-tapes.zip)

**Comment by mithrendal** [comment]
Hi @sy2002, 

good to hear from you again ... you wrote "on the web" ... did you mean the web version of VirtualC64 ?

**Comment by sy2002** [comment]
@mithrendal Great progress! Congrats! I tried today (after a long time) your latest version on https://dirkwhoffmann.github.io/virtualc64web/ and I am totally impressed. But I had challenges with tapes.

(BTW: I just noticed, that I probably posted my issue to the wrong repository; sorry for that.)

**Comment by mithrendal** [comment]
>BTW: I just noticed, that I probably posted my issue to the wrong repository; sorry for that.

no I think you have done the right thing 😄, because I just tried the Virtual C64 Mac version, which does not find the tapes either and thus cannot load them...

What I have done:
1. inserted one of the tape files 
2. typed "LOAD" + hit "RETURN"
3. pressed "play" on tape drive
4. light blue screen, waited 10 Minutes or so ... it does not find any title 
...

in contrast when I insert choplifter.tap, both versions Mac and Web are loading that tape fine...

So .... either is the tape corrupt or the Virtual C64 Core cannot handle it ...


>... Great progress! Congrats! I tried today (after a long time) your latest version on https://dirkwhoffmann.github.io/virtualc64web/ and I am totally impressed. 

🤗 @sy2002 your input for the project setup in the beginning phase of the project and the later testing was of great value ... Thank you !! The project would not be in the current state without your great hints ...

**Comment by dirkwhoffmann** [comment]
VICE does find something on both tapes. This is from the second tape:

![tape](https://user-images.githubusercontent.com/12561945/116696625-7238b280-a9c2-11eb-848a-a25a873cad99.png)

I double-checked with Frogger and Choplifter. Choplifter is a type-0 TAP file (standard pulse layout) whereas Frogger is a type-1 TAP file (advanced pulse layout). The tapes under investigation are type 1, too. Both Choplifter and Frogger load just fine. Hence, I don't think it's related to the TAP format. 

Next step: Compare the pulse lengths of the broken tapes with Choplifter and Frogger.

**Comment by dirkwhoffmann** [comment]
Here are the first few pulses read from the tape:

```
Large pulse: 0
Large pulse: 0
Large pulse: 14409723
Standard pulse: 48
Standard pulse: 46
Standard pulse: 45
Standard pulse: 46
...
```

The first three pulses send the tape reader off the rails. When removed, the tape loads just fine:

<img width="755" alt="Bildschirmfoto 2021-04-30 um 16 36 01" src="https://user-images.githubusercontent.com/12561945/116710557-2c83e600-a9d2-11eb-92b4-ce7d78b06c71.png">

My first guess is that converting to pulses starts too early. The corresponding bytes may still belong to the TAP header.

**Comment by sy2002** [comment]
@dirkwhoffmann Thank you for the feedback. Sounds like the TAP files I provided seem to be corrupt, right?

**Comment by dirkwhoffmann** [comment]
> Sounds like the TAP files I provided seem to be corrupt, right?

I’m unsure about this. This is from the specs:

```
    Bytes: $0000-000B: File signature "C64-TAPE-RAW"
                 000C: TAP version (see below for description)
                        $00 - Original layout
                         01 - Updated
            000D-000F: Future expansion
            0010-0013: File  data  size  (not  including  this  header,  in
                       LOW/HIGH format) i.e. This image is $00082151  bytes
                       long.
            0014-xxxx: File data
```

I think the spec tries to tell me that the first data byte is located at 0x14. If this was true, the TAP file would be corrupted. See here:

<img width="675" alt="Bildschirmfoto 2021-05-01 um 12 19 46" src="https://user-images.githubusercontent.com/12561945/116779796-c00ff200-aa78-11eb-9e84-590a67e8cc19.png">

The red arrow is the TAP type number. Type 1 assigns special meaning to $00. If $00 is encountered, the next three bytes are taken as the pulse length. Now, look at the blue arrow. The parser reads $00 and treats the next three bytes as a 24-bit number in little-endian format. This generates a ultra-long pulse which is the reason why the loading process gets stuck. 

As a workaround, I'll try to make the TAP reader a little more flexible by skipping all $00 bytes between position $14 and the first non-zero byte. This shouldn't have any impact to all other existing TAP files.

I know it works in VICE. If somebody dares to look into their source code, please feel free to do so 🙄.

**Comment by dirkwhoffmann** [comment]
In the meantime, I am pretty sure the tapes are broken. Therefore, I think it's best to stick to the old code (which reads the first data byte from position 0x14). 

Fortunately, debugging this issue wasn't for nothing. I took the chance to refactor the whole datasette code.

**Comment by sy2002** [comment]
Glad to hear, that debugging the issue wasn't for nothing :-) Thanks for your detailed feedback: I always learn something new from you while reading it ;-)
