### ISSUE TITLE
Nintendo Switch Pro Controller seen but not working

### ISSUE THREAD

**Issue by MIKEP72** [dirkwhoffmann/virtualc64#656]
For some reason with updated VirtualC64 I am not able to use my Switch Bluetooth Pro Controller for games anymore. The app does recognise it but in the same time says in preferences : This device is not known to the emulator. It may or may not work. I used one with 3.4 version of VirtualC64 for sure and it worked great. Can anyone help please. Is it in the settings or should I connect via USB rather then BT? BUt again, the app does see the controller. Thank you. MIke

**Comment by dirkwhoffmann** [comment]
USB or BT shouldn't make a difference, because the same HID callback is called.

From here, I cannot tell what's going wrong. For the time being, I've added it to the Amazon list of yet unsupported controllers.

**Comment by dirkwhoffmann** [comment]
I'm closing this for now. I'll reopen when the controller is available.
