### ISSUE TITLE
v4.01 Keysets - Freezing Emulation

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#658]
https://csdb.dk/release/?id=202171

I am finding similar games like the one above that using keysets as a joystick and holding down the keys up and left direction freezes the emulation. Same also happens in v3.4 as well....

**Comment by dirkwhoffmann** [comment]
Findings: The games freezes when CUR DOWN + CUR LEFT are pressed simultaneously, but this has nothing to do with joystick emulation. It also happens if keyset 2 is assigned to the joystick, or if no keyset is assigned at all. If I haven't overseen anything, it's not a bug.
