### ISSUE TITLE
V4.01 Crash on Exporting a disk

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#661]
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [97854]

VM Regions Near 0x8:
--> 
    __TEXT                      10121a000-1013d2000    [ 1760K] r-x/r-x SM=COW  /Applications/Emulators/*/VirtualC64.app/Contents/MacOS/VirtualC64

[darkterm4b-86.g64.zip](https://github.com/dirkwhoffmann/virtualc64/files/6255768/darkterm4b-86.g64.zip)

**Comment by dirkwhoffmann** [comment]
The disk exporter crashes, because it cannot divide the GCR data stream into tracks and sectors (the G64 file contains a disk with a non-standard track / sector format). 

TODO: Display a proper error message instead of crashing.

**Comment by dirkwhoffmann** [comment]
Should be fixed in v4.1.
