### ISSUE TITLE
c64 app candidates for compatibility issues 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#662]
this issue is intended as a list of candidates which are suspected to exhibit differences to the real machine. The list items on the list have then in a next step to be validated that they really differ because of an issue in virtualC64. It can also turn out that we have false positives because the candidate is not compatible with certain chip configurations.

**Comment by mithrendal** [comment]
Asteroids
https://csdb.dk/release/?id=20576

hangs during decrunching

**Comment by dirkwhoffmann** [comment]
Asteroids is not compatible with flashing (not a bug). If the T64 is mounted as a disk and loaded via `LOAD "*",8,1`, it runs just fine:

<img width="985" alt="Bildschirmfoto 2021-05-11 um 09 05 10" src="https://user-images.githubusercontent.com/12561945/117773126-3f02e880-b238-11eb-9df2-85b81df639c2.png">
