### ISSUE TITLE
Commodore Key on Touch Bar Not Working

### ISSUE THREAD

**Issue by jcassara** [dirkwhoffmann/virtualc64#693]
Holding down the Commodore Key on the Touch Bar and depressing another key does not yield expected behavior.  Text color does not change with a digit. Additional graphics characters do not appear with other keys. Commodore Key mapped to physical keyboard keys does function. 

Running VirtualC64 4.4. on MacBook Pro M1 with macOS 11.5.12.

**Comment by dirkwhoffmann** [comment]
TouchBar support has been removed (following Apples decision to discontinue this technology).
