### ISSUE TITLE
Setting For Unplugging Datasette

### ISSUE THREAD

**Issue by LargeChips** [dirkwhoffmann/virtualc64#694]
I think it would be nice if you add a setting
so you could unplug the Datasette.

**Comment by dirkwhoffmann** [comment]
Such an option will be available in v4.5:

<img width="643" alt="Bildschirmfoto 2022-05-07 um 18 03 34" src="https://user-images.githubusercontent.com/12561945/167262492-22b52d31-5c51-417a-aa4e-2f040d3e75d6.png">

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
