### ISSUE TITLE
Mac OSX 11.5.2 Big sur - will not start VirtualC64

### ISSUE THREAD

**Issue by bthobaben** [dirkwhoffmann/virtualc64#695]
<img width="308" alt="VirtualC64-MacOSX-11-5-2-Error-Message" src="https://user-images.githubusercontent.com/91018809/133930961-c3a4a6df-a71a-4ca0-a99d-dcc70ef556ae.png">
Please help! :-)

**Comment by mithrendal** [comment]
You have to press control key when you open it or via finder with context menu open … and grant it access

**Comment by bthobaben** [comment]
Great - thank you for your fast reply!
