### ISSUE TITLE
1001 Crew Intro hangs

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#698]
Hi, after trying lots of intro I noticed that the following hangs on the virtualc64:
[1001 Crew #07 (19xx)(1001 Crew).prg.zip](https://github.com/dirkwhoffmann/virtualc64/files/7357144/1001.Crew.07.19xx.1001.Crew.prg.zip)

VirtualC64:
<img width="802" alt="Schermata 2021-10-16 alle 09 28 38" src="https://user-images.githubusercontent.com/34916641/137578506-520c8c8d-23f6-41b6-8d44-1c5367a35e63.png">

Vice:
<img width="717" alt="Schermata 2021-10-16 alle 09 30 20" src="https://user-images.githubusercontent.com/34916641/137578510-a2cc5143-4ec8-469c-a54c-743bc25a4198.png">

My settings (standard c64 roms):
<img width="636" alt="Schermata 2021-10-16 alle 09 31 31" src="https://user-images.githubusercontent.com/34916641/137578523-e7380dad-eef6-446d-b8e0-9f5c2f3f44e6.png">

Bye

**Comment by dirkwhoffmann** [comment]
Confirmed. Interestingly, the CPU is not jammed. It executes some code around here:

<img width="980" alt="Bildschirmfoto 2021-10-17 um 13 50 56" src="https://user-images.githubusercontent.com/12561945/137626235-f7e5052d-aecd-454e-a9e7-c13bb63e3880.png">

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
