### ISSUE TITLE
Commodore Key not working

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#700]
Either thru typing or using the virtual keyboard, the commodore key c= does not work. It would be nice if you had the ability to map out the special keys on the commodore. ie RUN STOP or RESTORE or C=.

Attached is an example of the need to press then commodore key c=. The key is suppose to show the greets and the main menu. Please fix....

[Smoke Exploration Tool, The.t64.zip](https://github.com/dirkwhoffmann/virtualc64/files/7385360/Smoke.Exploration.Tool.The.t64.zip)
.

**Comment by dirkwhoffmann** [comment]
I haven't been able to reproduces this.

Just to make sure we're on the same page: I've loaded the demo and opened the virtual keyboard:

<img width="937" alt="Bildschirmfoto 2021-10-21 um 06 24 07" src="https://user-images.githubusercontent.com/12561945/138211829-cf51087a-cc07-4657-9b51-17ae8cb30faf.png">

After that I pressed "Commodore" and the credits screen appeared:

<img width="937" alt="Bildschirmfoto 2021-10-21 um 06 24 20" src="https://user-images.githubusercontent.com/12561945/138211880-fc061c34-eef4-4b41-a62e-7c881972431e.png">

Pease be aware of #701. The keyboard preferences are broken in the latest version. I.e., you are not able to switch between positional and symbolic mode in v4.4 nor can you use customised key assignments. This will be fixes asap.

**Comment by bluecursor** [comment]
It triggers fine, still… their are still unclaimed keys


Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
