### ISSUE TITLE
Floppy Disk Drive .d81 image support

### ISSUE THREAD

**Issue by Alvarez81** [dirkwhoffmann/virtualc64#706]
How can I load this GeoDesk OS ?
[gdesk64-v104.zip](https://github.com/dirkwhoffmann/virtualc64/files/7511680/gdesk64-v104.zip)

**Comment by Alessandro1970** [comment]
Some images .d64 can be found on the project page but you need a REU card [4mb] emulation first, I don't' know if this megapatch can be used with georam.

Project folder GEODEX64: 
https://gitlab.com/mkslack/Area6510/-/tree/master/releases

Someone has already done it whit Vice:
https://faberpixel.blogspot.com/2021/08/geos-megapatch-33-r8.html

**Comment by dirkwhoffmann** [comment]
I'm closing this issue, because 1581 support is unlikely to come (too much work for a limited benefit).
