### ISSUE TITLE
Unidentified Kernal/VC Roms

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#707]
Attached are Kernal/VC Roms images that work but come up as unknown and/or doesn't accept them.

**Comment by dirkwhoffmann** [comment]
Please don't post copyrighted material. 

Do you know the names of the kernels? I don't know what to put into the database for them.

**Comment by bluecursor** [comment]
Do you need me to send them via email? The filenames are clearly marked what they are.

Frank Michielli
Sent with OSX/iOS Spark!

**Comment by dirkwhoffmann** [comment]
> Do you need me to send them via email?

Not this time. Please use email next time.

**Comment by dirkwhoffmann** [comment]
I've added the Rom fingerprints for all Roms, but `VC-1541_JiffyDOS.bin`. This Rom is not recognized by VirtualC64 as a Rom at all. It must be some special patch, but I haven't been able to find out any details.

**Comment by Alessandro1970** [comment]
Jiffydos
https://rr.pokefinder.org/rrwiki/images/4/48/The_Transactor_Vol09_03_1989_Feb_JD_review.pdf

http://users.on.net/~clockmeister/JiffyDOS-Binaries/

**Comment by dirkwhoffmann** [comment]
The "standard" JiffyDOS Roms are already supported:

       case 0xDE7F07008B787040: return KERNAL_64_JIFFY;
       case 0xA9D2AD1A4E5F782C: return KERNAL_SX64_JIFFY; 

       case 0x8B2A523E29BED889: return VC1541_II_JIFFY;
       case 0xF7F4D931219DBB5D: return VC1541_II_JIFFY_V600;

The particular Rom (`VC-1541_JiffyDOS.bin`) crashes the emulator. It seems to be a kernel Rom and might need a special drive Rom to work.

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
