### ISSUE TITLE
Screensaver starts if plays with a joystick or joypad USB

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/virtualc64#709]
When I play using my Speedlink Competition PRO USB, my iMac starts the screensaver after time I set in Sys Pref on macOS. Same thing with other joypad USB (Gravis GamePro).
I think it also happens with a Bluetooth gamepad but I haven't tried it yet.

Virtual C64 v4.4
macOS Monterey (12.0.1)

**Comment by dirkwhoffmann** [comment]
I've implemented a fix according to [this article](https://stackoverflow.com/questions/64172687/what-is-the-proper-way-to-disable-screensaver-and-display-sleep-on-macos):

```Swift
    var token: NSObjectProtocol!

    public func applicationDidFinishLaunching(_ aNotification: Notification) {
        
        debug(.lifetime)

        token = ProcessInfo.processInfo.beginActivity(options: [ .userInitiated ],
                                                      reason: "Running VirtualC64")
    }
    
    public func applicationWillTerminate(_ aNotification: Notification) {
        
        debug(.lifetime)

        ProcessInfo.processInfo.endActivity(token)
    }
```

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
