### ISSUE TITLE
REU (Ram Expansion Unit)

### ISSUE THREAD

**Issue by Gianmarco72** [dirkwhoffmann/virtualc64#710]
Plans to implement REU cartridge (Ram Expansion Unit) to increase the C64 ram?

**Comment by dirkwhoffmann** [comment]
I had no plans to support the REU until yesterday when I heard about the C64 port of Sonic. As far as I understand, this game only works with the REU expansion and not the GeoRam. 

However, it'll take some time because vAmiga keeps me very busy at the moment.

**Comment by dirkwhoffmann** [comment]
Continued in #735.
