### ISSUE TITLE
Sid emulation in vice 3.6

### ISSUE THREAD

**Issue by Alessandro1970** [dirkwhoffmann/virtualc64#711]
Hi, are there many improvments in new sid emulation (vice3.6) to be imported in VirtualC64 ?
Bye

**Comment by dirkwhoffmann** [comment]
I've merged in (some) of the new reSID code from VICE 3.6.1. There are no real functional changes though (mostly some code reformatting). They also added a workaround for a bug which I reported some time ago. I've replaced my own workaround with the "official one" (both are hacks).
