### ISSUE TITLE
add support for null modem cable

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#715]
Work great on VAmiga. Wanting the same for VirtualC64, please!!

**Comment by dirkwhoffmann** [comment]
Do you have some special games / apps in mind that would benefit from a serial cable?

**Comment by bluecursor** [comment]
No games come to mind, bur for calling bbs's: terminal programs such as CCGMS, StrikeTerm, NovaTerm,ect...

**Comment by bluecursor** [comment]
Still looking for the serial cable added back again...

**Comment by dirkwhoffmann** [comment]
I'm closing this issue, because I don't have plans to support bbs's.
