### ISSUE TITLE
Customizable speed is not frame accurate.

### ISSUE THREAD

**Issue by holovicc** [dirkwhoffmann/virtualc64#716]
With 4.4 a new great feature arrived, allowing smooth video output on 50 and 60Hz. Huge improvement, but it is not perfect. Regardless whether you lock it into 50 or 60Hz, the emulation will hiccup every once in a while (eg. goes smooth for seconds, then it shakes a little, then goes smooth for a while and the pattern keeps repeating). Tested on Eizo CS2740 and the new 16" M1 Max Macbook pro, both supports 50 and 60Hz, both produced the same result.

**Comment by dirkwhoffmann** [comment]
v4.6 offers a real VSYNC mode. Please note that it'll always use the refresh rate of the main display. I haven't found a way to change this.
