### ISSUE TITLE
FFmpeg doesn't work on Apple Silicon Macs

### ISSUE THREAD

**Issue by Alvarez81** [dirkwhoffmann/virtualc64#718]
FFmpeg doesn't work on Apple Silicon Macs. Rosetta 2 is not a stable and "good" solution.
Is there any other way to record video in  VirtualC64 without FFmpeg ?

**Comment by Alessandro1970** [comment]
https://formulae.brew.sh/formula/ffmpeg

![Untitled 2](https://user-images.githubusercontent.com/34916641/150740957-6a960788-824a-4b47-b255-e4a41224821d.png)

**Comment by Alvarez81** [comment]
Is there an easy solution ?
Homebrew software is really native ? Where will be located compiled software ?
Could it be added to VirtualC64 code ?

**Comment by dirkwhoffmann** [comment]
Homebrew *is* the easy solution, I use it all the time. In fact, I've installed ffmpeg with Homebrew, too.

**Comment by KinaKai** [comment]
On a fresh install of Homebrew on Apple Silicon systems, Homebrew will install into `/opt/homebrew`, which breaks the hardcoded assumption that ffmpeg will be found in `/usr/local`. You can workaround around this by just doing a symlink: `ln -s /opt/homebrew/bin/ffmpeg /usr/local/bin/ffmpeg`.

**Comment by dirkwhoffmann** [comment]
Thanks a lot for posting a workaround!

> A permanent fix could be to expose the location of ffmpeg as user-definable setting.

Yes, this should be done. It's already on my To-Do list for vAmiga (which unfortunately consumes all my spare time at the moment).

**Comment by dirkwhoffmann** [comment]
Code from vAmiga has been ported.
<img width="758" alt="Bildschirmfoto 2022-05-07 um 18 33 14" src="https://user-images.githubusercontent.com/12561945/167263457-3021d235-f1f6-40e7-bcfd-1aba3b7c9cc7.png">

**Comment by dirkwhoffmann** [comment]
v4.5b1 is online.
