### ISSUE TITLE
1581 and REU support

### ISSUE THREAD

**Issue by Vweber73** [dirkwhoffmann/virtualc64#729]
Hi,
Any plan to support 1581 disks and REU memory expansion ? That would be great for GEOS, as well as support for 1351 mouse...
Not talking about C128 support ! :)

Thanks and cheers

**Comment by dirkwhoffmann** [comment]
Duplicate of #706 and #710.

> Any plan to support 1581 disks and REU memory expansion ?

Maybe eventually... Right now I am stuck in a pile of other work.

**Comment by Vweber73** [comment]
Ok, thanks !
