### ISSUE TITLE
Get waveform for each SID separately

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#732]
Requested by @chris70c

TODO:
- Move the waveform generation code from the GUI to the core emulator (like in vAmiga)
- Allow multiple sources (SID ring buffers (1..4) or mixed output stream)

**Comment by chris70c** [comment]
Not sure I understand, you can already get a buffer for each sid (sidStream[0..3]) what I was interested in was to get each voice of a sid before they're mixed together to create an oscilloscope view like this:
https://www.youtube.com/watch?v=e7kZaHUC74E

**Comment by dirkwhoffmann** [comment]
> https://www.youtube.com/watch?v=e7kZaHUC74E

Ok, I see. I thinks this would be difficult, because I don't know if reSID provides an easy way to access the data for a particular voice. 

Anyway, I've added a new function to the Muxer class that draws a waveform directly inside the emulator core:

    float draw(u32 *buffer, isize width, isize height, float maxAmp, u32 color, isize sid = -1) const;

It's similar to what vAmiga provides with the exception of the `sid` parameter. If this variable equals 0,...,3, the samples of a single SID are visualised. Otherwise, the mixed stereo output stream is drawn.
