### ISSUE TITLE
emulate REU RAM and SuperCPU expanded RAM

### ISSUE THREAD

**Issue by DannyCork** [dirkwhoffmann/virtualc64#735]
It would be great if Virtualc64 could emulate REU RAM and SuperCPU expanded RAM.

 I would like to run a [program](https://visionbasic.net/) but it requires this ram expansion. 

"Only REU RAM and SuperCPU expanded RAM are currently supported at this time. If you don't have any such RAM, there are a few modern cartridges currently being sold that provide an emulated solution (like the 1541 Ultimate II+). C64 emulators like VICE also support REU emulation"

**Comment by DNSGeek** [comment]
Yes, please. I also have Vision BASIC and would love to use it in Virtual64.

**Comment by dirkwhoffmann** [comment]
v4.6 will support the 1764 REU (256KB): 

<img width="907" alt="Bildschirm­foto 2022-12-26 um 09 11 03" src="https://user-images.githubusercontent.com/12561945/209525320-c065c5e8-a49d-41cd-ac9d-076e9a993e48.png">

<img width="907" alt="Bildschirm­foto 2022-12-26 um 09 23 42" src="https://user-images.githubusercontent.com/12561945/209525364-01b2f494-84b0-4242-8d75-107fd7bb7bef.png">

**Comment by DNSGeek** [comment]
Whoa, that is sweet! I’m stoked!On Dec 26, 2022, at 2:32 AM, Dirk Hoffmann ***@***.***> wrote:﻿
v4.6 will support the 1764 REU (256KB):

**Comment by dirkwhoffmann** [comment]
I can't get Vision BASIC to run in VICE (version 3.6.1).

First attempt: Attached a REU with 512 KB and dragged the Vision BASIC file into the emulator. 

Result: CPU JAM at $8F08

<img width="832" alt="Bildschirm­foto 2022-12-30 um 10 02 11" src="https://user-images.githubusercontent.com/12561945/210053372-b9e47fdd-9184-4bfb-a0fe-dd71fccd4d1b.png">

Second attempt: Attached a REU with 512 KB. Mounted the Vision BASIC disk via the menu and typed LOAD "*",8,1. 

Result: Out of memory

<img width="832" alt="Bildschirm­foto 2022-12-30 um 10 04 48" src="https://user-images.githubusercontent.com/12561945/210053503-7102aa2d-022d-44ef-9415-7e4aed2a2b14.png">

**Comment by DNSGeek** [comment]
You have to use NTSC mode. It will not work in PAL mode. >=256 REU.  On Dec 30, 2022, at 3:11 AM, Dirk Hoffmann ***@***.***> wrote:﻿
I can't get Vision BASIC to run in VICE (version 3.6.1).
First attempt: Attached a REU with 512 KB and dragged the Vision BASIC file into the emulator.
Result: CPU JAM at $8F08

Second attempt: Attached a REU with 512 KB. Mounted the Vision BASIC disk via the menu and typed LOAD "*",8,1.
Result: Out of memory

**Comment by dirkwhoffmann** [comment]
> You have to use NTSC mode.

Oh yes, now I remember that I've been told this before...

Looks much better now:

<img width="832" alt="Bildschirm­foto 2022-12-30 um 14 22 28" src="https://user-images.githubusercontent.com/12561945/210075040-85ba27d8-b63b-4cf3-922f-85baf5ae523a.png">

**Comment by DNSGeek** [comment]
Wow, that looks amazing. Thank you!On Dec 30, 2022, at 7:27 AM, Dirk Hoffmann ***@***.***> wrote:﻿

You have to use NTSC mode.

Oh yes, now I remember that I've been told this before...
Looks much better now:

**Comment by dirkwhoffmann** [comment]
Got it to work in VirtualC64, too. However, it only works with the REU 1750 at the moment. The REU 1764 is not emulated properly as it mirrors the lower 256 KB in the upper 256 KB range which is wrong. When reading from unmapped memory, the latest valid bus value has to be returned.

<img width="919" alt="Bildschirm­foto 2022-12-30 um 14 34 59" src="https://user-images.githubusercontent.com/12561945/210076324-2a8d2f55-8ce0-4d29-a6ac-77330bf7f808.png">

**Comment by DNSGeek** [comment]
When I set the power supply freq to 60 stable and attach a 1750, I still can't run VB. Am I missing an additional setting?

**Comment by dirkwhoffmann** [comment]
- Attach a REU 1750 with 512 KB.
- Make sure to select a NTSC revision of the VICII chip (power supply setting doesn't matter):

<img width="909" alt="Bildschirm­foto 2023-01-06 um 17 29 32" src="https://user-images.githubusercontent.com/12561945/211055545-6cac9664-4388-4a76-9022-a140ddf7f9f7.png">

It doesn't seem to work with the original 256KB REU which is most likely a bug in VirtualC64.
