### ISSUE TITLE
Bugs in  V4.5 Final

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#740]
- Right Clicking or Double clicking on a .prg causes a crash with no error msg.
- Screen Capture Engines are missing

**Comment by dirkwhoffmann** [comment]
Could you try again with v4.5.1? 

Regarding the FFmpeg issue, VirtualC64 scans the same default locations as vAmiga now, namely:

```
/Applications/ffmpeg
/usr/bin/ffmpeg
/usr/local/bin/ffmpeg
/opt/bin/ffmpeg
/opt/homebrew/bin/ffmpeg
```

**Comment by bluecursor** [comment]
Working!

Can we add to the preferences to autostart the flash program menu on/pff on insert of media. (like in the past...)

**Comment by bluecursor** [comment]
I am finding that v 4.4 run also smoother than the latest version. Apps seams to run choppy like program had run out RAM and is always trying to catch up. Tested with https://csdb.dk/release/?id=226252

**Comment by dirkwhoffmann** [comment]
v4.6b1 is online.
