### ISSUE TITLE
Typo in the menus?

### ISSUE THREAD

**Issue by neleabels** [dirkwhoffmann/virtualc64#756]
Only a small thing, but I am pretty sure that "pound" is not spelled as in the screenshot.
<img width="1280" alt="Bildschirm­foto 2023-01-29 um 12 21 47" src="https://user-images.githubusercontent.com/123799276/215323015-27a7fda7-63e8-4653-b5ab-33840ab71413.png">

**Comment by dirkwhoffmann** [comment]
Fixed in v4.6b2
