### ISSUE TITLE
VCenter setting is lost after VirtualC64 restart

### ISSUE THREAD

**Issue by boeckmann** [dirkwhoffmann/virtualc64#761]
Following line may be the cause:
https://github.com/dirkwhoffmann/virtualc64/blob/77ec77aeb9d36ea441fa2ec51353fdf086fa9b5f/GUI/Defaults.swift#L1348

**Comment by boeckmann** [comment]
It is also lost when starting a new machine.

**Comment by dirkwhoffmann** [comment]
Thanks for reporting and for pointing out the source of the bug.

**Comment by dirkwhoffmann** [comment]
Fixed in v4.6b2
