### ISSUE TITLE
Restart animation is annoying (and slow)

### ISSUE THREAD

**Issue by boeckmann** [dirkwhoffmann/virtualc64#762]
Would be great if it could be disabled in the settings.

**Comment by dirkwhoffmann** [comment]
Which restart animation do you mean? The rotating cube? Switching it off wouldn't help much, because after powering on, the screen remains black for a few seconds anyway.

**Comment by boeckmann** [comment]
Yes, the rotating cube :-)

**Comment by dirkwhoffmann** [comment]
Decided to keep it because I love the cube.
