### ISSUE TITLE
Keyboard Mapping of F6 and F7 when not in Inspector Window

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#765]
Can the Inspector Mapping of F6 & F7 be changed to other than F1-F8 that does not affect the daily usage of the emulator? 
I know shift+f6 and Shift+f7 is mapped but Maybe use F9-F12 instead for the inspector window? 
Either this or can F6 & F7 map to the inspector window when it is open otherwise the keys maps to the main window of the emulator?

**Comment by dirkwhoffmann** [comment]
> Can the Inspector Mapping of F6 & F7 be changed

Yes, definitely. Using F6 and F7 as shortcuts for menu items isn't a smart choice. I've removed the mapping in the latest checkin (it was mapped to "step into" and "step over").

**Comment by dirkwhoffmann** [comment]
Fixed in v4.6.
