### ISSUE TITLE
broken code signature in release 4.6

### ISSUE THREAD

**Issue by suschizu** [dirkwhoffmann/virtualc64#767]
the latest release contains a not valid Apple Development signature:

EXPECTED 'Dirk Hoffmann (3NG65ZLYW7)' but FOUND 'Apple Development: Dirk Hoffmann (8JY75JXGHP)'

**Comment by dirkwhoffmann** [comment]
I'm no longer able to notarize applications, because I quit the apple developer program a while ago. I guess this is the reason.

**Comment by suschizu** [comment]
thanks for the fast answer! let's hope apple will change this in autumn :)
