### ISSUE TITLE
"can't be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by user96x** [dirkwhoffmann/virtualc64#768]
When attempting to run the application VirtualC64 (version 4.6) I receive this (possible GateKeeper?) error on macOS 13.5 Ventura:

“VirtualC64” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.

**Comment by mithrendal** [comment]
See also https://github.com/dirkwhoffmann/vAmiga/issues/793

You have to right click and `open it`
