### ISSUE TITLE
Serial Port

### ISSUE THREAD

**Issue by bluecursor** [dirkwhoffmann/virtualc64#770]
What ever happened to adding the Serial port (like VAmiga) to virtialC64?

**Comment by mithrendal** [comment]
@bluecursor what would you like to do with the serial port ?

**Comment by bluecursor** [comment]
Exactly the same reason why Amiga has a serial port option...

**Comment by dirkwhoffmann** [comment]
I have no plans to implement serial port support in the near future. There is just too much other stuff on my plate.
