### ISSUE TITLE
Add MAME SID implementation as another sound backend

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#776]
Currently, VirtualC64 offers reSID and FastSID as audio backends, with the latter not at all being competitive in terms of quality.

As an experimental project, it should be tried to add MAME's SID implementation. The implementation is licensed under the BSD clause, except for two data tables taken from reSID. If the new backend proves to be suitable enough (without the data tables, which only cover some unusual scenarios where multiple waveforms are activated simultaneously), reSID could be removed. This is a requisite to change the license of VirtualC64 from GPL to BSD, which I want to do eventually. 

https://github.com/mamedev/mame/tree/master/src/devices/sound

**Comment by dirkwhoffmann** [comment]
The `MameSID` branch contains an experimental version of VirtualC64 with the MAME SID backend included:

<img width="959" alt="Bildschirmfoto 2024-01-20 um 12 40 08" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/077a8c58-640a-4b3e-9dd3-78f409cb2a4f">

The good: 
- Code integration was not that difficult as there were little dependecies to the rest of the MAME code. 

The bad: 
- I am pretty disappointed about the audio quality of the MAME implementation. Compared to reSID, it appears to be much inferior. I didn't compare it to the real MAME app, so there is still a slight chance that something is misconfigured. 

Assuming there is no configuration error, I don't think merging the code back to the main branch makes sense. It would just bloat the app without adding any substantial improvement.

**Comment by Haroldo64** [comment]
Hi, there is a new RESID version in VICE 3.8:

- reSID: fixed a Noise Init problem
- reSID: filter tweaks
- reSID: The 6581 saw+pulse waveform was wrong
- reSID: tweak shift register reset time for 6581
- reSID: 8580 Filter ringing fix
- reSID: 6581 filters: allow negative values for kVg-Vx

Could Virtualc64 work better with this upgrade importing it into ?

Thanks

**Comment by bhall408** [comment]
Necro bump... Was looking at this again recently, and one of the SID implementations that has come up multiple times when I was looking this week for non-GPL implementations is cSID/crSID... It is under a "WTF" (do what you want) license.

Latest version (updated March 2026) at  https://csdb.dk/release/?id=257992 

It is used by [Audio Overload](https://www.bannister.org/software/ao.htm) if you want to try it out for quality without (or ahead of) integrating it.

**Comment by dirkwhoffmann** [comment]
> cSID/crSID... It is under a "WTF" (do what you want) license.

That sounds quite promising to me. I wasn’t aware of this implementation before, so I can’t comment on its audio quality. Unfortunately, the Mac App Store link for Audio Overload appears to be broken, so I haven’t been able to test it myself.

That said, given the permissive licensing and the fact that the library is actively maintained, it seems worth trying out. Sadly, I don’t have the time to attempt an integration myself at the moment.

**Comment by bhall408** [comment]
> That sounds quite promising to me. I wasn’t aware of this implementation before, so I can’t comment on its audio quality. Unfortunately, the Mac App Store link for Audio Overload appears to be broken, so I haven’t been able to test it myself.

Weird... I tried that link just now (from the devs web site) and it worked. Perhaps it is region related? When I visit the page in the App Store, this is the direct link the App Store provides (to the listing) -- https://apps.apple.com/us/app/audio-overload/id1512000244?mt=12

Worst case, you should be able to find it doing a search for "Audio Overload" in the app store. If that fails, only thing I can think of would be if the listing were not available worldwide for some odd reason.

> That said, given the permissive licensing and the fact that the library is actively maintained, it seems worth trying out. Sadly, I don’t have the time to attempt an integration myself at the moment.

It is possible we'll end up trying that ourselves, in which case we could provide that back to you!
