### ISSUE TITLE
Name of .VC64-config not shown in titlebar

### ISSUE THREAD

**Issue by ha24-1** [dirkwhoffmann/virtualc64#784]
Hi,
I have several saved .VC64-configs (f.i. with different attached .crt). 
When starting VC64 with such a config-File, the name of it is not shown in titlebar ("Untitled" is shown although the correct config is active).
I'm using VirtualC64  4.7 (240127) / OSX 14.3.1 (23D60).

No big thing, just in case... 
Best regards and thank you very much!

Fun fact: in vAmiga-App it works :-)

**Comment by dirkwhoffmann** [comment]
The bug [is in this line](https://github.com/dirkwhoffmann/virtualc64/blob/d1ef29b8e9c3e2d7c8f7a08f02e94fe522257846/GUI/MyDocumentController.swift#L16). The proper file ending is `VC64`, not `V64`. 

New code (on v5.0 branch):

```Swift
if typeName != UTType.vc64.identifier {
```

**Comment by dirkwhoffmann** [comment]
Fixed in v5.0b1
