### ISSUE TITLE
audio buffer fill level periodically drops to 0

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#794]
Davids Midnight Magic

at this screen

<img width="880" alt="IMG_6278" src="https://github.com/dirkwhoffmann/virtualc64/assets/17108995/50d11def-4235-45c5-8daf-e79470a25bea">

sound is silent in 4.7 which is normal I think

4.7
<img width="581" alt="image" src="https://github.com/dirkwhoffmann/virtualc64/assets/17108995/ad159033-cfb7-4d5b-95e9-a06292da6707">

in  5.0b2 the fill level is periodically going down to 0 see picture below

5.0b2
<img width="581" alt="image" src="https://github.com/dirkwhoffmann/virtualc64/assets/17108995/39682ee8-ad31-4872-91ff-6981b56d19b4">

everytime it hits fill level 0 it outputs a crackle sound. The intervall between the cracks is like 1 second ...

**Comment by dirkwhoffmann** [comment]
<img width="985" alt="PNG-Bild" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/1532127c-279a-4210-9f8c-849ea6ee6064">

Thanks for reporting! Please enter `host` in RetroShell. I have a suspicion...

**Comment by mithrendal** [comment]
<img width="581" alt="IMG_5551" src="https://github.com/dirkwhoffmann/virtualc64/assets/17108995/8f73cba2-0390-4adb-8c99-4e6153e67ca1">

**Comment by dirkwhoffmann** [comment]
OK, nailed it. When configuring my Mac to use a sample frequency of 48000 Hz, SID still runs with 44100 Hz. This can be seen in the RetroShell debugger:

<img width="985" alt="PNG-Bild" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/fa4ecce0-7fb7-4bc5-a248-b31a0a5dd655">

For some reason, the virtual SID chips do not pick up the host sample rate. They always use the default sample rate which is set to 44100.

**Comment by dirkwhoffmann** [comment]
Fixed in v5.0b3
