### ISSUE TITLE
5.0b4: USB-Joystickadater

### ISSUE THREAD

**Issue by TMO2018** [dirkwhoffmann/virtualc64#797]
5.0b4:
Bei eingestecktem USB-Joystickadpater beendet sich das Programm nach dem Start sofort.
Getestet mit:
- ajoy
- retronic design
- hexagons USB-Joystick Adapter

macOS 14.5

**Comment by dirkwhoffmann** [comment]
Duplicate of #796

**Comment by dirkwhoffmann** [comment]
Fixed in v5.0b5

**Comment by TMO2018** [comment]
Die Joystick-Adapter funktionieren mit v5.0b5. :-)
