### ISSUE TITLE
Version 5.0b5 (240615) crashes on some Prefs-Tabs after "Use as Default"

### ISSUE THREAD

**Issue by ha24-1** [dirkwhoffmann/virtualc64#799]
Hi, 

Version 5.0b5 crashes on some (not all) Preferences-Tabs after Pressing "Use As Default", f.i. "Hardware", "Peripherals"...
On Tab "Audio" and "Video" it works as expected.
Stacktrace attached.

Best regards!

[vc64_505_stacktrace_useAsDefault.txt](https://github.com/user-attachments/files/15881884/vc64_505_stacktrace_useAsDefault.txt)

**Comment by dirkwhoffmann** [comment]
Confirmed. Thanks for reporting!
