### ISSUE TITLE
serial port communication via the userport

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#801]
We've had serial port communication in [vc64web](https://vc64web.github.io), the web version of virtualC64, for a while now.

To make it easier to update to newer core versions and merge the code, I thought it would be a good idea to bring the serial port communication feature from vc64web over to virtualC64.

So, I've put in PR #800  for this.

**Comment by dirkwhoffmann** [comment]
I'm currently reimplementing the merged code to make it fit into the existing component architecture. I am also adapting the Commander interface from vAmiga which allows the emulated computer (the C64 in this case) to control RetroShell. An early prototype is already working.

Step 1: Activate the commander:

<img width="898" alt="Bildschirmfoto 2024-07-03 um 19 36 04" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/18ae16c1-25eb-47c6-8aa4-542e8f64f4fd">

Step 2: Type a RetroShell command in a terminal program. The command will execute inside RetroShell:

<img width="898" alt="Bildschirmfoto 2024-07-03 um 19 36 24" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/4a24c7d2-417d-4148-8c63-95bc17f68cc2">

**Comment by dirkwhoffmann** [comment]
This book has some decent information about RS232 communication on the C64:

<img width="770" alt="Bildschirmfoto 2024-07-04 um 10 55 25" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/e65c9c60-3157-4ee8-aa90-2c6b86555a84">

Besides explaining how the user port pins map to the RS232 signals... 

<img width="673" alt="Bildschirmfoto 2024-07-04 um 10 55 08" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/0a2cea98-542b-40fc-a742-3ec3b5607a71">

... it also explains how data can be received and sent via BASIC. This could be used for testing, if more complex protocols should be supported (different packet sizes, parity bits etc.):

<img width="487" alt="Bildschirmfoto 2024-07-04 um 10 59 18" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/f6d54897-f35f-4612-ba73-886d9a612da9">

**Comment by dirkwhoffmann** [comment]
New RS232 code is in place.

@mithrendal: From RetroShell, you can use it like this:

<img width="963" alt="Bildschirmfoto 2024-07-04 um 13 21 10" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/66ed6600-29c6-4863-a30e-56179442654c">

The following functions are provided by the public API:

```C++
/** RS232 Public API
 */
struct RS232API : API {

    class RS232 *rs232 = nullptr;

    /** @brief  Returns the component's current state.
     */
    // const RS232Info &getInfo() const;
    // const RS232Info &getCachedInfo() const;

    /** @brief  Feeds textual data into the RS232 adapter
     *  This function emulates the transmission of incoming data from an
     *  external device.
     */
    void operator<<(char c);
    void operator<<(const string &s);

    /** @brief  Read a printable byte from the incoming logbuffer.
     *  Calling this function empties the logbuffer. When the logbuffer is
     *  empty and a new data packet is received, a MSG_RS232_IN message is
     *  sent to the GUI.
     */
    std::u16string readIncoming();

    /** @brief  Read the logbuffer that records outgoing data.
     *  Calling this function empties the logbuffer. When the logbuffer is
     *  empty and a new data packet is sent, a MSG_RS232_OUT message is
     *  sent to the GUI.
     */
    std::u16string readOutgoing();

    /** @brief  Read a printable byte from the incoming logbuffer.
     */
    int readIncomingPrintableByte();

    /** @brief  Read a printable byte from the outgoing logbuffer.
     */
    int readOutgoingPrintableByte();
};
```

**Comment by dirkwhoffmann** [comment]
Seems to work...

Let's open a 300 Baud connection with 8 bit packets, no parity (this is the only supported format yet)...

<img width="963" alt="Bildschirmfoto 2024-07-04 um 13 54 38" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/d2006433-778b-4a7f-9b6d-e62d47bedb3c">

The output appears in RetroShell...

<img width="963" alt="Bildschirmfoto 2024-07-04 um 13 55 07" src="https://github.com/dirkwhoffmann/virtualc64/assets/12561945/1b1acd9f-d5dc-4db3-82f7-2d86621a9d84">

Note: To see the output in RetroShell, `RETROSHELL` has to be selected as RS232 device.

**Comment by mithrendal** [comment]
@dirkwhoffmann perfectly. I merged your latest code back into vc64web which replaces my RS232 hack with your new RS232 code. It works perfectly !
