### ISSUE TITLE
Treu Love [2015] does not work

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#803]
To reproduce:
- Install REU
- Drag [TreuLove](https://github.com/user-attachments/files/16196661/TreuLove.prg.zip) into memory

The CPU will jam eventually.

**Comment by mithrendal** [comment]
a few seconds after run


[real c64](https://youtu.be/-X_xJvxan9s?si=E1guu7LBRUvWykSf)

<img width="532" alt="image" src="https://github.com/user-attachments/assets/b415d24b-8ac2-406f-934e-435af28d941e">




virtualC64 5.0b7

<img width="532" alt="image" src="https://github.com/user-attachments/assets/70445f45-c02e-43ed-a13c-cf85cb5bfddd">


looks like its somehow not using the correct width when the REU is blitting that [bob](https://cx16forum.com/forum/viewtopic.php?t=1384) "Blitter object" into video buffer

**Comment by dirkwhoffmann** [comment]
Findings: To make the demo scene work, REU timing is critical. First, it is important to transfer one byte at a time. In v5.1, there will be an option OPT_EXP_REU_SPEED. It must be set to 1 (native speed): 

<img width="885" alt="Bildschirmfoto 2024-08-29 um 09 56 44" src="https://github.com/user-attachments/assets/5ba9a09d-6cc5-4368-85e9-ec2060441feb">

Second, timing inside the emulator is essential. When a DMA transfer is requested, the following code is executed (new 5.1 code):

```c++
void 
Reu::prepareDma()
{
    if (REU_DEBUG) { dump(Category::Dma, std::cout); }

    c64Addr = c64Base;
    reuAddr = reuBase;
    isize len = tlen ? tlen : 0x10000;

    // Freeze the CPU
    cpu.pullDownRdyLine(INTSRC_EXP);
    
    // Schedule the first event
    c64.scheduleRel<SLOT_EXP>(2, EXP_REU_PREPARE, len);
}
```

To get the demo work, there must be a 2 cycle delay before the first DMA access happens. This is emulated in the last line by scheduling an `EXP_REU_PREPARE` event in 2 cycles. A value of 0 or 1 causes the screen to remain blank. A value of 3 causes distortion. 

<img width="885" alt="Bildschirmfoto 2024-08-29 um 11 32 54" src="https://github.com/user-attachments/assets/98b68175-aeb0-4143-8224-5689d5aba051">

Hence, 2 seems to be the correct value (assuming the demo runs fine on real hardware).

**Comment by dirkwhoffmann** [comment]
Update: To get the second scene working, timing on VICII's BA line is crucial.

 On [csdb](https://csdb.dk/release/?id=144105), there is a lot of talk about REU hardware bugs, stealing cycles from VICII etc. I doubt this is true. When reading the BA line with the proper delay (3 cycles), the demo scene looks in VirtualC64 like it does on the original C64 (at least to my aging eyes).

This is how I changed `REU::processEvent` to make the scene work:

```c++
   // Perform DMA if VICII does not block the bus
    if (!vic.baLine.delayed()) for (; todo; todo--, remaining--) doDma(id);

    if (remaining) {

        // Prepare the next event
        c64.scheduleInc<SLOT_EXP>(1, id, remaining);

    } else {

        // Finalize DMA if this was the last cycle
        finalizeDma(id);
        c64.cancel<SLOT_EXP>();
    }
 ```

Note: Using `baLine.delayed()` instead of `baLine.current()` is essential here.

**Comment by dirkwhoffmann** [comment]
Seems to work flawlessly in v5.1b2.
