### ISSUE TITLE
v5 ReSID resampling broken, fill level hits periodically zero

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#804]
https://csdb.dk/release/?id=241359

on `resampling` 

<img width="285" alt="image" src="https://github.com/user-attachments/assets/f6d83c19-1b35-489b-b6ed-f0923ff8763f">

the fill level of audio buffer runs periodically to zero 

<img width="553" alt="image" src="https://github.com/user-attachments/assets/2359a8d3-6054-4eda-b7cd-4e446bbe1e25">

resulting stuttering sound with crackling noises 

sound works fine on setting `fast` and `interpolate`

also affects https://vc64web.github.io

**Comment by mithrendal** [comment]
ReSID resampling works fine when switching back to a v4.5 emulation core 

<img width="1152" alt="image" src="https://github.com/user-attachments/assets/1dfbe634-92de-404f-8c92-b3a3b12a4501">



I did some more tests on ReSID resampling mode

findings

1. the ReSID resampling in v5 draws more computing power. When using Macbook M1 solely on battery, energy saving measurements seems to kick in.  With these measurements it is not able to sufficiently compute sound samples,  app activity hits 100%. Resulting in audio buffer underruns... fill level drops periodically to 0. When on power line again app activity drops to 67%, fill level stable. 

2. there is a constantly crackling noise which does not come from buffer underruns. It is just there.

**Comment by dirkwhoffmann** [comment]
Culpript for the cracking noise is commit 2ce74bc

**Comment by mithrendal** [comment]
merged latest commits into vc64web. You fixed the issue. ✌️
