### ISSUE TITLE
Support the VICE test bench?

### ISSUE THREAD

**Issue by dirkwhoffmann** [dirkwhoffmann/virtualc64#810]
Lately, there has been some discussion about whether the [VICE testbench](https://vice-emu.pokefinder.org/wiki/Testbench) should be supported. 

I've tried that in the past but gave up at some point, mainly because I am poor at reading shell scripts. The VICE testbench consists of script files, running the emulator with the VICE tests, and recording the outcome. 

I have done some preliminary work in case someone wants to get involved and help out.

1. VirtualC64 can now be configured via the command line

   To be as flexible as possible, arbitrary RetroShell commands can be passed in:
  Syntax: `virtualc64 -"<RetroShell command 1>" -"<RetroShell command 2>"` etc.
  VirtualC64 will collect and execute all provided arguments as a RetroShell script on startup.

2. The `debugcart` feature is supported

   It is deactivated by default. To enable it, set `OPT_EXP_DEBUGCART` to true (e.g., via the command line or inside RetroShell).

   Debugcart is sniffing at address `0xD7FF`. When this address is written, the emulator exists with the provided value as the return code.

**Comment by mrdudz** [comment]
If you implement the required features, i can add support for virtualc64 in the testbench - however, i don't have access to a macOS machine right now, so i can not test anything (or run the testbench with virtualc64 for that matter). If you can do that, i am more than happy to include your results to the testbench page on the VICE wiki of course :)

So, besides the debug-register (that you already have implemented) some more things are needed:

- an option to reset all settings to their defaults, this will always be used as the first option on the cmdline, to make sure the config is always predictable (and we don't get surprises because of some user settings)
- an option that will make the emulator quit (with exit status 1) after X cycles. This is needed for the case when a test program crashes or hangs, so the testbench can continue after a timeout
- an option that will save a screenshot with a given name when (before) the emulator exits (make sure the current frame is actually completely rendered before that happens)

Besides that, of course various other things need to be configurable... most importantly mounting disks and carts must be possible, and running programs - but i guess this is already the case :) However, i have no idea why you mean by your "Retroshell" examples - please point me to a list of all valid options and give some examples of how the resulting commandline would look like.

I'll prepare some rudimentary things in the meantime, it should be fairly straightforward to add :)

It'd also help if you checked out the testbench and make it work with any of the other supported emulators on your system (VICE is probably the most straightforward thing to do). If you do that in a svn tree, you can then just pull my updates later - and even produce patches easily should you find a bug.

**Comment by mrdudz** [comment]
I prepared some things already, see https://sourceforge.net/p/vice-emu/code/45328/ ... the only things missing now is fixing the commandline options to match whatever is needed in the virtualc64-hooks.sh file

Oh and i forgot above - please also point me to a list of features so i can filter the tests accordingly (what cartridges are supported, what other extensions, what drives, what image formats, what c64 models, pal/ntsc etc)

**Comment by dirkwhoffmann** [comment]
> However, i have no idea what you mean by your "Retroshell" examples - please point me to a list of all valid options and give some examples of how the resulting commandline would look like.

I know you have no Mac, but the easiest way to learn about all available RetroShell commands is to enter the shell, hit TAB twice, or enter the beginning of a command and then hit TAB twice. It will auto-complete what has been typed in and print some help like this:

<img width="871" alt="Bildschirmfoto 2024-09-04 um 08 52 50" src="https://github.com/user-attachments/assets/951bfe33-2590-4397-b30f-a92afb6dda37">

However, VirtualC64 comes with a small app called `Headless`, which is used to check the integrity of the build. One of its options is to run a [RetroShell test script](https://github.com/dirkwhoffmann/virtualc64/blob/master/Emulator/HeadlessScripts.h) that executes all available commands to see if syntax errors occur. The script gives you an impression of the syntax and all available options.

A typical RetroShell script looks like this:

```bash
# Regression testing script for VirtualC64
# Dirk W. Hoffmann, 2021

# Setup the test environment
regression setup PAL

# Launch the test
regression run "/tmp/cpu_decimal.prg"

# Exit with a screenshot
wait 3 seconds
screenshot save "cpu_decimal"
```

In the meantime, I'll take care of the watchdog feature (exiting the emulator after a specific number of frames)...

**Comment by dirkwhoffmann** [comment]
Update: I've added the required infrastructure...

1. `regression setup PAL`
   This already existing command initializes the emulator with default settings and turns on warp mode. I am using this command in the existing regression tests. Other options than PAL are:

    <img width="757" alt="Bildschirmfoto 2024-09-04 um 15 15 51" src="https://github.com/user-attachments/assets/7cefea70-1fcb-4e20-85aa-36eff727e29b">

2. `regression set DEBUGCART true` 

    Activates the VICE debugcart feature: Writing a value into 0xD7FF terminates the emulator. The written value is passed back as the return code. 

3. `regression set WATCHDOG <cylces>` 

    After initiating this command, the emulator will terminate after the specified number of CPU cycles with error code 1.

4. `screenshot save <filename>` 

    Saves the latest stable texture in raw format. If the provided filename is relative, it will be prepended by a default path, which is `/tmp` (to not break the existing regression tests). However, the path can be changed via `screenshot set path`. 

    Note: The screenshot command saves the texture in raw format. To convert it, e.g., into TIFF, ImageMagick can help out:

    `magick -depth 8 -size 716x285 rgb:/tmp/texture.raw texture.tiff`

    This command has been copied from a vAmiga Makefile. Hence, the texture size needs to be adjusted accordingly. VirtualC64 supports saving a cutout instead of the entire texture. The cutout size can be specified via the command `screenshot set cutout`. 

For Mac users: The RetroShell commands `regression` and `screenshot` are only shown in the online help in debug builds. In release builds, they are registered as hidden commands. They are still available, though.

That's it for today.

**Comment by mrdudz** [comment]
> If the provided filename is relative, it will be prepended by a default path, which is `/tmp` (to not break the existing regression tests). However, the path can be changed via `screenshot set path`. 

Please don't - that will break the testbench. Relative path should be just that - the testbench handles whatever is needed.  Using a separate option for the path will only make it more complicated.

**Comment by dirkwhoffmann** [comment]
> Relative path should be just that - the testbench handles whatever is needed.

OK, no problem. The current code looks like this:

```c++
    // Add the target directory if the path is relative
    if (!filename.is_absolute()) filename = screenshotPath / filename;

    // Add a filename extension if none is specified
    if (!filename.has_extension()) filename.replace_extension("raw");
```

Setting the path to an empty string via `screenshot set path ""` will cause relative paths to stay relative.

**Comment by mrdudz** [comment]
ok, fine... i will try to update that script a bit, then you can have a look and see what happens :)

**Comment by mithrendal** [comment]
I did the following

+ cloned the `testprogs` folder from svn
+ in folder `testprogs/testbench` I renamed the example config to `Makefile.config` 
+ set VICEDIR to vice 3.8 folder


```
# should point to the directory contain VICE x64 binary.
# if you have checked out "trunk" and "testprogs" into the same directory AND
# built the VICE binaries in-tree, you may leave this empty to use these 
# binaries.
#VICEDIR="/usr/local/bin"
VICEDIR="/Users/c64/projects/vice/bin"
```

(inside VICEDIR is the x64sc from vice3.8 mac sdl)

./testbench.sh x64sc

gives me this 

```
./testbench.sh x64sc
running tests for x64sc (all):
make: svn: No such file or directory
make[1]: petcat: No such file or directory
make[1]: *** [format.prg] Error 1
make: svn: No such file or directory
make[1]: acme: No such file or directory
make[1]: *** [tamtest.crt] Error 1
make: svn: No such file or directory
make: svn: No such file or directory
make: svn: No such file or directory
make[1]: acme: No such file or directory
make[1]: *** [rpm1.prg] Error 1
./selftest/ c64-pass.prg - error 
./selftest/ c64-fail.prg - error 
./selftest/ c64-pass.prg - 
error: call to ../../trunk/vice/src/x64sc failed.
```

I expected it to look into VICEDIR and start the tests ... what am I missing ?

(when I directly call /Users/c64/projects/vice/bin/x64sc from shell vice by itself just starts fine.)

**Comment by mrdudz** [comment]
oh well... you'll probably have to install a couple tools - i have never used the testbench on a box that isn't a development machine (which has all those tools) to be honest, so i never really noticed :) (i should put whatever comes out of this into the readme later... :))

a) if you call the testbench script directly (not via the Makefile), then you will have to give it the path in EMUDIR. ie call it like this:

`EMUDIR=/Users/c64/projects/vice/bin ./testbench.sh x64sc`

else it will look for the VICE binary in ../../trunk/vice/src/ - which would be the case when checking out the VICE repo and the testbench into the same toplevel directory (this is is the common development setup)

b) the tools that come with VICE have to be in the PATH (petcat, cartconv, c1541). This should be the case if VICE is properly "installed" on your system (i have no idea about using the macOS app thing, i guess you can add the path to your local bashrc)

c) as you see in the error messages.... you will also need the "acme" crossassembler and "subversion". acme builds the selftests and some helper programs (those it should actually skip when testing VICE...oh well) and svn is used to revert some changes to d64s that are being written to when testing. Admittedly both isnt the smartest solution - but it worked so far (i'll be happy to merge any patches that provide the same functionality and remove the requirement). I have no idea where to find macOS packages for those, but subversion must exist somewhere - and acme is trivial to build from source (there is also a macOS binary, although its a somewhat older version: https://sourceforge.net/projects/acme-crossass/files/macOS/ )

**Comment by mrdudz** [comment]
So, i have committed some updates, changed the needed commandline options to what i think is the equivalent option for virtualc64.

The way commandline options work (with spaces in them and no clear separation between option and argument) makes this a very annoying quoting mess - there will certainly be errors left

Also, from the description above, it seems the screenshot feature doesn't do what it should do. What it should do is save a screenshot when the emulator exits - no more no less. No extra wait should be required before that, the testprogram will trigger exit by writing to the debug register, and then the screenshot should happen.

I have marked a few places where i couldnt figure out what the respective option is with #TODO - mostly mounting disk images and cartridges IIRC

However, i recommend testing it like this:

`EMUDIR="/home/foo/bar" ./testbench.sh virtualc64 selftest --verbose`

That way you can (hopefully) see what is going on. 

I'd try to make the regular (no screenshots) tests work first, that is probably only a matter of fixing some of quoting here and there

Once that is OK adjust the magick command and the offsets, and those tests should start working as well - provided the screenshot is saved in a "known" palette.

**Comment by mithrendal** [comment]
```
 EMUDIR=/Users/c64/projects/vice/bin ./testbench.sh x64sc
running tests for x64sc (all):
make: svn: No such file or directory
make: *** ../drive/format/: No such file or directory.  Stop.
make: svn: No such file or directory
make: *** ../C64/carts/tamtest/: No such file or directory.  Stop.
make: svn: No such file or directory
make: svn: No such file or directory
make: svn: No such file or directory
make: *** ../drive/rpm/: No such file or directory.  Stop.
./selftest/ c64-pass.prg - ok 
./selftest/ c64-fail.prg - error 
./selftest/ c64-pass.prg - ok 
./selftest/ c64-fail.prg - error 
(cartridge:c64-pass.crt) ./selftest/  - ok 
(cartridge:c64-fail.crt) ./selftest/  - error 
(cartridge:c64-pass.crt) ./selftest/  - ok 
(cartridge:c64-fail.crt) ./selftest/  - error 
../C64/raminitpattern/ cyberloadtest.prg - timeout 
../C64/raminitpattern/ darkstarbbstest.prg - timeout 
../C64/raminitpattern/ pattern00ff.prg -  analyzer (skipped)
../C64/raminitpattern/ platoontest.prg - timeout 
../C64/raminitpattern/ typicaltest.prg - timeout 
../C64/autostart/basic/ basictest.prg - timeout 
../C64/autostart/basic/ printpoint.prg - timeout 
../C64/autostart/basic/ printpoint2.prg - timeout 
../C64/autostart/defaults/ test.prg - timeout 
(disk:test.d64) ../C64/autostart/defaults/ test.prg - timeout 
../C64/autostart/random/ raster.prg -  interactive (skipped)
../C64/bankio/ bankio.prg - timeout 
../C64/openio/ dadb.prg -  interactive (skipped)
../C64/openio/ de00all.prg -  interactive (skipped)
../C64/openio/ de00int.prg -  interactive (skipped)
../C64/openio/ trivial.prg -  interactive (skipped)
../C64/openio/ gauntlet.prg - timeout 
../crtemulation/paltest/ paltest.prg -  interactive (skipped)
../crtemulation/ emusuxX0r-crest.prg -  interactive (skipped)
../general/banking00/ banking00.prg - timeout 
../general/Lorenz-2.15/src/ start.prg - timeout 
../general/Lorenz-2.15/src/ ldab.prg - timeout 
../general/Lorenz-2.15/src/ ldaz.prg - timeout 
../general/Lorenz-2.15/src/ ldazx.prg - timeout 
../general/Lorenz-2.15/src/ ldaa.prg - timeout 
../general/Lorenz-2.15/src/ ldaax.prg - timeout 
../general/Lorenz-2.15/src/ ldaay.prg - timeout 
../general/Lorenz-2.15/src/ ldaix.prg - timeout 
...
```

how to stop the skript ?

**Comment by mrdudz** [comment]
CTRL-C in the terminal

**Comment by mithrendal** [comment]
timeout was a stupid error by me... it did not found the .prg files ... now I corrected the paths

<img width="660" alt="image" src="https://github.com/user-attachments/assets/5fce3b2e-828b-4db9-b3f8-d05d6a9200b5">

looks already better ✌️

**Comment by mrdudz** [comment]
yup :) you should also fix that svn error (ie install svn cmdline utils) - else some tests will randomly break after first run of the testbench

**Comment by mithrendal** [comment]
I’ve decided to pause the work on getting the test bench running on macOS. Initially, I thought it would only take a few days, but there are some missing packages like micro64disktool and still quite a bit left to do—such as pixel comparison of the test images. Also I have some other projects which currently need my attention. 

The progress made so far was that the virtualC64 was successfully called using
```bash
EMUDIR="./" ./testbench.sh virtualc64 selftest --verbose
```

which waited for completion and then displayed the OK/error message in the console

There were still several other warnings / error messages, and I decided to stop at this point, as I realized it would likely take several more weeks to get everything running perfectly, which isn't feasible with the limited time I have.

**Comment by dirkwhoffmann** [comment]
>  I decided to stop at this point, as I realized it would likely take several more weeks to get everything running perfectly, which isn't feasible with the limited time I have.

OK, maybe at a later point. I'll close the issue for now...

**Comment by mrdudz** [comment]
> I'll close the issue for now...
but why? *shrug*

> I thought it would only take a few days, but there are some missing packages like micro64disktool and still quite a bit left to do—such as pixel comparison of the test images. Also I have some other projects which currently need my attention.

I seriously wonder what kind of problems you are facing there - i have adopted the testbench for quite some things already and never had "weeks of work". *shrug* The missing micro64disktool shouldn't stop you - just skip those handful tests for the time being. And for comparing the test images you shouldnt have to do anything, the tool that does this is in the testbench, all that is needed is providing the right x/y offsets for the screen in the script. (But again - even this shouldnt stop you, as you can just skip all tests with screenshots first).
