### ISSUE TITLE
Is there a way to export RAM bank C edit this locally and import after amendments?

### ISSUE THREAD

**Issue by TyrfingMjolnir** [dirkwhoffmann/virtualc64#811]
I'm on Virtual C64 4.6

Is there a way to export RAM bank C edit this locally and import after amendments?

I would like to work with some memory from the C64 inside vim on my Mac, and after doing my edits( nvim or hexpatch ) I would like to load the amended data back in.

**Comment by dirkwhoffmann** [comment]
Hi,

v4.6 does not support such a feature. I only added such functionality recently (first in vAmiga).  The first supporting version will be v5.1: 

<img width="871" alt="Bildschirmfoto 2024-09-05 um 12 34 25" src="https://github.com/user-attachments/assets/33b2b72a-a3dc-4504-b997-330898c271d0">
