### ISSUE TITLE
Crash on restored snapshot with attached REU 

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#812]
How to reproduce

Start virtualC64.app v5.1 b2, versions before worked flawless

Attach REU 512K

Load something which accesses REU

Save snapshot

Restore snapshot

—> now the restored snapshot has capacity of 0Kb 😬

Game on … when game accesses the REU virtualC64 exists with a crash

**Comment by dirkwhoffmann** [comment]
The issue is solved. Fix is on the dev branch.

**Comment by dirkwhoffmann** [comment]
Fixed in v5.1
