### ISSUE TITLE
soft reset

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#813]
<img width="882" alt="image" src="https://github.com/user-attachments/assets/c2c07101-6ef0-4dea-ad27-0e9e46131893">

when applying `soft reset`  

<img width="882" alt="image" src="https://github.com/user-attachments/assets/b327d3a5-a202-4531-938f-3ba9e03cf617">

it does a reset but the cursor will not blink anymore

sometimes after long time of waiting the blinking cursor comes finally back...

waiting time varies between 30 seconds to a couple of minutes, sometimes it seems to never come back...

**Comment by dirkwhoffmann** [comment]
Fixed in v5.1
