### ISSUE TITLE
Floppy drive failures occurring at speed settings over 100%.

### ISSUE THREAD

**Issue by mithrendal** [dirkwhoffmann/virtualc64#814]
Version 5.1b2 (240909)

<img width="514" alt="image" src="https://github.com/user-attachments/assets/7b167240-16fd-489e-912e-ca0c37780304">

lead to disk drive problems ... 

<img width="851" alt="image" src="https://github.com/user-attachments/assets/30dd1134-4e85-41d8-a5b1-7afb3c2fe6ec">

when starting demos with 100% and at a later stage changing the speed, the music will continue to play but the display is frozen.

<img width="863" alt="image" src="https://github.com/user-attachments/assets/bcdfe458-af5d-409f-86b2-21ace2043b3e">

when using .prg files everything seems to work normal with different speed settings.

**Comment by mithrendal** [comment]
<img width="819" alt="image" src="https://github.com/user-attachments/assets/a7889d48-f18f-4142-ba95-976ae64f65a8">


first load was done with 200%
second load with 100%
third load with 200%
fourth load with 100%


=> disk drive can not handle speeds over 100%.

**Comment by mithrendal** [comment]
seems it can be fixed by the following change

<img width="684" alt="image" src="https://github.com/user-attachments/assets/c81eb2c1-44c4-4903-afa5-a3cb2bb843aa">

**Comment by dirkwhoffmann** [comment]
Thanks for reporting. Your fix is correct and has been checked in on the dev branch.

**Comment by dirkwhoffmann** [comment]
Fixed in v5.1
