### ISSUE TITLE
Save files to .d64 not possible 

### ISSUE THREAD

**Issue by ha24-1** [dirkwhoffmann/virtualc64#815]
Hi, I assume it's my fault - but I cannot save any (Basic)-File to an inserted .d64? 
When I try to eject the .d64 with before saved file (SAVE "TEST1",8) I get following requester: "Drive 8 contains an unsaved disk. Your changes will be lost if you proceed". And the file ist really lost if proceed. 

As long the .d64 stays attached, everything is fine: I can list the directory with my new file, I can load and re-save it. 
But after exit VC64 or eject the .d64 the new file is gone?!

There is no "Save"-command in Drive8-Menu. 

I cannot imagine, that no one has ever tried to save files into attached .d64? 

I'm running VC64 Version 5.0.1 (240724). 

Thank you for check my issue!

**Comment by dirkwhoffmann** [comment]
VirtualC64 is designed to *not* modify any file in the host file system on the fly. To preserve your changes, you need to export the disk via `Export...` from the `Drive 8` menu.

**Comment by ha24-1** [comment]
oh... shame on me!  Amazingly I never noticed that! 
(but in the case of games with a high score list, it would be a nice feature... :-).  )
